/**
 * The Faerie Queene — allegory-note data model and seed entries.
 *
 * This is Spenser's signature pedagogical contribution to the Tome catalog:
 * no other book in the library teaches *how allegorical reading works*,
 * and The Faerie Queene is the canonical example in the English tradition.
 *
 * The allegory-note is a distinct annotation subtype that explicitly
 * presents *multiple simultaneous readings* of a figure, passage, or
 * place — moral, theological, political, typological, personal — rather
 * than collapsing to a single interpretive claim. The data shape honors
 * the doubleness Spenser wrote in: every figure is simultaneously a
 * person in a story AND a figure for a virtue, vice, Church, historical
 * personage, theological concept. Neither reading cancels the other.
 *
 * Rendering (reader component, Part 3B integration):
 *   - Shows the `literalNote` first (what happens at the plot level).
 *   - Expands to show the `readings[]` as layered panels, each typed
 *     (moral / theological / political / typological / personal).
 *   - Authorities cited (where present) are scholarly, verified — never
 *     fabricated. Spec: "Do not cite Greenblatt, Hamilton, Nohrnberg,
 *     Berger, Teskey, or any other specific critic without verifying
 *     the citation."
 *
 * Target density (per Part 4):
 *   - Books I–II: 2–4 allegory notes per canto (cleanest allegory)
 *   - Books III–VI: 1–3 per canto
 *   - Mutabilitie Cantos: 2–3 per canto (densely philosophical, brief)
 *   ≈ 120–180 allegory notes across the whole poem.
 *
 * Seed entries below cover Book I canto i — the demo-critical opening —
 * as templates for the Part 4 annotation pass. Additional notes are
 * generated by the Part 4 pipeline (Opus for the ten named clusters,
 * Sonnet for the rest), patterned on these seeds.
 */

import type { FaerieQueeneSpeaker } from "./speakers"

/** Anchor into the poem's four-level structural hierarchy. */
export interface AnchorRef {
  book: number          // 1–6, or 7 for Mutabilitie
  canto: number         // 1–12 (or 6/7 for Mutabilitie)
  stanza?: number       // 1-based; absent = canto-level note
  line?: number         // 1–9; absent = stanza-level note
  /** Optional range end; if present, the note spans [stanza.line, endStanza.endLine]. */
  endStanza?: number
  endLine?: number
}

/** Types of allegorical reading. A note usually carries several. */
export type AllegoryReadingType =
  | "moral"         // virtue/vice personification — what the figure teaches
  | "theological"   // Christian doctrine — grace, sin, faith, works
  | "political"     // Elizabethan politics — the queen, Ireland, Mary, Spain
  | "typological"   // Old-Testament-prefigures-New figuration; Revelation
  | "personal"      // Spenser's own biography; Ralegh, Grey, Ireland
  | "literary"      // acknowledged inheritance (Ariosto, Virgil, Ovid, Chaucer, Bible)

export interface AllegoryReading {
  type: AllegoryReadingType
  /** 1–3 sentences of interpretation. Honest about debate where debate exists. */
  reading: string
  /** Optional scholarly authority. MUST be verifiable — do not fabricate. */
  authority?: string
}

export interface AllegoryNote {
  id: string
  anchor: AnchorRef
  /** The figure, place, or passage being read — a short descriptive label. */
  subject: string
  /** Optional speaker id(s) the note concerns (keys into FAERIE_QUEENE_SPEAKERS). */
  speakerIds?: string[]
  /** What happens at the plot level — the story-as-story. 1–2 sentences. */
  literalNote: string
  /** The layered readings. Order is conventional: moral → theological → typological → political → personal → literary. */
  readings: AllegoryReading[]
  /** Optional cross-references to passages elsewhere in Spenser, or to other books in the catalog. */
  crossReferences?: Array<{
    bookId: string       // tome book id, e.g. "orlando-furioso", "paradise-lost"
    anchor?: string      // e.g. "canto-1 stanza-42" or "book-4 line-268"
    note: string
  }>
}

/**
 * Seed entries — Book I canto i, the demo-critical opening. These serve
 * as the template for Part 4 annotation generation; the Opus run for
 * "Book I canto i (opening)" extends this seed set.
 */
export const ALLEGORY_NOTE_SEEDS: AllegoryNote[] = [
  {
    id: "fq-1-1-redcrosse-introduction",
    anchor: { book: 1, canto: 1, stanza: 1 },
    subject: "The Redcrosse Knight — opening portrait",
    speakerIds: ["Redcrosse"],
    literalNote:
      "A young knight rides across a plain, armed in old battle-scarred armor " +
      "he has never himself wielded, with a bloody cross on breast and shield — " +
      "the \"deare remembrance of his dying Lord.\" He is bound on a great " +
      "adventure set by Gloriana, the Faerie Queene.",
    readings: [
      {
        type: "moral",
        reading:
          "Redcrosse is Holiness — the virtue Book I allegorizes — at the " +
          "beginning of its quest, and therefore untested. The armor he has " +
          "\"never wielded\" is the Pauline armor of God (Ephesians 6:10–17), " +
          "received but not yet proved in combat. The book traces the virtue's " +
          "growth from formal possession to lived habit.",
      },
      {
        type: "theological",
        reading:
          "He is Everyman — the Christian soul on pilgrimage, carrying the " +
          "Cross as emblem of a redemption he has not yet earned. The old " +
          "\"dints of deepe woundes\" in his armor are the marks of every " +
          "Christian who has worn this armor before him; they do not belong " +
          "to his story, and they foreshadow the falls he will suffer.",
      },
      {
        type: "typological",
        reading:
          "He is St. George, patron saint of England, called to kill the " +
          "dragon who besieges Una's parents' kingdom (revealed at canto xii " +
          "to be the dragon of Revelation 20). The typological chain — Adam / " +
          "St. George / every Christian / Redcrosse — is one Spenser makes " +
          "explicit at the House of Holiness (I.x).",
      },
      {
        type: "political",
        reading:
          "As St. George, he is England itself — Protestant, militant, on " +
          "quest for Elizabeth-as-Gloriana. The reader can hear the poem " +
          "beginning to identify the Christian soul's war with sin and " +
          "England's war with Rome; the two allegories operate at once.",
      },
    ],
    crossReferences: [
      {
        bookId: "paradise-lost",
        anchor: "book-4",
        note:
          "Milton's first view of Satan in Eden (Paradise Lost IV) answers " +
          "this opening — where Spenser's untested knight wears armor he has " +
          "never wielded, Milton's Satan wears angelic form he has already " +
          "ruined. The two openings bracket English Protestant epic.",
      },
    ],
  },

  {
    id: "fq-1-1-una",
    anchor: { book: 1, canto: 1, stanza: 4, endStanza: 6 },
    subject: "Una — the companion",
    speakerIds: ["Una"],
    literalNote:
      "A lady on a white ass, leading a snow-white lamb, follows Redcrosse " +
      "at slow pace. She is royal — daughter of a king whose lands a dragon " +
      "has seized — and she rides veiled in black despite her inner radiance.",
    readings: [
      {
        type: "moral",
        reading:
          "Una is singleness — truth-as-unity — against Duessa's doubleness. " +
          "Her name means \"one.\" The pair Una/Duessa is the poem's " +
          "first and most load-bearing allegorical binary.",
      },
      {
        type: "theological",
        reading:
          "Una is the true Church — the one (Protestant) faith — leading her " +
          "lamb (Christ, by typology from Revelation) through a world that " +
          "mistakes her for her sister Duessa (the Roman Church). The black " +
          "veil over radiant beauty images the true Church suffering under " +
          "persecution, misrecognized in the world.",
        authority: "Standard reading since the 17c; see any scholarly edition.",
      },
      {
        type: "typological",
        reading:
          "She echoes the woman clothed with the sun of Revelation 12, " +
          "persecuted by the dragon. This sets up the book's governing " +
          "apocalyptic frame, which pays off in the dragon-fight at I.xi–xii.",
      },
    ],
  },

  {
    id: "fq-1-1-wandring-wood",
    anchor: { book: 1, canto: 1, stanza: 7, endStanza: 13 },
    subject: "The Wandering Wood — Error's forest",
    literalNote:
      "Seeking shelter from a sudden storm, Redcrosse and Una enter a thick " +
      "wood whose many winding paths confuse them; they are led deeper by the " +
      "pleasant variety of trees, each named and catalogued by the narrator, " +
      "until they are lost and reach the cave of the monster Error.",
    readings: [
      {
        type: "moral",
        reading:
          "The wood is the moral condition of untested virtue — one misses " +
          "the way by pursuing pleasant variety rather than holding to a " +
          "single path. The tree-catalogue (thirteen species, each with a " +
          "cultural association) is Spenser's inheritance of a Chaucerian " +
          "catalogue, but here it is a *seduction* — the beauty of the " +
          "catalogue figures the seductiveness of mere variety over truth.",
      },
      {
        type: "theological",
        reading:
          "To enter the Wood of Error is to mistake any single created good " +
          "for the highest good — the Augustinian definition of sin as " +
          "disordered love. The wood is not evil in itself; the knight's " +
          "choice to wander rather than press on makes it so.",
      },
      {
        type: "literary",
        reading:
          "The wood answers Dante's \"selva oscura\" — Inferno's opening " +
          "forest — but secularized and Protestantized: no Virgil-guide " +
          "appears; Redcrosse must learn to navigate the allegory himself. " +
          "The tree-catalogue is borrowed from Chaucer's Parliament of Fowls.",
      },
    ],
    crossReferences: [
      {
        bookId: "the-divine-comedy",
        anchor: "inferno canto-1",
        note:
          "Spenser's Wood of Error deliberately re-sets Dante's selva " +
          "oscura — a lost knight in a confusing wood — but the resolution " +
          "differs radically: Dante receives Virgil; Redcrosse must kill " +
          "Error himself.",
      },
    ],
  },

  {
    id: "fq-1-1-error",
    anchor: { book: 1, canto: 1, stanza: 14, endStanza: 28 },
    subject: "Error — the monster and her brood",
    speakerIds: ["Error"],
    literalNote:
      "Redcrosse enters Error's cave, finds a half-woman half-serpent " +
      "suckling a thousand monstrous young; when he strikes her, she vomits " +
      "a flood of black liquid full of books, papers, and frogs, and her " +
      "brood swarm him until he beheads her and the young devour her body.",
    readings: [
      {
        type: "moral",
        reading:
          "Error is the first vice Holiness meets: intellectual falsehood, " +
          "not sensual temptation. That Holiness begins with a test of " +
          "doctrine rather than desire is itself a Protestant claim — " +
          "error of belief precedes every other sin.",
      },
      {
        type: "theological",
        reading:
          "The books and papers vomited up are Roman Catholic polemic — " +
          "the specific Protestant reading is unmistakable to a 1590 " +
          "reader. The brood-devouring-the-mother closing image: " +
          "error finally destroys itself on its own excess.",
      },
      {
        type: "political",
        reading:
          "Redcrosse, shining in mail, killing the serpent-woman whose " +
          "brood are Roman books, is England killing the Roman Church on " +
          "its own soil — the Armada had been defeated two years before " +
          "publication, and this is the theological echo of that victory.",
      },
      {
        type: "literary",
        reading:
          "Error is a composite of the Hydra (classical), the whore of " +
          "Babylon (Revelation), and the Ovidian Echidna. Spenser " +
          "assembles monsters more than he invents them; annotation " +
          "should surface the sources at each component.",
      },
    ],
  },
]

/**
 * Group seed entries by (book, canto) for the reader component's drawer.
 */
export function allegoryNotesForCanto(book: number, canto: number): AllegoryNote[] {
  return ALLEGORY_NOTE_SEEDS.filter(
    (n) => n.anchor.book === book && n.anchor.canto === canto,
  )
}

/** Total count (used by verification gate Part 9 step 7). */
export const ALLEGORY_NOTE_COUNT = ALLEGORY_NOTE_SEEDS.length

/** Speaker-id validator — ensures any referenced speaker exists in the palette. */
export function validateSpeakerReferences(
  notes: AllegoryNote[],
  validIds: Set<string>,
): { valid: boolean; missing: string[] } {
  const missing: string[] = []
  for (const n of notes) {
    for (const id of n.speakerIds ?? []) {
      if (!validIds.has(id)) missing.push(`${n.id}: ${id}`)
    }
  }
  return { valid: missing.length === 0, missing }
}

// Type re-export so downstream code (Part 4 annotation pipeline) can import both.
export type { FaerieQueeneSpeaker }
