/**
 * Aeneid chapter trials — Books I through XII (chapterIndex 0..11) plus
 * the "Aeneid Master Trial" (chapterIndex 12) that awards the Pius Aeneas
 * seal, and the "Classical Triad Trial" (chapterIndex 13) — a capstone
 * trial available when the reader has completed all three epics (Iliad,
 * Odyssey, Aeneid), which awards the Epic Succession seal.
 *
 * These are merged at lookup time by `getQuestionsForChapter` in
 * chapter-questions.ts, following the Odyssey pattern. Schema matches
 * `ChapterQuestion` in that file.
 */

import type { ChapterQuestion } from "./chapter-questions"

export const AENEID_TRIALS: Record<number, ChapterQuestion[]> = {
  // ── Book I ───────────────────────────────────────────────────────────
  0: [
    { id: "aeneid-1-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Virgil's opening three words — *Arma virumque canō* — compress which two Homeric poems into a single literary claim?",
      options: ["Works and Days + Theogony", "Iliad + Odyssey", "Catullus + Horace", "Aeschylus + Sophocles"],
      correctIndex: 1,
      explanation: "*Arma* (war) is the Iliad's subject; *virum* (the man) is the Odyssey's subject; *canō* (I sing) collapses the Homeric invocation formula. Virgil names both predecessors in three words." },
    { id: "aeneid-1-2", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Who or what causes the Book I storm that wrecks the Trojan fleet on the Libyan coast?",
      options: ["Poseidon in a rage", "Juno, by bribing Aeolus", "An accident of weather", "Athena punishing the Trojans"],
      correctIndex: 1,
      explanation: "Juno bribes Aeolus (keeper of the winds) with a nymph-bride to unleash the storm. The bribery scene is the Aeneid's first piece of divine machinery and a direct reworking of Homer's Aeolus episode in Odyssey X." },
    { id: "aeneid-1-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The line *sunt lacrimae rerum* (Aeneid I.462) is spoken by Aeneas as he sees murals depicting the fall of Troy on the walls of Juno's temple in Carthage.",
      correctBool: true,
      explanation: "The scene is one of the Aeneid's most self-conscious moments: the hero encounters his own backstory as public art in a foreign temple, dedicated to the goddess who hates him. Virgil lets the irony stand unexplained." },
  ],
  // ── Book II ──────────────────────────────────────────────────────────
  1: [
    { id: "aeneid-2-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Who warns the Trojans against the wooden horse with the line 'I fear the Greeks, even when they bring gifts'?",
      options: ["Cassandra", "Laocoön", "Hector's ghost", "Sinon"],
      correctIndex: 1,
      explanation: "Laocoön's *Timeō Danaōs et dōna ferentēs* is one of the four most-quoted Latin phrases. The truth-teller is immediately killed by divine serpents — one of the Aeneid's sharpest theological puzzles." },
    { id: "aeneid-2-2", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Who kills Priam at the altar on Troy's last night?",
      options: ["Agamemnon", "Odysseus", "Pyrrhus (son of Achilles)", "Diomedes"],
      correctIndex: 2,
      explanation: "Pyrrhus (also called Neoptolemus) drags Priam to the altar by his hair and kills him. Shakespeare's Hamlet asks the Player for this exact scene in II.ii of *Hamlet*." },
    { id: "aeneid-2-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Aeneas carries Anchises out of burning Troy on his shoulders and holds Ascanius by the hand. What Roman virtue is this tableau meant to define?",
      options: ["*Fortitudo* (courage)", "*Pietas* (duty to gods, parents, country, future)", "*Gravitas* (seriousness)", "*Virtus* (manliness)"],
      correctIndex: 1,
      explanation: "*Pietas* fuses duty to the gods, duty to parents, duty to country, and duty to descendants in a single virtue. Three generations in one image is the physical definition of the word." },
  ],
  // ── Book III ─────────────────────────────────────────────────────────
  2: [
    { id: "aeneid-3-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Whom do the Trojans find at Buthrotum, living in a miniature replica of Troy?",
      options: ["Cassandra", "Helen and Menelaus", "Andromache, now married to Helenus", "Aeneas's mother Venus"],
      correctIndex: 2,
      explanation: "Andromache — Hector's widow, once a captive of Pyrrhus — is now remarried to Helenus (another son of Priam) and rules a tiny Trojan diaspora. It is one of the Aeneid's most pathos-laden scenes." },
    { id: "aeneid-3-2", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The Trojans find a Greek named Achaemenides on Sicily — a survivor whom Odysseus left behind at the Cyclops's cave — and take him aboard.",
      correctBool: true,
      explanation: "The Achaemenides scene is Virgil's most literal Homeric interpolation: a character from Odyssey IX picked up and rescued by the Trojan fleet. It signals the Aeneid's dissolving of the Greek/Trojan enmity into a Roman universalism." },
    { id: "aeneid-3-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Book III ends with the quietest of its losses. What is it?",
      options: ["The loss of Ascanius", "The death of Creusa", "The death of Anchises at Drepanum", "The burning of the Trojan fleet"],
      correctIndex: 2,
      explanation: "Anchises dies at Drepanum in Sicily; Virgil marks it in three lines. The under-description is deliberate — Aeneas, narrating, is a man whose voice breaks at his father's name." },
  ],
  // ── Book IV ──────────────────────────────────────────────────────────
  3: [
    { id: "aeneid-4-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Which pair of goddesses arranges the storm that drives Dido and Aeneas into the same cave?",
      options: ["Juno and Venus", "Minerva and Diana", "Juno and Diana", "Venus and Aphrodite"],
      correctIndex: 0,
      explanation: "Juno wants to delay Aeneas's Italian destiny; Venus wants her son sheltered and Dido bound to protect him. The two goddesses collaborate at cross-purposes — and Dido pays the cost." },
    { id: "aeneid-4-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Dido's simile of the wounded deer — struck by an *ignāra* (unknowing) shot, running through the forest with the arrow still in her side — resonates in what Renaissance sonnet?",
      options: ["Sidney's 'Astrophil and Stella 31'", "Wyatt's 'Whoso list to hunt, I know where is an hind'", "Spenser's 'Amoretti 75'", "Shakespeare's Sonnet 130"],
      correctIndex: 1,
      explanation: "Wyatt's 1535 sonnet addresses Anne Boleyn under Henry VIII's court in the image of Virgil's deer. Three traditions — Virgil's Dido, Petrarch's Laura, Wyatt's England — meet in the one poem." },
    { id: "aeneid-4-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "In which circle of Dante's Inferno does Dido appear?",
      options: ["Limbo (I) — the virtuous pagans", "The lustful (V) — those ruled by passion", "The suicides (XIII) — lodged in trees", "The falsifiers (XXX) — Virgil's Sinon's neighborhood"],
      correctIndex: 1,
      explanation: "Dante places Dido in Inferno V among the lustful — the circle where Francesca also appears. Dante's Virgil names her. The placement is Dante's direct response to Aeneid IV." },
  ],
  // ── Book V ───────────────────────────────────────────────────────────
  4: [
    { id: "aeneid-5-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Book V's funeral games are held for whom?",
      options: ["Palinurus", "Dido", "Anchises (one-year anniversary)", "Creusa"],
      correctIndex: 2,
      explanation: "The games on Sicily mark the anniversary of Anchises's death. Virgil is directly rewriting Iliad XXIII's funeral games for Patroclus — same structure, different beloved dead." },
    { id: "aeneid-5-2", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Palinurus, Aeneas's helmsman, dies as the price Neptune exacts for safe passage to Italy — he is lulled overboard by the god of Sleep.",
      correctBool: true,
      explanation: "The ethical weight of the scene is that Palinurus has done nothing wrong; he is the *most faithful* crew member, the one who stays at his post when Sleep tries to pull him away. The universe of the Aeneid extracts the price from the innocent." },
  ],
  // ── Book VI ──────────────────────────────────────────────────────────
  5: [
    { id: "aeneid-6-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Whom does Aeneas meet in the Fields of Mourning, and how does she respond?",
      options: ["Creusa, who warmly greets him", "Dido, who turns away in silence", "Helen, who begs his forgiveness", "Andromache, who weeps with him"],
      correctIndex: 1,
      explanation: "Dido's silent shade turning away is one of the most morally devastating scenes in classical literature. Aeneas apologizes at last; she is not required to forgive him." },
    { id: "aeneid-6-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Book VI ends with Anchises sending Aeneas out of the underworld through which gate?",
      options: ["The gate of horn (true dreams)", "The gate of ivory (false dreams)", "A cave-mouth at dawn", "The same gate he entered"],
      correctIndex: 1,
      explanation: "Virgil sends his hero out through the gate of false dreams. The choice has been debated for two thousand years and remains unresolved — every reading (symbolic, timing-based, politically critical) is still live in current scholarship." },
    { id: "aeneid-6-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The Latin phrase *tu Marcellus eris* — 'you shall be Marcellus' — addresses whom?",
      options: ["Augustus himself, as flattery", "The shade of Marcellus, Augustus's nephew who died at nineteen", "An unborn Roman emperor of the future", "Julius Caesar"],
      correctIndex: 1,
      explanation: "Marcus Claudius Marcellus, Augustus's heir, died in 23 BCE. Virgil addresses the dead youth's shade directly. Servius records that Octavia (Marcellus's mother) fainted when Virgil recited the passage." },
    { id: "aeneid-6-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Virgil's simile of souls at the Styx 'thick as autumn leaves' is picked up almost verbatim by which later poet?",
      options: ["Ovid in Metamorphoses", "Dante in Inferno III", "Statius in Thebaid", "Lucretius in De Rerum Natura"],
      correctIndex: 1,
      explanation: "Dante's Inferno III ('come d'autunno si levan le foglie') is a direct lift from Virgil. Milton then rewrites both in Paradise Lost I ('Thick as autumnal leaves…'). Three poets' leaves, one genealogy." },
  ],
  // ── Book VII ─────────────────────────────────────────────────────────
  6: [
    { id: "aeneid-7-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Which goddess sends the Fury Allecto to Italy to provoke the war?",
      options: ["Venus", "Minerva", "Juno", "Diana"],
      correctIndex: 2,
      explanation: "Juno, unwilling to accept the Italian settlement, goes to the underworld and dispatches Allecto — one of the three Furies — to poison Amata and enrage Turnus." },
    { id: "aeneid-7-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Virgil's Book VII catalogue of Italian warriors closes on which figure, in the position of honor?",
      options: ["Turnus", "Mezentius", "Camilla the Volscian warrior-maiden", "Messapus"],
      correctIndex: 2,
      explanation: "Camilla closes the catalogue. Virgil's gesture — ending the warrior-list on a woman — is a deliberate reversal of Iliadic convention and foreshadows her aristeia and death in Book XI." },
  ],
  // ── Book VIII ────────────────────────────────────────────────────────
  7: [
    { id: "aeneid-8-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Where does Aeneas travel upriver in Book VIII?",
      options: ["To Cumae, to meet the Sibyl", "To Pallanteum, to meet Evander — the future site of Rome", "To Carthage, to ask Dido for allies", "To Troy, for reinforcements"],
      correctIndex: 1,
      explanation: "Pallanteum, Evander's small Arcadian settlement on the Palatine hill, is the future site of Rome. Virgil writes a double-vision walking-tour where the reader sees the Forum-to-be as a goat-path." },
    { id: "aeneid-8-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The engravings on Aeneas's shield culminate in which specific historical scene?",
      options: ["The founding of Rome by Romulus", "The sack of Alba Longa", "The Battle of Actium (31 BCE) — Augustus defeating Antony and Cleopatra", "The death of Julius Caesar"],
      correctIndex: 2,
      explanation: "Actium is the center of the shield — the Augustan political program rendered in metalwork. The line that closes the book, *rērumque ignārus imāgine gaudet* ('ignorant of these matters, he rejoices in the image'), is one of Virgil's most interpretively charged." },
  ],
  // ── Book IX ──────────────────────────────────────────────────────────
  8: [
    { id: "aeneid-9-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "The night-raid in Book IX is Virgil's rewriting of which Iliadic episode?",
      options: ["The chariot race in Iliad XXIII", "The Doloneia in Iliad X", "The killing of Patroclus in Iliad XVI", "Priam's ransoming of Hector in Iliad XXIV"],
      correctIndex: 1,
      explanation: "Iliad X — where Odysseus and Diomedes raid the Trojan camp at night — is the template. Virgil uses the structure but reassigns the moral weight: his sympathetic pair is the *victim* of the night-raid's reversal." },
    { id: "aeneid-9-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Virgil's apostrophe *fortunati ambo* ('happy both') addresses whom?",
      options: ["Aeneas and Ascanius", "Nisus and Euryalus, just killed on the night-raid", "Dido and Sychaeus", "Hector and Andromache"],
      correctIndex: 1,
      explanation: "Virgil promises that his verse will keep Nisus and Euryalus alive 'as long as the house of Aeneas inhabits the unmoved rock of the Capitol.' The apostrophe has in fact delivered for two thousand years." },
  ],
  // ── Book X ───────────────────────────────────────────────────────────
  9: [
    { id: "aeneid-10-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Turnus kills Pallas (son of Evander) and strips which object from the corpse?",
      options: ["Pallas's helmet", "Pallas's sword-belt (baldric)", "Pallas's bow", "Pallas's armor"],
      correctIndex: 1,
      explanation: "The sword-belt will reappear on Turnus's shoulder in Book XII — and is the sight that reverses Aeneas's impulse to spare him. Virgil plants the fuse two books before it fires." },
    { id: "aeneid-10-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "In the Book X death of Lausus, which figure — surprisingly — is depicted weeping over an enemy's corpse?",
      options: ["Turnus", "Mezentius (already wounded)", "Aeneas", "Evander"],
      correctIndex: 2,
      explanation: "Aeneas weeps over Lausus — recognizing in his enemy's son the exact pietas that defined his own flight from Troy (Anchises on his shoulders). The Aeneid's most honest moment of enemy-sympathy." },
  ],
  // ── Book XI ──────────────────────────────────────────────────────────
  10: [
    { id: "aeneid-11-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "Camilla's death in Book XI is caused by what?",
      options: ["A javelin from Aeneas", "A treacherous arrow from the archer Arruns while Camilla pursues the gold-armored Chloreus", "A sword-thrust from Turnus", "A fall from her horse"],
      correctIndex: 1,
      explanation: "Camilla is distracted by Chloreus's ornate Phrygian armor — *femineō praedae ardēbat amōre*, 'burning with a feminine love of spoils.' Arruns, stalking her, throws the fatal javelin. Diana's nymph Opis then kills Arruns in vengeance." },
    { id: "aeneid-11-2", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The closing line of Camilla's death scene — *vītaque cum gemitū fugit indignāta sub umbrās* — is the same line that will close the entire Aeneid at Turnus's death in Book XII.",
      correctBool: true,
      explanation: "Virgil repeats the line verbatim (Aeneid XI.831 = XII.952) for both tragic enemy deaths. The formula signals that Camilla's and Turnus's deaths belong to the same moral category — warriors from the losing side departing indignant." },
  ],
  // ── Book XII ─────────────────────────────────────────────────────────
  11: [
    { id: "aeneid-12-1", type: "multiple_choice", difficulty: "Foundational", xpReward: 5,
      text: "The Iliadic model for the Book XII single combat between Aeneas and Turnus is which Homeric scene?",
      options: ["Iliad I: the quarrel of Achilles and Agamemnon", "Iliad VI: Hector and Andromache's farewell", "Iliad XXII: Achilles killing Hector", "Iliad XXIV: Priam ransoming Hector"],
      correctIndex: 2,
      explanation: "Virgil is rewriting Iliad XXII at the level of scene, speech, and simile. The Aeneid XII ↔ Iliad XXII pairing is the single most demonstrable literary-inheritance moment in the classical corpus." },
    { id: "aeneid-12-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What sight, at the book's climax, reverses Aeneas's impulse to spare Turnus's life?",
      options: ["Juno weeping in the clouds above", "The sword-belt Turnus stripped from Pallas", "Turnus's helmet catching the sun", "The blood of Lausus on Turnus's cloak"],
      correctIndex: 1,
      explanation: "Aeneas is 'hesitating' and 'more and more' being moved to mercy — until he sees Pallas's belt. He then kills Turnus 'in Pallas's name' (*Pallās tē immolat*). The reversal is the Aeneid's whole moral architecture in twenty lines." },
    { id: "aeneid-12-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "What is the final word of the Aeneid (as Latin), and what does it convey?",
      options: ["*pius* — 'pious,' confirming Aeneas's virtue", "*indignāta* — 'indignant,' describing Turnus's soul refusing to accept its death", "*Rōma* — naming the poem's goal", "*fātum* — 'fate'"],
      correctIndex: 1,
      explanation: "The last word of the poem is Turnus's soul being *indignāta* — unreconciled to the killing. Virgil closes on the victim's interior state, not the victor's triumph. Any reading of the Aeneid's ending has to contend with this word." },
  ],
  // ── Aeneid Master Trial (chapterIndex 12, awards Pius Aeneas seal) ────
  12: [
    { id: "aeneid-master-1", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "*Arma virumque cano* — the poem's opening three words — are a deliberate compression of which two Homeric predecessors?",
      options: ["Works and Days + Theogony", "Iliad + Odyssey", "Aeschylus's Oresteia + Persians", "Pindar's Olympian + Pythian Odes"],
      correctIndex: 1,
      explanation: "*Arma* is the Iliad; *virum* is the Odyssey; *canō* collapses Homer's two invocation-verbs. Virgil names both predecessors in three words." },
    { id: "aeneid-master-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The phrase *saevae memorem Iūnōnis ob īram* — 'because of cruel Juno's unforgetting wrath' — names which of the following?",
      options: ["A passing detail", "The engine of the entire poem's plot", "An Iliadic callback only", "A curse placed by Aphrodite"],
      correctIndex: 1,
      explanation: "Juno's *memor iram* drives twelve books of plot. Virgil names the cause in line 4; the resolution in Book XII is a negotiated absorption, not a removal, of her wrath." },
    { id: "aeneid-master-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which of these is NOT among the five canonical Virgilian authorial apostrophes (the moments the narrator directly addresses a character)?",
      options: ["Tu Marcellus eris (Book VI)", "Fortunati ambo (Book IX)", "Arma virumque cano (Book I)", "The Caieta invocation (Book VII)"],
      correctIndex: 2,
      explanation: "*Arma virumque cano* is the invocation to the Muse, not an apostrophe to a character. The five canonical apostrophes are Caieta (VII), Tu Marcellus eris (VI), Fortunati ambo (IX), the Lausus address (X), and the gates of sleep coda (VI)." },
    { id: "aeneid-master-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The line *hoc opus, hic labor est* — 'this is the task, this is the labor' — is delivered by whom, in which context?",
      options: ["Jupiter, warning Venus", "The Sibyl, warning Aeneas that descending to the underworld is easy but returning is hard", "Dido, on her pyre", "Aeneas, in his speech to Dido"],
      correctIndex: 1,
      explanation: "*Facilis descensus Averno… hoc opus, hic labor est* is the Sibyl's warning in Book VI.126–129. The second half of the line entered Latin culture as a standalone proverb." },
    { id: "aeneid-master-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "*Sunt lacrimae rerum* (Aeneid I.462) — one of the most translated lines in Latin poetry — is spoken where and by whom?",
      options: ["By Aeneas, looking at murals of Troy in Juno's temple in Carthage", "By Dido, on her pyre", "By Anchises, in Elysium", "By the Sibyl, at Cumae"],
      correctIndex: 0,
      explanation: "The line — 'there are tears for things,' or 'the world is a world of tears' — is spoken by Aeneas weeping in front of paintings of the Trojan War on the walls of Juno's temple. It is the Aeneid at its most untranslatable." },
    { id: "aeneid-master-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which figure in the poem is *contemptor divum* ('despiser of the gods')?",
      options: ["Turnus", "Mezentius, the exiled Etruscan tyrant and father of Lausus", "Drances, the Latin senator", "Arruns, the archer who kills Camilla"],
      correctIndex: 1,
      explanation: "Mezentius is the Aeneid's theological villain — and, in Book X, its most surprisingly recuperated one. When his son Lausus dies for him, Mezentius dies a grieving father mourned by the enemy who killed him." },
    { id: "aeneid-master-7", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The Book VI 'parade of heroes' ends on which figure, in the climactic position?",
      options: ["Julius Caesar", "Augustus himself", "Marcellus, Augustus's nephew who died at nineteen", "Aeneas, returned in glory"],
      correctIndex: 2,
      explanation: "Virgil's most politically charged set-piece ends on a dead teenager. The Augustan triumphalism of the parade is bordered on its far side by *tu Marcellus eris* — grief for a boy the regime lost." },
    { id: "aeneid-master-8", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which phrase from Aeneid VI.853 became Rome's imperial self-definition — quoted or invoked in every subsequent imperial tradition?",
      options: ["*Arma virumque canō*", "*Parcere subiectīs et dēbellāre superbōs* ('spare the submissive and subdue the proud')", "*Vīxī, et quem dederat cursum Fortūna perēgī* ('I have lived')", "*Sic itur ad astra* ('thus one goes to the stars')"],
      correctIndex: 1,
      explanation: "Anchises's formulation in the Elysian parade — *parcere subiectis et debellare superbos* — has been quoted by every empire wanting to justify itself and every critic wanting to indict one. Auden called it the sentence that 'sold Virgil to the Augustan regime forever.'" },
    { id: "aeneid-master-9", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which character does Dante place in Inferno V (the circle of the lustful)?",
      options: ["Camilla", "Dido", "Creusa", "Lavinia"],
      correctIndex: 1,
      explanation: "Dante places Dido in Inferno V as a direct response to Aeneid IV. Dante's Virgil names her. Dante's own Francesca, three cantos later, is his medieval answer to Virgil's Dido." },
    { id: "aeneid-master-10", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "In Book IX, Virgil addresses Nisus and Euryalus directly: *fortunati ambo!* — 'happy both!' What specifically does he promise them?",
      options: ["Elysium in the next world", "That his verse will preserve their names as long as Rome stands", "That Aeneas will build them a shrine", "That Jupiter will make them gods"],
      correctIndex: 1,
      explanation: "The promise is literary-civic: 'as long as the house of Aeneas inhabits the unmoved rock of the Capitol and the Roman father holds the *imperium*.' The poem is offering itself as the medium of their immortality." },
    { id: "aeneid-master-11", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Virgil's Book II reworks one major scene from the Iliad as a dream. Which?",
      options: ["The quarrel of Achilles and Agamemnon", "Hector's death and degradation (Iliad XXII)", "The night-raid on Rhesus", "The funeral of Patroclus"],
      correctIndex: 1,
      explanation: "Hector appears to Aeneas in a dream in the physical state of the Iliad's Book XXII — dust-blackened, the thongs through his feet where Achilles dragged him. The apparition tells Aeneas to flee: the Homeric warrior-code is being handed off to a different ethic." },
    { id: "aeneid-master-12", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Juno's surrender-terms at the end of Book XII include which condition?",
      options: ["Aeneas must marry Juturna", "Lavinium must be burned", "The Trojans must lose their name and language; the Italians keep theirs", "Rome must be founded in Sicily instead"],
      correctIndex: 2,
      explanation: "Juno concedes the Italian settlement on the condition that the Trojans vanish into the Latins they conquered. Rome is the outcome; but on Juno's terms, Rome is really *Italy with new blood*. The Trojan inheritance is partially dissolved." },
    { id: "aeneid-master-13", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The Book XII 'nightmare simile' — a warrior trying to run but finding his legs will not obey, tongue cleaving to the palate — describes whose interior state?",
      options: ["Aeneas before the duel", "Turnus in his final moments", "Juturna losing her brother", "Drances in the Latin senate"],
      correctIndex: 1,
      explanation: "Virgil's nightmare simile is the most-imitated psychological image in European epic. Turnus, divinely armed Aeneas closing on him, cannot run. The simile places the reader INSIDE the enemy's head thirty lines before the killing." },
    { id: "aeneid-master-14", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The sword-belt Turnus is wearing in his final moments — the sight that turns Aeneas from mercy to vengeance — was taken from whom?",
      options: ["Mezentius's son Lausus", "Evander's son Pallas", "The Arcadian ally Metabus", "The Trojan Nisus"],
      correctIndex: 1,
      explanation: "Book X: Turnus kills Pallas and strips the belt as a trophy. Book XII: Aeneas sees the belt on Turnus's shoulder, his hesitation dissolves, and he kills in Pallas's name. The whole ending of the poem pivots on this object." },
    { id: "aeneid-master-15", type: "multiple_choice", difficulty: "Scholar", xpReward: 20,
      text: "The final word of the poem — *indignāta* — describes whose interior state?",
      options: ["Aeneas's, as he strikes", "Turnus's soul, unreconciled to the killing", "Juno's, at her defeat", "Lavinia's, at the outcome"],
      correctIndex: 1,
      explanation: "The Aeneid closes on the defeated man's soul refusing to accept its death. Virgil's choice of *indignāta* (rather than *maesta* or *tristis*) is one of the most consequential word-choices in Latin poetry: the poem ends inside the enemy's grief, not the hero's triumph." },
  ],
  // ── Classical Triad Trial (chapterIndex 13, awards Epic Succession) ───
  // Unlocks only when the reader has also completed the Iliad and Odyssey.
  // Tests the reader on the *inheritance* across the three poems.
  13: [
    { id: "triad-1", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The Aeneid's Books I–VI reuse the structure of the ______, and Books VII–XII reuse the structure of the ______.",
      options: ["Theogony / Iliad", "Odyssey / Iliad", "Iliad / Odyssey", "Aeschylus's Oresteia / Euripides's Bacchae"],
      correctIndex: 1,
      explanation: "Virgil writes Books I–VI as his Odyssey (the wanderings) and Books VII–XII as his Iliad (the war in Italy). The second invocation at VII.37 names the switch: *maius opus moveō* — 'a greater work I set in motion.'" },
    { id: "triad-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Aeneid VI (the descent to the underworld) responds most directly to which Homeric book?",
      options: ["Iliad VI (Hector and Andromache)", "Iliad XXIII (funeral games)", "Odyssey XI (the Nekyia)", "Odyssey IX (the Cyclops)"],
      correctIndex: 2,
      explanation: "The Aeneid VI ↔ Odyssey XI pairing is the single most philosophically weighty cross-reference in classical epic. Odysseus summons the dead at the border; Aeneas goes all the way down. The civilizational difference is the different journey." },
    { id: "triad-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Virgil's Book XII single combat between Aeneas and Turnus is a formal rewriting of which Iliadic book?",
      options: ["Iliad I (the quarrel)", "Iliad XVI (the death of Patroclus)", "Iliad XXII (Achilles kills Hector)", "Iliad XXIV (the ransom)"],
      correctIndex: 2,
      explanation: "Homer's Iliad XXII ends in Achilles killing Hector and dragging his body; Iliad XXIV is the reconciliation. Virgil's Aeneid XII stops at the equivalent of Iliad XXII — there is no reconciliation scene, no Book XIII. The missing epilogue IS the argument." },
    { id: "triad-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which of these scenes has a direct Homer → Virgil → Dante inheritance chain at the level of an individual image?",
      options: ["The wooden horse", "The wrath of Achilles", "The three-fold embrace of a shade who slides through the hero's arms", "The shield of the greatest warrior"],
      correctIndex: 2,
      explanation: "Odyssey XI (Odysseus and Anticlea) → Aeneid II + VI (Aeneas and Creusa, Aeneas and Anchises) → Purgatorio II (Dante and Casella). One image, three poets, twenty-six centuries." },
    { id: "triad-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which Virgilian epithet has NO real Homeric counterpart — it expresses a specifically Roman virtue?",
      options: ["Swift-footed Achilles", "Polytropos Odysseus", "Pius Aeneas", "Rosy-fingered Dawn"],
      correctIndex: 2,
      explanation: "*Pius* fuses duty to gods, parents, country, and descendants in a single virtue. Homer's epithets describe physical qualities; Virgil's *pius* is moral. The shift from description to prescription is the single clearest marker of the Aeneid's Roman literary DNA." },
    { id: "triad-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The three classical epics each end differently. Which matches the pairings?",
      options: [
        "Iliad ends on a funeral (Hector); Odyssey ends on an embrace (Odysseus/Penelope); Aeneid ends on a killing (Turnus)",
        "All three end on funerals",
        "All three end on reconciliations",
        "Iliad ends on a killing; Odyssey ends on a storm; Aeneid ends on a founding",
      ],
      correctIndex: 0,
      explanation: "The Iliad closes Book XXIV with Hector's funeral. The Odyssey closes Book XXIII's reunion and Book XXIV's settlement. The Aeneid closes on Turnus's soul fleeing 'indignant to the shades.' The three endings are the three civilizations' final verdicts on their own stories." },
    { id: "triad-7", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The night-raid of Nisus and Euryalus (Aeneid IX) reworks which Iliadic episode?",
      options: ["The Doloneia (Iliad X)", "The funeral games (Iliad XXIII)", "Thetis's lament (Iliad XVIII)", "The wall-and-ships fighting (Iliad XII–XV)"],
      correctIndex: 0,
      explanation: "Iliad X: Odysseus and Diomedes raid the Trojan camp at night, kill the spy Dolon, slaughter the Thracian king Rhesus and his men in their sleep. Virgil adopts the form, inverts the moral valence: his pair is killed by the raid." },
    { id: "triad-8", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Virgil's shield of Aeneas (Book VIII) deliberately differs from the shield of Achilles (Iliad XVIII) in which way?",
      options: ["Virgil's is larger", "Homer's shield depicts the whole human world; Virgil's depicts Roman political history specifically", "Virgil's shield is not made by a god", "Homer's shield is not round"],
      correctIndex: 1,
      explanation: "Homer's shield contains a city at peace, a city at war, harvests, dances, and the river of Ocean — the cosmos. Virgil's narrows to Roman national history culminating at Actium. The reduction is the point: the universe has been rewritten as a national narrative." },
    { id: "triad-9", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Aeneas's Book VI Dido-encounter (the shade who turns away silent) is an explicit structural echo of which Odyssean shade-encounter?",
      options: ["Odysseus's mother Anticlea", "The prophet Tiresias", "Ajax, who also turns away in silence after the quarrel over Achilles's armor", "Agamemnon's shade"],
      correctIndex: 2,
      explanation: "Odyssey XI.541–567: Odysseus tries to speak to Ajax in Hades; Ajax turns away silent, still furious about the Achilles's-armor judgment. Virgil's Dido scene is a deliberate Homeric homage with the gender and moral stakes reassigned." },
    { id: "triad-10", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which figure does Virgil NOT reuse as a character in the Aeneid, despite being an Iliadic major?",
      options: ["Andromache", "Helen", "Achilles (as a present-tense character)", "Priam"],
      correctIndex: 2,
      explanation: "Achilles is dead before the Aeneid begins; he is referenced throughout but never appears. His son Pyrrhus (Neoptolemus) carries the Achillean violence into Book II. Andromache, Helen, and Priam all appear — Andromache in Book III at Buthrotum, Helen glimpsed in Book II, Priam killed at the altar." },
    { id: "triad-11", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which pair of deaths in the Aeneid shares verbatim the same closing Latin line — *vītaque cum gemitū fugit indignāta sub umbrās*?",
      options: ["Dido's and Turnus's", "Pallas's and Lausus's", "Camilla's and Turnus's", "Creusa's and Anchises's"],
      correctIndex: 2,
      explanation: "Aeneid XI.831 (Camilla) = XII.952 (Turnus). Virgil repeats the line verbatim to mark that both deaths belong to the same moral category — warriors from the losing side leaving the world unreconciled." },
    { id: "triad-12", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Which Homeric hero is mentioned in the Aeneid almost exclusively as an object of Trojan curses — the architect of the wooden horse?",
      options: ["Agamemnon", "Ulysses (Odysseus)", "Diomedes", "Achilles"],
      correctIndex: 1,
      explanation: "Virgil's Trojans remember Ulysses with venom. Aeneas, Achaemenides, and Deiphobus all speak of him as the engineer of Troy's fall. His Odyssean character is almost invisible; what carries over is the Iliadic figure of wily intelligence weaponized against the Trojans." },
    { id: "triad-13", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "Dante places Virgil in which circle of the Commedia's afterlife?",
      options: ["Inferno IV (Limbo — the virtuous pagans)", "Purgatorio X (the proud)", "Paradiso V (the Moon sphere)", "He is not depicted"],
      correctIndex: 0,
      explanation: "Limbo (Inferno IV) is the best seat available to a virtuous pagan. Dante's placement is a considered theological judgment: Virgil's Aeneid contains everything of pre-Christian wisdom but cannot reach salvation as Dante understands it. The Book XII ending — violence without reconciliation — is part of what Dante is responding to." },
    { id: "triad-14", type: "multiple_choice", difficulty: "Scholar", xpReward: 15,
      text: "The simile of souls 'thick as autumn leaves' migrates through which genealogy?",
      options: ["Iliad VI → Aeneid VI → Inferno III → Paradise Lost I", "Only Virgil and Milton", "Homer and Dante only", "Virgil and Dante only"],
      correctIndex: 0,
      explanation: "Iliad VI.146 ('as is the generation of leaves, so is that of men') → Aeneid VI.309 (souls at the Styx) → Inferno III.112 ('come d'autunno si levan le foglie') → Paradise Lost I.302 ('Thick as autumnal leaves…'). Four poets, one image, three thousand years." },
    { id: "triad-15", type: "multiple_choice", difficulty: "Scholar", xpReward: 25,
      text: "Which phrase most precisely captures what makes the Aeneid's inheritance from Homer distinct from mere imitation?",
      options: [
        "Virgil compresses Homer into half the length",
        "Virgil preserves the Homeric scenes but reassigns their moral valence — the Roman ethic of pietas displacing the Greek warrior-code",
        "Virgil writes in Latin, Homer in Greek",
        "Virgil uses heroic couplets (in Dryden), Homer uses dactylic hexameter",
      ],
      correctIndex: 1,
      explanation: "The Aeneid is Virgil rewriting Homer's scenes with the moral sympathies redistributed and the civilizational ideals swapped out. The Iliadic warrior-code — die fighting where you stand — is displaced by the Roman ethic of *pietas* as survival for the sake of the future. The forms are Homeric; the arguments are Virgilian." },
  ],
}

/** Does the reader qualify for the Classical Triad Trial (chapter 13)?
 *  Requires completion of the Iliad, the Odyssey, and the Aeneid. */
export function canTakeClassicalTriadTrial(completedBookIds: string[]): boolean {
  return (
    completedBookIds.includes("the-iliad") &&
    completedBookIds.includes("the-odyssey") &&
    completedBookIds.includes("the-aeneid")
  )
}
