/**
 * The Faerie Queene chapter trials — one per book (Books I–VI + Mutabilitie),
 * each placed at the LAST canto of the book so reaching the trial requires
 * having read the book through. Plus a Master Trial ("Gloriana's Knight"
 * seal) and two stretch capstones.
 *
 * Post-canto-split chapter index mapping:
 *   ch-13   Book I trial          (after Canto XII — Dragon-fight + betrothal)
 *   ch-25   Book II trial         (after Canto XII — Bower of Bliss)
 *   ch-37   Book III trial        (after Canto XII — House of Busirane)
 *   ch-49   Book IV trial         (after Canto XII — Florimell reunited)
 *   ch-61   Book V trial          (after Canto XII — Grantorto defeated)
 *   ch-73   Book VI trial         (after Canto XII — Blatant Beast escapes)
 *   ch-75   Mutabilitie trial     (after Canto VIII Unperfite)
 *   ch-76   Master Trial          ("Gloriana's Knight" seal — 18 Q)
 *   ch-77   Renaissance Epic stretch (Orlando Furioso + Faerie Queene; "Romance Inheritance" seal)
 *   ch-78   Epic Succession stretch (Beowulf + Iliad + Odyssey + Aeneid + Divine Comedy
 *                                    + Orlando Furioso + Faerie Queene + Paradise Lost + Don Juan)
 *
 * Schema matches `ChapterQuestion`. Merged at lookup time by
 * `getQuestionsForChapter` in chapter-questions.ts. Difficulty is
 * Foundational (5 XP) or Scholar (10 XP); Foundational dominates Book
 * trials, Scholar dominates the Master and stretch trials.
 */

import type { ChapterQuestion } from "./chapter-questions"

export const FAERIE_QUEENE_TRIALS: Record<number, ChapterQuestion[]> = {
  // ── Book I — Holiness (Redcrosse Knight) ─────────────────────────────
  13: [
    { id: "fq-bk1-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What virtue does Book I allegorize, and through which titular knight?",
      options: ["Temperance / Sir Guyon", "Chastity / Britomart", "Holiness / Redcrosse Knight", "Justice / Sir Artegall"],
      correctIndex: 2,
      explanation: "Book I is The Legend of the Knight of the Red Cross, or of Holiness. Redcrosse — bearing the cross of St. George on his breast — is a composite figure: private Christian soul, England's national patron, and the Everyman in Pauline armor (Ephesians 6)." },
    { id: "fq-bk1-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Spenser invented a stanza form for The Faerie Queene. What is its structure?",
      options: ["Eight lines, ottava rima (ABABABCC)", "Nine lines (ABABBCBCC) with the ninth line an alexandrine", "Fourteen lines (Petrarchan sonnet)", "Heroic couplets (AA BB CC)"],
      correctIndex: 1,
      explanation: "The Spenserian stanza: eight iambic-pentameter lines plus a ninth alexandrine (iambic hexameter), rhyming ABABBCBCC. The closing alexandrine is the form's signature; it summarizes, deflates, or amplifies the preceding eight." },
    { id: "fq-bk1-3", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "In Canto I, what monster does Redcrosse kill in the Wandring Wood?",
      options: ["Orgoglio (Pride)", "Error — half woman, half serpent, who vomits books and papers", "The Dragon (which appears at the book's end, not in Canto I)", "Despair"],
      correctIndex: 1,
      explanation: "Error is a hybrid serpent-woman whose vomited books and papers identify her, in Spenser's Protestant polemic, with the Roman Church's theological writings. The composite design draws on Hesiod's Echidna, Revelation 12's dragon, and Genesis 3's serpent." },
    { id: "fq-bk1-4", type: "true_false", difficulty: "Apprentice", xpReward: 5,
      text: "Una and Duessa form Book I's central allegorical pair, representing the true Church and the false Church.",
      correctBool: true,
      explanation: "Una (Latin 'one') is true faith, the one true Church; Duessa (Latin 'two/double') is doubleness, falsehood, and — in Spenser's Protestant frame — the Roman Church. Their pair-logic structures the book's allegory; Duessa is finally unmasked in Canto VIII." },
    { id: "fq-bk1-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "In the Cave of Despair (Canto IX), what scriptural-theological doctrine does Una invoke to refuse Despair's argument?",
      options: ["The doctrine of works-based salvation", "The doctrine of election (the elect cannot be damned because grace is irrevocable)", "The doctrine of purgatory", "The doctrine of moral example"],
      correctIndex: 1,
      explanation: "Una's question — 'In heavenly mercies hast thou not a part? / Why shouldst thou then despeire, that chosen art?' — invokes the Calvinist-Reformed doctrine of election. Despair's accumulated-sin arithmetic is irrelevant if grace is logically prior to works; cf. Romans 5:20." },
    { id: "fq-bk1-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The three-day Dragon-fight in Canto XI is structured around what allegorical pattern?",
      options: ["The three temptations of Christ", "The three days of Christ's tomb (Passion-Resurrection); Redcrosse falls and rises each night, healed by the Well of Life and the Tree of Life", "The Trinity", "The three theological virtues (Faith, Hope, Charity)"],
      correctIndex: 1,
      explanation: "Each night Redcrosse 'dies' (defeated, falls backward into the Well of Life on night 1, at the Tree of Life on night 2); each morning he rises restored. The structure is Passion-Resurrection: the Christian soul's combat with Satan won by participation in Christ's death-and-rising via baptism (Well) and Eucharist (Tree)." },
    { id: "fq-bk1-7", type: "passage_id", difficulty: "Scholar", xpReward: 10,
      text: "Which Spenserian line — the most famous in The Faerie Queene — is spoken by the figure of Despair in Canto IX?",
      options: ["'A gentle knight was pricking on the plaine'", "'Sleepe after toyle, port after stormie seas, / Ease after warre, death after life does greatly please'", "'Lo! I, the man whose Muse whylome did maske'", "'Of Man's first disobedience'"],
      correctIndex: 1,
      explanation: "Despair's seductive carpe-mortem rhetoric — built on three felt experiences (sleep/toil, port/storm, ease/war) leading to a fourth claim (death/life) — is the canto's central temptation. The line's rhetorical power IS the danger; Spenser stages the persuasion's pull on the reader as well as on the knight." },
    { id: "fq-bk1-8", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Bunyan's Giant Despair, who imprisons Christian and Hopeful in Doubting Castle, descends directly from which canto?",
      options: ["Faerie Queene I.iv (House of Pride)", "Faerie Queene I.vii (Orgoglio)", "Faerie Queene I.ix (Cave of Despair)", "Faerie Queene I.xii (the Dragon-fight)"],
      correctIndex: 2,
      explanation: "Bunyan's Pilgrim's Progress (1678) borrows the personification, the rhetorical-rather-than-physical combat, and the deliverance-by-named-virtue (Hope/Una) directly from Spenser. The Giant Despair / Doubting Castle episode is the most-recognized inheritance from Spenser into popular Protestant English allegory." },
    { id: "fq-bk1-9", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "How does Book I close (Canto XII)?",
      options: ["With Redcrosse's death in combat", "With the Dragon slain, Una's parents freed, and Redcrosse's betrothal to Una", "With Redcrosse becoming king of Faery Land", "With Redcrosse retiring to a hermitage"],
      correctIndex: 1,
      explanation: "Book I ends celebratively: the Dragon is dead, the kingdom is restored, and Redcrosse is betrothed to Una — but he must return to Gloriana's court for six more years of service before the marriage can be sealed. The arc closes on completed quest + deferred wedding." },
  ],

  // ── Book II — Temperance (Sir Guyon) ─────────────────────────────────
  25: [
    { id: "fq-bk2-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Who is Guyon's near-constant companion through Book II, and what does he allegorize?",
      options: ["Britomart — Chastity", "The Palmer — Reason", "Una — Truth", "Prince Arthur — Magnificence"],
      correctIndex: 1,
      explanation: "The Palmer (= 'pilgrim,' a religious traveler) accompanies Guyon as the figure of Reason. He carries the staff that subdues passions; his absence in Canto VI–VII forces Guyon to face Mammon's temptations alone with internalized temperance." },
    { id: "fq-bk2-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "In the Cave of Mammon (Canto VII), what three temptations does the money-god offer Guyon?",
      options: ["Wealth / power (Philotime, the chain of ambition) / forbidden fruit (Garden of Proserpina)", "Lust / gluttony / sloth", "A throne / a horse / an army", "Doubt / despair / pride"],
      correctIndex: 0,
      explanation: "Mammon offers wealth (the heap of gold), then ambition (Philotime, the lady at the top of a golden chain whose links are degrees of dignity), then the apples of Proserpina's garden (the Eden temptation in classical-underworld dress). Guyon refuses all three across three days underground." },
    { id: "fq-bk2-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The figure of Mammon takes his name from which biblical passage?",
      options: ["Genesis 3 (the serpent)", "Matthew 6:24 — 'Ye cannot serve God and mammon'", "Revelation 13 (the beast from the sea)", "Job 41 (Leviathan)"],
      correctIndex: 1,
      explanation: "Matthew 6:24 (parallel Luke 16:13) personifies wealth as a rival god to whom one cannot give simultaneous service. Spenser makes Mammon a literal personage — 'God of the world and worldlings I me call' — who admits the rivalry and offers terms." },
    { id: "fq-bk2-4", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What is the Bower of Bliss, and who rules it?",
      options: ["A holy garden ruled by Una", "A martial training-ground ruled by Mars", "A seductive walled garden ruled by the enchantress Acrasia (= Greek 'incontinence')", "A pastoral retreat ruled by Pan"],
      correctIndex: 2,
      explanation: "Acrasia (Greek ἀκρασία, the Aristotelian ethical term for incontinence — failure of moral self-control) reigns in the Bower of Bliss. Guyon and the Palmer destroy the Bower at the end of Canto XII; Acrasia is bound but not killed." },
    { id: "fq-bk2-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Acrasia and her Bower are Spenser's direct rewriting of which Italian source?",
      options: ["Dante's Beatrice in the Earthly Paradise", "Tasso's Armida and her garden in Gerusalemme Liberata", "Ariosto's Alcina and her island in Orlando Furioso", "Both Ariosto's Alcina and Tasso's Armida"],
      correctIndex: 3,
      explanation: "Acrasia inherits from Ariosto's Alcina (Orlando Furioso VI–VIII — same enchantress-island-and-knight-victim structure) and Tasso's Armida (Gerusalemme Liberata XIV–XVI — a closer near-contemporary garden-of-seduction). Spenser knew both intimately." },
    { id: "fq-bk2-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Milton, in Areopagitica (1644), praises Spenser as 'a better teacher than Scotus or Aquinas' for which specific narrative sequence?",
      options: ["Redcrosse's combat with the Dragon in Book I", "Britomart's rescue of Amoret in Book III", "Guyon's journey through the Cave of Mammon and the Bower of Bliss in Book II", "The Mutabilitie Cantos in Book VII"],
      correctIndex: 2,
      explanation: "Milton: 'our sage and serious poet Spenser, whom I dare be known to think a better teacher than Scotus or Aquinas, describing true temperance under the person of Guyon, brings him in with his palmer through the cave of Mammon, and the bower of earthly bliss, that he might see and know, and yet abstain.' One of the great cross-poet acknowledgments." },
    { id: "fq-bk2-7", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Milton's Eden in Paradise Lost IV is composed in conscious response to which Faerie Queene canto?",
      options: ["I.i (the Wandring Wood)", "II.xii (the Bower of Bliss)", "III.vi (the Garden of Adonis)", "VI.x (Mount Acidale)"],
      correctIndex: 1,
      explanation: "Milton's Eden inverts every detail of Spenser's Bower: art-pretending-to-be-nature becomes nature-exceeding-any-art; the carpe-rosam song becomes pre-lapsarian abundance; bathing nymphs become companionate marriage; the false Genius becomes angelic guardians; the rose-to-be-gathered becomes the rose without thorn. The two scenes form the demo-critical English-epic inheritance." },
    { id: "fq-bk2-8", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Book II ends with Guyon and the Palmer transforming Acrasia's beasts back into men — and one named Gryll *refuses* the transformation, choosing to remain a pig.",
      correctBool: true,
      explanation: "'Let Gryll be Gryll, and have his hoggish minde.' The figure is from Plutarch's Gryllus dialogue, where a pig argues against Odysseus that pig-life is superior to human-life. Book II closes with the unsettling acknowledgment that some creatures prefer the dunghill — temperance has its limits." },
    { id: "fq-bk2-9", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Critics have debated for centuries whether Guyon's destruction of the Bower 'with rigour pittilesse' affirms or undermines temperance. Whose 1980 reading is the most influential modern revisionist case?",
      options: ["Northrop Frye", "Stephen Greenblatt, Renaissance Self-Fashioning", "Harold Bloom", "Frank Kermode"],
      correctIndex: 1,
      explanation: "Greenblatt's chapter 'To Fashion a Gentleman' in Renaissance Self-Fashioning (U. Chicago Press 1980) reads the destruction as the temperate self constituted by what it must repeatedly destroy — temperance built through redirected violence. Earlier orthodox readings (Lewis, others) treated the destruction as straightforwardly justified; the Greenblatt argument set the modern critical agenda." },
  ],

  // ── Book III — Chastity (Britomart) ──────────────────────────────────
  37: [
    { id: "fq-bk3-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Who is the titular knight of Book III, and what is unusual about her?",
      options: ["Sir Calidore — he is a poet rather than a soldier", "Britomart — she is a woman in armor, a warrior maiden", "Sir Guyon — he carries no sword", "The Palmer — he is a layman rather than a knight"],
      correctIndex: 1,
      explanation: "Britomart is the warrior maiden of Chastity. Book III's proem opens with Spenser's polemical defense of women warriors (Camilla, Penthesilea, Bonduca), placing the female knight at the center of the book." },
    { id: "fq-bk3-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "How does Britomart fall in love with Artegall?",
      options: ["She meets him at Gloriana's court", "She sees his face in her father's magic mirror (Merlin's glassy globe) without ever having met him", "He rescues her from a dragon", "Her brother arranges the match"],
      correctIndex: 1,
      explanation: "In Canto II, Britomart gazes into Merlin's mirror in her father King Ryence's closet, sees Artegall's face, and falls in love with the image. The whole rest of Books III–V is generated by this mirror-vision; her quest is to find the man she has only ever seen." },
    { id: "fq-bk3-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Britomart is Spenser's direct adaptation of which character from Orlando Furioso?",
      options: ["Angelica", "Marfisa", "Bradamante — the warrior maiden whose dynastic marriage to Ruggiero founds the Este line", "Olimpia"],
      correctIndex: 2,
      explanation: "Bradamante → Britomart is one of the most demonstrable formal inheritances in the English epic tradition. Both are peerless female warriors who fall in love with men they pursue across many cantos and whose dynastic marriages found royal lines (Este in Ariosto, British/Tudor in Spenser). The reader-palette continuity (Bradamante's silver-rose carries forward into Britomart's blue-shifted silver with rose-gold martial flare) is deliberate." },
    { id: "fq-bk3-4", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Who is Glauce, and what is her function in Britomart's narrative?",
      options: ["Britomart's sister", "Britomart's nurse / confidante, who diagnoses Britomart's lovesickness and proposes the quest", "Britomart's enemy", "Britomart's mother"],
      correctIndex: 1,
      explanation: "Glauce is the older confidante — a literary type from Euripides's Hippolytus and Medea through Virgil's Barce to Shakespeare's Nurse in Romeo and Juliet. She extracts Britomart's secret, supplies the name 'Artegall,' consults Merlin in Canto III, and dresses Britomart in armor. Without Glauce, Britomart never rides out." },
    { id: "fq-bk3-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "In the House of Busirane (Canto XII), what is the Masque of Cupid?",
      options: ["A theatrical entertainment performed for the queen", "A processional parade of personifications (Ease, Fancy, Desire, Doubt, Danger, Fear, Hope, Dissemblance, Suspect, Grief, Fury) that displays the psychology of love-suffering", "A wedding feast", "A sacred ritual of betrothal"],
      correctIndex: 1,
      explanation: "The Masque is Spenser's allegorical procession of the genealogy of love-suffering. Each figure dressed and labeled in court-masque convention; together they display, as parade, the phases through which infatuation becomes erotic captivity. Amoret is led at the procession's center as the captive victim." },
    { id: "fq-bk3-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What is Busirane doing in his inner chamber when Britomart finds him?",
      options: ["Reading the Bible aloud", "Writing magic verses with Amoret's living blood, dripping from her transfixed heart", "Playing chess against another sorcerer", "Forging a sword"],
      correctIndex: 1,
      explanation: "Busirane writes spell-verses with the blood that drips from Amoret's open chest, where her heart has been extracted and placed in a silver basin transfixed with a dart. The image literalizes the Petrarchan pierced-heart metaphor as actual vivisection — the canto's central horror. C. S. Lewis's Allegory of Love (1936) reads Busirane as the Petrarchan tradition itself." },
    { id: "fq-bk3-7", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Britomart kills Busirane after rescuing Amoret from his enchantment.",
      correctBool: false,
      explanation: "Britomart spares Busirane, *forcing him to read his magic verses backward* to reverse the enchantment. The reading-in-reverse undoes the binding; the same words in the opposite direction free what they had captured. Spenser's resolution refuses to mirror the canto's violence back onto its source." },
    { id: "fq-bk3-8", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The 1590 first edition of The Faerie Queene ended Book III differently than the 1596 edition: the 1590 ending featured a 'hermaphrodite' tableau in which Scudamour and Amoret embraced as a single statue.",
      correctBool: true,
      explanation: "Spenser deleted the hermaphrodite ending in 1596 because Book IV needed Amoret and Scudamour to be still separated. The famous statue-fusion image, anthologized and read since the 1590 first printing, was sacrificed to make narrative room for the continuing poem. One of the most consequential editorial revisions in English Renaissance poetry." },
    { id: "fq-bk3-9", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What does the name 'Acrasia' mean in Greek, and what does the name 'Britomart' suggest?",
      options: ["Acrasia = 'pure soul'; Britomart = 'British peace'", "Acrasia = 'incontinence' (failure of self-control); Britomart = 'British Mart' or 'sweet British maid' (combining Britain + martial)", "Acrasia = 'gentle lady'; Britomart = 'Brittany's flower'", "Acrasia = 'hidden one'; Britomart = 'small Britain'"],
      correctIndex: 1,
      explanation: "Greek ἀκρασία (Aristotelian ethical term, NE Book VII) names the failure of self-control — the exact opposite of Guyon's temperance, which she figures negatively. Britomart's name compounds 'British' with 'martial' (or with the Greek βρίθω + μάρτυς), naming her as both nationally British and warrior-marked." },
  ],

  // ── Book IV — Friendship (Cambel & Triamond) ─────────────────────────
  49: [
    { id: "fq-bk4-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Who are the dual titular knights of Book IV?",
      options: ["Britomart and Artegall", "Cambel and Triamond — the friendship pair", "Florimell and Marinell", "Amoret and Scudamour"],
      correctIndex: 1,
      explanation: "Book IV is The Legend of Cambel and Triamond, or of Friendship — the only book with paired titular knights. Their friendship-bond is the book's nominal frame, though Britomart, Amoret, Florimell, Scudamour, and others continue to drive the actual narrative interlace." },
    { id: "fq-bk4-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What allegorical structure is dominant in Book IV?",
      options: ["Single-quest narrative", "Interlace — multiple plots advancing in alternation, characters separated and reunited across cantos", "Underworld descent", "Pastoral interlude"],
      correctIndex: 1,
      explanation: "Book IV continues and amplifies Book III's interlaced plotting (inherited from Ariosto's Orlando Furioso). Britomart, Amoret, Florimell, Scudamour, Cambel, Triamond, and Artegall move in and out of one another's narratives across the twelve cantos. Friendship as virtue is enacted by the structural cooperation of the storylines as much as by individual characters." },
    { id: "fq-bk4-3", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What is Florimell's girdle, and what does it test (Canto V)?",
      options: ["A magic weapon that defeats giants", "A chastity-testing belt that fits only the truly chaste woman; the false Florimell is exposed when it does not fit her", "A garland that grants invisibility", "A talisman that summons Cupid"],
      correctIndex: 1,
      explanation: "The cestus-girdle of Florimell is Spenser's chastity-test object. When the false Florimell (a snowy fabrication who has been mistaken for the real one) attempts the girdle, it falls off; when the true Florimell tries it, it fits. The girdle's mechanic resolves the long-running false-vs-true Florimell narrative." },
    { id: "fq-bk4-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "In Book IV Canto VI, Britomart and Artegall meet for the first time. What happens?",
      options: ["They marry on the spot", "They fight each other (he does not recognize her); when her helmet is knocked off, he sees her face and recognizes the woman of his own prophesied marriage", "She rescues him from imprisonment", "He flees because he has no interest in her"],
      correctIndex: 1,
      explanation: "Britomart and Artegall meet in single combat without recognition (she is in her armor; he sees only an opponent). When her helmet is dislodged in the fight, her face is revealed; he recognizes the woman he has been told he would marry. The combat-to-recognition-to-betrothal scene is one of Book IV's quiet high points and pays off the mirror-vision of Book III canto ii." },
    { id: "fq-bk4-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What is the Temple of Venus (Canto X), and what does Scudamour's narrative there illustrate?",
      options: ["A scene of erotic torture similar to the House of Busirane", "A vision of erotic concord at the poem's center: married love figured as a temple visitable but not capturable", "An underworld of damned lovers", "A trial of erotic purity"],
      correctIndex: 1,
      explanation: "The Temple of Venus is one of the poem's most beautiful set-pieces. Scudamour narrates his earlier winning of Amoret from the temple's shrine; the scene articulates a positive vision of married love (concordia) against Book III's negative diagnosis of erotic captivity (House of Busirane). The two cantos pair as critique-and-vision." },
    { id: "fq-bk4-6", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "How does Book IV close (Canto XII)?",
      options: ["With Amoret returned to Scudamour", "With Florimell finally reunited with her beloved Marinell after Marinell is healed of a wound and the gods consent", "With Britomart marrying Artegall", "With the Blatant Beast being captured"],
      correctIndex: 1,
      explanation: "Book IV resolves the Florimell–Marinell plot. Marinell, healed of his wound, accepts the love he had refused. The book's close pairs the friendship-virtue with the marriage-completion of two characters whose separation drove much of Book IV's interlace. Amoret-Scudamour will not yet be reunited; that arc continues into Book V." },
  ],

  // ── Book V — Justice (Sir Artegall) ──────────────────────────────────
  61: [
    { id: "fq-bk5-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Who is the titular knight of Book V, and who is his iron-man executioner?",
      options: ["Sir Calidore / the Blatant Beast", "Sir Guyon / the Palmer", "Sir Artegall / Talus", "Britomart / Glauce"],
      correctIndex: 2,
      explanation: "Artegall is the knight of Justice; Talus is his iron groom (= servant), an automaton-like figure who literally executes Artegall's judgments by killing the guilty. Talus is among Spenser's most controversial inventions — implacable, mechanical, never softened." },
    { id: "fq-bk5-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What is Radigund (Cantos IV–VII), and what does she do to Artegall?",
      options: ["A holy hermitess who instructs him in justice", "An Amazon queen who defeats Artegall in single combat and forces him to wear women's clothes and spin wool", "His sister, who has been captured by brigands", "A goddess who blesses his quest"],
      correctIndex: 1,
      explanation: "Artegall, defeated by Radigund through her unveiling of her face during combat (he refuses to strike a beautiful woman), is enslaved, cross-dressed, and put to women's work. Britomart eventually rescues him by killing Radigund. The episode is one of Spenser's most politically and gender-troubling passages." },
    { id: "fq-bk5-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "In Canto IX, Mercilla judges Duessa. Whom does this thinly veiled trial allegorize?",
      options: ["Mary Tudor and Lady Jane Grey", "Elizabeth I and Mary Queen of Scots", "Catherine de' Medici and Marguerite de Valois", "Ferdinand of Spain and Isabella of Castile"],
      correctIndex: 1,
      explanation: "Mercilla = Elizabeth I in her aspect of merciful sovereign-judge; Duessa here = Mary Queen of Scots, whom Elizabeth executed in 1587 (eight years before Book V's 1596 publication). The trial-scene Spenser depicts replays the political-theological drama of the Tudor succession and the Scottish Catholic threat. Mary's son James VI of Scotland complained about the passage to Elizabeth." },
    { id: "fq-bk5-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Grantorto in Cantos XI–XII allegorizes which contemporary geopolitical enemy?",
      options: ["The Ottoman Empire", "Spain and the Catholic Counter-Reformation (Philip II)", "France under Henri III", "The Holy Roman Empire"],
      correctIndex: 1,
      explanation: "Grantorto ('great wrong') is Catholic Spain — the imperial-Catholic threat against which Elizabeth's England defined itself. The Armada had been defeated in 1588; Spenser's Book V (1596) is post-Armada Protestant English imperial-mythology. The Irish campaign within Book V's allegory reflects Spenser's own colonial-administrator role under Lord Grey." },
    { id: "fq-bk5-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Spenser's prose treatise A View of the Present State of Ireland (c. 1596, published 1633 posthumously) is contemporary with Book V. What policy does it advocate?",
      options: ["Reconciliation and partnership with Irish chieftains", "Severe military suppression of Irish resistance and English colonial settlement", "Withdrawal of English forces from Ireland", "A peaceful religious mission to convert Ireland from Catholicism"],
      correctIndex: 1,
      explanation: "The View advocates brutal English colonial repression in Ireland — including starvation campaigns. Book V's allegory is entangled with Spenser's biographical position as colonial administrator. Modern annotations should name this honestly: Spenser was complicit in (and a theorist of) genuinely brutal colonial violence, and Book V's justice-allegory is conditioned by that complicity." },
    { id: "fq-bk5-6", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Talus is among Spenser's most contested figures because he is described as iron, never tires, never feels mercy, and kills with mechanical efficiency.",
      correctBool: true,
      explanation: "Talus is read variously as: just-justice's necessary hardness; colonial English military force allegorized; the early-modern emergence of bureaucratic-mechanical violence; or — by some Marxian and postcolonial critics — the precursor of state-violence as such. The figure refuses straightforward moral framing." },
  ],

  // ── Book VI — Courtesy (Sir Calidore) ────────────────────────────────
  73: [
    { id: "fq-bk6-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Who is the titular knight of Book VI, and what is his quest?",
      options: ["Sir Artegall — to bring Justice to Faery Land", "Sir Calidore — to capture and bind the Blatant Beast (slander)", "Britomart — to find her lost husband", "Prince Arthur — to rescue Gloriana"],
      correctIndex: 1,
      explanation: "Calidore is the knight of Courtesy; the Blatant Beast — a hundred-tongued monster of slander and defamation — is his charged enemy. The chase forms the book's nominal spine; it ends in Canto XII with the Beast escaping its binding to roam the world still." },
    { id: "fq-bk6-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What happens in Canto X on Mount Acidale that makes it the most personal moment in The Faerie Queene?",
      options: ["Calidore finally captures the Blatant Beast", "Calidore interrupts a vision of the Three Graces dancing for the shepherd-poet Colin Clout (= Spenser's own pastoral persona); the vision vanishes at his approach", "Calidore meets Gloriana for the first time", "Calidore is knighted by Prince Arthur"],
      correctIndex: 1,
      explanation: "Spenser writes himself into his own poem as Colin Clout, the persona he had used in The Shepheardes Calender (1579). Colin pipes for the Graces; Calidore approaches; the vision dissolves. The fourth Grace at the dance's center is most plausibly Elizabeth Boyle, Spenser's wife — placed among the classical goddesses by the poet's declaration." },
    { id: "fq-bk6-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Mount Acidale takes its name from which classical figure?",
      options: ["Apollo (the sun)", "Hermes (the messenger)", "Venus, called Acidalia after the Boeotian spring where she bathed with the Three Graces", "Diana (the moon)"],
      correctIndex: 2,
      explanation: "Acidalia is a classical byname of Venus; the Acidalian spring (Pausanias IX.35) was where Venus bathed with the Charites/Graces. Spenser locates his vision in Faery-Land using the classical name with full awareness — Mount Acidale is where the Graces have always traditionally danced." },
    { id: "fq-bk6-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What are the names of the Three Graces in classical-Hesiodic genealogy?",
      options: ["Faith, Hope, Charity", "Aglaia (Splendor), Euphrosyne (Mirth), Thalia (Festivity) — daughters of Zeus and Eurynome", "Spring, Summer, Winter", "Memory, Wisdom, Justice"],
      correctIndex: 1,
      explanation: "Hesiod's Theogony 907–911 gives the Graces' canonical names and genealogy. They are the divinities of social adornment — beauty, kindness, festivity — exactly the virtues Book VI's Courtesy descends from. Spenser's choice of the Graces as Book VI's central vision-figures is allegorically precise." },
    { id: "fq-bk6-5", type: "true_false", difficulty: "Apprentice", xpReward: 5,
      text: "Book VI ends with Calidore successfully binding the Blatant Beast for ever after.",
      correctBool: false,
      explanation: "Calidore captures the Beast in Canto XII but it later breaks free and runs at large, biting and slandering still. Book VI is the only book that ends with its quest *unfinished* — the courtesy-virtue cannot fully overcome the slander it must contend with. The tonal darkening that begins at Mount Acidale culminates here." },
    { id: "fq-bk6-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Pastorella, the shepherdess Calidore loves, is captured by brigands while Calidore is on Mount Acidale. What pattern does this complete?",
      options: ["A pattern of the Graces' protection", "A pattern by which every preference for pleasure over duty produces catastrophic loss of the pleasure itself", "A pattern of divine reward", "A pattern of dynastic succession"],
      correctIndex: 1,
      explanation: "Calidore abandons the Blatant Beast hunt → the Beast remains free; pursues Pastorella → she is now captive; approaches the vision too eagerly → the Graces vanish. Every local preference of canto x's opening produces catastrophic loss. Spenser's most unsparing depiction of virtue-failure-by-misapplication." },
  ],

  // ── Mutabilitie Cantos (Book VII, fragmentary) ───────────────────────
  75: [
    { id: "fq-bk7-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What virtue would the unwritten Book VII have allegorized, and who are its two presiding figures?",
      options: ["Wisdom — Athena and Solomon", "Constancy — Mutabilitie (Titaness, plaintiff) and Dame Nature (judge)", "Magnanimity — Arthur and Hercules", "Hope — Una and Speranza"],
      correctIndex: 1,
      explanation: "Book VII (the two surviving Mutabilitie Cantos plus the two-stanza 'Unperfite' fragment) was titled 'Constancy' and posed the question of whether change or constancy is the universe's ruling principle. Mutabilitie storms Jove's throne claiming sovereignty; Dame Nature judges the case." },
    { id: "fq-bk7-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Where does the trial of Mutabilitie take place?",
      options: ["Mount Olympus", "Paris", "Arlo Hill — an Irish mountain in County Tipperary, near Spenser's own Kilcolman estate", "The court of Gloriana"],
      correctIndex: 2,
      explanation: "Spenser sets the cosmic-philosophical trial in specific Irish geography — Arlo Hill, visible from his own home. The Irish-colonial context is direct: Spenser was writing during the Nine Years' War (1594–1603); Kilcolman was destroyed by O'Neill's forces in 1598 and Spenser fled to London where he died in 1599." },
    { id: "fq-bk7-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Mutabilitie's argument before Nature consists of a procession. What does she parade as evidence for her claim that change rules the universe?",
      options: ["The seven planets", "The four elements", "The four Seasons, twelve Months (with their zodiacal animals), the Hours, Day and Night, Life and Death", "A catalogue of dead heroes"],
      correctIndex: 2,
      explanation: "Each procession-figure visibly demonstrates change. Mutabilitie's method is to make her case by showing rather than syllogizing. The procession is structured at every scale — yearly (Seasons), monthly (twelve Months on zodiacal animals), daily (Day-Night), once-only (Life-Death) — a comprehensive demonstration that everything in time alters." },
    { id: "fq-bk7-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What is Dame Nature's judgment?",
      options: ["Mutabilitie is right and Jove must abdicate", "Mutabilitie is wrong because change is illusion", "Mutabilitie's evidence is sound but her conclusion is wrong: things are not 'changed from their first estate' but 'by their change their being doe dilate, / And turning to themselves at length agayne, / Doe worke their own perfection so by fate'", "Nature refuses to judge and dismisses both parties"],
      correctIndex: 2,
      explanation: "Nature accepts Mutabilitie's evidence and reframes the conclusion: change is internal to each being's nature, serving its self-completion (Aristotelian entelecheia). Things reign over Change rather than Change over things. Spenser's most articulate philosophical stanza." },
    { id: "fq-bk7-5", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The Mutabilitie Cantos were published in Spenser's lifetime alongside the second edition of The Faerie Queene in 1596.",
      correctBool: false,
      explanation: "The Mutabilitie Cantos were first printed in 1609, ten years after Spenser's 1599 death, by Matthew Lownes from Spenser's surviving papers. The 'Canto VIII Unperfite' header is Lownes's editorial note, signaling that the two surviving stanzas constitute an incomplete continuation." },
    { id: "fq-bk7-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What is the famous closing line of the 'Unperfite' fragment, the last surviving verse of Spenser's hand?",
      options: ["'In every step Truth follows him on foot.'", "'O that great Sabaoth God, grant me that sabaoths sight.'", "'The mind is its own place, and in itself / Can make a Heaven of Hell, a Hell of Heaven.'", "'The course of true love never did run smooth.'"],
      correctIndex: 1,
      explanation: "The dying poet's prayer for the eschatological Sabbath-rest (Hebrews 4:9), with the careful Sabaoth/Sabbath pun ('Lord of Hosts' and 'eternal rest' both invoked). The line is the poem's true ending — not despite its incompleteness but in honor of it; the work argued for completion-through-time and ends with the prayer for the only completion that exceeds time." },
  ],

  // ── Master Trial: "Gloriana's Knight" ────────────────────────────────
  76: [
    { id: "fq-master-1", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Spenser's Letter to Sir Walter Raleigh (1589, prefixed to the 1590 edition) names what 'general end' for The Faerie Queene?",
      options: ["To rival Homer in poetic glory", "'To fashion a gentleman or noble person in virtuous and gentle discipline'", "To attack the Roman Catholic Church", "To celebrate the Tudor dynasty"],
      correctIndex: 1,
      explanation: "Spenser's pedagogical-formative aim is named in his own words. The phrase shaped the title of Stephen Greenblatt's Renaissance Self-Fashioning (1980); 'fashion' here is the active craft-verb (to shape, to form), and the gentleman is *made* by reading the right books — of which The Faerie Queene aims to be one." },
    { id: "fq-master-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which six virtues are completed in the published six books?",
      options: ["Faith, Hope, Charity, Justice, Prudence, Temperance", "Holiness, Temperance, Chastity, Friendship, Justice, Courtesy", "Wisdom, Strength, Beauty, Truth, Goodness, Love", "Virtue, Honor, Loyalty, Mercy, Patience, Diligence"],
      correctIndex: 1,
      explanation: "The six virtues map to the six titular knights: Holiness (Redcrosse), Temperance (Guyon), Chastity (Britomart), Friendship (Cambel/Triamond), Justice (Artegall), Courtesy (Calidore). Spenser planned twelve total private moral virtues; only the first six were completed before his 1599 death." },
    { id: "fq-master-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Prince Arthur, who appears across all six books to rescue the titular knights at crucial moments, allegorizes which virtue?",
      options: ["Mercy", "Magnificence (Aristotle's *megalopsychia*) — the totalizing virtue that contains all the others", "Patience", "Faith"],
      correctIndex: 1,
      explanation: "Per the Letter to Raleigh, Arthur 'before he was king' represents Magnificence — Aristotelian magnanimitas/megalopsychia, the virtue that 'is the perfection of all the rest, and containeth in it them all.' Each titular knight embodies one partial virtue; Arthur's appearance enacts the totality toward which each partial virtue aspires." },
    { id: "fq-master-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "How many cantos did Spenser complete in total, across all six books and the Mutabilitie fragment?",
      options: ["72 cantos (six books × 12)", "74 cantos (six books × 12 + 2 Mutabilitie cantos)", "76 cantos (including the 'Unperfite' fragment)", "60 cantos"],
      correctIndex: 1,
      explanation: "72 cantos in Books I–VI (six books × 12 cantos each) + 2 cantos in the Mutabilitie fragment (numbered VI and VII as if late in an unwritten Book VII) = 74 cantos. The two-stanza 'Canto VIII Unperfite' is a fragment, not a full canto. The unwritten Book XII would have framed the whole twelve-day feast from which the other books' quests depart." },
    { id: "fq-master-5", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Gloriana, the Faerie Queene of the title, is referred to throughout the poem but never actually appears as a present character in any canto.",
      correctBool: true,
      explanation: "Per the Letter to Raleigh, Gloriana presides over an annual feast in Cleopolis from which the knights' quests depart. She is referred to, promised, remembered — but never directly shown. The structural absence is deliberate: she is Elizabeth I-as-glory, the sovereign whose presence is felt only through her sent-out servants and never directly beheld." },
    { id: "fq-master-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What allegorical names does Spenser give to Elizabeth I across the poem?",
      options: ["Just Gloriana", "Gloriana (public majesty), Belphoebe (virgin-huntress chastity), Mercilla (merciful sovereign-judge), and at moments Cynthia", "Elizabeth and Beatrice", "Mary and Diana"],
      correctIndex: 1,
      explanation: "Per the Letter to Raleigh, Elizabeth 'beareth two persons' (the king's-two-bodies doctrine — public office and private virtue), so Spenser splits her across multiple figures. Gloriana names her in glory; Belphoebe names her in virginal-huntress aspect; Mercilla in sovereign-judge aspect; Cynthia in the moon-allusive register Raleigh's own poetry used." },
    { id: "fq-master-7", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which canto contains the poem's most-imitated set-piece, the direct formal source for Milton's Eden in Paradise Lost IV?",
      options: ["I.i (the Wandring Wood)", "I.xi (the Dragon-fight)", "II.xii (the Bower of Bliss)", "III.xii (the House of Busirane)"],
      correctIndex: 2,
      explanation: "The Bower of Bliss is the demo-critical inheritance. Milton's unfallen Eden (PL IV.131–287) inverts every detail: art-pretending-to-be-nature → nature-exceeding-any-art; carpe-rosam song → no song needed; bathing nymphs → companionate marriage; the rose-to-be-gathered → the rose without thorn. Milton acknowledged the debt explicitly in Areopagitica (1644)." },
    { id: "fq-master-8", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which character is the most important demonstrable inheritance from Orlando Furioso into The Faerie Queene?",
      options: ["Acrasia ← Alcina", "Britomart ← Bradamante — both peerless female warriors who fall in love with men they pursue across many cantos and whose marriages found royal lines", "Duessa ← Angelica", "Florimell ← Olimpia"],
      correctIndex: 1,
      explanation: "Bradamante (Orlando Furioso) and Britomart (Faerie Queene) are the strongest cross-poem character-line in the European Renaissance romance-epic tradition. Both are warrior-maidens; both fall in love through revelation (Merlin-cave / Merlin-mirror); both pursue their beloved across many cantos; both marry into a dynastic line (Este / Tudor)." },
    { id: "fq-master-9", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What did Milton say about Spenser in Areopagitica (1644)?",
      options: ["'A poet of light entertainment'", "'Our sage and serious poet Spenser, whom I dare be known to think a better teacher than Scotus or Aquinas'", "'A pleasant fabricator of fictions'", "'A great but flawed predecessor'"],
      correctIndex: 1,
      explanation: "Milton's acknowledgment is the highest cross-poet praise in the English-epic line. The full passage cites Guyon's journey 'through the cave of Mammon, and the bower of earthly bliss, that he might see and know, and yet abstain' as Spenser's exemplary teaching of Christian temperance — the very passage Milton would echo in Paradise Lost IV." },
    { id: "fq-master-10", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which Spenser canto is the direct narrative source for Bunyan's Giant Despair / Doubting Castle in The Pilgrim's Progress (1678)?",
      options: ["I.iv — House of Pride", "I.ix — Cave of Despair", "II.vii — Cave of Mammon", "III.xii — House of Busirane"],
      correctIndex: 1,
      explanation: "The Despair episode in Faerie Queene I.ix is the direct narrative source. Bunyan's Giant captures Christian and Hopeful, urges them to suicide, is defeated when Christian remembers the key of Promise; the architecture, rhetorical-rather-than-physical combat, and deliverance-by-named-virtue are Spenser's. Bunyan is the popular Protestant inheritance of Spenser's allegorical pedagogy." },
    { id: "fq-master-11", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Spenser invented the Spenserian stanza for The Faerie Queene. The closing alexandrine — the ninth line — does what to the preceding eight?",
      options: ["Repeats them in shorter form", "Summarizes, deflates, or amplifies — gives the stanza its rhetorical close", "Always changes subject", "Provides factual context"],
      correctIndex: 1,
      explanation: "The alexandrine (iambic hexameter, six feet vs. the preceding pentameter) gives the Spenserian stanza its characteristic rhythmic close. The extra foot allows a fuller summative breath; the ninth line typically completes, deflates, or amplifies what the eight have built. Spenser's signature gesture." },
    { id: "fq-master-12", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Spenser's deliberate archaism — words like *whylome*, *eftsoones*, *ycladd*, *hight* — is meant to imitate which earlier English poet?",
      options: ["Shakespeare (his contemporary)", "Sir Thomas Wyatt", "Geoffrey Chaucer (1340s–1400)", "John Skelton"],
      correctIndex: 2,
      explanation: "Spenser writes in 1590 in deliberately old-fashioned English, modeled on Chaucer (whom he calls 'Tityrus' and his master). The reading-experience compounds: a 1590 poet imitating a 1400 poet, in 2026 we read the result. The archaism signals antique moral seriousness; Ben Jonson quipped that 'Spenser, in affecting the ancients, writ no language.'" },
    { id: "fq-master-13", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which classical and biblical traditions converge in Book I's Dragon-fight (Canto XI)?",
      options: ["Only the classical Hercules-and-Hydra tradition", "Only the biblical Revelation 20 dragon", "Revelation 12 + 20 (the apocalyptic dragon), Job 41 (Leviathan), the Hydra of classical mythology, and the St. George iconographic tradition", "Only St. George"],
      correctIndex: 2,
      explanation: "Spenser's Dragon is a typological composite: the apocalyptic dragon of Revelation, the fire-breathing Leviathan of Job, the multi-fold Hydra of Hercules's labors, and the dragon of the St. George iconographic tradition. All four name, in different cultural registers, the same archetypal cosmic enemy. Spenser fuses them by Renaissance Christian-humanist method." },
    { id: "fq-master-14", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The 1590 first edition of Book III ended with what tableau, deleted from the 1596 second edition?",
      options: ["The wedding of Britomart and Artegall", "Scudamour and Amoret reunited as a 'hermaphrodite' statue, two bodies fused into one", "The destruction of the Bower of Bliss", "The trial of Duessa"],
      correctIndex: 1,
      explanation: "The 1590 ending compared the reunited Scudamour-Amoret to a Roman white-marble hermaphrodite statue ('two bodies grown in one'). Spenser deleted it in 1596 because Book IV needed Amoret and Scudamour separated to drive its plot. One of the most consequential editorial revisions in English poetry; the famous tableau survives only in 1590-text scholarly editions." },
    { id: "fq-master-15", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The Mutabilitie Cantos' philosophical resolution — that change is each being's working-out of its own nature toward perfection — adapts which classical philosophical concept?",
      options: ["Stoic apatheia", "Platonic Form", "Aristotelian *entelecheia* (actualization of potentiality, the form-toward-which-a-being-tends)", "Epicurean atomism"],
      correctIndex: 2,
      explanation: "Aristotle's De Anima II.1 and Metaphysics IX.8 articulate entelecheia — the doctrine that beings are directed processes whose changes serve the realization of an inherent form. Nature's judgment in canto vii is Aristotelian metaphysics rendered in allegorical verse." },
    { id: "fq-master-16", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Spenser was born in England, served as a colonial administrator in Ireland, wrote The Faerie Queene mostly at Kilcolman estate in Munster, and died in London in 1599 in near-poverty after Kilcolman was destroyed by Hugh O'Neill's forces in 1598.",
      correctBool: true,
      explanation: "The biographical-political context conditions the entire late poem. The Mutabilitie Cantos were composed during the Nine Years' War; the destruction of Kilcolman, the loss of his Irish position, and his death within months of returning to London frame the poem's tonal darkening from Mount Acidale through 'Canto VIII Unperfite.'" },
    { id: "fq-master-17", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What is the 'Letter to Sir Walter Raleigh' (prefixed to the 1590 first edition), and why does it matter?",
      options: ["A satirical attack on Raleigh's politics", "A private love-letter that Raleigh later published", "A 1,500-word prose statement in which Spenser describes the allegorical plan of the whole twelve-book project, names Gloriana as Elizabeth, identifies Arthur with Magnificence, and explains his method against Homer/Virgil/Ariosto/Tasso", "A short biographical preface by Spenser's editor"],
      correctIndex: 2,
      explanation: "The Letter is the door to the whole work. Spenser names the 'continued allegory, or dark conceit' as his method, declares the pedagogical aim ('to fashion a gentleman'), unpacks the twelve-virtue Aristotelian frame, identifies Gloriana with Elizabeth ('two persons'), and places himself in the Homer→Virgil→Ariosto→Tasso lineage. A reader who works the Letter's annotations has the interpretive key to the rest of the poem." },
    { id: "fq-master-18", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Spenser's poem is unfinished. What did Spenser plan for the (never-written) Book XII?",
      options: ["The death of Gloriana", "The narrative of Gloriana's twelve-day annual feast, in which the twelve quests of the previous books were assigned — the 'first day' chronologically but the last book in the publication order", "A second journey of Redcrosse", "The wedding of Arthur"],
      correctIndex: 1,
      explanation: "Per the Letter to Raleigh: Book XII would have framed the whole poem by narrating the annual feast at which the quests are dispatched. The structural irony: the *first* event chronologically (the feast) is the *last* book in the planned reading order. Without Book XII the framing-narrative remains a future-tense promise; the poem-as-published is a series of quests without their generating frame." },
  ],

  // ── Renaissance Epic Stretch — Orlando Furioso + Faerie Queene ───────
  77: [
    { id: "fq-stretch-renaissance-1", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What stanza form does Ariosto invent for Orlando Furioso, and how does Spenser's Spenserian stanza extend it?",
      options: ["Terza rima → Spenserian; Spenser adds three lines", "Ottava rima (ABABABCC, eight iambic-pentameter lines) → Spenserian (ABABBCBCC, nine lines with alexandrine close); Spenser adds a ninth hexameter line and tightens the rhyme network", "Heroic couplets → Spenserian; Spenser converts to four-line groups", "Sonnet → Spenserian; Spenser shortens to nine lines"],
      correctIndex: 1,
      explanation: "Ariosto's ottava rima is six setup lines + closing couplet, all pentameter. Spenser's Spenserian stanza extends to nine lines, ABABBCBCC, with the ninth as alexandrine. Spenser tightens Ariosto's rhyme net (B reappears four times, C three times, overlapping the tercet-couplet boundary) and makes the close longer rather than snappier. Two genuinely different rhythmic settlements of the long-narrative-stanza problem." },
    { id: "fq-stretch-renaissance-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Bradamante (Orlando Furioso) and Britomart (Faerie Queene) share which structural features?",
      options: ["Both are male warriors", "Both are peerless female warriors who fall in love through providential revelation, pursue their beloveds across many cantos, and marry into dynastic lines (Este in Italy, Tudor in England)", "Both die in their final cantos", "Both are princesses of small kingdoms"],
      correctIndex: 1,
      explanation: "The most demonstrable Italian-to-English character inheritance in the Renaissance epic. Bradamante in Merlin's tomb (OF III) → Britomart in Merlin's mirror (FQ III.ii); Bradamante's marriage to Ruggiero founding the Este line → Britomart's marriage to Artegall founding the British/Tudor line. Spenser converts the dynastic-procession revelation into a single-person mirror-vision; the rest of the structural pattern is preserved." },
    { id: "fq-stretch-renaissance-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Acrasia in the Bower of Bliss inherits from which Italian sources?",
      options: ["Only Petrarch's Laura", "Both Ariosto's Alcina (Orlando Furioso VI–VIII, the enchantress-island-and-knight-victim structure) and Tasso's Armida (Gerusalemme Liberata XIV–XVI, the closer near-contemporary garden-of-seduction)", "Only Dante's Francesca", "Only Boccaccio's Fiammetta"],
      correctIndex: 1,
      explanation: "Acrasia compresses both Italian enchantress-traditions. Ariosto's Alcina supplies the structural template (knight is captivated, enchantress's true face is revealed by virtuous-figure intervention); Tasso's Armida (1581) supplies the more-elaborated garden-of-seduction iconography. Spenser knew both intimately; the carpe-rosam song in II.xii directly paraphrases Tasso's parrot-song in Armida's garden." },
    { id: "fq-stretch-renaissance-4", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Both Orlando Furioso and The Faerie Queene use *interlace* (multiple plots advancing in alternation, with characters separated and reunited across cantos) as their dominant narrative architecture.",
      correctBool: true,
      explanation: "Interlace (entrelacement) was perfected in 12c–13c French romance, theorized by Chrétien de Troyes, taken up by Boiardo and Ariosto, and inherited by Spenser. Books III–IV especially are saturated with interlace; characters drift in and out of one another's narratives. The technique allows the long romance-epic to maintain narrative density across hundreds of cantos." },
    { id: "fq-stretch-renaissance-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What is the key difference between Ariosto's narrator and Spenser's narrator?",
      options: ["Ariosto writes in prose, Spenser in verse", "Ariosto's narrator is continuously digressive, ironic, and present in a Ferrara-court register; Spenser's is Elizabethan-courtly, reverent toward the queen, deliberately archaizing in a Chaucerian register", "Both narrators are absent from their poems", "Ariosto's narrator is Christian, Spenser's is pagan"],
      correctIndex: 1,
      explanation: "Both narrators are continuously present, but in different registers. Ariosto: ironic-Ferrara-courtly; Spenser: reverent-Elizabethan-archaizing. The shared formal-narrative DNA (continuous-narrator-with-intrusions) is the lineage; the tonal-cultural register is each poet's local color." },
  ],

  // ── Full Epic Succession Stretch — all nine epics ────────────────────
  78: [
    { id: "fq-stretch-succession-1", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Place the nine epics in this catalog in chronological order of composition:",
      options: [
        "Beowulf, Iliad, Odyssey, Aeneid, Divine Comedy, Orlando Furioso, Faerie Queene, Paradise Lost, Don Juan",
        "Iliad, Odyssey, Aeneid, Beowulf, Divine Comedy, Orlando Furioso, Faerie Queene, Paradise Lost, Don Juan",
        "Iliad, Odyssey, Aeneid, Divine Comedy, Beowulf, Orlando Furioso, Faerie Queene, Paradise Lost, Don Juan",
        "Iliad, Odyssey, Aeneid, Beowulf, Divine Comedy, Faerie Queene, Orlando Furioso, Paradise Lost, Don Juan",
      ],
      correctIndex: 1,
      explanation: "Iliad/Odyssey (8c BCE), Aeneid (29–19 BCE), Beowulf (composed roughly 8c–10c CE in its surviving manuscript), Divine Comedy (1308–20), Orlando Furioso (1516/1532), Faerie Queene (1590/1596 + 1609 Mutabilitie), Paradise Lost (1667/1674), Don Juan (1819–24, unfinished at Byron's 1824 death). Beowulf's manuscript is c. 1000 CE; composition predates that." },
    { id: "fq-stretch-succession-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which two epics most strongly demonstrate inheritance from one to the other in this catalog?",
      options: [
        "Iliad and Odyssey",
        "Aeneid and Divine Comedy (Virgil literally appears as Dante's guide)",
        "Faerie Queene and Paradise Lost (Milton wrote Eden in conscious response to the Bower of Bliss; Areopagitica acknowledges the debt by name)",
        "Orlando Furioso and Don Juan",
      ],
      correctIndex: 2,
      explanation: "All four pairs show inheritance, but the Faerie Queene → Paradise Lost relationship is the most explicitly documented and the most demonstrable on the page. Milton names Spenser as 'a better teacher than Scotus or Aquinas' in Areopagitica (1644), citing the cave of Mammon and the bower of bliss specifically. Paradise Lost IV's Eden is the inversion-by-inversion of Faerie Queene II.xii's Bower." },
    { id: "fq-stretch-succession-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which character/figure recurs (in different forms) across the most epics in this catalog?",
      options: [
        "Helen of Troy (Iliad, Odyssey, mentioned in Aeneid and others)",
        "The katabasis (underworld descent): Odyssey XI (Odysseus to Hades) → Aeneid VI (Aeneas with the Sibyl) → Inferno (Dante guided by Virgil) → Faerie Queene II.vii (Guyon in Mammon's cave) → Paradise Lost II (Satan's flight through Hell)",
        "The wandering hero (Iliad, Odyssey, Aeneid)",
        "Athena/Minerva (multiple)",
      ],
      correctIndex: 1,
      explanation: "Katabasis is the inheritance-form most explicitly carried across the catalog. Each major epic stages a descent into the underworld with its own theological-cultural cargo. Spenser's Mammon-cave canto explicitly draws from Homeric, Virgilian, and Dantean katabases simultaneously; Milton inherits the whole chain." },
    { id: "fq-stretch-succession-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which two epics in the catalog were left UNFINISHED by their authors?",
      options: [
        "Iliad and Odyssey (each missing books)",
        "Faerie Queene (six of twelve books + the Mutabilitie fragment) and Don Juan (sixteen of seventeen-projected cantos + a fragment)",
        "Aeneid and Divine Comedy",
        "Beowulf and Paradise Lost",
      ],
      correctIndex: 1,
      explanation: "Spenser died in 1599 with six of twelve projected books complete plus the two Mutabilitie cantos and the two-stanza 'Unperfite' fragment. Byron died in 1824 mid-composition of Don Juan, leaving sixteen complete cantos and a stanza of the seventeenth. Both poems' incompleteness becomes thematically resonant — Spenser's 'Unperfite' canto explicitly thematizes the unfinishedness; Don Juan's is biographical-comic." },
    { id: "fq-stretch-succession-5", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Across the nine-epic succession, the question of whether the hero is essentially *active* (heroic action that shapes the world) or *contemplative* (heroic insight that recognizes the world) is one of the long-running structural questions of the form.",
      correctBool: true,
      explanation: "Achilles (Iliad) is the active warrior; Odysseus (Odyssey) is the contemplative-resourceful traveler; Aeneas (Aeneid) holds both in tension; Dante (Comedy) is purely contemplative; the Spenserian knights are active under formative tutelage; Milton's Adam-and-Eve are passive-then-active; Byron's Don Juan is comic-passive. The active/contemplative axis runs through the whole tradition; each major poet adjusts the balance." },
  ],
}
