/**
 * Idylls of the King chapter trials — 14 chapters (Dedication + 12
 * idylls + "To the Queen") plus capstones.
 *
 * Structure (chapterIndex → questions):
 *   0   — Dedication (framing verse; 2 foundational questions on Albert/Victoria)
 *   1–12 — the twelve idylls, 4 questions each (Foundational + Scholar mix)
 *   13  — "To the Queen" (framing verse; 2 questions)
 *   14  — Mid-cycle Trial A: the first four idylls (Hope and Establishment)
 *   15  — Mid-cycle Trial B: the middle four idylls (Corruption)
 *   16  — Master Trial: "Old Order Changeth" — 15 questions synthesizing
 *         the whole cycle; awards the "Old Order Changeth" Seal.
 *   17  — Anglophone Epic Line Trial — extended: Beowulf + Faerie
 *         Queene + Paradise Lost + Don Juan + Idylls. Awards the
 *         "Englisc" Seal (updated for five-book span).
 *
 * Merged at lookup time by `getQuestionsForChapter` in
 * chapter-questions.ts. Schema matches `ChapterQuestion`.
 */

import type { ChapterQuestion } from "./chapter-questions"

export const IDYLLS_OF_THE_KING_TRIALS: Record<number, ChapterQuestion[]> = {
  // ── Dedication (ch-0) ────────────────────────────────────────────
  0: [
    { id: "iotk-0-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Tennyson's Dedication was composed after whose death in December 1861?",
      options: ["Queen Victoria", "Prince Albert", "Arthur Hallam", "Lord Palmerston"],
      correctIndex: 1,
      explanation: "Prince Albert, Victoria's consort, died 14 December 1861. Tennyson composed the Dedication in winter 1861–62 and placed it at the head of the collected Idylls, framing Arthur as Albert's legendary analogue." },
    { id: "iotk-0-2", type: "true_false", difficulty: "Apprentice", xpReward: 5,
      text: "The phrase \"the white flower of a blameless life\" is Tennyson's description of Prince Albert.",
      correctBool: true,
      explanation: "The Dedication's most famous image — \"Wearing the white flower of a blameless life\" — became the Victorian imagination's summary of Albert. It passed immediately into sermons, obituaries, and public speech." },
  ],

  // ── The Coming of Arthur (ch-1) ──────────────────────────────────
  1: [
    { id: "iotk-1-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "In Bellicent's mystic account, how does the infant Arthur arrive at Merlin's feet?",
      options: ["Carried by three queens", "Borne on the ninth great wave in flame", "Found sleeping in a hollow oak", "Delivered by Uther on his deathbed"],
      correctIndex: 1,
      explanation: "Bellicent tells Leodogran of a fiery ninth wave bearing a naked babe to Merlin, who catches him and cries 'The King!' This mystic birth is wholly Tennyson's invention, replacing Malory's plainly-narrated adulterous conception." },
    { id: "iotk-1-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Which famous Tennysonian line appears in \"The Coming of Arthur\" and returns at \"The Passing of Arthur\"?",
      options: ["Theirs not to reason why", "The old order changeth, yielding place to new", "Break, break, break, on thy cold gray stones", "More things are wrought by prayer"],
      correctIndex: 1,
      explanation: "The line is the cycle's signature — triumphal in the young Arthur's mouth, elegiac in the dying Arthur's. The doubling brackets the entire cycle." },
    { id: "iotk-1-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Tennyson's primary source for the Idylls is Sir Thomas Malory's Le Morte d'Arthur (1485).",
      correctBool: true,
      explanation: "Almost every major scene in the Idylls has a Malory source, with the Geraint/Enid material (Idylls III–IV) drawn from the Welsh Mabinogion via Lady Charlotte Guest's 1838–45 translation." },
    { id: "iotk-1-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What does Arthur refuse to pay to Rome at the idyll's close?",
      options: ["Tribute", "A tithe of knights", "The white horse emblem", "His sister in marriage"],
      correctIndex: 0,
      explanation: "\"Arthur strove with Rome\" — the refusal of imperial tribute is Arthur's first act as established sovereign and a Victorian-era assertion of civilizational self-definition under medieval garb." },
  ],

  // ── Gareth and Lynette (ch-2) ────────────────────────────────────
  2: [
    { id: "iotk-2-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What promise does Gareth give his mother Bellicent before going to court?",
      options: ["To avenge her dead husband", "To serve a year in the kitchen without revealing his name", "To return in three years", "To marry no lady without her consent"],
      correctIndex: 1,
      explanation: "Bellicent, unwilling to let Gareth go, extracts the kitchen-vow. It is Tennyson's invention — Malory's Gareth serves in the kitchen by his own choice." },
    { id: "iotk-2-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Tennyson renames Malory's four opposing knights as stages of:",
      options: ["The four seasons", "The four classical elements", "The four times of day (Morning-Star, Noon-Sun, Evening-Star, Night)", "The four cardinal virtues"],
      correctIndex: 2,
      explanation: "Tennyson's allegorical superimposition. Malory's colors (Black, Green, Red, Blue) become cosmological stages; the final knight \"Night\" unhelms to reveal a boy's face — the idyll's comic deflation." },
    { id: "iotk-2-3", type: "true_false", difficulty: "Apprentice", xpReward: 5,
      text: "Gareth and Lynette, published in 1872, was one of the last-composed major idylls.",
      correctBool: true,
      explanation: "The cycle's bright-morning idyll was written after Tennyson had already completed the dark late-idylls (Grail 1869, Passing of Arthur 1869). The older poet wrote the youth." },
    { id: "iotk-2-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which line from the idyll's closing signals its comic register?",
      options: ["\"And Gareth won his knighthood\"", "\"Such was the custom of the Round\"", "\"Only proven a blooming boy\"", "\"And sprang into the dark\""],
      correctIndex: 2,
      explanation: "Night (Death) unhelms as a blooming boy — the allegorical-death turns comic. The closing lines compound the effect, refusing to resolve whether Gareth marries Lyonors or Lynette." },
  ],

  // ── The Marriage of Geraint (ch-3) ───────────────────────────────
  3: [
    { id: "iotk-3-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "The Geraint/Enid material derives from which source?",
      options: ["Malory's Le Morte d'Arthur", "The Welsh Mabinogion (via Lady Charlotte Guest)", "Chrétien de Troyes's Lancelot", "Tennyson's own invention"],
      correctIndex: 1,
      explanation: "Tennyson worked from Lady Charlotte Guest's 1838–45 English translation of the Mabinogion tale \"Geraint son of Erbin.\" This is the cycle's primary exception to Malory-sourcing." },
    { id: "iotk-3-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What is the prize at the central tournament of the idyll?",
      options: ["A golden falcon", "A sparrow-hawk", "Excalibur's twin sword", "The seat at Arthur's right hand"],
      correctIndex: 1,
      explanation: "The sparrow-hawk tournament is the Welsh source's chivalric set-piece — an annual contest whose prize goes to the most beautiful lady present." },
    { id: "iotk-3-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Edyrn, son of Nudd, is one of the cycle's rare characters who undergoes genuine moral reform.",
      correctBool: true,
      explanation: "Edyrn is defeated by Geraint, sent to court for judgment, repents, and becomes a loyal knight of the Round Table. The cycle otherwise does not permit moral restoration of fallen characters." },
    { id: "iotk-3-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What does Enid preserve reverently in the cedarn cabinet?",
      options: ["Her father's last letter", "A lock of Geraint's hair", "The faded silk gown she wore when Geraint first found her", "A pressed flower from her wedding"],
      correctIndex: 2,
      explanation: "The faded silk is Enid's preservation of her origins — and the gown she puts on at the idyll's closing, at Geraint's command, initiates the crisis of Idyll IV." },
  ],

  // ── Geraint and Enid (ch-4) ──────────────────────────────────────
  4: [
    { id: "iotk-4-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "The idyll opens with a seven-line reflection on what?",
      options: ["The ideal of chivalric marriage", "The folly of taking true for false, or false for true", "The beauty of the Welsh landscape", "Arthur's rising realm"],
      correctIndex: 1,
      explanation: "\"O purblind race of miserable men\" — Tennyson's rare direct editorial preface frames Geraint's coming misunderstanding of Enid as human error, not authority." },
    { id: "iotk-4-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "At Earl Doorm's hall, what finally breaks Geraint's pretended unconsciousness?",
      options: ["Doorm striking Enid", "The sound of Guinevere's voice", "Doorm ordering wine", "A messenger from Arthur"],
      correctIndex: 0,
      explanation: "Doorm strikes Enid when she refuses to eat or drink with him. Geraint, who has been feigning unconsciousness to observe her fidelity, rises and kills Doorm with a single blow." },
    { id: "iotk-4-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Tennyson's Enid is more Victorian-domesticated than the Welsh source's Enid.",
      correctBool: true,
      explanation: "The Mabinogion's Enid is stronger, clearer-eyed, less sacrificial. Tennyson overlays Victorian wifely-patience ideology, producing an idyll whose gender politics have been a major focus of modern feminist criticism." },
    { id: "iotk-4-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "How does Geraint eventually die?",
      options: ["At Camlann, fighting Modred", "Of grief after Enid's death", "Fighting heathen invaders from the Northern Sea, for the blameless King", "In prison, poisoned by Limours"],
      correctIndex: 2,
      explanation: "The idyll's closing sentence names Geraint's \"fair death\" — a good knightly end in defense of Arthur's realm. Geraint is one of the few Round Table knights whose death is not ambiguous." },
  ],

  // ── Balin and Balan (ch-5) ───────────────────────────────────────
  5: [
    { id: "iotk-5-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "How do Balin and Balan die?",
      options: ["Killed by Modred in ambush", "Both slain by Vivien's charm", "At each other's hands, not recognizing each other in armor", "Defending Arthur at Camlann"],
      correctIndex: 2,
      explanation: "The recognition-in-death combat is preserved from Malory II.18–19 — the one Malory element Tennyson kept largely intact because it fit his cycle's moral frame." },
    { id: "iotk-5-2", type: "true_false", difficulty: "Apprentice", xpReward: 5,
      text: "Balin and Balan was added in 1885 as the latest-composed idyll.",
      correctBool: true,
      explanation: "Tennyson at 76 added the idyll to bridge the middle-cycle success to the dark end. It prepares the reader for Vivien's full-scale appearance in Idyll VI." },
    { id: "iotk-5-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What emblem does Balin choose for his shield as token of his reform?",
      options: ["The red cross", "The crown-royal of Guinevere", "A white stag", "Arthur's dragon"],
      correctIndex: 1,
      explanation: "The queen's emblem becomes Balin's reform-pattern. When he glimpses Guinevere and Lancelot in apparent intimacy, the shield-emblem is revealed as false and his reform collapses." },
    { id: "iotk-5-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which element of Malory's Balin tale does Tennyson omit entirely?",
      options: ["The brothers' fatal combat", "Vivien's appearance", "The Dolorous Stroke of Pellam with the sacred spear", "Balin's exile from court"],
      correctIndex: 2,
      explanation: "The Dolorous Stroke — Malory's most mythically loaded moment — is removed. Tennyson reframes the tragedy from sacred-violence to moral-corruption, keyed to Vivien's rumor rather than the wounded Grail-king." },
  ],

  // ── Merlin and Vivien (ch-6) ─────────────────────────────────────
  6: [
    { id: "iotk-6-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Where does Vivien seal Merlin after extracting the charm from him?",
      options: ["Beneath a great stone", "Inside a hollow oak", "On an island in the lake", "In a mountain cave"],
      correctIndex: 1,
      explanation: "Tennyson's setting is the hollow oak in the wild woods of Broceliande — the traditional Breton-Arthurian site of Merlin's imprisonment." },
    { id: "iotk-6-2", type: "true_false", difficulty: "Apprentice", xpReward: 5,
      text: "Critical consensus identifies \"Merlin and Vivien\" as the cycle's weakest idyll in character-handling.",
      correctBool: true,
      explanation: "Tennyson's Vivien is a flattening of Malory's ambiguous Nimuë; the idyll lacks the psychological complexity of Guinevere, Lancelot, or Elaine. Reading her honestly requires naming the compositional problem." },
    { id: "iotk-6-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Malory's Nimuë (Tennyson's Vivien) elsewhere in Malory appears as:",
      options: ["Morgan le Fay's apprentice", "A disguised devil", "A positive figure who rescues Arthur from poison and Pelleas from Ettarde", "Mordred's mother"],
      correctIndex: 2,
      explanation: "Malory's Nimuë is ambiguous — enchantress but also helper. Tennyson collapses the ambiguity into a single-register villain, part of the idyll's character-flattening problem." },
    { id: "iotk-6-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which 1874 Pre-Raphaelite painting depicts the idyll's central scene?",
      options: ["Waterhouse, The Lady of Shalott", "Millais, Ophelia", "Burne-Jones, The Beguiling of Merlin", "Rossetti, La Ghirlandata"],
      correctIndex: 2,
      explanation: "Burne-Jones's painting (Lady Lever Art Gallery, Port Sunlight) depicts Vivien leaning over the entranced Merlin — the Stoa gallery painting paired with the Idylls in the Tome catalog." },
  ],

  // ── Lancelot and Elaine (ch-7) ───────────────────────────────────
  7: [
    { id: "iotk-7-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "How does Elaine's body travel to Camelot at the idyll's close?",
      options: ["Carried on a horse-drawn bier", "On a funeral barge down the Thames", "Buried at Astolat, then exhumed", "In a sealed casket by ship"],
      correctIndex: 1,
      explanation: "The funeral-barge passage — composed with sustained sound-painting — is one of the most-imitated in Victorian poetry. Malory has the same figure; Tennyson lingers on its ekphrastic detail." },
    { id: "iotk-7-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "The \"Diamond Jousts\" — nine annual tournaments whose diamonds Lancelot gives Guinevere — are:",
      options: ["Directly from Malory, unchanged", "Tennyson's invention", "From the Welsh Mabinogion", "Added by Burne-Jones as a visual source"],
      correctIndex: 1,
      explanation: "Malory has one tournament; Tennyson expands it into a nine-year pattern whose accumulated weight is dissolved when Guinevere throws the diamonds into the Thames just as Elaine's barge passes the window." },
    { id: "iotk-7-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "\"His honour rooted in dishonour stood, / And faith unfaithful kept him falsely true\" is Lancelot's interior monologue about his divided self.",
      correctBool: true,
      explanation: "One of Victorian poetry's keystone formulations of the divided self — Lancelot knows his public honor rests on private adultery. Cross-references forward to Idyll VIII's Grail-chapel scene." },
    { id: "iotk-7-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which Tennyson earlier poem is the imaginative precursor to Elaine?",
      options: ["Ulysses", "The Lady of Shalott", "Maud", "The Lotos-Eaters"],
      correctIndex: 1,
      explanation: "Tennyson fused the Fair Maid of Astolat with the Lady of Shalott — different Arthurian figures, but in his imagination the same tragic type (tower, fatal love for Lancelot, river-journey, arrival at Camelot)." },
  ],

  // ── The Holy Grail (ch-8) ────────────────────────────────────────
  8: [
    { id: "iotk-8-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Who narrates \"The Holy Grail\" in Tennyson's version?",
      options: ["Arthur", "Percivale, now a monk", "Merlin from his oak prison", "Galahad before ascending"],
      correctIndex: 1,
      explanation: "Tennyson's retrospective frame has Percivale (now retired to the monastery) telling the quest to the monk Ambrosius — a radical departure from Malory's omniscient narration." },
    { id: "iotk-8-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "How is Galahad's Grail-attainment rendered?",
      options: ["In Catholic Eucharistic detail", "Compressed to an Elijah-type chariot of fire translation", "As a shared vision with Arthur", "Through a long prayer at Corbenic"],
      correctIndex: 1,
      explanation: "Tennyson radically compresses Malory's 100-chapter Sankgreal into a few lines. The Elijah-chariot (2 Kings 2:11) replaces Malory's Sarras Eucharist, re-theologizing the Grail for Victorian Anglican sensibility." },
    { id: "iotk-8-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Arthur, when the Grail-questers return, affirms that the quest was the right path for his knights.",
      correctBool: false,
      explanation: "Arthur critiques the quest severely — his knights \"followed wandering fires, / Lost in the quagmire.\" The idyll holds the quest's value in honest ambivalence, neither fully endorsing nor dismissing it." },
    { id: "iotk-8-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What does the voice in the chapel say to Lancelot, refusing him full Grail-vision?",
      options: ["\"Too late, Sir Knight, too late\"", "\"Not for thee, O knight of sin\"", "\"The Queen hath called thee\"", "\"Return to thy fallen king\""],
      correctIndex: 1,
      explanation: "Lancelot is refused the Grail specifically because of his adultery — the cosmic counterpart to his interior division named in Idyll VII. \"Not yet the pure in heart\" — the \"not yet\" is morally load-bearing." },
  ],

  // ── Pelleas and Ettarre (ch-9) ───────────────────────────────────
  9: [
    { id: "iotk-9-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What does Pelleas find when he returns to Ettarre's castle and discovers Gawain with her?",
      options: ["He kills them both in a rage", "He lays his sword across their sleeping throats and leaves", "He challenges Gawain to a duel at dawn", "He burns the castle"],
      correctIndex: 1,
      explanation: "The sword-across-throats gesture is one of the cycle's most restrained and devastating scenes. Pelleas's chivalric mercy outstrips the wrongdoers'; his subsequent disillusionment is total." },
    { id: "iotk-9-2", type: "true_false", difficulty: "Apprentice", xpReward: 5,
      text: "Tennyson preserves Malory's ending, in which Nimuë magically rescues Pelleas and marries him.",
      correctBool: false,
      explanation: "Tennyson omits Nimuë's rescue entirely. Pelleas rides off in disillusion — unresolved, unrescued — becoming the cycle's tonal turning-point into despair." },
    { id: "iotk-9-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Who betrays Pelleas by sleeping with Ettarre himself?",
      options: ["Modred", "Kay", "Gawain", "Tristram"],
      correctIndex: 2,
      explanation: "Gawain — senior knight of the Round Table — was sent to woo Ettarre on Pelleas's behalf. His betrayal is the cycle's clearest individual-moral-failure and the institutional collapse of chivalric trust." },
    { id: "iotk-9-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "At the idyll's close, which character thinks \"The time is hard at hand\"?",
      options: ["Arthur", "Guinevere", "Lancelot", "Modred"],
      correctIndex: 3,
      explanation: "Modred, watching Guinevere and Lancelot foresee \"the dolorous day to be,\" silently registers that his moment approaches. Tennyson plants the traitor's awareness at exactly the cycle's turning-point." },
  ],

  // ── The Last Tournament (ch-10) ──────────────────────────────────
  10: [
    { id: "iotk-10-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What is the name of the tournament around which the idyll is structured?",
      options: ["The Diamond Jousts", "The Tournament of the Dead Innocence", "The Tournament of the Holy Grail", "The Last Joust of Camelot"],
      correctIndex: 1,
      explanation: "The name (Tennyson's invention) comes from an infant found dead with a necklace of rubies, whose rubies become the tournament-prize. The name also allegorizes the court's own dead innocence." },
    { id: "iotk-10-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Who murders Tristram on his return to Isolt at Tintagel?",
      options: ["Modred", "Lancelot, mistaking him for Gawain", "King Mark of Cornwall, Isolt's husband", "Arthur, in defense of the realm"],
      correctIndex: 2,
      explanation: "Mark — the cycle's other cuckolded king — kills Tristram in ambush. The parallel with Arthur/Guinevere/Lancelot is structurally deliberate: one resolution is forgiveness-with-judgment, the other is murder." },
    { id: "iotk-10-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The Last Tournament is Tennyson's most sustained sound-painting in the cycle.",
      correctBool: true,
      explanation: "Rain, autumn, yellowing leaves, wet wind — the atmospheric register is maintained across the entire idyll. The prosody panel curates the opening 30 lines as one of the cycle's concentrated sound-passages." },
    { id: "iotk-10-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The idyll's closing words are spoken by whom?",
      options: ["Arthur, to Guinevere", "Modred, plotting", "Dagonet the fool, sobbing to Arthur", "Lancelot, in soliloquy"],
      correctIndex: 2,
      explanation: "\"I am thy fool, / And I shall never make thee smile again\" — the fool's confession to Arthur is the idyll's final prophecy of the cycle's close. Shakespearean in lineage, drawn from the Lear-fool tradition." },
  ],

  // ── Guinevere (ch-11) ────────────────────────────────────────────
  11: [
    { id: "iotk-11-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Where does Guinevere take refuge after the adultery becomes public?",
      options: ["With Lancelot in Joyous Gard", "The nunnery at Almesbury", "Her father Leodogran's court", "A hermit's cell in the northern wilderness"],
      correctIndex: 1,
      explanation: "Almesbury (real place: Amesbury in Wiltshire) is the site of the idyll's action. The opening pluperfect — \"Queen Guinevere had fled the court\" — places the flight before the narrative begins." },
    { id: "iotk-11-2", type: "true_false", difficulty: "Apprentice", xpReward: 5,
      text: "In Malory, Arthur and Guinevere meet one last time at the nunnery; Tennyson preserves this scene.",
      correctBool: false,
      explanation: "The confrontation is Tennyson's invention — in Malory, Arthur and Guinevere never meet again after her flight. Tennyson's invention is load-bearing: it gives the cycle its moral climax and generates its central critical controversy." },
    { id: "iotk-11-3", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What does Arthur's speech to Guinevere conclude with?",
      options: ["\"Depart, then, until thou art punished\"", "\"I forgive thee, as Eternal God forgives\"", "\"There is no mercy in this hall\"", "\"Thou wast my queen, and art no more\""],
      correctIndex: 1,
      explanation: "Arthur forgives Guinevere in theological register but refuses to take her hand (\"that too is flesh, / And in the flesh thou hast sinned\"). The forgiveness-with-withheld-intimacy is the cycle's most morally contested passage." },
    { id: "iotk-11-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "What does Guinevere eventually become at Almesbury?",
      options: ["A simple nun until her death", "A hermit on Avalon", "Abbess of the nunnery", "A pilgrim to Jerusalem"],
      correctIndex: 2,
      explanation: "She is chosen Abbess for \"good deeds and pure life.\" Tennyson's Abbess-position is diminished compared to Malory's — Malory's Guinevere exercises independent spiritual authority; Tennyson's is primarily penitential." },
  ],

  // ── The Passing of Arthur (ch-12) ────────────────────────────────
  12: [
    { id: "iotk-12-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "What does Arthur order Bedivere to do with Excalibur?",
      options: ["Carry it to Guinevere as final gift", "Fling it into the middle mere", "Bury it with his own body", "Bring it to Modred as challenge"],
      correctIndex: 1,
      explanation: "Bedivere twice hesitates before finally throwing Excalibur back into the lake, where an arm rises to catch and withdraw it. The scene is from Tennyson's 1833 \"Morte d'Arthur,\" the oldest passage in the cycle." },
    { id: "iotk-12-2", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "The phrase \"from the great deep to the great deep he goes\" describes:",
      options: ["Lancelot's return to France", "Modred's death in battle", "Arthur's departure for Avalon", "The dead Tristram's soul"],
      correctIndex: 2,
      explanation: "One of the cycle's most-quoted lines. Arthur came from the great deep (Bellicent's ninth wave in Idyll I) and returns to it — the cycle's architectural ring is closed in this phrase." },
    { id: "iotk-12-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The Passing of Arthur incorporates passages from Tennyson's 1833 \"Morte d'Arthur,\" his first Arthurian poem.",
      correctBool: true,
      explanation: "The cycle's closing idyll is also its oldest material. The older Tennyson (60) wrapped his 24-year-old self's work in new framing; the poet spent 52 years writing toward his own earliest vision." },
    { id: "iotk-12-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "How does the Idylls' closing contrast with the Aeneid's closing?",
      options: ["Both end in violence", "Tennyson ends in transfiguration (vanishing into light); Virgil ends in the indignant shade of the killed Turnus", "Both end in peaceful sleep", "Tennyson ends in Christian resurrection; Virgil in pagan rebirth"],
      correctIndex: 1,
      explanation: "The 1,900-year tonal trajectory. Virgil closes his epic in violent injustice (Aeneas killing Turnus, the shade \"indignata\"); Tennyson closes in serene transfiguration (the ship vanishing \"from less to less and vanish into light\"). The difference is ancient fatalism vs. Victorian providentialism." },
  ],

  // ── To the Queen (ch-13) ─────────────────────────────────────────
  13: [
    { id: "iotk-13-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "When was \"To the Queen\" composed as the cycle's closing coda?",
      options: ["1859", "1862, immediately after the Dedication", "1872, ten years after the Dedication, after the Prince of Wales's recovery", "1885, as Tennyson's last major addition"],
      correctIndex: 2,
      explanation: "The ten-year gap between Dedication (1862) and Coda (1872) is tonally visible — the coda is more tired, more imperially-anxious, more directly addressed to Victoria." },
    { id: "iotk-13-2", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The coda's final gesture turns from looking back (Albert, Arthur, the legendary past) to looking forward (\"only lives that are to be\").",
      correctBool: true,
      explanation: "The closing rejects the monument-making mode of the Dedication in favor of a forward-facing instruction. The Idylls, in its final gesture, is a work that uses the past to free the future." },
  ],

  // ── 14: Mid-cycle Trial A — First four idylls (Hope & Establishment)
  14: [
    { id: "iotk-c1-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Which four idylls trace the Round Table's bright establishment phase?",
      options: ["Dedication, Coming of Arthur, Gareth, Holy Grail", "Coming of Arthur, Gareth and Lynette, Marriage of Geraint, Geraint and Enid", "Coming of Arthur, Balin, Merlin and Vivien, Lancelot and Elaine", "Dedication, Coming of Arthur, Gareth, To the Queen"],
      correctIndex: 1,
      explanation: "The first four idylls in the reading order — I, II, III, IV — are the cycle's hope-and-establishment phase. From Balin and Balan (V) onward the cycle begins its darkening arc." },
    { id: "iotk-c1-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which single character appears — warmly, in her unblemished queen-phase — across all four idylls of the bright phase?",
      options: ["Merlin", "Lancelot", "Guinevere", "Bedivere"],
      correctIndex: 2,
      explanation: "Guinevere is present as generous court-mother across the first four idylls. Reading these against Idyll XI (her penitential nunnery scene) measures what the cycle loses." },
    { id: "iotk-c1-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The rumor of Guinevere's adultery first appears as early as Idyll III (The Marriage of Geraint).",
      correctBool: true,
      explanation: "\"Touching her guilty love for Lancelot, / Though yet there lived no proof\" — the court-rumor is seeded in Idyll III and becomes operationally consequential in Idyll V (Balin's garden-glimpse) and especially Idyll VI (Merlin and Vivien)." },
  ],

  // ── 15: Mid-cycle Trial B — Middle four idylls (Corruption phase)
  15: [
    { id: "iotk-c2-1", type: "multiple_choice", difficulty: "Apprentice", xpReward: 5,
      text: "Which idyll centers on the sage's silencing, which removes the kingdom's prophetic intelligence?",
      options: ["Balin and Balan", "Merlin and Vivien", "The Holy Grail", "Pelleas and Ettarre"],
      correctIndex: 1,
      explanation: "Idyll VI (Merlin and Vivien) is the cycle's hinge — after Merlin is sealed in the hollow oak, the kingdom navigates without foresight, and the remaining six idylls are the working-out of that loss." },
    { id: "iotk-c2-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The corruption arc links Idylls VI through IX. Which sequence of catastrophes is correct?",
      options: ["Grail quest → Merlin silenced → Pelleas disillusioned → Elaine dies", "Merlin silenced → Elaine dies → Grail quest scatters knights → Pelleas disillusioned", "Merlin silenced → Pelleas disillusioned → Grail quest → Elaine dies", "Merlin silenced → Elaine dies → Pelleas disillusioned → Grail quest"],
      correctIndex: 1,
      explanation: "The canonical reading order: Merlin and Vivien (VI) → Lancelot and Elaine (VII) → Holy Grail (VIII) → Pelleas and Ettarre (IX). Each idyll compounds the moral collapse." },
    { id: "iotk-c2-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "Tennyson's Holy Grail idyll compresses roughly 100 Malory chapters into fewer than 1,000 lines.",
      correctBool: true,
      explanation: "Malory's Sankgreal (Books XIII–XVII) runs ~100 chapters; Tennyson's idyll is 920 lines. The radical compression is the idyll's formal signature — and its theological re-framing for Victorian Anglican readership." },
  ],

  // ── 16: Master Trial — "Old Order Changeth" Seal ─────────────────
  16: [
    { id: "iotk-m-1", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which line, doubled across Idylls I and XII, is the cycle's philosophical signature?",
      options: ["\"I have lived my life\"", "\"The old order changeth, yielding place to new\"", "\"From the great deep to the great deep he goes\"", "\"Man's word is God in man\""],
      correctIndex: 1,
      explanation: "The line is triumphal in the young Arthur's mouth (Idyll I) and elegiac in the dying Arthur's (Idyll XII). The doubling is the cycle's philosophical argument: history is change, and the cycle's achievement is in the process of change itself." },
    { id: "iotk-m-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Tennyson's stated moral frame (Dedication) reads the cycle as an allegory of what?",
      options: ["Arthur as England and Guinevere as France", "Arthur as soul, Guinevere as flesh, Round Table as Victorian civilization", "Arthur as Christianity and Lancelot as paganism", "Arthur as the ideal king and Modred as tyranny"],
      correctIndex: 1,
      explanation: "Tennyson's own reading, printed in annotations to the 1891 collected edition. The critical tradition since the late nineteenth century has argued that the cycle's practice often exceeds this frame." },
    { id: "iotk-m-3", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The cycle's primary source is Sir Thomas Malory's Le Morte d'Arthur, except for the Geraint/Enid idylls, which derive from the Welsh Mabinogion via Lady Charlotte Guest.",
      correctBool: true,
      explanation: "Two-source rule for the cycle: Malory for Arthurian material, Mabinogion (Guest 1838–45) for Geraint/Enid. A few moments are Tennyson's own invention." },
    { id: "iotk-m-4", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which of Tennyson's characters is the critical consensus most often identified as flattened for the cycle's moral frame?",
      options: ["Lancelot", "Guinevere", "Vivien", "Elaine"],
      correctIndex: 2,
      explanation: "The consensus runs from contemporary reviewers (Walter Bagehot) through modern scholarship. Vivien serves as the villain the cycle's moral frame requires, at the cost of the psychological complexity Tennyson gave Guinevere, Lancelot, and Elaine." },
    { id: "iotk-m-5", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which Victorian painter's 1874 canvas is paired with the Idylls in the Tome Stoa gallery?",
      options: ["Millais, Ophelia", "Burne-Jones, The Beguiling of Merlin", "Waterhouse, The Lady of Shalott", "Rossetti, Proserpine"],
      correctIndex: 1,
      explanation: "Burne-Jones's canvas (Lady Lever Art Gallery) depicts the idyll's pivotal scene — Vivien leaning over the entranced Merlin with the book of charms. Contemporary with Tennyson's composition and visually canonical." },
    { id: "iotk-m-6", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which two idylls are the cycle's framing matter, paired across a ten-year composition gap?",
      options: ["Dedication (1862) and Passing of Arthur (1869)", "Dedication (1862) and To the Queen (1872)", "Coming of Arthur (1869) and To the Queen (1872)", "Gareth and Lynette (1872) and Balin and Balan (1885)"],
      correctIndex: 1,
      explanation: "Dedication and To the Queen are the cycle's twin framing poems — the 1862 public mourning for Albert and the 1872 address to Victoria after the cycle's darker completion. Reading them as a pair reveals the older Tennyson's tonal evolution." },
    { id: "iotk-m-7", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The Passing of Arthur incorporates Tennyson's 1833 \"Morte d'Arthur,\" making the cycle's ending also its oldest compositional material.",
      correctBool: true,
      explanation: "Tennyson spent fifty-two years writing toward his own earliest vision. The older poet (60, in 1869) wrapped the 24-year-old poet's work in new framing — the cycle's architectural recursion." },
    { id: "iotk-m-8", type: "multiple_choice", difficulty: "Master", xpReward: 25,
      text: "Arthur's critique of the Grail quest — \"wandering fires, lost in the quagmire\" — reveals which theological position?",
      options: ["Endorsement of Catholic mysticism", "Civic-faith: active work in the world over otherworldly visionary withdrawal", "Rejection of all religious experience as illusion", "Affirmation of the cloister over the court"],
      correctIndex: 1,
      explanation: "Arthur's position is continuous with Tennyson's \"In Memoriam\" register — honest doubt, civic virtue, suspicion of visionary absorption that abandons the realm. The idyll holds both pious and skeptical readings honestly." },
    { id: "iotk-m-9", type: "multiple_choice", difficulty: "Master", xpReward: 25,
      text: "Lancelot's partial Grail-vision (\"Not for thee, O knight of sin\") connects which two idylls architecturally?",
      options: ["Idylls I and XII", "Idylls VII (Lancelot and Elaine) and VIII (Holy Grail)", "Idylls VI (Merlin and Vivien) and XI (Guinevere)", "Idylls III (Marriage of Geraint) and IV (Geraint and Enid)"],
      correctIndex: 1,
      explanation: "Idyll VII's \"honour rooted in dishonour\" soliloquy (adultery as interior state) and Idyll VIII's chapel-scene (adultery as barrier to Grail) are architectural pair. The sin at two scales — inward and cosmic." },
    { id: "iotk-m-10", type: "multiple_choice", difficulty: "Master", xpReward: 25,
      text: "Which of these passages is most-often cited as the cycle's sustained technical peak in sound-painting?",
      options: ["The opening of The Coming of Arthur", "The Diamond Jousts passage", "Elaine's funeral-barge voyage", "Vivien's seduction-speeches"],
      correctIndex: 2,
      explanation: "The funeral-barge passage (Idyll VII) is the most-imitated Victorian set-piece of ekphrastic sound-painting — long open vowels, liquid consonants, the pentameter pulled across caesurae. The Millais-Waterhouse-Pre-Raphaelite visual tradition descends from or runs parallel to it." },
    { id: "iotk-m-11", type: "true_false", difficulty: "Scholar", xpReward: 10,
      text: "The confrontation between Arthur and Guinevere at Almesbury is invented by Tennyson; Malory never has them meet again after her flight.",
      correctBool: true,
      explanation: "Malory's Arthur and Guinevere die separately; no confrontation-and-forgiveness. Tennyson's invention is the cycle's most morally contested passage and critical-debate generator." },
    { id: "iotk-m-12", type: "multiple_choice", difficulty: "Master", xpReward: 25,
      text: "The cycle's \"three queens\" appear twice. At the opening (Bellicent's account) they are adjacent to Arthur's arrival; at the close they:",
      options: ["Kill Modred in the final battle", "Appear to Guinevere at Almesbury", "Bear the dying Arthur on the barge to Avalon", "Crown a new king at Camelot"],
      correctIndex: 2,
      explanation: "The numinous-feminine figures frame Arthur's beginning and end. Malory names them (Morgan le Fay, Queen of Northgalis, Queen of the Wastelands); Tennyson leaves them unnamed for mythic-universal register." },
    { id: "iotk-m-13", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which Victorian movement does the Idylls most directly engage on questions of religious faith?",
      options: ["The Oxford Movement (high-church ritualism)", "Broad Church theology (liberal Anglican, honest-doubt tradition)", "Methodist revivalism", "Catholic emancipation"],
      correctIndex: 1,
      explanation: "Tennyson's intellectual orbit included F.D. Maurice, Henry Sidgwick, the Cambridge Apostles — figures associated with Broad Church theology. \"In Memoriam\" had already formalized the honest-doubt tradition; the Grail idyll extends it into Arthurian material." },
    { id: "iotk-m-14", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which modern epic draws on the Idylls' wounded-king / wasted-land pattern as a twentieth-century inheritance?",
      options: ["Yeats's Byzantium poems", "Eliot's The Waste Land", "Pound's Cantos", "Auden's The Age of Anxiety"],
      correctIndex: 1,
      explanation: "Eliot's 1922 poem re-activates the Grail-and-wasted-land pattern, read via Jessie Weston's scholarship. Tennyson is an acknowledged antecedent — the Idylls' wasted-land-framed opening and Grail-departed-closing are part of the pattern's long inheritance." },
    { id: "iotk-m-15", type: "multiple_choice", difficulty: "Master", xpReward: 25,
      text: "Arthur's final question to Bedivere — asking if the old wound still bleeds — receives what answer?",
      options: ["No direct answer; Arthur is borne away", "Yes, the wound bleeds still", "The wound has closed in peace", "Arthur himself answers: \"Never again\""],
      correctIndex: 0,
      explanation: "The idyll's closing defers resolution. Bedivere watches the barge vanish \"from less to less and vanish into light,\" the wound unsettled. The new sun rises bringing the new year — the cycle closes on providential-renewal rather than pronouncement on Arthur's healing." },
  ],

  // ── 17: Anglophone Epic Line Trial — "Englisc" Seal ──────────────
  17: [
    { id: "iotk-epl-1", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "The Anglophone Epic Line in the Tome catalog spans:",
      options: ["Beowulf → Faerie Queene → Paradise Lost → Idylls", "Beowulf → Faerie Queene → Paradise Lost → Don Juan → Idylls of the King", "Faerie Queene → Paradise Lost → Don Juan → Idylls", "Paradise Lost → Idylls only"],
      correctIndex: 1,
      explanation: "The full five-book Anglophone arc: ca. 1000 (Beowulf) → 1590–96 (Faerie Queene) → 1667/1674 (Paradise Lost) → 1819–24 (Don Juan) → 1859–85 (Idylls). A 900-year arc of English-language epic composition." },
    { id: "iotk-epl-2", type: "multiple_choice", difficulty: "Scholar", xpReward: 10,
      text: "Which two works in the Anglophone Epic Line are the great Arthurian poems?",
      options: ["Beowulf and Faerie Queene", "Faerie Queene and Idylls of the King", "Paradise Lost and Idylls", "Beowulf and Don Juan"],
      correctIndex: 1,
      explanation: "Spenser's Faerie Queene (1590s) and Tennyson's Idylls (1859–85) are the two monumental English-language Arthurian epics. Their cross-reference cluster in the Tome catalog includes the Arthur-figure, the allegorical-moral framing, and the Merlin-seduction motif." },
    { id: "iotk-epl-3", type: "true_false", difficulty: "Master", xpReward: 25,
      text: "Tennyson's closing — \"from the great deep to the great deep he goes\" — is tonally opposite to Virgil's Aeneid closing (Turnus's indignant shade) and more closely echoes Milton's Paradise Lost closing (\"the world was all before them\").",
      correctBool: true,
      explanation: "The tonal contrast is the Idylls' deliberate positioning inside the epic tradition: rejecting Virgilian violence-closure, embracing Miltonian forward-facing renewal. The 1,900-year trajectory from Roman civic violence to Victorian providentialism." },
  ],
}
