/**
 * Decameron annotations — second batch. One focused annotation per tale
 * for the 86 tales not covered in the load-bearing seed set. Short form
 * (2–4 sentences each) honoring the same Virgil voice. Anchors are
 * protagonist names or distinctive phrases confirmed to appear in each
 * tale's opening paragraphs of the Payne translation.
 */

import type { Annotation } from "./types"

export const DECAMERON_ANNOTATIONS_BATCH_2: Annotation[] = [
  // Day I — remaining
  { id: "decameron-i-2-abraham", bookId: "the-decameron", chapterNumber: 4,
    anchorText: "Abraham", anchorOccurrence: 1,
    title: "Abraham Converts",
    quotedPassage: "Abraham",
    passageReference: "Day I, Tale 2 — Neifile's tale",
    commentary: `A Jewish merchant, Abraham, is pressed by his Christian friend Giannotto to convert. Abraham insists on visiting Rome first to see the head of the faith. He returns converted — not in spite of the corruption of the Curia, but because of it: any religion that survives such leadership must be propped up by the Holy Spirit. The tale sits beside I.1 as a diptych of anticlerical satire turned upside-down, and its sympathy for Abraham as a reasoning agent is part of Boccaccio's notably warm posture toward Jewish characters (continuing in I.3).`,
    crossReferences: [], tags: ["historical"] },

  { id: "decameron-i-4-monk-abbot", bookId: "the-decameron", chapterNumber: 6,
    anchorText: "monk", anchorOccurrence: 1,
    title: "Dioneo's First Tale",
    quotedPassage: "monk",
    passageReference: "Day I, Tale 4 — Dioneo's tale",
    commentary: `Dioneo's first tale in the collection and a declaration of his register: a young monk caught with a woman in his cell is outmaneuvered by the abbot — who, inspecting the evidence, falls into the same sin himself and thereby cannot punish it. The hypocrisy-trap structure will recur throughout the Decameron's anticlerical tales. Dioneo tells it fourth on Day I, and afterwards he bargains successfully for the privilege of always telling the tenth.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-i-5-montferrat", bookId: "the-decameron", chapterNumber: 7,
    anchorText: "Marchioness", anchorOccurrence: 1,
    title: "The Dinner of Hens",
    quotedPassage: "Marchioness",
    passageReference: "Day I, Tale 5 — Fiammetta's tale",
    commentary: `The Marchioness of Montferrat deflects the King of France's infatuation during his crusading visit by serving a dinner of nothing but hens, dressed every way possible. "Your Majesty," she explains when he marvels, "the hens here, though differently plumaged, are the same meat as hens anywhere." The lesson — all women are the same in essential substance — shames him off his suit without ever being spoken as a rebuke. This is Boccaccio's ideal female witty riposte, anticipating Day VI's entire theme.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-i-6-inquisitor", bookId: "the-decameron", chapterNumber: 8,
    anchorText: "inquisitor", anchorOccurrence: 1,
    title: "A Single Reply",
    quotedPassage: "inquisitor",
    passageReference: "Day I, Tale 6 — Emilia's tale",
    commentary: `A Florentine inquisitor fines a worthy man for the remark that the inquisitor's wine is so good even Christ would drink it. The fined man returns later, reports that at dinner he had seen the friars receive "for one measure, a hundred in return" — and notes that by that math the friars will drown in hell-broth. The inquisitor gets the point and drops the prosecution. Boccaccio's Florentine inquisitions were a living institution; naming his satire at Emilia's day makes it specific, not abstract.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-i-7-bergamino", bookId: "the-decameron", chapterNumber: 9,
    anchorText: "Bergamino", anchorOccurrence: 1,
    title: "Primasso and the Abbot",
    quotedPassage: "Bergamino",
    passageReference: "Day I, Tale 7 — Filostrato's tale",
    commentary: `The jester Bergamino rebukes Can Grande della Scala's unaccustomed stinginess with a nested tale: Primasso, a medieval Latin poet, arrives at the Abbot of Cluny's table and receives no bread. When the abbot sees him, he is moved to generosity. Bergamino tells this at Verona, Can Grande understands, and the purse opens. The tale is a defense of poets and their need for patronage — and a piece of fourteenth-century self-awareness about the economics of storytelling that Boccaccio himself lived under.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-i-8-borsiere", bookId: "the-decameron", chapterNumber: 10,
    anchorText: "Guglielmo Borsiere", anchorOccurrence: 1,
    title: "The Rebuke of Avarice",
    quotedPassage: "Guglielmo Borsiere",
    passageReference: "Day I, Tale 8 — Lauretta's tale",
    commentary: `Guglielmo Borsiere, a courtly jester of Boccaccio's own lineage — he is named in Dante's *Inferno* XVI among the Florentine sodomites — shames the miser Messer Ermino de' Grimaldi into generosity with a single reply: "Paint me Courtesy, for I see you have seen none in your house." The tale's piquancy is that Borsiere is a historical figure Dante had damned for personal sin; Boccaccio retrieves him as the agent of civic virtue. A small retrieval from Dante's judgment.`,
    crossReferences: [
      { type: "compare", description: "Guglielmo Borsiere appears in Dante's Inferno XVI among Florentine sodomites. Boccaccio's use of him as a virtuous figure is a quiet retrieval.",
        workTitle: "The Divine Comedy", workAuthor: "Dante Alighieri",
        passageReference: "Inferno XVI", targetBookId: "the-divine-comedy", targetChapterNumber: 15, targetAnchorText: null },
    ],
    tags: ["literary-influence", "historical"] },

  { id: "decameron-i-9-cyprus", bookId: "the-decameron", chapterNumber: 11,
    anchorText: "King of Cyprus", anchorOccurrence: 1,
    title: "The Shamed King",
    quotedPassage: "King of Cyprus",
    passageReference: "Day I, Tale 9 — Elisa's tale",
    commentary: `A noblewoman of Gascony, assaulted on pilgrimage to the Holy Land, appeals to the cowardly King of Cyprus. "Teach me," she says, "how you endure the injuries others do to you — so I may as patiently endure this one." Shamed by a single sentence from a stranger, the king is afterwards the justest of rulers. The tale's bite is its brevity; Boccaccio gives it to Elisa, the sharpest of the seven ladies, for exactly that economy.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-i-10-alberto", bookId: "the-decameron", chapterNumber: 12,
    anchorText: "Alberto", anchorOccurrence: 1,
    title: "The Dignity of Late Love",
    quotedPassage: "Alberto",
    passageReference: "Day I, Tale 10 — Pampinea's closing tale of Day I",
    commentary: `Pampinea, as queen, closes Day I with a defense of love at any age: the elderly physician Master Alberto of Bologna, mocked by a lady for his open affection, answers that women are like leeks — the head white, the tail green — and that his age gives him insight her youth lacks. The tale is the gentlest in the collection and a statement of the brigata's first principle: desire is not the young alone's prerogative, and dignity in love is possible at every age.`,
    crossReferences: [], tags: ["literary-influence"] },

  // Day II — remaining
  { id: "decameron-ii-1-martellino", bookId: "the-decameron", chapterNumber: 15,
    anchorText: "Martellino", anchorOccurrence: 1,
    title: "The False Cripple",
    quotedPassage: "Martellino",
    passageReference: "Day II, Tale 1 — Neifile's tale",
    commentary: `Three Florentine jokers in Treviso pretend Martellino is a cripple come to be healed at the shrine of a new saint; the cure performed, the ruse is exposed, and Martellino is nearly hanged. This is Day II's opening, and its theme — fortune's reversals ending well — is already tested: the tale's comedy is the narrowness of the escape, not the guarantee of one. Boccaccio dislikes easy providential endings; the brigata will learn that across ten tales.`,
    crossReferences: [], tags: ["literary-influence", "philosophical", "historical"] },

  { id: "decameron-ii-2-rinaldo", bookId: "the-decameron", chapterNumber: 16,
    anchorText: "Rinaldo", anchorOccurrence: 1,
    title: "The Widow's Hospitality",
    quotedPassage: "Rinaldo",
    passageReference: "Day II, Tale 2 — Filostrato's tale",
    commentary: `Rinaldo d'Asti, robbed and stripped on the road, is taken in by a widow who has just been stood up by her lover. The accidental substitution proves satisfactory for both. Boccaccio's ethics here are pragmatic rather than devotional: Rinaldo had been praying to Saint Julian (patron of travelers' lodgings) as the robbers approached, and the saint's kindness arrived in unexpected form.`,
    crossReferences: [], tags: ["philosophical", "historical"] },

  { id: "decameron-ii-3-abbot-england", bookId: "the-decameron", chapterNumber: 17,
    anchorText: "abbot", anchorOccurrence: 1,
    title: "The Abbot of England",
    quotedPassage: "abbot",
    passageReference: "Day II, Tale 3 — Pampinea's tale",
    commentary: `Alessandro, one of three nephews who have bankrolled their uncles' spending, meets "the Abbot of England" at an inn — who turns out to be the King of England's daughter fleeing a forced marriage. They wed secretly; the Pope reconciles the match; all is well. The tale's generic machinery (secret royal identity, cross-dressing, papal brokerage) is Boccaccio in his purest romance register.`,
    crossReferences: [], tags: ["philosophical", "historical"] },

  { id: "decameron-ii-4-landolfo", bookId: "the-decameron", chapterNumber: 18,
    anchorText: "Landolfo", anchorOccurrence: 1,
    title: "The Jeweled Chest",
    quotedPassage: "Landolfo",
    passageReference: "Day II, Tale 4 — Lauretta's tale",
    commentary: `Landolfo Rufolo of Ravello, ruined as a merchant, turns pirate; ruined as a pirate, he is shipwrecked and clings to a chest which he discovers is filled with jewels. Fortune, Boccaccio is demonstrating, turns on an axis no one controls — but turns. The closing detail that Landolfo, restored to wealth, retires to live prudently is the day's implicit moral: second fortunes are only kept by those who learn from the first loss.`,
    crossReferences: [], tags: ["historical", "philosophical"] },

  { id: "decameron-ii-6-beritola", bookId: "the-decameron", chapterNumber: 20,
    anchorText: "Beritola", anchorOccurrence: 1,
    title: "Madonna Beritola Among the Beasts",
    quotedPassage: "Beritola",
    passageReference: "Day II, Tale 6 — Emilia's tale",
    commentary: `Madonna Beritola is shipwrecked alone on an island, where she nurses a pair of roe-deer kids alongside her grief and lives as a woman wild. Over years her children, sold into slavery, find their ways back to her. This is the Decameron at its most melodramatic — and most attentive to maternal suffering as a plot engine. Emilia tells it with the warmth Boccaccio reserves for his warmest narrator.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-ii-7-alatiel", bookId: "the-decameron", chapterNumber: 21,
    anchorText: "Alatiel", anchorOccurrence: 1,
    title: "The Bride of Nine Beds",
    quotedPassage: "Alatiel",
    passageReference: "Day II, Tale 7 — Pamfilo's tale",
    commentary: `The longest tale in the Decameron. Alatiel, daughter of the Sultan of Babylon, is shipped west to her bridegroom; wrecked, abducted, rescued, abducted again, she passes through nine lovers' beds across four years and is at last delivered to her bridegroom as a supposed virgin. The tale is a satire of Mediterranean commerce as much as of chastity: Alatiel changes hands like a precious cargo. Pamfilo's long form here is a test of the brigata's patience for the novella form itself.`,
    crossReferences: [], tags: ["philosophical", "historical"] },

  { id: "decameron-ii-8-antwerp", bookId: "the-decameron", chapterNumber: 22,
    anchorText: "Antwerp", anchorOccurrence: 1,
    title: "The Exiled Count",
    quotedPassage: "Antwerp",
    passageReference: "Day II, Tale 8 — Elisa's tale",
    commentary: `The Count of Antwerp, falsely accused of soliciting the Queen of France, flees with his two small children, serves anonymously as a groom in England, and is eventually restored to name and honors. The "calumny and restoration" plot is a European commonplace — but Boccaccio's count serves as a horse-keeper, not a knight-errant, and the class observation is load-bearing: nobility is preserved, he says, by the willingness to do humble work.`,
    crossReferences: [], tags: ["philosophical"] },

  { id: "decameron-ii-10-paganino", bookId: "the-decameron", chapterNumber: 24,
    anchorText: "Paganino", anchorOccurrence: 1,
    title: "The Wife Who Chose the Pirate",
    quotedPassage: "Paganino",
    passageReference: "Day II, Tale 10 — Dioneo's tale",
    commentary: `Messer Ricciardo, an elderly jurist with a young wife, is so careful with her honor — and his own performance — that the pirate Paganino, who abducts her, has the easier task. When Ricciardo comes to ransom her, she chooses the pirate. Dioneo's tale, closing Day II, turns the day's fortune-reversal theme on its head: fortune here is the wife's — and the reversal is the husband's discovery that his caution had cost him everything. A pointed counter-tale to Day III's various cuckoldries.`,
    crossReferences: [], tags: ["historical", "philosophical"] },

  // Day III — remaining
  { id: "decameron-iii-1-masetto", bookId: "the-decameron", chapterNumber: 27,
    anchorText: "Masetto", anchorOccurrence: 1,
    title: "The Silent Gardener",
    quotedPassage: "Masetto",
    passageReference: "Day III, Tale 1 — Filostrato's tale",
    commentary: `Masetto of Lamporecchio feigns himself dumb and is hired as gardener by a convent of nuns, who — reasoning that a mute cannot tell tales — all in turn resort to him, to his increasing exhaustion. When he finally speaks (the abbess having overreached), the convent and the abbess settle on a rotating schedule and the peace is kept for decades. The comedy is blunt; the satiric target is the logic of enclosed communities, where silence is complicity's currency.`,
    crossReferences: [], tags: ["historical"] },

  { id: "decameron-iii-2-agilulf", bookId: "the-decameron", chapterNumber: 28,
    anchorText: "Agilulf", anchorOccurrence: 1,
    title: "The King and the Groom",
    quotedPassage: "Agilulf",
    passageReference: "Day III, Tale 2 — Pampinea's tale",
    commentary: `A Lombard groom, having lain with King Agilulf's queen by imposture, is identified by the king — who, rather than expose the queen's shame, silently cuts the groom's hair as a mark. The groom, awake and understanding, shaves every man in the stable to defeat the mark. Agilulf's choice to absorb the insult rather than betray his own honor is, for Boccaccio, an under-recognized form of sovereign wisdom.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-iii-3-friar-messenger", bookId: "the-decameron", chapterNumber: 29,
    anchorText: "friar", anchorOccurrence: 1,
    title: "The Unwitting Messenger",
    quotedPassage: "friar",
    passageReference: "Day III, Tale 3 — Filomena's tale",
    commentary: `A lady, desiring a man she dare not address, invents sins committed against her by him and confesses them weekly to a gullible friar, who lectures the supposed offender each time. The man, who was not offending her, understands the coded signals and presents himself. The tale is a piece of ingenuity — communication by negation, routed through an institution that prides itself on knowing the heart. The friar never knows he has been a postman.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-iii-4-fra-puccio", bookId: "the-decameron", chapterNumber: 30,
    anchorText: "Fra Puccio", anchorOccurrence: 1,
    title: "The Penance at the Window",
    quotedPassage: "Fra Puccio",
    passageReference: "Day III, Tale 4 — Pamfilo's tale",
    commentary: `Dom Felice invents for the pious Fra Puccio a miraculous penance — standing at a window reciting prayers while fasting — which usefully occupies him every night that Felice lies with his wife. The satire aims precisely: excessive devotion, Boccaccio suggests, is no devotion at all, and leaves household and marriage alike vulnerable to whoever is devout in more worldly ways.`,
    crossReferences: [], tags: ["historical"] },

  { id: "decameron-iii-6-minutolo", bookId: "the-decameron", chapterNumber: 32,
    anchorText: "Ricciardo", anchorOccurrence: 1,
    title: "The Bathhouse Substitution",
    quotedPassage: "Ricciardo",
    passageReference: "Day III, Tale 6 — Fiammetta's tale",
    commentary: `Ricciardo Minutolo of Naples, in love with Filippello Sighinolfo's wife, persuades her that her husband has an appointment at a bathhouse with another woman. She arrives in a darkened chamber to catch him; Ricciardo substitutes himself; the deception holds until after. When revealed, she accepts him — on the reasoning that the scandal of refusal would cost her more than the substitution already has. Naples, urban and cynical, is Boccaccio's chosen setting for the darker comedies of desire.`,
    crossReferences: [], tags: ["historical"] },

  { id: "decameron-iii-7-tedaldo", bookId: "the-decameron", chapterNumber: 33,
    anchorText: "Tedaldo", anchorOccurrence: 1,
    title: "The Pilgrim Returned",
    quotedPassage: "Tedaldo",
    passageReference: "Day III, Tale 7 — Emilia's tale",
    commentary: `Tedaldo degli Elisei, long absent and thought dead, returns to Florence disguised as a pilgrim and discovers his beloved estranged and her husband unjustly convicted of his own supposed murder. He unweaves the calamity, reconciles the marriage, reveals himself. The tale is a portrait of how displacement clarifies — and of Emilia's belief that a patient speaker can fix what hasty action has broken.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-iii-8-ferondo", bookId: "the-decameron", chapterNumber: 34,
    anchorText: "Ferondo", anchorOccurrence: 1,
    title: "The Abbot's Purgatory",
    quotedPassage: "Ferondo",
    passageReference: "Day III, Tale 8 — Lauretta's tale",
    commentary: `The abbot gives the jealous peasant Ferondo a sleeping-draught that simulates death; buried as a corpse, Ferondo is revived secretly in a cell styled as Purgatory, where he is flogged by disguised monks while the abbot visits his wife. Restored to life and duly chastened, Ferondo never again accuses. The tale's scandal is the abbot's cool operational competence — not passion but management.`,
    crossReferences: [], tags: ["historical"] },

  { id: "decameron-iii-10-alibech", bookId: "the-decameron", chapterNumber: 36,
    anchorText: "Alibech", anchorOccurrence: 1,
    title: "Putting the Devil in Hell",
    quotedPassage: "Alibech",
    passageReference: "Day III, Tale 10 — Dioneo's tale",
    commentary: `Notoriously the most explicit tale in the Decameron. Alibech, a girl in the Thebaid seeking instruction in the service of God, is taught by the hermit Rustico a euphemism — "putting the devil back into hell" — which denotes exactly what the reader suspects. Victorian translators often left this tale in Italian or Latin; Payne translates it into English, without shrinkage.

Dioneo tells it as the tenth tale of Day III, exploiting his theme-exemption privilege to land the collection's single most transgressive piece of rhetoric. The satiric target is not sexuality but desert-father asceticism: the renunciation that is so extreme it becomes its own form of appetite. Read intellectually, it is a contribution to the theological argument about whether nature and grace can be opposed — Boccaccio's answer is "not on Rustico's terms."`,
    crossReferences: [], tags: ["historical", "philosophical"] },

  // Day IV — remaining (load-bearing IV.1/IV.5 already covered)
  { id: "decameron-iv-2-frate-alberto", bookId: "the-decameron", chapterNumber: 40,
    anchorText: "Frate Alberto", anchorOccurrence: 1,
    title: "The Angel Gabriel in Venice",
    quotedPassage: "Frate Alberto",
    passageReference: "Day IV, Tale 2 — Pampinea's tale",
    commentary: `The friar Alberto of Imola, preying on the vanity of Madonna Lisetta, persuades her that the angel Gabriel is in love with her — and that he, Alberto, will "lend" Gabriel his body for visits. Exposed, Alberto is forced to flee Venice daubed with honey and feathers. Auerbach's *Mimesis* devotes its chapter IX to this tale as a model of Boccaccio's stylistic layering — three registers (pious, mock-epic, street comedy) braided in a single paragraph.`,
    crossReferences: [
      { type: "compare", description: "Auerbach treats this tale in *Mimesis* chapter IX as an exemplar of Boccaccio's stylistic range — three registers (devotional, mock-heroic, Venetian street) layered in a single paragraph.",
        workTitle: "Mimesis", workAuthor: "Erich Auerbach",
        passageReference: "Chapter IX", targetBookId: null, targetChapterNumber: null, targetAnchorText: null },
    ],
    tags: ["historical", "literary-influence"] },

  { id: "decameron-iv-3-marseilles", bookId: "the-decameron", chapterNumber: 41,
    anchorText: "Marseilles", anchorOccurrence: 1,
    title: "Three Brothers, Three Sisters",
    quotedPassage: "Marseilles",
    passageReference: "Day IV, Tale 3 — Lauretta's tale",
    commentary: `Three young Marseillais brothers flee with three sisters to Crete; love thickens into jealousy, jealousy into murder, and all six come to ruin. Lauretta, who sings the day's ballads, here narrates its coldest tale: a study in how desire unchecked by social constraint destroys not one couple but a whole network of them.`,
    crossReferences: [], tags: ["philosophical"] },

  { id: "decameron-iv-4-gerbino", bookId: "the-decameron", chapterNumber: 42,
    anchorText: "Gerbino", anchorOccurrence: 1,
    title: "The Princess on the Ship",
    quotedPassage: "Gerbino",
    passageReference: "Day IV, Tale 4 — Elisa's tale",
    commentary: `Gerbino, grandson of King William of Sicily, has loved the daughter of the King of Tunis only by her reputation; when her father ships her west for an arranged marriage, Gerbino attacks the ship — and her escort kills her on deck rather than lose her. Gerbino is executed for violating his grandfather's pledge of safe passage. The tale reads as a test of courtly love against realpolitik: the code demanded he act; the state demanded he not.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-iv-6-andreuola", bookId: "the-decameron", chapterNumber: 44,
    anchorText: "Andreuola", anchorOccurrence: 1,
    title: "The Dream of Death",
    quotedPassage: "Andreuola",
    passageReference: "Day IV, Tale 6 — Pamfilo's tale",
    commentary: `Andreuola dreams her secret lover Gabriotto will die — and, waking, finds him dying. Accused of his murder, she clears her name before the judge by the truthfulness and self-possession of her grief. The tale is less about the dream's prophetic weight than about the legal and emotional authority of a woman's transparent mourning: honesty, in Boccaccio, has evidentiary force.`,
    crossReferences: [], tags: ["philosophical"] },

  { id: "decameron-iv-7-simona", bookId: "the-decameron", chapterNumber: 45,
    anchorText: "Simona", anchorOccurrence: 1,
    title: "The Poisoned Sage",
    quotedPassage: "Simona",
    passageReference: "Day IV, Tale 7 — Emilia's tale",
    commentary: `Simona and Pasquino die — he first, she demonstrating how — from rubbing their teeth with a sage-leaf grown from a poisoned root. The magistrate, investigating, concludes innocence on both sides and destroys the plant. Emilia's gentleness in narration here is pointed: the couple did nothing wrong; the tragedy was horticultural. Day IV's theme includes this: love may end unhappily not through moral failure but through sheer misfortune.`,
    crossReferences: [], tags: ["philosophical"] },

  { id: "decameron-iv-8-girolamo", bookId: "the-decameron", chapterNumber: 46,
    anchorText: "Girolamo", anchorOccurrence: 1,
    title: "Two Silent Deaths",
    quotedPassage: "Girolamo",
    passageReference: "Day IV, Tale 8 — Neifile's tale",
    commentary: `Girolamo, parted from Salvestra by his mother's intervention and sent abroad, returns to find her married. He lies beside her in the dark and dies of grief; at his funeral she sees his corpse and dies upon it. Two self-chosen deaths without a word spoken between them. Neifile — the modest narrator — tells the tale without inflating it; Boccaccio trusts the reader not to need sentiment added.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-iv-9-rossiglione", bookId: "the-decameron", chapterNumber: 47,
    anchorText: "Rossiglione", anchorOccurrence: 1,
    title: "The Eaten Heart",
    quotedPassage: "Rossiglione",
    passageReference: "Day IV, Tale 9 — Filostrato's tale",
    commentary: `Guiglielmo Rossiglione slays his wife's lover, Guardastagno, and serves her the heart disguised in a meal. When she learns what she has eaten, she declares no lesser food will ever enter her after, and throws herself from the window. The "eaten heart" motif is old — it appears in troubadour biographies — but Boccaccio, giving it to Filostrato on his own day of tragedies, lets the narrator close his kingship with the archetype of destructive jealousy.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-iv-10-physician-chest", bookId: "the-decameron", chapterNumber: 48,
    anchorText: "physician", anchorOccurrence: 1,
    title: "The Chest in the Street",
    quotedPassage: "physician",
    passageReference: "Day IV, Tale 10 — Dioneo's tale",
    commentary: `Dioneo closes Day IV — the day of tragic loves — with a farce. The wife of a Salerno physician, thinking her lover dead after he mistakenly drinks a surgical sleeping-draught, hides him in a chest. Two neighbors, thinking the chest abandoned, steal it; the lover wakes inside it to a series of absurd misadventures and is eventually restored. Dioneo's theme-exemption privilege is used here as relief — closing a day of weeping with a tale so ridiculous the brigata laughs.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  // Day V — remaining (V.8 Nastagio and V.9 Federigo already covered)
  { id: "decameron-v-1-cimone", bookId: "the-decameron", chapterNumber: 51,
    anchorText: "Cimone", anchorOccurrence: 1,
    title: "Love Civilizes",
    quotedPassage: "Cimone",
    passageReference: "Day V, Tale 1 — Pamfilo's tale",
    commentary: `Cimone — whose name means "beast" — is a brutish nobleman's son whose father had given up on educating him. Sight of the sleeping Efigenia transforms him: he learns letters, manners, and arms, wins her by force after shipwrecks and captures, and ends a civilized prince. The tale is Boccaccio's most Ovidian: love as the humanizing force that reason could not supply. Read it as a pagan gloss on the medieval education-of-princes tradition.`,
    crossReferences: [], tags: ["literary-influence", "philosophical"] },

  { id: "decameron-v-2-gostanza", bookId: "the-decameron", chapterNumber: 52,
    anchorText: "Gostanza", anchorOccurrence: 1,
    title: "Adrift to Africa",
    quotedPassage: "Gostanza",
    passageReference: "Day V, Tale 2 — Emilia's tale",
    commentary: `Gostanza of Lipari, believing her beloved Martuccio drowned at sea, embarks in an open boat meaning to die. Wind takes her to the Barbary coast, where she finds Martuccio alive and prospering in the king of Tunis's service. The Mediterranean here is neither obstacle nor exotic backdrop but common ground — a zone of continuous movement for ordinary people and their griefs.`,
    crossReferences: [], tags: ["literary-influence", "philosophical"] },

  { id: "decameron-v-3-pietro-agnolella", bookId: "the-decameron", chapterNumber: 53,
    anchorText: "Pietro", anchorOccurrence: 1,
    title: "A Night Among Wolves",
    quotedPassage: "Pietro",
    passageReference: "Day V, Tale 3 — Elisa's tale",
    commentary: `Pietro Boccamazza and Agnolella, eloping from Rome, are separated in the wilderness of the Campagna. Agnolella finds shelter with a hospitable woman; Pietro spends a night in an oak tree while wolves devour his tied horse below. Reunited, they marry. The tale's closeness to folktale — the night in the forest, the threatening beasts — marks the edge of Boccaccio's realism: the Decameron accepts fairy-tale shape when fairy-tale stakes are already in play.`,
    crossReferences: [], tags: ["literary-influence", "philosophical"] },

  { id: "decameron-v-4-nightingale", bookId: "the-decameron", chapterNumber: 54,
    anchorText: "Ricciardo", anchorOccurrence: 1,
    title: "The Nightingale",
    quotedPassage: "Ricciardo",
    passageReference: "Day V, Tale 4 — Filostrato's tale",
    commentary: `Ricciardo Manardi arranges with his beloved Caterina that she will sleep on the balcony "to hear the nightingale." Her father, discovering them in the morning, is too shrewd to be angry: he makes her hold the "nightingale" in her hand until Ricciardo wakes, then unites them on the spot. A rare Decameron moment where a father reacts to his daughter's desire with laughter rather than a blade; Filostrato, on Day V's happier axis, lets it stand unchallenged.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-v-5-guidotto", bookId: "the-decameron", chapterNumber: 55,
    anchorText: "Guidotto", anchorOccurrence: 1,
    title: "The Lost Brother",
    quotedPassage: "Guidotto",
    passageReference: "Day V, Tale 5 — Neifile's tale",
    commentary: `Guidotto da Cremona, dying, commends his adopted daughter to his friend Giacomino. Two suitors quarrel over her; a sword-fight is averted when her true brother, now a man of substance, recognizes a childhood nurse. Recognition scenes are Greek-romance machinery that medieval Italy inherited; Boccaccio deploys them matter-of-factly without the period's typical melodrama.`,
    crossReferences: [], tags: ["literary-influence", "philosophical"] },

  { id: "decameron-v-6-gianni-procida", bookId: "the-decameron", chapterNumber: 56,
    anchorText: "Gianni", anchorOccurrence: 1,
    title: "The Stake at Palermo",
    quotedPassage: "Gianni",
    passageReference: "Day V, Tale 6 — Pampinea's tale",
    commentary: `Gianni of Procida, caught in bed with Restituta at King Frederick of Sicily's court, is condemned to burn alongside her. A minister, Ruggieri de' Loria, intervenes; the king spares them and marries them nobly. The historical Ruggieri was a real admiral of the Sicilian Vespers era; Boccaccio is wiring his tale into the political history of late-medieval Sicily.`,
    crossReferences: [], tags: ["literary-influence", "philosophical", "historical"] },

  { id: "decameron-v-7-teodoro", bookId: "the-decameron", chapterNumber: 57,
    anchorText: "Teodoro", anchorOccurrence: 1,
    title: "The Slave Revealed",
    quotedPassage: "Teodoro",
    passageReference: "Day V, Tale 7 — Lauretta's tale",
    commentary: `Teodoro, sold into slavery as a child, serves the Sicilian noble Amerigo and loves his daughter Violante. Condemned to death for their secret affair, he is identified at the scaffold as the lost son of an Armenian lord by a visiting envoy. The tale's recognition scene is pure Byzantine; its tenderness is Lauretta's. The slave-economy premise is reported without editorial alarm — accurate to the period and sharper for that reason.`,
    crossReferences: [], tags: ["literary-influence", "philosophical"] },

  { id: "decameron-v-10-pietro-vinciolo", bookId: "the-decameron", chapterNumber: 60,
    anchorText: "Pietro", anchorOccurrence: 1,
    title: "The Hen-Coop",
    quotedPassage: "Pietro",
    passageReference: "Day V, Tale 10 — Dioneo's tale",
    commentary: `Dioneo closes Day V — the day of loves ending well — with the bawdiest tale of the collection so far. Pietro di Vinciolo's wife has hidden her lover under a hen-coop just as Pietro returns with a young guest whose tastes lie elsewhere than with women. A donkey steps on the lover's fingers, cries of pain ensue, the hen-coop is lifted, and the situation unravels. Dioneo's theme-exemption is used here to balance the day's sentiment with pure farce. The tale is one of the two or three the Victorians most objected to; Payne leaves nothing out.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  // Day VI — remaining (VI.9 Cavalcanti already covered)
  { id: "decameron-vi-1-oretta", bookId: "the-decameron", chapterNumber: 63,
    anchorText: "Oretta", anchorOccurrence: 1,
    title: "Madonna Oretta on the Road",
    quotedPassage: "Oretta",
    passageReference: "Day VI, Tale 1 — Filomena's tale",
    commentary: `A knight, riding with Madonna Oretta, offers to shorten the road with a tale — then tells it so badly (repeating himself, misordering the action, losing his own point) that she dismounts rather than endure more. Her rebuke is a single line: "Sir, your horse trots too hard; please let me go on foot." The tale's placement is Boccaccio's own joke on himself: Day VI opens with a lady critiquing a bad story-teller, and the whole day will be short tales each turning on a perfect reply.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-vi-2-cisti", bookId: "the-decameron", chapterNumber: 64,
    anchorText: "Cisti", anchorOccurrence: 1,
    title: "The Baker and the Bottle",
    quotedPassage: "Cisti",
    passageReference: "Day VI, Tale 2 — Pampinea's tale",
    commentary: `Cisti the baker, whose fine wine passing noblemen have often admired, is asked to send a bottle to Messer Geri Spina by a servant carrying a disproportionately large flask. Cisti returns the flask untouched with a message: "This is no wine for flasks; it is wine for bottles." Geri, understanding, comes himself. The tale models a civic aesthetic — quality at scale is honored by respect for proportion — that defined the Florentine merchant-republic's image of itself.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-vi-3-nonna", bookId: "the-decameron", chapterNumber: 65,
    anchorText: "Nonna", anchorOccurrence: 1,
    title: "Silencing the Bishop",
    quotedPassage: "Nonna",
    passageReference: "Day VI, Tale 3 — Lauretta's tale",
    commentary: `Monna Nonna de' Pulci, publicly insulted by the Bishop of Florence in company, answers with a reply that folds her supposed shame back on him; he has no further words. The tale is four paragraphs long. Boccaccio's Day VI gives women — including the unmarried Nonna — the same civic space for verbal sovereignty that Day VI's men claim.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-vi-4-chichibio", bookId: "the-decameron", chapterNumber: 66,
    anchorText: "Chichibio", anchorOccurrence: 1,
    title: "The One-Legged Crane",
    quotedPassage: "Chichibio",
    passageReference: "Day VI, Tale 4 — Neifile's tale",
    commentary: `Chichibio the cook, having given one leg of a cooked crane to his sweetheart, tells his master that all cranes have only one leg. Taken out at dawn to see a crane standing, Chichibio claps and the crane drops its second leg; he says his master should have clapped at dinner. The master laughs rather than beat him. The tale is the Decameron's cleanest model of the quick reply that buys the servant's life — a form Boccaccio prefers over explicit moralism.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-vi-5-giotto", bookId: "the-decameron", chapterNumber: 67,
    anchorText: "Giotto", anchorOccurrence: 1,
    title: "Giotto in the Rain",
    quotedPassage: "Giotto",
    passageReference: "Day VI, Tale 5 — Pamfilo's tale",
    commentary: `The painter Giotto di Bondone and the jurist Forese da Rabatta, caught in a rainstorm on the road back to Florence, shelter in a farmhouse, emerge drenched and comical, and trade ironies on their mutual homeliness. Giotto's presence as a character is itself the point: the Florentine intellectual community treats him as an intimate, a generation after his death. Boccaccio is cataloguing the Florence he inherited.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-vi-6-baronci", bookId: "the-decameron", chapterNumber: 68,
    anchorText: "Baronci", anchorOccurrence: 1,
    title: "The Ugliest Family in Florence",
    quotedPassage: "Baronci",
    passageReference: "Day VI, Tale 6 — Fiammetta's tale",
    commentary: `Michele Scalza, pressed by his friends to name the noblest family in Florence, argues for the spectacularly ugly Baronci — on the ground that the angels who made them were evidently practicing at the time and had not yet mastered the art of faces. The joke — nobility proved by undisguisable human rough-edge — is Boccaccio at his most affectionate toward the city. The Baronci were a real Florentine clan; the reader circling them at dinner would have known them on sight.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-vi-7-filippa", bookId: "the-decameron", chapterNumber: 69,
    anchorText: "Filippa", anchorOccurrence: 1,
    title: "Madonna Filippa Reforms the Law",
    quotedPassage: "Filippa",
    passageReference: "Day VI, Tale 7 — Filostrato's tale",
    commentary: `Madonna Filippa of Prato, charged under an ordinance that punished adultery with burning, defends herself before the podestà with a single question: has her husband ever been denied what he sought? When he admits he has not, she asks what ought she do with the surplus — throw it to the dogs? The tale ends with the statute reformed. This is Boccaccio's most explicitly feminist tale; the legal and rhetorical victory belongs to her alone.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-vi-8-cesca", bookId: "the-decameron", chapterNumber: 70,
    anchorText: "Cesca", anchorOccurrence: 1,
    title: "The Mirror",
    quotedPassage: "Cesca",
    passageReference: "Day VI, Tale 8 — Emilia's tale",
    commentary: `Cesca, Fresco's niece, finds everyone she passes in town vulgar. Fresco answers: then daughter, since you find all vulgar men unpleasant, never look in a mirror. Two sentences and the tale is over. It is the Decameron's most compact tale and a good gauge of what Boccaccio's reader was expected to do — absorb fast.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-vi-10-cipolla", bookId: "the-decameron", chapterNumber: 72,
    anchorText: "Cipolla", anchorOccurrence: 1,
    title: "The Feather That Became Coals",
    quotedPassage: "Cipolla",
    passageReference: "Day VI, Tale 10 — Dioneo's tale",
    commentary: `Frate Cipolla ("Brother Onion") promises to show his rustic congregation the feather of the angel Gabriel. When two village pranksters steal the feather and substitute coals, he improvises on the pulpit a parallel story in which the coals are the very coals that roasted Saint Lawrence, and sells them (by donation) more successfully than the original relic. A brilliant set-piece on rhetoric's independence of truth — and, at 3,400 words, the longest tale of Day VI's short day. Dioneo's privilege again used for formal contrast: a day of quick ripostes closed by a day-length sermon.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  // Day VII — remaining (VII.2 Peronella already covered)
  { id: "decameron-vii-1-werewolf", bookId: "the-decameron", chapterNumber: 75,
    anchorText: "Gianni Lotteringhi", anchorOccurrence: 1,
    title: "The Werewolf at the Door",
    quotedPassage: "Gianni Lotteringhi",
    passageReference: "Day VII, Tale 1 — Emilia's tale",
    commentary: `Emilia opens King Dioneo's day of wives' tricks with the most domestic of supernaturals: Gianni Lotteringhi's wife, her lover at the door, persuades her dutifully pious husband that the knocking is a werewolf and that a whispered prayer will drive it off. The lover hears the prayer, translates it back through the keyhole, and retreats for the night. A small tale, tender rather than sharp; Emilia's register.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-vii-3-friar-rinaldo", bookId: "the-decameron", chapterNumber: 77,
    anchorText: "Rinaldo", anchorOccurrence: 1,
    title: "A Piece of Inspired Theology",
    quotedPassage: "Rinaldo",
    passageReference: "Day VII, Tale 3 — Elisa's tale",
    commentary: `Friar Rinaldo, surprised by his gossip's husband in bed with the woman, explains his presence as an exorcism — the child of the house has worms, he says, and the prayer must be performed over the mother. The husband, reassured, thanks him. The satiric target is the rhetorical flexibility of learned piety when rhetoric alone is all that stands between the friar and disaster.`,
    crossReferences: [], tags: ["historical"] },

  { id: "decameron-vii-4-tofano", bookId: "the-decameron", chapterNumber: 78,
    anchorText: "Tofano", anchorOccurrence: 1,
    title: "The Well at Midnight",
    quotedPassage: "Tofano",
    passageReference: "Day VII, Tale 4 — Lauretta's tale",
    commentary: `Tofano, a jealous husband, locks his wife out at night when she returns late. She pretends to drown herself in the well by dropping a stone; he rushes down to save her; she locks him out in turn and calls the neighbors. The set-piece — inversion of door-locking between spouses as a choreography of revenge — is Molière avant la lettre. French comedy will lift this device whole.`,
    crossReferences: [
      { type: "allusion", description: "The door-lock inversion here descends through the commedia dell'arte into Molière's *Georges Dandin* and *L'École des femmes*; the specific stone-in-the-well ruse remains a stage commonplace through the seventeenth century.",
        workTitle: "Georges Dandin", workAuthor: "Molière",
        passageReference: "Act III", targetBookId: null, targetChapterNumber: null, targetAnchorText: null },
    ],
    tags: ["literary-influence", "historical"] },

  { id: "decameron-vii-5-jealous-confessor", bookId: "the-decameron", chapterNumber: 79,
    anchorText: "jealous", anchorOccurrence: 1,
    title: "The Husband as Confessor",
    quotedPassage: "jealous",
    passageReference: "Day VII, Tale 5 — Fiammetta's tale",
    commentary: `A jealous husband, disguising himself as a priest to hear his wife's confession, hears the sins she has crafted expressly for his ears: she is in love, she confesses, with a priest who comes to her every night. The priest is, of course, him. She has told him the truth the whole time; he heard it as betrayal. The tale is an essay on how jealousy manufactures its own evidence.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-vii-6-isabella", bookId: "the-decameron", chapterNumber: 80,
    anchorText: "Isabella", anchorOccurrence: 1,
    title: "Three Men, One Wife",
    quotedPassage: "Isabella",
    passageReference: "Day VII, Tale 6 — Pampinea's tale",
    commentary: `Madonna Isabella, with one lover already in her house, greets a second at the door just as her husband arrives home. She invents on the spot a story that casts the second lover as a man fleeing his pursuer (the first) — the husband, chivalrous, shields him; both lovers depart unscathed. Pampinea's eye for female ingenuity; she hands the king's day a model of composure under triple-pressure.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-vii-7-lodovico", bookId: "the-decameron", chapterNumber: 81,
    anchorText: "Lodovico", anchorOccurrence: 1,
    title: "The Garden Beating",
    quotedPassage: "Lodovico",
    passageReference: "Day VII, Tale 7 — Filomena's tale",
    commentary: `Lodovico and Beatrice conspire to test her husband Egano's jealousy by mistaken-identity choreography in a garden: Lodovico, disguised as Egano, beats Egano (disguised as Beatrice) for having "come to the garden to test him." The husband is simultaneously reassured of Beatrice's virtue and unable to catch her with Lodovico, who follows Egano's beating with Beatrice elsewhere. Pure Plautine mechanics, in Filomena's hand.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-vii-8-arriguccio", bookId: "the-decameron", chapterNumber: 82,
    anchorText: "Arriguccio", anchorOccurrence: 1,
    title: "The String on the Toe",
    quotedPassage: "Arriguccio",
    passageReference: "Day VII, Tale 8 — Neifile's tale",
    commentary: `Arriguccio, suspecting his wife, ties a string from her toe to his hand to know when she rises to meet her lover. She substitutes a servant, and when Arriguccio in a rage beats the wrong woman, her brothers arrive and thrash him for slandering their sister. The detail of the toe-string — mechanically specific, slightly ridiculous — is Boccaccio's gift for the telling procedural image.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-vii-9-lidia-pear-tree", bookId: "the-decameron", chapterNumber: 83,
    anchorText: "Lidia", anchorOccurrence: 1,
    title: "The Pear-Tree",
    quotedPassage: "Lidia",
    passageReference: "Day VII, Tale 9 — Pamfilo's tale",
    commentary: `Lidia, to convince her lover that she loves him without limit, performs with him in her garden what her aged husband can see from the window — and convinces the husband that the pear-tree above is bewitching his sight. Chaucer rewrites this as the Merchant's Tale (January, May, and Damian); the pear-tree becomes one of European literature's most famous comic props. Boccaccio's version places the woman, not the lover, as the architect of the deception.`,
    crossReferences: [
      { type: "allusion", description: "Chaucer's Merchant's Tale (Canterbury Tales, Fragment IV) adapts the pear-tree deception directly; Januarie, May, and Damian are Chaucer's equivalents of the aged husband, the wife, and her lover. The set-piece becomes one of the most reprinted in medieval literature.",
        workTitle: "The Canterbury Tales", workAuthor: "Geoffrey Chaucer",
        passageReference: "The Merchant's Tale", targetBookId: "the-canterbury-tales", targetChapterNumber: null, targetAnchorText: null },
    ],
    tags: ["historical", "literary-influence"] },

  { id: "decameron-vii-10-tingoccio", bookId: "the-decameron", chapterNumber: 84,
    anchorText: "Tingoccio", anchorOccurrence: 1,
    title: "News from the Afterlife",
    quotedPassage: "Tingoccio",
    passageReference: "Day VII, Tale 10 — Dioneo's tale",
    commentary: `Dioneo closes Day VII (his own day as king) with a piece of theological mischief: two compari — close friends bound by godparenthood — pledge that whichever dies first will return to tell the other how it goes on the other side. Tingoccio dies; returns; reports that lying with a godmother, a specifically-prohibited sin, is not counted as any sin there. His friend, receiving the news with interest, proceeds. The tale needles the machinery of medieval moral classification while treating the afterlife's existence as matter-of-fact.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  // Day VIII — remaining
  { id: "decameron-viii-1-gulfardo", bookId: "the-decameron", chapterNumber: 87,
    anchorText: "Gulfardo", anchorOccurrence: 1,
    title: "The Money That Paid Itself",
    quotedPassage: "Gulfardo",
    passageReference: "Day VIII, Tale 1 — Neifile's tale",
    commentary: `Gulfardo, a German mercenary in Milan, borrows 200 gold florins from a merchant; gives them to the merchant's wife in exchange for her favors; then tells the merchant he has repaid her. She cannot deny receipt without revealing her own transaction. Boccaccio's merchant-class morality works here by pure arithmetic: the wife has been made the cash register of her own adultery.`,
    crossReferences: [], tags: ["historical"] },

  { id: "decameron-viii-2-belcolore", bookId: "the-decameron", chapterNumber: 88,
    anchorText: "Belcolore", anchorOccurrence: 1,
    title: "The Cloak in Pledge",
    quotedPassage: "Belcolore",
    passageReference: "Day VIII, Tale 2 — Pamfilo's tale",
    commentary: `The priest of Varlungo, courting Monna Belcolore, leaves his cloak in pledge for a payment she demands. Later he sends a boy to recover it under a transparent pretext. Belcolore sees through it, refuses to return the cloak, and the quarrel over pledge and pawn is sharper than the courtship was. A rural satire on clerical petty-money-lending; the cloak becomes a tiny monument to what the parish owes — or doesn't — its priest.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-viii-3-heliotrope", bookId: "the-decameron", chapterNumber: 89,
    anchorText: "Calandrino", anchorOccurrence: 1,
    title: "The Invisibility Stone",
    quotedPassage: "Calandrino",
    passageReference: "Day VIII, Tale 3 — Elisa's tale",
    commentary: `The first of the four Calandrino tales. Bruno and Buffalmacco persuade the credulous painter Calandrino that the heliotrope — a stone that renders its bearer invisible — can be found in a specific field by the river Mugnone. Calandrino gathers stones all afternoon, convinced he is already invisible when his friends pretend not to see him. His wife's fury on his return compounds the humiliation. Calandrino is the Decameron's great comic victim — a man whose combination of greed, credulity, and self-importance the brigata returns to four times (VIII.3, VIII.6, IX.3, IX.5).`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-viii-4-fiesole", bookId: "the-decameron", chapterNumber: 90,
    anchorText: "Fiesole", anchorOccurrence: 1,
    title: "The Provost Tricked",
    quotedPassage: "Fiesole",
    passageReference: "Day VIII, Tale 4 — Emilia's tale",
    commentary: `The Provost of Fiesole, pursuing a widow, is lured to her house at night and unknowingly sleeps with her aged, ill-favored maidservant. At dawn the widow's brothers bring the Bishop to witness the scene, and the Provost is publicly shamed. Emilia's sharpest anticlerical tale: a senior clergyman humiliated at his own cathedral level by a widow he tried to coerce.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-viii-5-judge-breeches", bookId: "the-decameron", chapterNumber: 91,
    anchorText: "judge", anchorOccurrence: 1,
    title: "The Judge in Court",
    quotedPassage: "judge",
    passageReference: "Day VIII, Tale 5 — Filostrato's tale",
    commentary: `Three young Florentines at the court of the Marches of Ancona, displeased with the cheap foreign judge presiding, pull down his breeches while he hears a case. The court erupts; the judge complains; no one punishes the boys. A piece of communal satire on mercenary judges sent to Italian cities from outside their own jurisdictions — the institution of the foreign *podestà* exploited for xenophobic humor, which Boccaccio neither endorses nor condemns but reports as the way cities entertained themselves.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-viii-6-pig", bookId: "the-decameron", chapterNumber: 92,
    anchorText: "Calandrino", anchorOccurrence: 1,
    title: "The Stolen Pig",
    quotedPassage: "Calandrino",
    passageReference: "Day VIII, Tale 6 — Filomena's tale",
    commentary: `Bruno and Buffalmacco steal Calandrino's pig, then propose a test: each guest at the inn must eat a ginger-and-wine pastille, and the thief's pastille will taste bitter. They have doctored Calandrino's. He protests; they beat him with his own logic. The tale is the Decameron's most effective demonstration that cruelty can be dressed as fairness — and that crowds accept the dressing.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-viii-7-scholar-revenge", bookId: "the-decameron", chapterNumber: 93,
    anchorText: "scholar", anchorOccurrence: 1,
    title: "The Scholar's Revenge",
    quotedPassage: "scholar",
    passageReference: "Day VIII, Tale 7 — Pampinea's tale",
    commentary: `The longest tale of Day VIII and one of the most disturbing. A scholar, made to wait a freezing night in a courtyard by the widow he had courted, takes his revenge by luring her, naked, onto a tower in summer where she is sunburned to the point of near-death. The cruelty is extended, elaborate, and narrated without flinching. Scholars have argued for decades whether Boccaccio is endorsing the revenge or indicting it; he leaves the reader unaided. Pampinea, who told Day I.10's gentlest tale, here tells the cycle's coldest. The brigata's range is on display.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-viii-8-sienese", bookId: "the-decameron", chapterNumber: 94,
    anchorText: "Siena", anchorOccurrence: 1,
    title: "Two Friends, One Bed",
    quotedPassage: "Siena",
    passageReference: "Day VIII, Tale 8 — Fiammetta's tale",
    commentary: `Two Sienese friends discover they have each lain with the other's wife; rather than destroy the friendship, they settle on a shared marriage-bed arrangement whose unbroken friendship is the tale's concluding detail. Boccaccio's most genuinely pagan piece of social machinery. The tale was popular in the Renaissance; Painter's *Palace of Pleasure* reprinted it for English readers.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  { id: "decameron-viii-9-master-simone", bookId: "the-decameron", chapterNumber: 95,
    anchorText: "Simone", anchorOccurrence: 1,
    title: "The Physician in the Sewer",
    quotedPassage: "Simone",
    passageReference: "Day VIII, Tale 9 — Lauretta's tale",
    commentary: `Master Simone, a physician of middling talent and consuming vanity, is persuaded by Bruno and Buffalmacco that he is being initiated into a nocturnal brotherhood of esoteric pleasures. They drop him into a sewer. The Calandrino cycle's third entry, with Bruno and Buffalmacco transferring their mockery from the painter to his social better — and proving the physician's vanity as gullible as Calandrino's greed.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-viii-10-salabaetto", bookId: "the-decameron", chapterNumber: 96,
    anchorText: "Salabaetto", anchorOccurrence: 1,
    title: "The Merchant Outfoxed",
    quotedPassage: "Salabaetto",
    passageReference: "Day VIII, Tale 10 — Dioneo's tale",
    commentary: `Dioneo closes Day VIII with a cycle of reversals. Salabaetto, a young Florentine merchant in Palermo, is fleeced by the courtesan Madam Iancofiore. Months later, he returns in disguise with crates supposed to contain valuable cloth but full of rocks, borrows her money on the credit of the fake goods, and vanishes. The tale inverts Day VIII's pattern — the tricked becomes the tricker — and ends the day on a note of commercial vengeance specifically Mediterranean in its geography.`,
    crossReferences: [], tags: ["historical", "literary-influence", "philosophical"] },

  // Day IX — remaining (IX.2 Abbess already covered)
  { id: "decameron-ix-1-francesca", bookId: "the-decameron", chapterNumber: 99,
    anchorText: "Francesca", anchorOccurrence: 1,
    title: "Two Suitors Dispatched",
    quotedPassage: "Francesca",
    passageReference: "Day IX, Tale 1 — Filomena's tale",
    commentary: `Madonna Francesca, tired of two suitors she cannot otherwise refuse, sends the first to lie as a corpse in a tomb and the second to enter the tomb and carry the corpse out. Both, discovering the setup, quit her in disgust. Boccaccio's mechanism is exact: she has made the suitors do the work of refusing each other.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-ix-3-calandrino-pregnant", bookId: "the-decameron", chapterNumber: 101,
    anchorText: "Calandrino", anchorOccurrence: 1,
    title: "Calandrino Pregnant",
    quotedPassage: "Calandrino",
    passageReference: "Day IX, Tale 3 — Filostrato's tale",
    commentary: `The last of the four Calandrino tales. Bruno, Buffalmacco, and Master Simone persuade Calandrino that he is pregnant — the result of lying uppermost in the marital bed. He pays Master Simone a small fortune for the "cure" (a hot drink and his wife's subsequent insistence that she will no longer permit the dangerous position). Of all the Calandrino tales, this is the cruelest and the most misogynist, the joke depending on treating Calandrino's wife's complaint as the source of his folly. Boccaccio does not flinch from the register he has chosen.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-ix-4-angiulieri", bookId: "the-decameron", chapterNumber: 102,
    anchorText: "Angiulieri", anchorOccurrence: 1,
    title: "Cecco and Cecco",
    quotedPassage: "Angiulieri",
    passageReference: "Day IX, Tale 4 — Neifile's tale",
    commentary: `Cecco Fortarrigo gambles away the horse and clothes of his traveling companion Cecco Angiulieri, then turns around and accuses Angiulieri of the theft. The Sienese onlookers believe the louder man. The tale's darkest humor is that the historical Cecco Angiulieri was himself a real Sienese poet — a friend of Dante's in his youth — and Boccaccio is needling a specific literary figure by casting him as the dupe.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-ix-5-niccolosa", bookId: "the-decameron", chapterNumber: 103,
    anchorText: "Niccolosa", anchorOccurrence: 1,
    title: "Calandrino in Love",
    quotedPassage: "Niccolosa",
    passageReference: "Day IX, Tale 5 — Fiammetta's tale",
    commentary: `Bruno arranges for Calandrino to receive a "magical" love-charm (a scroll with nonsensical letters) that will make Niccolosa love him. She plays along, Calandrino believes the magic is working, his wife arrives, chaos ensues. The cycle's setup-and-beating formula again. Fiammetta tells it, perhaps because no tale in the sequence has yet been told by her; the pattern of tellers rotating across Calandrino's humiliations spreads the complicity across the brigata.`,
    crossReferences: [], tags: ["literary-influence", "historical"] },

  { id: "decameron-ix-6-inn-cradle", bookId: "the-decameron", chapterNumber: 104,
    anchorText: "inn", anchorOccurrence: 1,
    title: "The Cradle at the Inn",
    quotedPassage: "inn",
    passageReference: "Day IX, Tale 6 — Pamfilo's tale",
    commentary: `Two young men lodge at a tight rural inn with a host, his wife, a daughter, and a cradle. One suitor slips into the daughter's bed; the other moves the cradle to the wife's bedpost as a landmark; the wife, returning in the dark, mistakes the moved cradle and slides into the wrong bed. Chaos, mistaken identity, eventual reconciliation. Chaucer takes the plot whole for the Reeve's Tale — right down to the cradle — and Northern European students of the fabliau trace their whole genre back to this tale's comic engineering.`,
    crossReferences: [
      { type: "allusion", description: "Chaucer's Reeve's Tale adapts this tale directly; the cradle-displacement and the subsequent bed-confusions are preserved intact.",
        workTitle: "The Canterbury Tales", workAuthor: "Geoffrey Chaucer",
        passageReference: "The Reeve's Tale", targetBookId: "the-canterbury-tales", targetChapterNumber: null, targetAnchorText: null },
    ],
    tags: ["literary-influence", "historical"] },

  { id: "decameron-ix-7-talano", bookId: "the-decameron", chapterNumber: 105,
    anchorText: "Talano", anchorOccurrence: 1,
    title: "The Dream of the Wolf",
    quotedPassage: "Talano",
    passageReference: "Day IX, Tale 7 — Pampinea's tale",
    commentary: `Talano of Molese dreams his wife will be torn by a wolf; she scorns the warning and walks in the wood, where a wolf does disfigure her face. The tale belongs to Day IX's free-subject day; its darkness — the prophetic dream unheeded, the mutilation permanent — is unusual for a nominally loose day. Pampinea tells it without commentary.`,
    crossReferences: [], tags: ["philosophical"] },

  { id: "decameron-ix-8-biondello-ciacco", bookId: "the-decameron", chapterNumber: 106,
    anchorText: "Biondello", anchorOccurrence: 1,
    title: "The Glutton's Revenge",
    quotedPassage: "Biondello",
    passageReference: "Day IX, Tale 8 — Lauretta's tale",
    commentary: `Biondello tricks the celebrated Florentine glutton Ciacco into making an unprofitable journey. Ciacco, rather than take it lightly, arranges for a servant to deliver Biondello a beating of the most thorough kind at an unsuspecting taverner's hands. Ciacco is a real figure — he appears in Dante's *Inferno* VI as a damned glutton — and Boccaccio is again retrieving a Dante character into the Decameron's own Florence.`,
    crossReferences: [
      { type: "compare", description: "Ciacco appears in Dante's Inferno VI among the gluttons; Boccaccio's inclusion of him as a living Florentine (before Dante placed him below) is another Decameron retrieval from the Commedia.",
        workTitle: "The Divine Comedy", workAuthor: "Dante Alighieri",
        passageReference: "Inferno VI", targetBookId: "the-divine-comedy", targetChapterNumber: 5, targetAnchorText: null },
    ],
    tags: ["literary-influence", "historical"] },

  { id: "decameron-ix-9-solomon", bookId: "the-decameron", chapterNumber: 107,
    anchorText: "Solomon", anchorOccurrence: 1,
    title: "Counsel at Goose Bridge",
    quotedPassage: "Solomon",
    passageReference: "Day IX, Tale 9 — Emilia's tale",
    commentary: `Two men — one whose wife will not obey him, one who cannot love — ask King Solomon's counsel. Solomon tells the first "go to Goose Bridge" and the second "love." Both puzzle at the answers. At Goose Bridge the first sees a muleteer beat a stubborn mule; the second, by time, finds that love returns. The tale is a medieval wisdom-tale set-piece, pragmatic and not particularly sentimental; Emilia tells it on her own day (IX) as king.`,
    crossReferences: [], tags: ["literary-influence"] },

  { id: "decameron-ix-10-mare", bookId: "the-decameron", chapterNumber: 108,
    anchorText: "mare", anchorOccurrence: 1,
    title: "The Mare That Didn't Transform",
    quotedPassage: "mare",
    passageReference: "Day IX, Tale 10 — Dioneo's tale",
    commentary: `Dioneo closes Day IX with the bawdiest of the priest-and-peasant tales. Fra Rinaldo convinces a peasant that he can transform the peasant's wife into a mare during the day (to plow) and return her to human form at night. The ritual requires a specific gesture at the final step; the peasant, seeing it performed, cries "no tail!" and breaks the spell. Dioneo's theme-exemption again deployed for maximum transgression; the tale is nearly always the one anthologists dropped.`,
    crossReferences: [], tags: ["historical", "literary-influence"] },

  // Day X — remaining (X.10 Griselda already covered)
  { id: "decameron-x-1-ruggieri", bookId: "the-decameron", chapterNumber: 111,
    anchorText: "Ruggieri", anchorOccurrence: 1,
    title: "The King of Spain's Neglect",
    quotedPassage: "Ruggieri",
    passageReference: "Day X, Tale 1 — Neifile's tale",
    commentary: `Ruggieri de' Figiovanni, having served King Alfonso of Castile loyally, misreads the king's apparent failure to reward him as personal disfavor. The king, on his departure, shows him a pair of mules — one laden with treasure, one with stones — and reveals that Ruggieri had drawn the stone-mule by lot. Fortune, not the king's judgment, had denied him advancement. Day X opens on the theme of magnificence by redefining who is generous when success is withheld.`,
    crossReferences: [], tags: ["philosophical"] },

  { id: "decameron-x-2-ghino", bookId: "the-decameron", chapterNumber: 112,
    anchorText: "Ghino", anchorOccurrence: 1,
    title: "The Brigand Who Cured the Abbot",
    quotedPassage: "Ghino",
    passageReference: "Day X, Tale 2 — Elisa's tale",
    commentary: `Ghino di Tacco — a real fourteenth-century Sienese brigand, also mentioned in Dante's *Purgatorio* VI — captures the Abbot of Cluny, who suffers from a stomach complaint. Ghino cures him by imposed plain fare and a tower's seclusion, and the Abbot, grateful, reconciles him with the Pope. Elisa places a historical bandit in the magnificent-deed slot without irony; Boccaccio's point is that nobility of gesture is not a function of social standing.`,
    crossReferences: [
      { type: "compare", description: "Ghino di Tacco appears in Dante's Purgatorio VI among the late-repentant; Boccaccio's affectionate tale retrieves him as an agent of unexpected civic kindness.",
        workTitle: "The Divine Comedy", workAuthor: "Dante Alighieri",
        passageReference: "Purgatorio VI", targetBookId: "the-divine-comedy", targetChapterNumber: 39, targetAnchorText: null },
    ],
    tags: ["philosophical", "historical"] },

  { id: "decameron-x-3-nathan", bookId: "the-decameron", chapterNumber: 113,
    anchorText: "Nathan", anchorOccurrence: 1,
    title: "The Generosity That Disarmed",
    quotedPassage: "Nathan",
    passageReference: "Day X, Tale 3 — Filostrato's tale",
    commentary: `The wealthy Nathan, learning that the envious Mithridanes is riding to murder him for the reputation of his generosity, rides out to meet him unrecognized and offers himself. Mithridanes, finding that what he envied cannot be taken away by violence, converts. The tale is the Decameron's cleanest piece of moral philosophy: a virtue that can be destroyed by attack is not a virtue; a virtue that disarms its attacker is.`,
    crossReferences: [], tags: ["philosophical"] },

  { id: "decameron-x-4-gentile", bookId: "the-decameron", chapterNumber: 114,
    anchorText: "Gentile", anchorOccurrence: 1,
    title: "The Returned Bride",
    quotedPassage: "Gentile",
    passageReference: "Day X, Tale 4 — Lauretta's tale",
    commentary: `Messer Gentile de' Carisendi, finding his beloved entombed apparently dead, takes her home and revives her by warmth. He keeps her in secret during her recovery, then arranges a public dinner at which he returns her, alive and his no longer, to her husband. The tale is Day X's demonstration that magnificence includes renunciation — that the greatest gift is often the one deliberately not kept.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-x-5-dianora", bookId: "the-decameron", chapterNumber: 115,
    anchorText: "Dianora", anchorOccurrence: 1,
    title: "The January Garden",
    quotedPassage: "Dianora",
    passageReference: "Day X, Tale 5 — Emilia's tale",
    commentary: `Madonna Dianora, to put off an unwanted suitor, demands an impossible gift: a flowering garden in January. The knight hires a magician who produces one; Dianora, honor-bound, prepares to give herself; the knight, moved by her distress, releases her without claim. The husband, learning, thanks the knight. The magician then releases the knight from the hire-fee — and so the cascading gift that defines magnificent liberality completes. Chaucer adapts the tale as the Franklin's Tale, preserving its machinery.`,
    crossReferences: [
      { type: "allusion", description: "Chaucer's Franklin's Tale adapts this tale directly; the question of 'who was the most generous' becomes Chaucer's explicit rhetorical frame.",
        workTitle: "The Canterbury Tales", workAuthor: "Geoffrey Chaucer",
        passageReference: "The Franklin's Tale", targetBookId: "the-canterbury-tales", targetChapterNumber: null, targetAnchorText: null },
    ],
    tags: ["philosophical", "literary-influence"] },

  { id: "decameron-x-6-charles", bookId: "the-decameron", chapterNumber: 116,
    anchorText: "Charles", anchorOccurrence: 1,
    title: "The King Reproved",
    quotedPassage: "Charles",
    passageReference: "Day X, Tale 6 — Fiammetta's tale",
    commentary: `King Charles of Anjou, enamoured of two young daughters of a country nobleman, is reproved by an old counselor who reminds him that his own honor depends on his self-mastery. Charles marries both girls nobly with rich dowries. Fiammetta's tale aligns Day X's magnificence with the check on sovereign desire — the king's greatness is in yielding to his own virtue, not in claiming what power allows.`,
    crossReferences: [], tags: ["philosophical"] },

  { id: "decameron-x-7-king-pietro", bookId: "the-decameron", chapterNumber: 117,
    anchorText: "Pietro", anchorOccurrence: 1,
    title: "The King Who Visited Lisa",
    quotedPassage: "Pietro",
    passageReference: "Day X, Tale 7 — Pampinea's tale",
    commentary: `King Pietro of Aragon, told that the apothecary's daughter Lisa is wasting away for unrequited love of him, visits her, kisses her brow, names her his ceremonial champion, and marries her to a young baron with a rich dowry. The tale is the Decameron's sweetest portrait of royal grace: a king who will not consummate Lisa's love but does not mock it — and whose magnanimity transforms her unrequited desire into a respected public identity.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-x-8-titus-gisippus", bookId: "the-decameron", chapterNumber: 118,
    anchorText: "Titus", anchorOccurrence: 1,
    title: "Friend Gives Friend a Bride",
    quotedPassage: "Titus",
    passageReference: "Day X, Tale 8 — Filomena's tale",
    commentary: `Two friends, Titus (Roman) and Gisippus (Athenian), exchange everything including the bride Gisippus was about to marry; years later, Gisippus falls into destitution in Rome and is on the point of being executed for a murder he did not commit. Titus recognizes him and confesses to the murder in his stead. The Roman court, unable to decide which man to believe, acquits both. The tale is medieval Europe's standard argument for friendship as equal to — or above — family love; it descends from Cicero *De Amicitia* and appears in John Lyly's *Euphues* and elsewhere in Elizabethan culture.`,
    crossReferences: [], tags: ["philosophical", "literary-influence"] },

  { id: "decameron-x-9-saladin-torello", bookId: "the-decameron", chapterNumber: 119,
    anchorText: "Torello", anchorOccurrence: 1,
    title: "Saladin and the Magician's Bed",
    quotedPassage: "Torello",
    passageReference: "Day X, Tale 9 — Pamfilo's tale",
    commentary: `Messer Torello of Pavia entertains Saladin — traveling in Christian lands in the disguise of a merchant — with a lavish hospitality that Saladin silently vows to repay. Years later, Torello is captured on crusade; Saladin recognizes him, loads him with honors, and has his magician transport him home on an enchanted bed in a single night, arriving on the eve of his wife's second wedding. Pamfilo, as king, saves the penultimate tale for himself: Boccaccio's most generous picture of the Muslim world, and the Decameron's warmest moment of sustained friendship across the medieval Christian-Islamic divide.`,
    crossReferences: [], tags: ["philosophical", "historical"] },
]
