// ── Orlando Furioso Glosses ──
// One-line glosses for difficult words, proper names, foreign phrases,
// and the dense Carolingian/classical/Italian-Renaissance proper-name
// load of Ariosto's poem. Target per spec Part 5: 30–45 per canto.
//
// This first pass seeds Canto I only (Carolingian orientation + the
// figures who actually speak or act in the opening); Cantos II–XLVI
// will be generated by a Haiku 4.5 pass, per the ingestion spec's
// model allocation and budget.
//
// Glosses are looked up by chapterNumber (1-indexed, matching the canto
// number and the ch-N.json filename — ch-0 is the editor's introduction).
// They render as the shared .tome-gloss CSS class: dotted underline with
// a hover/tap tooltip.

export interface OrlandoFuriosoGloss {
  phrase: string
  definition: string
}

// ── Canto I (ch-1) — Carolingian orientation ────────────────────────
const CANTO_1_GLOSSES: OrlandoFuriosoGloss[] = [
  // The framing battle and its participants
  { phrase: "Agramant",     definition: "Agramante — young king of Africa, leader of the Saracen invasion of France. Historical fiction, not a real Carolingian antagonist; Ariosto inherits him from Boiardo. Killed by Orlando in Canto XLI." },
  { phrase: "Marsilius",    definition: "Marsilius (Marsilio), Saracen king of Spain and Agramante's ally. The Chanson-de-Roland tradition makes him the villain of Roncevaux; Ariosto borrows the name without tethering to the Chanson plot." },
  { phrase: "Troyano",      definition: "Troyano — Agramante's father. In Boiardo, killed by Christian forces; Agramante's invasion is revenge for his father's death." },
  { phrase: "Charlemagne",  definition: "Charles the Great (c. 748–814), king of the Franks and first Holy Roman Emperor. In the Matter of France he is the framing monarch; in Ariosto's Italian-romance tradition he is less a historical figure than the stage on which paladin fantasies are played out." },
  { phrase: "paladin",      definition: "Paladino — one of Charlemagne's twelve sworn companions and peers. Italian romance treats the paladins as the flower of chivalric virtue; the order is more legendary than historical." },
  { phrase: "Namus",        definition: "Duke Namo of Bavaria — Charlemagne's wisest counselor in the Matter-of-France tradition. Here entrusted with Angelica's safekeeping." },

  // The cast of Canto I
  { phrase: "Angelica",     definition: "Daughter of the king of Cathay (Cathay = medieval European China). Pursued through the first half of the poem by Orlando, Rinaldo, Sacripante, Ferraù, and others; eventually loves and marries Medoro in Canto XIX." },
  { phrase: "Orlando",      definition: "Italianized form of Roland — Charlemagne's nephew and most famous paladin. Driven mad by jealousy in Canto XXIII; cured by Astolfo with the recovered wits in Canto XXXIX. The poem's titular hero." },
  { phrase: "Rinaldo",      definition: "Italianized form of Renaud de Montauban — a paladin of the French chanson-de-geste tradition. Orlando's cousin (son of Aymon of Dordogne) and rival for Angelica." },
  { phrase: "Sacripant",    definition: "Sacripante, king of Circassia — Angelica's oldest suitor, who followed her from the East. Unhorsed in Canto I by Bradamante (whom he does not recognize as a woman)." },
  { phrase: "Ferrau",       definition: "Ferraù — Saracen knight, son of Lanfusa. In Canto I he drops his helmet in the stream and is shamed by the ghost of Argalìa (Angelica's brother, whom he had killed)." },
  { phrase: "Bradamant",    definition: "Bradamante — warrior maiden, Rinaldo's sister, betrothed to Ruggiero. The dynastic mother-figure of the poem: her children with Ruggiero are the mythological founders of the Este line." },
  { phrase: "Argalìa",      definition: "Argalìa — Angelica's brother, killed by Ferraù in Boiardo's Innamorato. His ghost rises from the stream in Canto I to shame Ferraù for breaking his oath." },
  { phrase: "Aymon",        definition: "Aymon of Dordogne — Rinaldo's father; a paladin of the older generation. Hence Rinaldo is called 'Aymon's son' throughout." },
  { phrase: "Mount Albano", definition: "Montauban (Mont Albano) — Rinaldo's hereditary seat in Dordogne. A stock locus of the chanson-de-geste tradition; Rinaldo is \"the good master of Albano's hill.\"" },
  { phrase: "Aspramont",    definition: "Aspromonte — the battle in Calabria where the young Orlando killed the Saracen Almonte and took his helmet. Central episode of the Italian romance Aspramonte (c. 1350), which lies in the background of Ariosto's poem." },
  { phrase: "Almontes",     definition: "Almonte — Saracen king, father of Agramante's general Troiano (not Agramante's own father Troyano). Killed at Aspromonte by the young Orlando, whose helmet the Saracens want back." },
  { phrase: "Mambrino",     definition: "Mambrino — a Saracen king of romance tradition whose iron helmet was famously prized. Cervantes later borrows the name for the barber's basin Don Quixote mistakes for a helmet." },

  // Horses and arms
  { phrase: "Bayardo",      definition: "Bayard — Rinaldo's magical horse, carried over from the French tradition. Preternaturally intelligent; recognizes Angelica in Canto I from the days when she fed him at Albracca (in Boiardo's Innamorato)." },
  { phrase: "Durindana",    definition: "Durindana — Italianized form of Durendal, Orlando's sword in the Chanson de Roland tradition. Ferraù's vow to win Orlando's helmet and sword threads through the poem." },
  { phrase: "Frontino",     definition: "Frontino — Ruggiero's warhorse, a cause of quarrel later between Ruggiero and Sacripante. Not yet in play in Canto I; will enter later." },
  { phrase: "morion",       definition: "An open-faced helmet with a crest running fore-to-aft, standard Renaissance infantry headgear; Rose uses it as a general term for helmet." },
  { phrase: "faulchion",    definition: "Falchion — a heavy single-edged sword, curved or with a clip-point; Rose's general term for the knights' swords." },

  // Places and ethnic-geographic terms
  { phrase: "Catày",        definition: "Cathay — the medieval European name for China. Angelica is \"the lady of Catày\"; the East as romance-geography, not historical place." },
  { phrase: "Sericane",     definition: "Sericana — a vague \"far East\" kingdom in the poem, ruled by the Saracen king Gradasso. Borrowed from Boiardo." },
  { phrase: "Albracca",     definition: "Albracca — the Cathayan fortress where Angelica's father Galafron was besieged in Boiardo's Innamorato. Ariosto alludes to Albracca as the reader's assumed backstory." },
  { phrase: "Arden",        definition: "Ardennes — the legendary forest of French/Italian romance (distinct from the historical Belgian/French Ardennes). Contains the Fountains of Love and Disdain in Boiardo; Merlin's tomb is elsewhere." },
  { phrase: "paynim",       definition: "Archaic English for a pagan or non-Christian, used throughout Rose to translate Italian pagano or Saracino. Not a slur in 19c scholarly usage; a neutral term for the Saracen knights." },
  { phrase: "Moor",         definition: "In romance-historical usage, a Muslim inhabitant of North Africa or Iberia. Ariosto uses it of Agramante's invading force; Rose preserves the term." },
  { phrase: "Tartarian",    definition: "Of the Tartars (Mongols) or, more loosely, of Central Asia. Orlando's wars \"in Tartarian land\" are the romance-East adventures inherited from Boiardo." },
  { phrase: "Median",       definition: "Of the Medes — ancient Iranian peoples. Used by Ariosto as a romance-decorative term for \"Persian\" rather than a historical designation." },

  // Religious and classical references
  { phrase: "bonnibel",     definition: "Rose's 19c English for the Italian donzella or bella donna — a beautiful young woman. Archaic even in Rose's day; he reaches for it to preserve the poem's courtly register." },
  { phrase: "Hercules",     definition: "The Greek hero Heracles, from whom the Este family claimed descent through Ercole (Duke Ercole I of Ferrara). \"Good seed of Hercules\" addresses Cardinal Ippolito via his dynastic ancestry." },
  { phrase: "Hippolitus",   definition: "Cardinal Ippolito d'Este (1479–1520) — Ariosto's patron 1503–17 and the poem's dedicatee. A prince of the Church at eighteen; a noted military commander; a famously difficult employer." },
  { phrase: "Rogero",       definition: "Rose's English for Ruggiero — the Saracen-born, Christian-converting dynastic hero of the poem, mythical ancestor of the House of Este. Betrothed to Bradamante; pagan raised by the sorcerer Atlante; baptized in Canto XLI." },
  { phrase: "Cupid's snare", definition: "The classical-romance figure of Cupid as the hunter who nets lovers in his snare. Standard in Petrarchan and Italian-Renaissance amatory verse." },
  { phrase: "palfrey",      definition: "A light riding horse (as distinct from a destrier, the heavy warhorse). Noblewomen rode palfreys; Angelica's palfrey carries her through the opening cantos." },

  // 19c English vocabulary that may trip a modern reader
  { phrase: "hies",         definition: "Archaic verb: hurries, hastens. Rose reaches for archaic diction throughout to preserve the chivalric register." },
  { phrase: "pricked",      definition: "In 19c verse, \"to prick\" is to ride or spur a horse forward — borrowed from Spenser's language (\"A gentle Knight was pricking on the plaine\"). Neutral old-poetry usage, no double entendre intended." },
  { phrase: "sell",         definition: "Archaic: saddle. \"Had sprung into her sell\" = had leapt into her saddle." },
  { phrase: "meed",         definition: "Archaic: reward, recompense. The \"valiant victor's meed\" is the prize promised to whichever knight fights best." },
  { phrase: "wight",        definition: "Archaic: creature, person — especially in poetic or chivalric English. Neutral in Rose's idiom." },
  { phrase: "wold",         definition: "An open upland, a moorland tract; with \"waste\" (\"by waste and wold\"), a stock romance landscape phrase." },
  { phrase: "dingle",       definition: "A small wooded dell or glen. Part of Rose's forest-romance vocabulary." },
  { phrase: "crupper",      definition: "The horse's hindquarters, or by extension the strap or rear part of the saddle. A second rider \"mounted upon the crupper\" rides double, behind the main rider." },
  { phrase: "vauntage",     definition: "Advantage (archaic variant). Rose borrows it from 16–17c English poetry for rhyme and register." },
  { phrase: "guerdon",      definition: "A reward or recompense — cognate with German Widergeben. A stock word of chivalric English poetry, borrowed into French from Old Germanic via Occitan." },
]

// ── Stubs for Cantos II–XLVI (Haiku pass) ──────────────────────────
const EMPTY: OrlandoFuriosoGloss[] = []

export const ORLANDO_FURIOSO_GLOSSES: Record<number, OrlandoFuriosoGloss[]> = {
  1:  CANTO_1_GLOSSES,
  2:  EMPTY, 3:  EMPTY, 4:  EMPTY, 5:  EMPTY, 6:  EMPTY, 7:  EMPTY, 8:  EMPTY,
  9:  EMPTY, 10: EMPTY, 11: EMPTY, 12: EMPTY, 13: EMPTY, 14: EMPTY, 15: EMPTY,
  16: EMPTY, 17: EMPTY, 18: EMPTY, 19: EMPTY, 20: EMPTY, 21: EMPTY, 22: EMPTY,
  23: EMPTY, 24: EMPTY, 25: EMPTY, 26: EMPTY, 27: EMPTY, 28: EMPTY, 29: EMPTY,
  30: EMPTY, 31: EMPTY, 32: EMPTY, 33: EMPTY, 34: EMPTY, 35: EMPTY, 36: EMPTY,
  37: EMPTY, 38: EMPTY, 39: EMPTY, 40: EMPTY, 41: EMPTY, 42: EMPTY, 43: EMPTY,
  44: EMPTY, 45: EMPTY, 46: EMPTY,
}

export function getOrlandoFuriosoGlossesForChapter(
  chapterNumber: number
): OrlandoFuriosoGloss[] {
  return ORLANDO_FURIOSO_GLOSSES[chapterNumber] ?? EMPTY
}
