// ─────────────────────────────────────────────
// The Stoa — Reward Catalog
// ─────────────────────────────────────────────
// Twelve seeded Stoa rewards, one per featured book experience
// (MASTER_EXECUTION_PLAN §11). Mirrors the stoa_paintings model
// (docs/architecture/supabase-data-map.md §2.3): 1:1 painting ↔ book,
// unlock derived from quiz_results.passed for that book. This module is
// the static catalog; per-user restored state for the showcase lives in
// ./state.ts (localStorage, no Supabase writes).
//
// Every passage is a short, real, public-domain excerpt from the book
// itself. All artwork is original Tome art (scripts/stoa/gen-stoa-art.mjs)
// — never historical source material.

import { BOOK_EXPERIENCES } from "@/lib/books/registry"
import type { BookSlug } from "@/lib/books/types"

export const STOA_ART_DIR = "/stoa"

export const STOA_PROVENANCE_LABEL = "Original Tome art"

export const STOA_LICENSE_NOTE =
  "Original Tome art, procedurally generated by scripts/stoa/gen-stoa-art.mjs " +
  "for the Stoa reward gallery. Displayed and shareable within Tome; not a " +
  "public-domain historical source and not licensed for redistribution."

// ── Types ────────────────────────────────────

export interface StoaPassage {
  /** Short verbatim excerpt (public domain). */
  text: string
  /** Where it lives in the book, incl. translation when relevant. */
  citation: string
}

export interface StoaReward {
  /** Stable reward id — matches the book's world slug, 1:1 with the book. */
  id: BookSlug
  bookSlug: BookSlug
  /** Canonical catalog book ID (books.id / stoa_paintings.unlocking_book_id). */
  bookId: string
  title: string
  bookTitle: string
  author: string
  /** What the restored painting depicts (curatorial wall label). */
  description: string
  /** Related public-domain passage from the book. */
  passage: StoaPassage
  /** One line of Virgil commentary, in his voice. */
  virgilLine: string
  provenanceLabel: typeof STOA_PROVENANCE_LABEL
  /** Human-readable provenance/licensing note (rendered in detail view). */
  provenanceNote: string
  /** Copy for the EMPTY niche (locked) state. */
  emptyCopy: { heading: string; body: string }
  /** Copy for the RESTORED (unlocked) state. */
  restoredCopy: { heading: string; body: string }
  /** Painting asset (original Tome art). */
  artSrc: string
  altText: string
  /** Seal medallion earned alongside this reward (registry sealName). */
  sealName: string
}

// ── Per-book curatorial content ──────────────

type StoaSeed = Omit<
  StoaReward,
  "id" | "bookSlug" | "bookId" | "bookTitle" | "author" | "sealName" | "provenanceLabel" | "artSrc" | "altText"
>

const STOA_SEEDS: Record<BookSlug, StoaSeed> = {
  macbeth: {
    title: "The Storm over the Heath",
    description:
      "A gold crown hangs above an upturned dagger while storm-light splits " +
      "the dark — the exact moment prophecy becomes a plan.",
    passage: {
      text:
        "Tomorrow, and tomorrow, and tomorrow,\n" +
        "Creeps in this petty pace from day to day,\n" +
        "To the last syllable of recorded time;",
      citation: "Macbeth, Act V, Scene 5",
    },
    virgilLine:
      "You stood in the storm and named what ambition costs. Hang this where the light can find it.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Macbeth Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The storm has settled into paint. The crown keeps its own counsel now.",
    },
  },

  "moby-dick": {
    title: "The White Silence",
    description:
      "A pale fluke sounds beneath a compass star — the sea keeps the whale, " +
      "and the reader keeps the horizon.",
    passage: {
      text: "It is not down on any map; true places never are.",
      citation: "Moby-Dick, Chapter 12, “Biographical”",
    },
    virgilLine:
      "The whale is still out there — but so are you, and now the map bears your own line.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Moby-Dick Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The sea gave the shape back. The star holds its bearing.",
    },
  },

  alice: {
    title: "The Door Too Small",
    description:
      "A golden key, a curtain-small door, and one red diamond — every rule " +
      "in the garden bends for a reader who asks why.",
    passage: {
      text: "“Who in the world am I?” Ah, that’s the great puzzle!",
      citation: "Alice's Adventures in Wonderland, Chapter 2",
    },
    virgilLine:
      "You asked the questions that bent the rules. Keep this key; doors remember polite knockers.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass an Alice Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The key fits again. The door is exactly your size today.",
    },
  },

  "paradise-lost": {
    title: "The Gate of Choice",
    description:
      "A gate of gold light stands open while a single star falls past — " +
      "the instant before every choice that matters.",
    passage: {
      text:
        "The mind is its own place, and in itself\n" +
        "Can make a Heaven of Hell, a Hell of Heaven.",
      citation: "Paradise Lost, Book I",
    },
    virgilLine:
      "You crossed the gate with your eyes open. That is the only way anyone crosses.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Paradise Lost Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The gate is lit from within. The star has landed softly.",
    },
  },

  "divine-comedy": {
    title: "The Lantern Ascent",
    description:
      "A lantern climbs through turning rings toward one white star — " +
      "the architecture of hope, drawn step by step.",
    passage: {
      text:
        "Midway upon the journey of our life\n" +
        "I found myself within a forest dark,\n" +
        "For the straightforward pathway had been lost.",
      citation: "The Divine Comedy, Inferno I (Longfellow translation, 1867)",
    },
    virgilLine:
      "Step by step you climbed out of the dark wood. The lantern keeps your place.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Divine Comedy Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The rings have turned true. The lantern remembers every step.",
    },
  },

  iliad: {
    title: "Wrath in Bronze",
    description:
      "A shield broken into quarters catches first light on the shoreline — " +
      "glory, counted piece by piece.",
    passage: {
      text:
        "Sing, O goddess, the anger of Achilles son of Peleus, that brought " +
        "countless ills upon the Achaeans.",
      citation: "The Iliad, Book I (Butler translation, 1898)",
    },
    virgilLine:
      "Bronze remembers every blow. You counted the cost of glory — few readers do.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass an Iliad Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The fragments hold together. The bronze is warm again.",
    },
  },

  odyssey: {
    title: "The Long Way Home",
    description:
      "A mast under a turning field of stars, islands rising along a dotted " +
      "gold line — ten years, one bearing.",
    passage: {
      text:
        "Tell me, O Muse, of that ingenious hero who travelled far and wide " +
        "after he had sacked the famous town of Troy.",
      citation: "The Odyssey, Book I (Butler translation, 1900)",
    },
    virgilLine:
      "Ten years, one bearing. You know now why the stars were worth learning.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass an Odyssey Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The stars are out. The line home is lit.",
    },
  },

  frankenstein: {
    title: "The Spark in the Ice",
    description:
      "One cyan spark crosses an alpine ridge under a pale moon — the line " +
      "between making a thing and answering for it.",
    passage: {
      text:
        "It was on a dreary night of November that I beheld the accomplishment " +
        "of my toils.",
      citation: "Frankenstein, Chapter 5",
    },
    virgilLine:
      "You followed the spark to its maker and asked the harder question: who answers for it?",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Frankenstein Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The ridge is quiet. The spark has found its ground.",
    },
  },

  "pride-prejudice": {
    title: "The Letter Unsent",
    description:
      "Two circles overlap like dancers changing partners above one sealed " +
      "letter — every first impression awaiting revision.",
    passage: {
      text:
        "It is a truth universally acknowledged, that a single man in possession " +
        "of a good fortune, must be in want of a wife.",
      citation: "Pride and Prejudice, Chapter 1",
    },
    virgilLine:
      "First impressions are drafts. You revised — which is all Austen ever asked.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Pride and Prejudice Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The ribbon lies flat. The letter, at last, is sent.",
    },
  },

  "jane-eyre": {
    title: "The Ember in the Window",
    description:
      "A four-paned window burns ember-red over a dark moor — a self that " +
      "refuses to be owned, lit from within.",
    passage: {
      text:
        "I am no bird; and no net ensnares me: I am a free human being with " +
        "an independent will.",
      citation: "Jane Eyre, Chapter 23",
    },
    virgilLine:
      "No bird, no net. You read her refusal aloud simply by finishing.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Jane Eyre Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The ember caught. The moor wind cannot reach it.",
    },
  },

  meditations: {
    title: "The Quiet Citadel",
    description:
      "A wax tablet and stylus in first dawn light — the empire within, " +
      "governed one sentence at a time.",
    passage: {
      text:
        "No longer talk at all about the kind of man that a good man ought " +
        "to be, but be such.",
      citation: "Meditations, Book X (George Long translation, 1862)",
    },
    virgilLine:
      "The quietest book on the shelf, and you sat with it. The citadel holds.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Meditations Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The wax is warm. The morning arrived slowly, as promised.",
    },
  },

  republic: {
    title: "The Light Outside the Cave",
    description:
      "A gold sun rises over a geometric city built above the cave's mouth — " +
      "the examined city, drawn to scale.",
    passage: {
      text: "…the true creator is necessity, who is the mother of our invention.",
      citation: "The Republic, Book II (Jowett translation, 1892)",
    },
    virgilLine:
      "You turned from the wall of shadows. Tell the others the light is climbable.",
    provenanceNote: STOA_LICENSE_NOTE,
    emptyCopy: {
      heading: "An empty niche",
      body: "Pass a Republic Trial to restore this painting to the courtyard.",
    },
    restoredCopy: {
      heading: "Restored",
      body: "The sun clears the wall. The city keeps its geometry.",
    },
  },
}

// ── Assembly (seed + registry) ───────────────

function buildReward(slug: BookSlug): StoaReward {
  const book = BOOK_EXPERIENCES[slug]
  const seed = STOA_SEEDS[slug]
  return {
    id: slug,
    bookSlug: slug,
    bookId: book.bookId,
    bookTitle: book.title,
    author: book.author,
    sealName: book.sealName,
    provenanceLabel: STOA_PROVENANCE_LABEL,
    artSrc: `${STOA_ART_DIR}/${slug}.svg`,
    altText: `Original Tome Stoa painting for ${book.title}: ${seed.title}, ` +
      `an arch-and-medallion composition in the book's palette. ${seed.description}`,
    ...seed,
  }
}

/** The twelve Stoa rewards, keyed by world slug (1:1 with books). */
export const STOA_REWARDS: Record<BookSlug, StoaReward> = Object.fromEntries(
  (Object.keys(STOA_SEEDS) as BookSlug[]).map((slug) => [slug, buildReward(slug)]),
) as Record<BookSlug, StoaReward>

// ── Accessors ────────────────────────────────

/** All rewards in registry order. */
export function listStoaRewards(): StoaReward[] {
  return (Object.keys(BOOK_EXPERIENCES) as BookSlug[]).map((slug) => STOA_REWARDS[slug])
}

/** Look up a reward by id (world slug). Returns undefined for unknown ids. */
export function getStoaReward(id: string): StoaReward | undefined {
  return id in STOA_REWARDS ? STOA_REWARDS[id as BookSlug] : undefined
}

/** Type guard for reward ids. */
export function isStoaRewardId(value: string): value is BookSlug {
  return value in STOA_REWARDS
}

export const STOA_REWARD_COUNT = listStoaRewards().length
