export { sharedIconRegistry } from "./registry"

export { default as HomeIcon, meta as homeMeta } from "./HomeIcon"
export { default as DashboardIcon, meta as dashboardMeta } from "./DashboardIcon"
export { default as LibraryIcon, meta as libraryMeta } from "./LibraryIcon"
export { default as BookmarksIcon, meta as bookmarksMeta } from "./BookmarksIcon"
export { default as ShelvesIcon, meta as shelvesMeta } from "./ShelvesIcon"
export { default as AuthorsIcon, meta as authorsMeta } from "./AuthorsIcon"
export { default as ReadingIcon, meta as readingMeta } from "./ReadingIcon"
export { default as TrialsIcon, meta as trialsMeta } from "./TrialsIcon"
export { default as BookClubsIcon, meta as bookClubsMeta } from "./BookClubsIcon"
export { default as ExploreIcon, meta as exploreMeta } from "./ExploreIcon"
export { default as TimelinesIcon, meta as timelinesMeta } from "./TimelinesIcon"
export { default as FriendsIcon, meta as friendsMeta } from "./FriendsIcon"
export { default as CommunityIcon, meta as communityMeta } from "./CommunityIcon"
export { default as SealsIcon, meta as sealsMeta } from "./SealsIcon"
export { default as ShopIcon, meta as shopMeta } from "./ShopIcon"
export { default as ProfileIcon, meta as profileMeta } from "./ProfileIcon"
