import { LUMINOUS_LIGHT_PALETTE_IDS, type CoverPaletteId, type CoverTextureProfile } from "../styles/palettes"

export type HorizonRange = "low" | "middle" | "high" | "variable"
export type NegativeSpaceRegion = "top" | "bottom" | "left" | "right" | "center" | "split"

export interface CompositionVariant {
  id: string
  label: string
  instructions: string
  routeDirection: "left-right" | "right-left" | "center" | "vertical" | "diagonal" | "none"
}

export interface CompositionFamily {
  id: string
  label: string
  suitableGenres: string[]
  suitableThemes: string[]
  unsuitableGenres: string[]
  heroObjectRules: string
  recommendedHorizon: HorizonRange
  negativeSpaceRegion: NegativeSpaceRegion
  foregroundBehavior: string
  middleGroundBehavior: string
  backgroundBehavior: string
  allowedNarrativeVectors: string[]
  figurePlacement: string
  figureCountRange: [number, number]
  titleSafeRecommendation: string
  allowedPaletteModes: CoverPaletteId[]
  allowedTextureProfiles: CoverTextureProfile[]
  optionalCelestialElements: string[]
  forbiddenCombinations: string[]
  thumbnailSilhouetteTest: string
  variants: CompositionVariant[]
}

const allTextures: CoverTextureProfile[] = [
  "soft-lithograph",
  "cut-paper-linocut",
  "restrained-screenprint",
  "mineral-stipple",
  "matte-overprint",
]

const lightPalettes: CoverPaletteId[] = [...LUMINOUS_LIGHT_PALETTE_IDS]
const civicPalettes: CoverPaletteId[] = ["clear-sky-parchment", "civic-stone-light", "luminous-ivory-sage", "clay-rose-garden"]
const naturePalettes: CoverPaletteId[] = ["luminous-ivory-sage", "wheat-and-celadon", "orchard-mist", "snowfield-ember-light"]
const seaPalettes: CoverPaletteId[] = ["sea-glass-day", "clear-sky-parchment", "luminous-ivory-sage", "wheat-and-celadon"]

function variants(base: string): CompositionVariant[] {
  return [
    {
      id: `${base}-a`,
      label: "Low Approach",
      instructions: "Use a low foreground entry, large negative field above, and one simplified destination shape.",
      routeDirection: "diagonal",
    },
    {
      id: `${base}-b`,
      label: "Lateral Tension",
      instructions: "Place the dominant symbol off center with a lateral narrative force crossing the frame.",
      routeDirection: "left-right",
    },
    {
      id: `${base}-c`,
      label: "Vertical Pressure",
      instructions: "Compress the lower plane and let a vertical mass or beam organize the image.",
      routeDirection: "vertical",
    },
    {
      id: `${base}-d`,
      label: "Quiet Distance",
      instructions: "Make the destination distant, keep object count sparse, and emphasize a calm title-safe field.",
      routeDirection: "center",
    },
  ]
}

export const COMPOSITION_FAMILIES = [
  {
    id: "luminous-path",
    label: "Luminous Path",
    suitableGenres: ["novel", "epic", "poetry", "travel", "philosophy"],
    suitableThemes: ["journey", "return", "growth", "choice", "pilgrimage"],
    unsuitableGenres: ["static interior chamber drama"],
    heroObjectRules: "Use one road, garden walk, stream, wake, furrow, beam, stair, or shadow crossing a quiet field toward one small destination.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "A broad simple entry shape may begin at the lower edge, with no busy stones or decorative border.",
    middleGroundBehavior: "Let the path/vector be the main readable force and keep supporting shapes sparse.",
    backgroundBehavior: "Use one destination, tree, house, hill, column, shore, or doorway in soft daylight.",
    allowedNarrativeVectors: ["path", "stream", "wake", "furrow", "beam", "staircase", "shoreline"],
    figurePlacement: "Optional tiny anonymous adult on or beside the vector, safely inside the central crop.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Upper warm paper, sky, meadow, wall, or sea field.",
    allowedPaletteModes: lightPalettes,
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["Do not repeat the same winding road plus tiny traveler in adjacent batch items."],
    thumbnailSilhouetteTest: "The single vector and destination must read in under one second at 96x144.",
    variants: variants("luminous-path"),
  },
  {
    id: "quiet-emblem-field",
    label: "Quiet Emblem Field",
    suitableGenres: ["war", "poetry", "philosophy", "tragedy", "political"],
    suitableThemes: ["power", "memory", "mortality", "justice", "fate"],
    unsuitableGenres: ["multi-scene adventure"],
    heroObjectRules: "Use one oversized symbolic object in a calm field, such as a shield, branch, mask, flower, seal, tool, crown, wheel, lamp, or animal-like silhouette.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "left",
    foregroundBehavior: "A small counterpoint object may anchor the lower edge, but avoid collage.",
    middleGroundBehavior: "Let the emblem dominate as a flat readable silhouette with soft print texture.",
    backgroundBehavior: "Keep the surrounding field quiet, breathable, and light.",
    allowedNarrativeVectors: ["shadow", "beam", "tilt", "field", "horizon"],
    figurePlacement: "Usually no figure; one tiny scale mark only when needed.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Opposite the emblem on a calm light field.",
    allowedPaletteModes: ["luminous-ivory-sage", "wheat-and-celadon", "civic-stone-light", "snowfield-ember-light"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["Do not make every emblem a sun, shield, or moon."],
    thumbnailSilhouetteTest: "The emblem shape must remain recognizable without detail.",
    variants: variants("quiet-emblem-field"),
  },
  {
    id: "open-threshold",
    label: "Open Threshold",
    suitableGenres: ["philosophy", "gothic", "drama", "domestic novel", "spiritual"],
    suitableThemes: ["knowledge", "freedom", "constraint", "revelation", "temptation"],
    unsuitableGenres: ["open sea voyage"],
    heroObjectRules: "Use one door, window, cave mouth, stage opening, curtain gap, garden gate, or lit room edge, kept light and inviting rather than black or horror-like.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "center",
    foregroundBehavior: "Frame the threshold with simple wall, hedge, curtain, stone, or interior plane.",
    middleGroundBehavior: "A path, beam, or shadow should pull through the opening.",
    backgroundBehavior: "Show only a simplified light field or destination beyond.",
    allowedNarrativeVectors: ["threshold", "beam", "window light", "garden walk", "shadow"],
    figurePlacement: "One tiny observer near the opening or none.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Flat wall, sky, or quiet revealed field.",
    allowedPaletteModes: ["clear-sky-parchment", "luminous-ivory-sage", "clay-rose-garden", "civic-stone-light"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["No dark cave allegory as the default for philosophy."],
    thumbnailSilhouetteTest: "The aperture must read as one clear opening.",
    variants: variants("open-threshold"),
  },
  {
    id: "shore-and-vessel",
    label: "Shore and Vessel",
    suitableGenres: ["epic", "adventure", "travel", "romance", "exile"],
    suitableThemes: ["return", "homecoming", "voyage", "temptation", "isolation"],
    unsuitableGenres: ["static domestic interior"],
    heroObjectRules: "Use one small vessel, shoreline, harbor route, river mouth, sail, wake, island, or beacon in daylight with broad sea and sky.",
    recommendedHorizon: "high",
    negativeSpaceRegion: "top",
    foregroundBehavior: "One shore, pier, wave band, or boat shape low in the frame.",
    middleGroundBehavior: "The wake, current, or shoreline should be the main narrative vector.",
    backgroundBehavior: "Use a single distant island, harbor, sun disk, or pale cloud gap.",
    allowedNarrativeVectors: ["wake", "current", "shoreline", "sail", "river mouth", "beacon"],
    figurePlacement: "Tiny figures only inside the vessel if present.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Large pale sky or calm upper sea.",
    allowedPaletteModes: seaPalettes,
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "beacon", "none"],
    forbiddenCombinations: ["Avoid giant moon plus tiny boat repetitions."],
    thumbnailSilhouetteTest: "The vessel or shore vector must remain readable at 96x144.",
    variants: variants("shore-and-vessel"),
  },
  {
    id: "garden-approach-light",
    label: "Garden Approach Light",
    suitableGenres: ["domestic novel", "romance", "satire", "children", "social novel"],
    suitableThemes: ["society", "growth", "courtship", "memory", "constraint"],
    unsuitableGenres: ["cosmic epic"],
    heroObjectRules: "Use an estate, orchard, maze, hedge, garden route, gate, village, or lawn axis in soft daylight.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Formal path, lawn, hedge, or flowerbed geometry should stay broad and uncluttered.",
    middleGroundBehavior: "One house, gate, tree, or social destination anchors the approach.",
    backgroundBehavior: "Quiet sky, hills, wall, or garden mass; no gothic mansion treatment.",
    allowedNarrativeVectors: ["garden walk", "estate road", "hedge axis", "gate", "sunlit path"],
    figurePlacement: "Zero to two distant anonymous figures, never portraits.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Upper sky, lawn, or garden wall.",
    allowedPaletteModes: ["luminous-ivory-sage", "clay-rose-garden", "orchard-mist", "wheat-and-celadon"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["Avoid sentimental cottage detail or ornate garden clutter."],
    thumbnailSilhouetteTest: "Approach route and destination must read as one social geometry.",
    variants: variants("garden-approach-light"),
  },
  {
    id: "solitary-dwelling-day",
    label: "Solitary Dwelling Day",
    suitableGenres: ["gothic", "nature writing", "domestic novel", "psychological", "romance"],
    suitableThemes: ["isolation", "shelter", "memory", "self-reliance", "constraint"],
    unsuitableGenres: ["public battle epic"],
    heroObjectRules: "Use one house, cabin, room, tent, hut, school, prison wall, or civic building set in a bright simplified field.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Minimal terrain, meadow, shore, snow, or interior floor in large planes.",
    middleGroundBehavior: "One dwelling or room edge with a single route, window light, or shadow.",
    backgroundBehavior: "Daylight sky, wall, moor, field, or pale weather; avoid horror lighting.",
    allowedNarrativeVectors: ["path", "window light", "wind", "shoreline", "shadow"],
    figurePlacement: "Usually no figure; one distant anonymous adult if scale is needed.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Large sky, wall, meadow, or snowfield.",
    allowedPaletteModes: ["orchard-mist", "luminous-ivory-sage", "snowfield-ember-light", "civic-stone-light"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["No black mansion, lightning, or horror-poster framing."],
    thumbnailSilhouetteTest: "The dwelling must remain iconic and calm at small size.",
    variants: variants("solitary-dwelling-day"),
  },
  {
    id: "botanical-monument",
    label: "Botanical Monument",
    suitableGenres: ["nature writing", "poetry", "children", "pastoral", "science"],
    suitableThemes: ["growth", "origin", "season", "mortality", "wonder"],
    unsuitableGenres: ["urban political trial"],
    heroObjectRules: "Use one plant, branch, leaf, seed, field, tree, flower, animal trace, or natural specimen treated as monumental.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "right",
    foregroundBehavior: "The natural form may enter from the lower edge or side, with no specimen labels.",
    middleGroundBehavior: "Let the botanical or natural object become the primary silhouette.",
    backgroundBehavior: "Keep meadow, sky, page, or mist field broad and uncluttered.",
    allowedNarrativeVectors: ["growth line", "branch", "furrow", "wind", "stream"],
    figurePlacement: "No figure unless a tiny mark clarifies scale.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Open field opposite the plant form.",
    allowedPaletteModes: naturePalettes,
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["No scientific labels, diagrams, or decorative floral wallpaper."],
    thumbnailSilhouetteTest: "The natural form must read as a single clear symbol.",
    variants: variants("botanical-monument"),
  },
  {
    id: "civic-axis",
    label: "Civic Axis",
    suitableGenres: ["philosophy", "political", "history", "social novel", "satire"],
    suitableThemes: ["justice", "law", "state", "class", "education", "revolution"],
    unsuitableGenres: ["wilderness lyric"],
    heroObjectRules: "Use a plaza, road, courthouse, market, factory, school, prison wall, column group, city edge, or public table reduced to clean blocks and one route.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "A road, plaza stripe, stair, or civic shadow may organize the lower half.",
    middleGroundBehavior: "Architecture should be blocky, calm, light, and readable.",
    backgroundBehavior: "Use pale sky, wall, or civic field; avoid cave darkness for philosophy.",
    allowedNarrativeVectors: ["axis", "road", "stair", "column row", "shadow", "threshold"],
    figurePlacement: "Zero to two anonymous adults as civic scale marks.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Upper sky or flat civic wall.",
    allowedPaletteModes: civicPalettes,
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["No dark cave default for The Republic-like works; keep inquiry open and architectural."],
    thumbnailSilhouetteTest: "The public axis and one architectural mass must read immediately.",
    variants: variants("civic-axis"),
  },
  {
    id: "interior-light-vector",
    label: "Interior Light Vector",
    suitableGenres: ["domestic novel", "drama", "psychological", "gothic", "letters"],
    suitableThemes: ["constraint", "privacy", "temptation", "self-knowledge", "family"],
    unsuitableGenres: ["wide sea voyage"],
    heroObjectRules: "Use one lamp, window, table, bed, mirror, chair, letterless page shape, hallway, or room edge organized by a path of light.",
    recommendedHorizon: "variable",
    negativeSpaceRegion: "split",
    foregroundBehavior: "A table, floor, wall, or bed plane can hold the lower frame.",
    middleGroundBehavior: "The light vector, shadow, or opening carries the symbolic conflict.",
    backgroundBehavior: "Interior detail must stay sparse, matte, and unfurnished except for one or two shapes.",
    allowedNarrativeVectors: ["window light", "lamp glow", "table edge", "shadow path", "mirror line"],
    figurePlacement: "One anonymous silhouette or none.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Flat wall, floor plane, or calm light field.",
    allowedPaletteModes: ["clay-rose-garden", "civic-stone-light", "luminous-ivory-sage", "clear-sky-parchment"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["window light", "none"],
    forbiddenCombinations: ["No literal scene reconstruction, readable letters, or detailed faces."],
    thumbnailSilhouetteTest: "Room geometry and light path must dominate.",
    variants: variants("interior-light-vector"),
  },
  {
    id: "elemental-force-light",
    label: "Elemental Force Light",
    suitableGenres: ["tragedy", "gothic", "nature writing", "epic", "science fiction"],
    suitableThemes: ["storm", "change", "catastrophe", "trial", "migration", "creation"],
    unsuitableGenres: ["quiet drawing-room satire"],
    heroObjectRules: "Use wind, snow, wave, fire, rain, migration, mountain, comet-like path, or weather rendered with daylight restraint.",
    recommendedHorizon: "variable",
    negativeSpaceRegion: "split",
    foregroundBehavior: "One small threatened or observing scale mark at most.",
    middleGroundBehavior: "Let the force divide or bend the composition in large clear shapes.",
    backgroundBehavior: "Keep sky, snow, sea, or field pale enough to stay breathable.",
    allowedNarrativeVectors: ["wind", "wave", "snow path", "fire line", "rain", "migration", "mountain route"],
    figurePlacement: "Optional tiny figure low and away from crop edges.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Calm pale area opposite the force.",
    allowedPaletteModes: ["snowfield-ember-light", "sea-glass-day", "clear-sky-parchment", "wheat-and-celadon"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["No stormy gothic atmosphere, lightning-poster drama, or dense disaster collage."],
    thumbnailSilhouetteTest: "The elemental force must be one bold readable movement.",
    variants: variants("elemental-force-light"),
  },
  {
    id: "processional-causeway",
    label: "Processional Causeway",
    suitableGenres: ["epic", "tragedy", "romance", "history"],
    suitableThemes: ["journey", "duty", "founding", "return"],
    unsuitableGenres: ["domestic miniature"],
    heroObjectRules: "Use one gate, arch, sanctuary, city wall, or threshold as the destination.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "A broad causeway may enter from the lower edge, but avoid busy stones or figures.",
    middleGroundBehavior: "Keep the route clear and monumental.",
    backgroundBehavior: "Use one destination silhouette with atmospheric depth.",
    allowedNarrativeVectors: ["road", "causeway", "procession", "smoke", "threshold"],
    figurePlacement: "One tiny anonymous adult on or beside the route.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Upper field or quiet sky.",
    allowedPaletteModes: ["clay-rose-garden", "clear-sky-parchment", "wheat-and-celadon", "civic-stone-light"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["star", "sun", "none"],
    forbiddenCombinations: ["Do not duplicate the Aeneid arch plus smoke plus central traveler layout."],
    thumbnailSilhouetteTest: "Route and destination must read in a 96x144 thumbnail.",
    variants: variants("processional-causeway"),
  },
  {
    id: "cosmic-ascent",
    label: "Cosmic Ascent",
    suitableGenres: ["spiritual", "philosophy", "epic", "metaphysical"],
    suitableThemes: ["ascent", "transformation", "knowledge", "fate"],
    unsuitableGenres: ["comic satire"],
    heroObjectRules: "Use a mountain, tower, terraces, or luminous axis rising toward a celestial destination.",
    recommendedHorizon: "low",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Dark base or entrance plane.",
    middleGroundBehavior: "Layered terraces or a continuous luminous route.",
    backgroundBehavior: "Celestial diagram or star field, never infographic.",
    allowedNarrativeVectors: ["ascent", "staircase", "orbit", "beam", "route"],
    figurePlacement: "One or two tiny travelers at the lower third.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Upper dark sky if stars are sparse.",
    allowedPaletteModes: ["clear-sky-parchment", "civic-stone-light", "sea-glass-day", "luminous-ivory-sage"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["star", "constellation", "concentric circles"],
    forbiddenCombinations: ["Avoid a single white winding road on every ascent variant."],
    thumbnailSilhouetteTest: "The rising mass must remain clear after downsampling.",
    variants: variants("cosmic-ascent"),
  },
  {
    id: "monumental-emblem",
    label: "Monumental Emblem",
    suitableGenres: ["war", "political", "philosophy", "tragedy"],
    suitableThemes: ["confrontation", "power", "memory", "fate"],
    unsuitableGenres: ["pastoral comedy"],
    heroObjectRules: "Use one oversized shield, disc, crown, mask, seal, wheel, relic, flower, or instrument.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "left",
    foregroundBehavior: "Use one small counterpoint object or figure, not clutter.",
    middleGroundBehavior: "Let the emblem dominate a simplified city or landscape.",
    backgroundBehavior: "Keep sky or field calm enough for type.",
    allowedNarrativeVectors: ["symbol", "shadow", "wall", "horizon", "fracture"],
    figurePlacement: "Tiny figure below or away from the emblem.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Opposite the emblem or on calm field.",
    allowedPaletteModes: ["wheat-and-celadon", "civic-stone-light", "snowfield-ember-light", "luminous-ivory-sage"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["none", "sun", "eclipse"],
    forbiddenCombinations: ["Do not make every emblem a sun or shield."],
    thumbnailSilhouetteTest: "The emblem shape must be recognizable immediately.",
    variants: variants("monumental-emblem"),
  },
  {
    id: "luminous-sea-route",
    label: "Luminous Sea Route",
    suitableGenres: ["epic", "adventure", "romance", "exile"],
    suitableThemes: ["return", "temptation", "destination", "isolation"],
    unsuitableGenres: ["domestic interior"],
    heroObjectRules: "Use one vessel, current, wake, moonlit path, or island as the dominant idea.",
    recommendedHorizon: "high",
    negativeSpaceRegion: "top",
    foregroundBehavior: "A vessel may sit low and small.",
    middleGroundBehavior: "Let water current act as the narrative vector.",
    backgroundBehavior: "Use distant island, constellation, or horizon beacon.",
    allowedNarrativeVectors: ["current", "wake", "river", "reflection", "constellation"],
    figurePlacement: "Figures should be tiny and inside the vessel if present.",
    figureCountRange: [0, 3],
    titleSafeRecommendation: "Large dark sky or calm upper sea.",
    allowedPaletteModes: ["sea-glass-day", "clear-sky-parchment", "luminous-ivory-sage", "wheat-and-celadon"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["moon", "stars", "beacon", "none"],
    forbiddenCombinations: ["Avoid giant moon plus tiny boat in adjacent batch items when possible."],
    thumbnailSilhouetteTest: "The bright current must still describe motion at thumbnail size.",
    variants: variants("luminous-sea-route"),
  },
  {
    id: "framed-revelation",
    label: "Framed Revelation",
    suitableGenres: ["philosophy", "political", "gothic", "spiritual"],
    suitableThemes: ["knowledge", "revelation", "threshold", "inner division"],
    unsuitableGenres: ["open pastoral comedy"],
    heroObjectRules: "Use one cave, doorway, aperture, arch, curtain, wall fracture, or forest opening.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "center",
    foregroundBehavior: "Dark framing shapes should be bold and simple.",
    middleGroundBehavior: "A beam, stair, or path may lead toward the revealed world.",
    backgroundBehavior: "Show a simplified destination world beyond the frame.",
    allowedNarrativeVectors: ["beam", "opening", "shadow", "threshold", "staircase"],
    figurePlacement: "One tiny observer at the edge of light.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Dark side frame or calm revealed field.",
    allowedPaletteModes: ["clear-sky-parchment", "civic-stone-light", "luminous-ivory-sage", "clay-rose-garden"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["none", "sun beam", "star"],
    forbiddenCombinations: ["Do not reuse the Republic cave opening exactly."],
    thumbnailSilhouetteTest: "The aperture must read as a frame, not a random patch.",
    variants: variants("framed-revelation"),
  },
  {
    id: "monumental-ascent",
    label: "Monumental Ascent",
    suitableGenres: ["gothic", "romance", "spiritual", "epic"],
    suitableThemes: ["ascent", "trial", "ambition", "transformation"],
    unsuitableGenres: ["comic domestic"],
    heroObjectRules: "Use cliff, stair, zigzag trail, stacked architecture, or steep ridge.",
    recommendedHorizon: "low",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Keep the lower edge anchored by one small object.",
    middleGroundBehavior: "Let the ascent occupy most of the frame.",
    backgroundBehavior: "Use mist, sky, or distant summit.",
    allowedNarrativeVectors: ["staircase", "cliff trail", "beam", "smoke"],
    figurePlacement: "Tiny figure low or midway, never detailed.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Upper sky or broad wall plane.",
    allowedPaletteModes: lightPalettes,
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["star", "moon", "none"],
    forbiddenCombinations: ["Avoid duplicating cosmic-ascent when no spiritual cue exists."],
    thumbnailSilhouetteTest: "The vertical rise must dominate.",
    variants: variants("monumental-ascent"),
  },
  {
    id: "solitary-voyage",
    label: "Solitary Voyage",
    suitableGenres: ["adventure", "exile", "romance", "psychological"],
    suitableThemes: ["isolation", "return", "temptation", "memory"],
    unsuitableGenres: ["crowd comedy"],
    heroObjectRules: "Use a single vessel, traveler, tent, or small flame against a vast plane.",
    recommendedHorizon: "high",
    negativeSpaceRegion: "top",
    foregroundBehavior: "One small scale object only.",
    middleGroundBehavior: "A huge field of sea, plain, desert, snow, or void.",
    backgroundBehavior: "Optional faint destination.",
    allowedNarrativeVectors: ["wake", "horizon", "wind", "shadow", "current"],
    figurePlacement: "One small traveler or vessel in lower third.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Dominant field above the figure.",
    allowedPaletteModes: lightPalettes,
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["moon", "star", "none"],
    forbiddenCombinations: ["No crowded fleets or caravans."],
    thumbnailSilhouetteTest: "Scale contrast must remain obvious.",
    variants: variants("solitary-voyage"),
  },
  {
    id: "coastal-citadel",
    label: "Coastal Citadel",
    suitableGenres: ["epic", "gothic", "adventure", "political"],
    suitableThemes: ["threshold", "siege", "return", "confrontation"],
    unsuitableGenres: ["interior drama"],
    heroObjectRules: "Use one fortress, harbor, wall, cliff city, or island fort.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Water or rock foreground with sparse scale object.",
    middleGroundBehavior: "Citadel silhouette should be blocky and iconic.",
    backgroundBehavior: "Keep sky or sea restrained.",
    allowedNarrativeVectors: ["shoreline", "wall", "current", "path", "beacon"],
    figurePlacement: "Tiny figures or boat low.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Sky or sea field opposite the citadel.",
    allowedPaletteModes: ["sea-glass-day", "civic-stone-light", "clear-sky-parchment", "wheat-and-celadon"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "moon", "beacon", "none"],
    forbiddenCombinations: ["Do not exceed castle/citadel batch caps."],
    thumbnailSilhouetteTest: "Fortress outline must be legible.",
    variants: variants("coastal-citadel"),
  },
  {
    id: "moonlit-sentinel",
    label: "Moonlit Sentinel",
    suitableGenres: ["gothic", "tragedy", "romance", "history"],
    suitableThemes: ["watching", "duty", "isolation", "danger"],
    unsuitableGenres: ["sunlit comedy"],
    heroObjectRules: "Use one guardian, tower, wall, lighthouse, or solitary figure beneath a large night element.",
    recommendedHorizon: "low",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Silhouette only.",
    middleGroundBehavior: "Keep architectural mass simple.",
    backgroundBehavior: "Large night sky or disc, but avoid overuse.",
    allowedNarrativeVectors: ["shadow", "beam", "horizon", "watch"],
    figurePlacement: "One figure on wall, pier, ridge, or threshold.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Dark sky with clear contrast.",
    allowedPaletteModes: ["sea-glass-day", "snowfield-ember-light", "clear-sky-parchment", "civic-stone-light"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["moon", "star", "beacon"],
    forbiddenCombinations: ["No detailed face or heroic portrait.",
    ],
    thumbnailSilhouetteTest: "Sentinel and sky element must not merge.",
    variants: variants("moonlit-sentinel"),
  },
  {
    id: "alpine-refuge",
    label: "Alpine Refuge",
    suitableGenres: ["gothic", "romance", "catastrophe", "spiritual"],
    suitableThemes: ["isolation", "trial", "memory", "shelter"],
    unsuitableGenres: ["urban satire"],
    heroObjectRules: "Use one shelter, flame, traveler, or pass overwhelmed by mountains, snow, storm, or stone.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Rocks or snow in broad simplified planes.",
    middleGroundBehavior: "Tiny refuge or figure should glow quietly.",
    backgroundBehavior: "Monumental mountain mass or storm.",
    allowedNarrativeVectors: ["storm", "stair", "smoke", "light", "path"],
    figurePlacement: "Tiny figure low or near shelter.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Sky, snow field, or dark cliff plane.",
    allowedPaletteModes: ["snowfield-ember-light", "orchard-mist", "luminous-ivory-sage", "civic-stone-light"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["lightning", "moon", "none"],
    forbiddenCombinations: ["Avoid photoreal mountain painting.",
    ],
    thumbnailSilhouetteTest: "Shelter or flame must remain visible.",
    variants: variants("alpine-refuge"),
  },
  {
    id: "storm-rupture",
    label: "Storm Rupture",
    suitableGenres: ["tragedy", "horror", "catastrophe", "war"],
    suitableThemes: ["rupture", "fall", "confrontation", "fate"],
    unsuitableGenres: ["quiet domestic"],
    heroObjectRules: "Use lightning, wave, fire, smoke, fracture, avalanche, or collapsing geometry.",
    recommendedHorizon: "variable",
    negativeSpaceRegion: "split",
    foregroundBehavior: "One threatened scale point.",
    middleGroundBehavior: "Let the rupture divide the composition.",
    backgroundBehavior: "Maintain clear graphic masses despite action.",
    allowedNarrativeVectors: ["fracture", "lightning", "wave", "fire", "smoke"],
    figurePlacement: "Optional tiny figure away from the edge crop.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Calm area opposite the rupture.",
    allowedPaletteModes: ["snowfield-ember-light", "wheat-and-celadon", "sea-glass-day", "clear-sky-parchment"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["lightning", "eclipse", "none"],
    forbiddenCombinations: ["No crowded disaster collage.",
    ],
    thumbnailSilhouetteTest: "The rupture shape must be bold.",
    variants: variants("storm-rupture"),
  },
  {
    id: "estate-approach",
    label: "Estate Approach",
    suitableGenres: ["domestic novel", "romance", "satire", "social novel"],
    suitableThemes: ["social constraint", "temptation", "destination", "memory"],
    unsuitableGenres: ["cosmic epic"],
    heroObjectRules: "Use one house, manor, village, institution, garden, or formal approach.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Garden, field, or path in controlled geometry.",
    middleGroundBehavior: "A single dwelling or social destination.",
    backgroundBehavior: "Quiet sky or hills.",
    allowedNarrativeVectors: ["path", "garden geometry", "threshold", "shadow"],
    figurePlacement: "One figure in formal distance.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "Upper field or calm lawn/sky.",
    allowedPaletteModes: ["luminous-ivory-sage", "clay-rose-garden", "orchard-mist", "wheat-and-celadon"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["Avoid sentimental cottage illustration.",
    ],
    thumbnailSilhouetteTest: "House and approach must read as one social geometry.",
    variants: variants("estate-approach"),
  },
  {
    id: "isolated-dwelling",
    label: "Isolated Dwelling",
    suitableGenres: ["gothic", "domestic", "psychological", "romance"],
    suitableThemes: ["isolation", "memory", "inner division", "constraint"],
    unsuitableGenres: ["public battle epic"],
    heroObjectRules: "Use a single house, room, tower, tent, or illuminated window in a large landscape.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Minimal terrain or interior threshold.",
    middleGroundBehavior: "One dwelling with one light or shadow.",
    backgroundBehavior: "Weather, hill, moor, sea, or blank field.",
    allowedNarrativeVectors: ["window light", "wind", "shadow", "path"],
    figurePlacement: "No figure or one distant figure.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Large sky or wall field.",
    allowedPaletteModes: ["orchard-mist", "luminous-ivory-sage", "snowfield-ember-light", "civic-stone-light"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["moon", "sun", "none"],
    forbiddenCombinations: ["No cozy realism or sentimental detail.",
    ],
    thumbnailSilhouetteTest: "Dwelling must remain iconic.",
    variants: variants("isolated-dwelling"),
  },
  {
    id: "horizon-beacon",
    label: "Horizon Beacon",
    suitableGenres: ["romance", "adventure", "political", "gothic"],
    suitableThemes: ["hope", "obsession", "danger", "destination"],
    unsuitableGenres: ["interior chamber drama"],
    heroObjectRules: "Use lighthouse, star, flame, tower, city light, sun, or signal as distant point.",
    recommendedHorizon: "high",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Quiet observer, pier, shore, or plain.",
    middleGroundBehavior: "Water or land vector aimed at the beacon.",
    backgroundBehavior: "One small radiant point.",
    allowedNarrativeVectors: ["beam", "reflection", "horizon", "wake"],
    figurePlacement: "Optional small observer low and off center.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Large dark field with beacon away from title block.",
    allowedPaletteModes: ["sea-glass-day", "clear-sky-parchment", "civic-stone-light", "luminous-ivory-sage"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["star", "lighthouse beam", "sun"],
    forbiddenCombinations: ["Beacon must not become a logo or text mark.",
    ],
    thumbnailSilhouetteTest: "Beacon and horizon must remain visible.",
    variants: variants("horizon-beacon"),
  },
  {
    id: "labyrinth-gate",
    label: "Labyrinth Gate",
    suitableGenres: ["mystery", "gothic", "psychological", "satire"],
    suitableThemes: ["secrecy", "inner division", "temptation", "knowledge"],
    unsuitableGenres: ["open sea journey"],
    heroObjectRules: "Use walls, hedges, passages, keys, doors, or repeated boundaries.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "One symbolic key, path, or threshold may sit low.",
    middleGroundBehavior: "Maze geometry must stay simple.",
    backgroundBehavior: "Door or opening as destination.",
    allowedNarrativeVectors: ["path", "threshold", "shadow", "repeated wall"],
    figurePlacement: "One figure before gate or none.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Upper field or flat wall mass.",
    allowedPaletteModes: ["luminous-ivory-sage", "civic-stone-light", "clay-rose-garden", "clear-sky-parchment"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["none", "sun", "moon"],
    forbiddenCombinations: ["No literal puzzle map or infographic.",
    ],
    thumbnailSilhouetteTest: "Gate/opening must read at small size.",
    variants: variants("labyrinth-gate"),
  },
  {
    id: "windmill-procession",
    label: "Windmill Procession",
    suitableGenres: ["comic", "pastoral", "satire", "quest"],
    suitableThemes: ["comic quest", "delusion", "duty", "transformation"],
    unsuitableGenres: ["solemn massacre"],
    heroObjectRules: "Use repeated figures, animals, machines, or structures to create comic scale.",
    recommendedHorizon: "middle",
    negativeSpaceRegion: "top",
    foregroundBehavior: "A small procession may enter the frame.",
    middleGroundBehavior: "Machines or structures must vary in scale.",
    backgroundBehavior: "Keep the landscape spare.",
    allowedNarrativeVectors: ["procession", "road", "wind", "repetition"],
    figurePlacement: "One to three tiny riders or walkers.",
    figureCountRange: [1, 3],
    titleSafeRecommendation: "Upper sky.",
    allowedPaletteModes: ["wheat-and-celadon", "luminous-ivory-sage", "clay-rose-garden", "clear-sky-parchment"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "none"],
    forbiddenCombinations: ["Do not use this for every comic work.",
    ],
    thumbnailSilhouetteTest: "Machine or repeated structure must be clear.",
    variants: variants("windmill-procession"),
  },
  {
    id: "interior-threshold",
    label: "Interior Threshold",
    suitableGenres: ["domestic", "drama", "psychological", "gothic"],
    suitableThemes: ["constraint", "temptation", "private conflict", "knowledge"],
    unsuitableGenres: ["wide sea voyage"],
    heroObjectRules: "Use one window, door, table, bed, mirror, hall, or domestic aperture.",
    recommendedHorizon: "variable",
    negativeSpaceRegion: "split",
    foregroundBehavior: "A table edge, floor, or wall may frame the lower plane.",
    middleGroundBehavior: "Threshold must carry the symbolic conflict.",
    backgroundBehavior: "Exterior or interior beyond should stay simplified.",
    allowedNarrativeVectors: ["doorway", "window light", "mirror", "shadow"],
    figurePlacement: "One anonymous figure or none.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Flat wall or floor plane.",
    allowedPaletteModes: ["clay-rose-garden", "civic-stone-light", "luminous-ivory-sage", "clear-sky-parchment"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["none", "window light"],
    forbiddenCombinations: ["No literal scene reconstruction.",
    ],
    thumbnailSilhouetteTest: "Threshold geometry must dominate.",
    variants: variants("interior-threshold"),
  },
  {
    id: "split-world",
    label: "Split World",
    suitableGenres: ["political", "tragedy", "romance", "philosophy"],
    suitableThemes: ["division", "choice", "rupture", "social constraint"],
    unsuitableGenres: ["single-mood lyric"],
    heroObjectRules: "Use two opposed spaces across one decisive boundary.",
    recommendedHorizon: "variable",
    negativeSpaceRegion: "split",
    foregroundBehavior: "Boundary may enter from lower edge.",
    middleGroundBehavior: "Both worlds should be legible but not equally busy.",
    backgroundBehavior: "Use contrast of light/dark, land/sea, order/wilderness, city/ruin.",
    allowedNarrativeVectors: ["boundary", "shadow", "river", "wall", "fracture"],
    figurePlacement: "One figure on the boundary.",
    figureCountRange: [0, 2],
    titleSafeRecommendation: "The calmer side of the split.",
    allowedPaletteModes: lightPalettes,
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["sun", "moon", "none"],
    forbiddenCombinations: ["No symmetrical poster split without hierarchy.",
    ],
    thumbnailSilhouetteTest: "Boundary must remain decisive.",
    variants: variants("split-world"),
  },
  {
    id: "fall-or-descent",
    label: "Fall or Descent",
    suitableGenres: ["tragedy", "gothic", "spiritual", "catastrophe"],
    suitableThemes: ["descent", "fall", "temptation", "knowledge"],
    unsuitableGenres: ["pastoral comedy"],
    heroObjectRules: "Use vertical plunge, staircase, shaft, waterfall, chasm, or downward procession.",
    recommendedHorizon: "high",
    negativeSpaceRegion: "top",
    foregroundBehavior: "High ledge, aperture, or rim.",
    middleGroundBehavior: "Descending vector must be unmistakable.",
    backgroundBehavior: "Depth can be flat bands rather than realism.",
    allowedNarrativeVectors: ["descent", "chasm", "shaft", "waterfall", "shadow"],
    figurePlacement: "One tiny figure at threshold or none.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Upper ledge or dark field.",
    allowedPaletteModes: ["clear-sky-parchment", "civic-stone-light", "snowfield-ember-light", "wheat-and-celadon"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["none", "distant light"],
    forbiddenCombinations: ["No action-movie falling body.",
    ],
    thumbnailSilhouetteTest: "The downward force must read immediately.",
    variants: variants("fall-or-descent"),
  },
  {
    id: "constellation-orbit",
    label: "Constellation Orbit",
    suitableGenres: ["philosophy", "science", "metaphysical", "romance"],
    suitableThemes: ["fate", "knowledge", "memory", "inner division"],
    unsuitableGenres: ["literal battlefield"],
    heroObjectRules: "Use stars, circles, instruments, or orbiting objects as symbolic geometry.",
    recommendedHorizon: "low",
    negativeSpaceRegion: "top",
    foregroundBehavior: "Small instrument, observer, or landscape base.",
    middleGroundBehavior: "Orbits or repeated points should be symbolic, not diagrammatic.",
    backgroundBehavior: "Large field for celestial geometry.",
    allowedNarrativeVectors: ["orbit", "constellation", "beam", "repeated points"],
    figurePlacement: "Optional tiny observer low.",
    figureCountRange: [0, 1],
    titleSafeRecommendation: "Open field between orbit elements.",
    allowedPaletteModes: ["clear-sky-parchment", "sea-glass-day", "civic-stone-light", "luminous-ivory-sage"],
    allowedTextureProfiles: allTextures,
    optionalCelestialElements: ["stars", "orbits", "moon", "sun"],
    forbiddenCombinations: ["Avoid scientific infographic labels or numbers.",
    ],
    thumbnailSilhouetteTest: "Orbit geometry must remain simple.",
    variants: variants("constellation-orbit"),
  },
] as const satisfies readonly CompositionFamily[]

export type CompositionFamilyId = (typeof COMPOSITION_FAMILIES)[number]["id"]

export const LUMINOUS_COMPOSITION_FAMILY_IDS = [
  "luminous-path",
  "quiet-emblem-field",
  "open-threshold",
  "shore-and-vessel",
  "garden-approach-light",
  "solitary-dwelling-day",
  "botanical-monument",
  "civic-axis",
  "interior-light-vector",
  "elemental-force-light",
] as const satisfies readonly CompositionFamilyId[]

export function getCompositionFamily(id: CompositionFamilyId): CompositionFamily {
  const family = COMPOSITION_FAMILIES.find((item) => item.id === id)
  if (!family) {
    throw new Error(`Unknown composition family: ${id}`)
  }
  return family
}
