#!/usr/bin/env npx tsx
/**
 * add-canonical-books-2.ts
 *
 * Adds ~130 canonical books to the Tome app library.
 * Reads meta.json for chapter data, generates TomeBook & TomeChapter entries,
 * and appends them to src/data/books.ts and src/data/chapters.ts.
 *
 * Run: npx tsx scripts/add-canonical-books-2.ts
 */

import * as fs from "fs";
import * as path from "path";

// ── Paths ──────────────────────────────────────────────────────────────────────

const ROOT = path.resolve(__dirname, "..");
const BOOKS_FILE = path.join(ROOT, "src/data/books.ts");
const CHAPTERS_FILE = path.join(ROOT, "src/data/chapters.ts");
const CONTENT_DIR = path.join(ROOT, "public/content");

// ── Tradition → Cover Colors ───────────────────────────────────────────────────

const TRADITION_COLORS: Record<string, { primary: string; secondary: string; accent: string }> = {
  Victorian:            { primary: "#2D1B5E", secondary: "#1E1145", accent: "#8B5CF6" },
  Russian:              { primary: "#5C1A1A", secondary: "#3D1010", accent: "#DC2626" },
  American:             { primary: "#143220", secondary: "#0A1F14", accent: "#22C55E" },
  French:               { primary: "#0A1F3D", secondary: "#061428", accent: "#EC4899" },
  Modernist:            { primary: "#111827", secondary: "#0A0F1A", accent: "#14B8A6" },
  Romantic:             { primary: "#4A0E2D", secondary: "#2D0819", accent: "#F43F5E" },
  Renaissance:          { primary: "#3D1A6E", secondary: "#2A1050", accent: "#D97706" },
  Enlightenment:        { primary: "#0F2744", secondary: "#091A2E", accent: "#06B6D4" },
  "Ancient Greek":      { primary: "#1E3A5F", secondary: "#0F2744", accent: "#0EA5E9" },
  "Medieval European":  { primary: "#1B4332", secondary: "#0F2B20", accent: "#F59E0B" },
  Eastern:              { primary: "#5C2800", secondary: "#3D1A00", accent: "#F97316" },
  "Post-Colonial":      { primary: "#065F46", secondary: "#034335", accent: "#10B981" },
  Contemporary:         { primary: "#1A1A2E", secondary: "#111122", accent: "#A78BFA" },
  Scandinavian:         { primary: "#1E293B", secondary: "#0F172A", accent: "#38BDF8" },
  Germanic:             { primary: "#1F2937", secondary: "#111827", accent: "#10B981" },
};

// ── Book Config Interface ──────────────────────────────────────────────────────

interface BookConfig {
  id: string;
  title: string;
  author: string;
  year: number;
  tradition: string;
  era: string;
  genres: string[];
  difficulty: "Beginner" | "Intermediate" | "Advanced" | "Scholar";
  synopsis: string;
  themes: string[];
  country: string;
  language?: string;
  readingLanguage?: string;
}

// ── Meta.json shape ────────────────────────────────────────────────────────────

interface MetaJson {
  bookId: string;
  title: string;
  author: string;
  chapterCount: number;
  totalWordCount: number;
  totalMinutes: number;
  chapters: Array<{
    index: number;
    title: string;
    wordCount: number;
    estimatedMinutes: number;
  }>;
}

// ── Helper: author → authorId ──────────────────────────────────────────────────

function toAuthorId(author: string): string {
  return author
    .toLowerCase()
    .replace(/\./g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ── Helper: format reading time ────────────────────────────────────────────────

function formatReadingTime(minutes: number): string {
  const hours = Math.round(minutes / 60);
  if (hours < 1) return `~${minutes} minutes`;
  return `~${hours} hour${hours !== 1 ? "s" : ""}`;
}

// ── All ~130 Book Configs ────────────────────────────────────────────────────

const BOOK_CONFIGS: BookConfig[] = [
  {
    id: "a-confession",
    title: "A Confession",
    author: "Leo Tolstoy",
    year: 1882,
    tradition: "Russian",
    era: "Victorian",
    genres: ["Autobiography", "Philosophy", "Religious Writing"],
    difficulty: "Intermediate",
    synopsis: "Tolstoy recounts his existential crisis at the height of fame and fortune, grappling with the meaning of life and the pull toward faith after reason fails to provide answers.",
    themes: ["Existential crisis", "Faith", "Meaning of life", "Despair", "Spiritual awakening"],
    country: "Russia",
    language: "Russian",
    readingLanguage: "English",
  },
  {
    id: "a-farewell-to-arms",
    title: "A Farewell to Arms",
    author: "Ernest Hemingway",
    year: 1929,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "War Fiction", "Romance"],
    difficulty: "Intermediate",
    synopsis: "An American ambulance driver on the Italian front in World War I falls in love with a British nurse, and their doomed romance unfolds against the senseless brutality of war.",
    themes: ["War", "Love", "Loss", "Disillusionment", "Courage"],
    country: "USA",
  },
  {
    id: "a-portrait-of-the-artist-as-a-young-man",
    title: "A Portrait of the Artist as a Young Man",
    author: "James Joyce",
    year: 1916,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Bildungsroman", "Autobiographical Fiction"],
    difficulty: "Advanced",
    synopsis: "Stephen Dedalus grows from a sensitive child in Catholic Dublin to a fiercely independent young artist, rejecting family, church, and nation to forge his identity through art.",
    themes: ["Artistic identity", "Religion", "Rebellion", "Irish identity", "Coming of age"],
    country: "Ireland",
  },
  {
    id: "a-vindication-of-the-rights-of-woman",
    title: "A Vindication of the Rights of Woman",
    author: "Mary Wollstonecraft",
    year: 1792,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Philosophy", "Feminist Writing", "Political Theory"],
    difficulty: "Advanced",
    synopsis: "Wollstonecraft argues that women are not naturally inferior to men but only appear so because of lack of education, making a revolutionary case for female intellectual equality.",
    themes: ["Women's rights", "Education", "Equality", "Reason", "Social reform"],
    country: "England",
  },
  {
    id: "agamemnon",
    title: "Agamemnon",
    author: "Aeschylus",
    year: -458,
    tradition: "Ancient Greek",
    era: "Ancient",
    genres: ["Tragedy", "Drama"],
    difficulty: "Advanced",
    synopsis: "The victorious King Agamemnon returns from Troy only to be murdered by his wife Clytemnestra, who has nursed vengeance for the sacrifice of their daughter Iphigenia.",
    themes: ["Justice", "Revenge", "Fate", "Hubris", "Sacrifice"],
    country: "Greece",
    language: "Ancient Greek",
    readingLanguage: "English",
  },
  {
    id: "agnes-grey",
    title: "Agnes Grey",
    author: "Anne Bront\u00eb",
    year: 1847,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Autobiographical Fiction"],
    difficulty: "Beginner",
    synopsis: "A clergyman's daughter endures the indignities and loneliness of life as a governess to wealthy but unfeeling families, finding quiet strength in virtue and eventual love.",
    themes: ["Class", "Morality", "Independence", "Love", "Perseverance"],
    country: "England",
  },
  {
    id: "all-quiet-on-the-western-front",
    title: "All Quiet on the Western Front",
    author: "Erich Maria Remarque",
    year: 1929,
    tradition: "Germanic",
    era: "Modern",
    genres: ["Novel", "War Fiction"],
    difficulty: "Intermediate",
    synopsis: "A young German soldier and his classmates experience the horrifying reality of trench warfare in World War I, which systematically destroys their youth, idealism, and humanity.",
    themes: ["War", "Lost generation", "Disillusionment", "Comradeship", "Death"],
    country: "Germany",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "an-enquiry-concerning-human-understanding",
    title: "An Enquiry Concerning Human Understanding",
    author: "David Hume",
    year: 1748,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Philosophy", "Epistemology"],
    difficulty: "Advanced",
    synopsis: "Hume systematically examines the foundations of human knowledge, arguing that our beliefs rest on custom and habit rather than rational demonstration, shaking the foundations of metaphysics.",
    themes: ["Skepticism", "Causation", "Knowledge", "Empiricism", "Reason"],
    country: "Scotland",
  },
  {
    id: "antony-and-cleopatra",
    title: "Antony and Cleopatra",
    author: "William Shakespeare",
    year: 1607,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["Tragedy", "Drama", "Historical Play"],
    difficulty: "Intermediate",
    synopsis: "The Roman general Mark Antony is torn between his duty to Rome and his passionate love for the Egyptian queen Cleopatra, leading both to magnificent ruin.",
    themes: ["Love vs. duty", "Power", "Honor", "Empire", "Desire"],
    country: "England",
  },
  {
    id: "arms-and-the-man",
    title: "Arms and the Man",
    author: "George Bernard Shaw",
    year: 1894,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Comedy", "Drama", "Satire"],
    difficulty: "Beginner",
    synopsis: "A pragmatic Swiss mercenary hiding in a Bulgarian woman's bedroom during the Serbo-Bulgarian War punctures romantic illusions about love and military glory.",
    themes: ["War", "Romanticism vs. realism", "Class", "Love", "Idealism"],
    country: "Ireland",
  },
  {
    id: "barchester-towers",
    title: "Barchester Towers",
    author: "Anthony Trollope",
    year: 1857,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Satire", "Comedy"],
    difficulty: "Intermediate",
    synopsis: "The appointment of a new bishop in the cathedral town of Barchester sets off a battle for ecclesiastical power among ambitious clergy and their scheming allies.",
    themes: ["Ambition", "Church politics", "Hypocrisy", "Social maneuvering", "Marriage"],
    country: "England",
  },
  {
    id: "beyond-good-and-evil",
    title: "Beyond Good and Evil",
    author: "Friedrich Nietzsche",
    year: 1886,
    tradition: "Germanic",
    era: "Victorian",
    genres: ["Philosophy"],
    difficulty: "Scholar",
    synopsis: "Nietzsche attacks the prejudices of past philosophers and proposes a new, dangerous philosophy that moves beyond conventional morality toward the will to power and the creation of new values.",
    themes: ["Morality", "Will to power", "Truth", "Philosophy", "Master-slave morality"],
    country: "Germany",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "buddenbrooks",
    title: "Buddenbrooks",
    author: "Thomas Mann",
    year: 1901,
    tradition: "Germanic",
    era: "Modern",
    genres: ["Novel", "Family Saga"],
    difficulty: "Advanced",
    synopsis: "Four generations of a wealthy North German merchant family rise and decline, as commercial vigor gives way to artistic sensitivity and physical decay in a masterful chronicle of bourgeois life.",
    themes: ["Decline", "Family", "Art vs. commerce", "Bourgeois life", "Mortality"],
    country: "Germany",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "candida",
    title: "Candida",
    author: "George Bernard Shaw",
    year: 1898,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Comedy", "Drama"],
    difficulty: "Beginner",
    synopsis: "A clergyman's wife must choose between her comfortable, confident husband and a passionate young poet who worships her, in a witty inversion of romantic expectations.",
    themes: ["Love", "Marriage", "Strength vs. weakness", "Idealism", "Domesticity"],
    country: "Ireland",
  },
  {
    id: "cane",
    title: "Cane",
    author: "Jean Toomer",
    year: 1923,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Poetry", "Experimental Fiction"],
    difficulty: "Advanced",
    synopsis: "A kaleidoscopic blend of prose, poetry, and drama evokes the lives of Black Americans in the rural South and urban North during the Harlem Renaissance.",
    themes: ["Race", "Identity", "Southern landscape", "Modernity", "Black experience"],
    country: "USA",
  },
  {
    id: "castle-rackrent",
    title: "Castle Rackrent",
    author: "Maria Edgeworth",
    year: 1800,
    tradition: "Victorian",
    era: "Romantic",
    genres: ["Novel", "Satire"],
    difficulty: "Intermediate",
    synopsis: "A loyal Irish servant narrates the decline of four generations of his Anglo-Irish masters, each more reckless than the last, in one of the first regional novels in English.",
    themes: ["Anglo-Irish relations", "Decline", "Loyalty", "Class", "Satire"],
    country: "Ireland",
  },
  {
    id: "clarissa",
    title: "Clarissa",
    author: "Samuel Richardson",
    year: 1748,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Epistolary Novel", "Tragedy"],
    difficulty: "Scholar",
    synopsis: "A virtuous young woman is pursued, entrapped, and ultimately destroyed by the charming but predatory rake Lovelace, in a monumental epistolary novel of conscience and violation.",
    themes: ["Virtue", "Seduction", "Power", "Class", "Death", "Autonomy"],
    country: "England",
  },
  {
    id: "coriolanus",
    title: "Coriolanus",
    author: "William Shakespeare",
    year: 1608,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["Tragedy", "Drama", "Political Play"],
    difficulty: "Intermediate",
    synopsis: "A proud Roman general, banished by the fickle populace he despises, turns against his own city, and only his mother's plea can avert total destruction.",
    themes: ["Pride", "Democracy", "Class conflict", "Honor", "Loyalty"],
    country: "England",
  },
  {
    id: "dangerous-liaisons",
    title: "Dangerous Liaisons",
    author: "Pierre Choderlos de Laclos",
    year: 1782,
    tradition: "French",
    era: "Enlightenment",
    genres: ["Epistolary Novel", "Psychological Fiction"],
    difficulty: "Advanced",
    synopsis: "Two aristocratic libertines wage a cruel game of seduction and manipulation through letters, destroying the innocent lives caught in their web of vanity and revenge.",
    themes: ["Manipulation", "Seduction", "Vanity", "Corruption", "Revenge"],
    country: "France",
    language: "French",
    readingLanguage: "English",
  },
  {
    id: "daniel-deronda",
    title: "Daniel Deronda",
    author: "George Eliot",
    year: 1876,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Social Fiction"],
    difficulty: "Advanced",
    synopsis: "A young Englishman discovers his Jewish heritage and is drawn into the nascent Zionist movement, while a beautiful but self-absorbed woman confronts the consequences of a disastrous marriage.",
    themes: ["Identity", "Judaism", "Moral growth", "Marriage", "Destiny"],
    country: "England",
  },
  {
    id: "death-comes-for-the-archbishop",
    title: "Death Comes for the Archbishop",
    author: "Willa Cather",
    year: 1927,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Historical Fiction"],
    difficulty: "Intermediate",
    synopsis: "Two French priests journey to the vast, ancient landscape of 1850s New Mexico to establish a new diocese, encountering diverse peoples and forging a spiritual life amid the desert's grandeur.",
    themes: ["Faith", "Landscape", "Friendship", "Cultural encounter", "Devotion"],
    country: "USA",
  },
  {
    id: "demons",
    title: "Demons",
    author: "Fyodor Dostoevsky",
    year: 1872,
    tradition: "Russian",
    era: "Victorian",
    genres: ["Novel", "Political Fiction", "Psychological Fiction"],
    difficulty: "Scholar",
    synopsis: "A provincial Russian town is torn apart by a cell of nihilist revolutionaries whose ideological fervor spirals into murder, madness, and destruction in a prophetic portrait of political extremism.",
    themes: ["Nihilism", "Revolution", "Evil", "Ideology", "Moral collapse"],
    country: "Russia",
    language: "Russian",
    readingLanguage: "English",
  },
  {
    id: "dialogues",
    title: "Dialogues",
    author: "Seneca",
    year: 65,
    tradition: "Ancient Greek",
    era: "Ancient",
    genres: ["Philosophy", "Stoicism", "Essays"],
    difficulty: "Advanced",
    synopsis: "Seneca's philosophical dialogues address anger, providence, the shortness of life, and the consolation of wisdom, offering practical Stoic guidance for living well amid adversity.",
    themes: ["Stoicism", "Virtue", "Death", "Anger", "Wisdom", "Fate"],
    country: "Italy",
    language: "Latin",
    readingLanguage: "English",
  },
  {
    id: "discourses-on-livy",
    title: "Discourses on Livy",
    author: "Niccol\u00f2 Machiavelli",
    year: 1531,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["Political Theory", "Philosophy", "History"],
    difficulty: "Advanced",
    synopsis: "Machiavelli examines the history of the Roman Republic to derive principles of republican government, arguing that political liberty depends on civic virtue and institutional design.",
    themes: ["Republicanism", "Liberty", "Power", "History", "Civic virtue"],
    country: "Italy",
    language: "Italian",
    readingLanguage: "English",
  },
  {
    id: "dodsworth",
    title: "Dodsworth",
    author: "Sinclair Lewis",
    year: 1929,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Social Fiction"],
    difficulty: "Intermediate",
    synopsis: "A retired American automobile magnate travels to Europe with his status-seeking wife, and their marriage unravels as each confronts what they truly want from life.",
    themes: ["Marriage", "American identity", "Europe vs. America", "Self-discovery", "Materialism"],
    country: "USA",
  },
  {
    id: "dombey-and-son",
    title: "Dombey and Son",
    author: "Charles Dickens",
    year: 1848,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Social Criticism"],
    difficulty: "Advanced",
    synopsis: "A proud London merchant pins all his hopes on his sickly son and heir while neglecting his devoted daughter, until ruin strips away his arrogance and reveals the love he spurned.",
    themes: ["Pride", "Family", "Commerce", "Neglect", "Redemption"],
    country: "England",
  },
  {
    id: "dubliners",
    title: "Dubliners",
    author: "James Joyce",
    year: 1914,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Short Stories"],
    difficulty: "Intermediate",
    synopsis: "Fifteen stories trace the moral paralysis of Dublin life from childhood to maturity, culminating in the masterful \"The Dead,\" where a man confronts the limits of his own emotional life.",
    themes: ["Paralysis", "Epiphany", "Irish life", "Death", "Loneliness"],
    country: "Ireland",
  },
  {
    id: "elmer-gantry",
    title: "Elmer Gantry",
    author: "Sinclair Lewis",
    year: 1927,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Satire"],
    difficulty: "Intermediate",
    synopsis: "A charismatic but morally bankrupt preacher rises to fame in the American evangelical movement, using religion as a vehicle for personal ambition and hypocrisy.",
    themes: ["Hypocrisy", "Religion", "Ambition", "American culture", "Corruption"],
    country: "USA",
  },
  {
    id: "eugenie-grandet",
    title: "Eug\u00e9nie Grandet",
    author: "Honor\u00e9 de Balzac",
    year: 1833,
    tradition: "French",
    era: "Romantic",
    genres: ["Novel", "Realism"],
    difficulty: "Intermediate",
    synopsis: "A provincial miser's daughter falls in love with her worldly cousin, but her father's obsessive greed and her cousin's faithlessness conspire to crush her hopes.",
    themes: ["Avarice", "Love", "Provincial life", "Sacrifice", "Betrayal"],
    country: "France",
    language: "French",
    readingLanguage: "English",
  },
  {
    id: "evelina",
    title: "Evelina",
    author: "Fanny Burney",
    year: 1778,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Epistolary Novel", "Comedy of Manners"],
    difficulty: "Intermediate",
    synopsis: "A young woman of uncertain birth enters London society for the first time, navigating its absurdities and dangers while searching for her true identity and a worthy suitor.",
    themes: ["Social class", "Female identity", "Manners", "Coming of age", "Marriage"],
    country: "England",
  },
  {
    id: "father-goriot",
    title: "Father Goriot",
    author: "Honor\u00e9 de Balzac",
    year: 1835,
    tradition: "French",
    era: "Romantic",
    genres: ["Novel", "Realism"],
    difficulty: "Intermediate",
    synopsis: "An old man sacrifices everything for his two ungrateful daughters in Paris, while an ambitious young law student learns the ruthless rules of society at a shabby boarding house.",
    themes: ["Paternal love", "Ambition", "Social climbing", "Ingratitude", "Money"],
    country: "France",
    language: "French",
    readingLanguage: "English",
  },
  {
    id: "flatland",
    title: "Flatland",
    author: "Edwin A. Abbott",
    year: 1884,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novella", "Satire", "Science Fiction"],
    difficulty: "Beginner",
    synopsis: "A square living in a two-dimensional world discovers the existence of a third dimension, satirizing Victorian social hierarchy and exploring the nature of perception and reality.",
    themes: ["Dimension", "Social hierarchy", "Perception", "Satire", "Mathematics"],
    country: "England",
  },
  {
    id: "gentlemen-prefer-blondes",
    title: "Gentlemen Prefer Blondes",
    author: "Anita Loos",
    year: 1925,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Satire", "Comedy"],
    difficulty: "Beginner",
    synopsis: "A shrewd blonde flapper chronicles her comic adventures across America and Europe in her diary, using men's infatuation with her to advance her material interests.",
    themes: ["Materialism", "Gender", "Satire", "1920s culture", "Wit"],
    country: "USA",
  },
  {
    id: "ghosts",
    title: "Ghosts",
    author: "Henrik Ibsen",
    year: 1881,
    tradition: "Scandinavian",
    era: "Victorian",
    genres: ["Drama", "Tragedy"],
    difficulty: "Intermediate",
    synopsis: "A respectable widow discovers that the sins of her dead husband have poisoned her family beyond redemption, as inherited disease and moral hypocrisy close in on her son.",
    themes: ["Heredity", "Hypocrisy", "Duty", "Moral decay", "Scandal"],
    country: "Norway",
    language: "Norwegian",
    readingLanguage: "English",
  },
  {
    id: "gitanjali",
    title: "Gitanjali",
    author: "Rabindranath Tagore",
    year: 1912,
    tradition: "Eastern",
    era: "Modern",
    genres: ["Poetry", "Spiritual Writing"],
    difficulty: "Beginner",
    synopsis: "A luminous collection of prose poems offers devotional songs to the divine, blending Hindu mysticism with a universal longing for spiritual union and inner peace.",
    themes: ["Devotion", "Spirituality", "Nature", "Divine love", "Humility"],
    country: "India",
    language: "Bengali",
    readingLanguage: "English",
  },
  {
    id: "hadji-murad",
    title: "Hadji Mur\u00e1d",
    author: "Leo Tolstoy",
    year: 1912,
    tradition: "Russian",
    era: "Modern",
    genres: ["Novella", "Historical Fiction"],
    difficulty: "Intermediate",
    synopsis: "A legendary Chechen warrior defects to the Russians in the Caucasus wars, caught between two empires, and meets a tragic end that exposes the cruelty of power on all sides.",
    themes: ["War", "Honor", "Betrayal", "Empire", "Courage"],
    country: "Russia",
    language: "Russian",
    readingLanguage: "English",
  },
  {
    id: "heartbreak-house",
    title: "Heartbreak House",
    author: "George Bernard Shaw",
    year: 1919,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Drama", "Comedy", "Satire"],
    difficulty: "Intermediate",
    synopsis: "A group of cultured but aimless English people gather in an eccentric captain's ship-shaped house, drifting toward catastrophe as Europe sleepwalks into the Great War.",
    themes: ["Disillusionment", "War", "English society", "Futility", "Culture"],
    country: "Ireland",
  },
  {
    id: "hedda-gabler",
    title: "Hedda Gabler",
    author: "Henrik Ibsen",
    year: 1891,
    tradition: "Scandinavian",
    era: "Victorian",
    genres: ["Drama", "Tragedy"],
    difficulty: "Intermediate",
    synopsis: "A brilliant, bored aristocrat trapped in a stifling marriage manipulates the lives of those around her with devastating consequences, refusing to submit to a world that offers her no power.",
    themes: ["Freedom", "Boredom", "Manipulation", "Gender", "Destruction"],
    country: "Norway",
    language: "Norwegian",
    readingLanguage: "English",
  },
  {
    id: "henry-iv-part-i",
    title: "Henry IV, Part I",
    author: "William Shakespeare",
    year: 1597,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["History Play", "Drama"],
    difficulty: "Intermediate",
    synopsis: "The young Prince Hal carouses with the roguish Falstaff in Eastcheap taverns while rebellion threatens his father's throne, until honor calls him to prove himself at the Battle of Shrewsbury.",
    themes: ["Honor", "Kingship", "Coming of age", "Rebellion", "Duty vs. pleasure"],
    country: "England",
  },
  {
    id: "henry-iv-part-ii",
    title: "Henry IV, Part II",
    author: "William Shakespeare",
    year: 1600,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["History Play", "Drama"],
    difficulty: "Intermediate",
    synopsis: "As his father's health fails and rebellion simmers, Prince Hal prepares for the crown, and his ascent requires a painful reckoning with Falstaff and the dissolute past.",
    themes: ["Power", "Aging", "Responsibility", "Justice", "Friendship"],
    country: "England",
  },
  {
    id: "henry-v",
    title: "Henry V",
    author: "William Shakespeare",
    year: 1599,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["History Play", "Drama"],
    difficulty: "Intermediate",
    synopsis: "The once-wayward prince, now King Henry V, leads England to a stunning victory at Agincourt, rallying his outnumbered troops with some of the most stirring speeches in English literature.",
    themes: ["Leadership", "War", "National identity", "Honor", "Kingship"],
    country: "England",
  },
  {
    id: "history-of-the-peloponnesian-war",
    title: "History of the Peloponnesian War",
    author: "Thucydides",
    year: -411,
    tradition: "Ancient Greek",
    era: "Ancient",
    genres: ["History", "Political Writing"],
    difficulty: "Scholar",
    synopsis: "Thucydides chronicles the devastating war between Athens and Sparta with rigorous analysis and unflinching realism, creating the foundational text of political history and international relations.",
    themes: ["War", "Power", "Democracy", "Human nature", "Empire"],
    country: "Greece",
    language: "Ancient Greek",
    readingLanguage: "English",
  },
  {
    id: "idylls-of-the-king",
    title: "Idylls of the King",
    author: "Alfred, Lord Tennyson",
    year: 1859,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Poetry", "Epic", "Arthurian Legend"],
    difficulty: "Advanced",
    synopsis: "Tennyson retells the Arthurian legend in a cycle of twelve narrative poems, tracing the rise and fall of Camelot as an allegory of Victorian ideals and their fragility.",
    themes: ["Chivalry", "Idealism", "Betrayal", "Faith", "Decline"],
    country: "England",
  },
  {
    id: "in-search-of-lost-time",
    title: "In Search of Lost Time",
    author: "Marcel Proust",
    year: 1913,
    tradition: "French",
    era: "Modern",
    genres: ["Novel", "Philosophical Fiction", "Autobiographical Fiction"],
    difficulty: "Scholar",
    synopsis: "A narrator recounts his life from childhood to middle age in extraordinary detail, exploring how memory, art, and love create meaning from the relentless passage of time.",
    themes: ["Memory", "Time", "Art", "Love", "Society", "Identity"],
    country: "France",
    language: "French",
    readingLanguage: "English",
  },
  {
    id: "incidents-in-the-life-of-a-slave-girl",
    title: "Incidents in the Life of a Slave Girl",
    author: "Harriet Jacobs",
    year: 1861,
    tradition: "American",
    era: "Victorian",
    genres: ["Autobiography", "Slave Narrative"],
    difficulty: "Intermediate",
    synopsis: "A woman born into slavery recounts her years of hiding in a cramped attic to escape her master's abuse, offering a searing firsthand account of slavery's impact on women and families.",
    themes: ["Slavery", "Female autonomy", "Family", "Resistance", "Freedom"],
    country: "USA",
  },
  {
    id: "jacobs-room",
    title: "Jacob's Room",
    author: "Virginia Woolf",
    year: 1922,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Experimental Fiction"],
    difficulty: "Advanced",
    synopsis: "The life of Jacob Flanders is constructed through the impressions and spaces he inhabits, from childhood to his death in World War I, in a radical experiment in absence and memory.",
    themes: ["Loss", "Memory", "War", "Identity", "Perception"],
    country: "England",
  },
  {
    id: "jude-the-obscure",
    title: "Jude the Obscure",
    author: "Thomas Hardy",
    year: 1895,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Tragedy"],
    difficulty: "Advanced",
    synopsis: "A stonemason's passionate desire for education and love is thwarted at every turn by class barriers, religious convention, and an implacable fate, in Hardy's darkest and most controversial novel.",
    themes: ["Class", "Education", "Marriage", "Religion", "Fate"],
    country: "England",
  },
  {
    id: "kidnapped",
    title: "Kidnapped",
    author: "Robert Louis Stevenson",
    year: 1886,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Adventure", "Historical Fiction"],
    difficulty: "Beginner",
    synopsis: "A young Scotsman is kidnapped by his treacherous uncle and shipwrecked on the Scottish Highlands, where he teams up with a Jacobite fugitive in a rousing tale of loyalty and adventure.",
    themes: ["Adventure", "Loyalty", "Scottish identity", "Justice", "Coming of age"],
    country: "Scotland",
  },
  {
    id: "king-solomons-mines",
    title: "King Solomon's Mines",
    author: "H. Rider Haggard",
    year: 1885,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Adventure", "Novel"],
    difficulty: "Beginner",
    synopsis: "Allan Quatermain leads an expedition into uncharted Africa in search of the legendary diamond mines of King Solomon, encountering peril, tribal warfare, and ancient treasure.",
    themes: ["Adventure", "Exploration", "Greed", "Courage", "Colonialism"],
    country: "England",
  },
  {
    id: "kusamakura",
    title: "Kusamakura",
    author: "Natsume S\u014dseki",
    year: 1906,
    tradition: "Eastern",
    era: "Modern",
    genres: ["Novel", "Philosophical Fiction"],
    difficulty: "Advanced",
    synopsis: "An artist retreats to a mountain hot spring to pursue pure aesthetic experience detached from emotion, but an enigmatic woman disrupts his quest for artistic tranquility.",
    themes: ["Art", "Detachment", "Nature", "Beauty", "East vs. West"],
    country: "Japan",
    language: "Japanese",
    readingLanguage: "English",
  },
  {
    id: "lady-chatterleys-lover",
    title: "Lady Chatterley's Lover",
    author: "D. H. Lawrence",
    year: 1928,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel"],
    difficulty: "Intermediate",
    synopsis: "A young aristocratic woman, trapped in a loveless marriage to a paralyzed husband, finds passionate fulfillment with the estate's gamekeeper, defying class boundaries and sexual repression.",
    themes: ["Sexuality", "Class", "Industrialization", "Vitality", "Freedom"],
    country: "England",
  },
  {
    id: "leviathan",
    title: "Leviathan",
    author: "Thomas Hobbes",
    year: 1651,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Political Theory", "Philosophy"],
    difficulty: "Scholar",
    synopsis: "Hobbes argues that the natural state of humanity is a war of all against all, and that peace requires surrendering freedom to an absolute sovereign — the great Leviathan of the state.",
    themes: ["Social contract", "Sovereignty", "Power", "Human nature", "Order"],
    country: "England",
  },
  {
    id: "looking-backward",
    title: "Looking Backward",
    author: "Edward Bellamy",
    year: 1888,
    tradition: "American",
    era: "Victorian",
    genres: ["Novel", "Utopian Fiction", "Science Fiction"],
    difficulty: "Intermediate",
    synopsis: "A Bostonian falls asleep in 1887 and wakes in the year 2000 to find America transformed into a peaceful socialist utopia, forcing a reckoning with the inequities of his own age.",
    themes: ["Utopia", "Social reform", "Inequality", "Progress", "Capitalism"],
    country: "USA",
  },
  {
    id: "lyrical-ballads",
    title: "Lyrical Ballads",
    author: "William Wordsworth",
    year: 1798,
    tradition: "Romantic",
    era: "Romantic",
    genres: ["Poetry"],
    difficulty: "Intermediate",
    synopsis: "Wordsworth and Coleridge's revolutionary collection rejects the artificial diction of the 18th century, finding poetry in common speech and the lives of humble people close to nature.",
    themes: ["Nature", "Common life", "Imagination", "Memory", "The supernatural"],
    country: "England",
  },
  {
    id: "manhattan-transfer",
    title: "Manhattan Transfer",
    author: "John Dos Passos",
    year: 1925,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Experimental Fiction"],
    difficulty: "Advanced",
    synopsis: "A kaleidoscopic portrait of New York City follows dozens of characters — immigrants, socialites, bootleggers, actors — as their lives intersect in the pulsing chaos of the modern metropolis.",
    themes: ["Urbanization", "Ambition", "Alienation", "Modernity", "American Dream"],
    country: "USA",
  },
  {
    id: "mcteague",
    title: "McTeague",
    author: "Frank Norris",
    year: 1899,
    tradition: "American",
    era: "Victorian",
    genres: ["Novel", "Naturalism"],
    difficulty: "Intermediate",
    synopsis: "A dim-witted San Francisco dentist's life unravels when greed, jealousy, and a lottery win destroy his marriage and drive him to murder and flight across Death Valley.",
    themes: ["Greed", "Determinism", "Violence", "Class", "Fate"],
    country: "USA",
  },
  {
    id: "measure-for-measure",
    title: "Measure for Measure",
    author: "William Shakespeare",
    year: 1604,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["Drama", "Comedy", "Problem Play"],
    difficulty: "Intermediate",
    synopsis: "A hypocritical deputy demands a novice nun surrender her virtue to save her brother's life, but the disguised Duke watches and orchestrates a complex web of justice and mercy.",
    themes: ["Justice", "Mercy", "Hypocrisy", "Power", "Morality"],
    country: "England",
  },
  {
    id: "moll-flanders",
    title: "Moll Flanders",
    author: "Daniel Defoe",
    year: 1722,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Novel", "Picaresque"],
    difficulty: "Intermediate",
    synopsis: "Born in Newgate Prison, Moll Flanders survives through five husbands, countless lovers, and a career as a thief before finding repentance and prosperity in the New World.",
    themes: ["Survival", "Crime", "Social mobility", "Gender", "Morality"],
    country: "England",
  },
  {
    id: "new-hampshire",
    title: "New Hampshire",
    author: "Robert Frost",
    year: 1923,
    tradition: "American",
    era: "Modern",
    genres: ["Poetry"],
    difficulty: "Intermediate",
    synopsis: "Frost's Pulitzer Prize-winning collection captures the landscapes and people of rural New England in deceptively simple verse that probes the darkest truths of human experience.",
    themes: ["Nature", "Rural life", "Isolation", "Choice", "Mortality"],
    country: "USA",
  },
  {
    id: "night-and-day",
    title: "Night and Day",
    author: "Virginia Woolf",
    year: 1919,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Romance"],
    difficulty: "Intermediate",
    synopsis: "Two young women in Edwardian London navigate the competing claims of love, intellectual ambition, and social expectation in Woolf's most conventional yet quietly subversive novel.",
    themes: ["Love", "Intellect", "Gender", "Social convention", "Modernity"],
    country: "England",
  },
  {
    id: "notre-dame-de-paris",
    title: "Notre-Dame de Paris",
    author: "Victor Hugo",
    year: 1831,
    tradition: "French",
    era: "Romantic",
    genres: ["Novel", "Historical Fiction", "Gothic"],
    difficulty: "Advanced",
    synopsis: "The hunchback bell-ringer Quasimodo, the beautiful gypsy Esmeralda, and the tormented archdeacon Frollo are caught in a web of obsession and cruelty in the shadow of medieval Paris's great cathedral.",
    themes: ["Obsession", "Beauty", "Cruelty", "Sanctuary", "Fate"],
    country: "France",
    language: "French",
    readingLanguage: "English",
  },
  {
    id: "of-human-bondage",
    title: "Of Human Bondage",
    author: "W. Somerset Maugham",
    year: 1915,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Bildungsroman"],
    difficulty: "Intermediate",
    synopsis: "A sensitive, club-footed orphan struggles through failed vocations, destructive love, and poverty before finding meaning in the ordinary pattern of a well-lived life.",
    themes: ["Freedom", "Obsession", "Art", "Self-discovery", "Suffering"],
    country: "England",
  },
  {
    id: "on-liberty",
    title: "On Liberty",
    author: "John Stuart Mill",
    year: 1859,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Philosophy", "Political Theory"],
    difficulty: "Advanced",
    synopsis: "Mill argues that individual liberty is essential to human flourishing and must be protected against both government tyranny and the stifling pressure of majority opinion.",
    themes: ["Liberty", "Individuality", "Democracy", "Free speech", "Tyranny of the majority"],
    country: "England",
  },
  {
    id: "one-of-ours",
    title: "One of Ours",
    author: "Willa Cather",
    year: 1922,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "War Fiction"],
    difficulty: "Intermediate",
    synopsis: "A restless young Nebraskan farmer finds unexpected purpose and fulfillment as a soldier in World War I France, though the glory he discovers is shadowed by the war's terrible cost.",
    themes: ["Purpose", "War", "Idealism", "Rural America", "Sacrifice"],
    country: "USA",
  },
  {
    id: "orlando",
    title: "Orlando: A Biography",
    author: "Virginia Woolf",
    year: 1928,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Fantasy", "Satire"],
    difficulty: "Advanced",
    synopsis: "A young Elizabethan nobleman lives for four centuries, changing sex along the way, in a dazzling romp through English literary history and a love letter to Vita Sackville-West.",
    themes: ["Gender", "Time", "Identity", "Literature", "Freedom"],
    country: "England",
  },
  {
    id: "point-counter-point",
    title: "Point Counter Point",
    author: "Aldous Huxley",
    year: 1928,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Satire"],
    difficulty: "Advanced",
    synopsis: "A large cast of intellectuals, artists, and socialites in 1920s London debate philosophy, science, and love in an intricate polyphonic novel that counterpoints ideas as music counterpoints melodies.",
    themes: ["Intellectualism", "Desire", "Art", "Science", "Disillusionment"],
    country: "England",
  },
  {
    id: "pragmatism",
    title: "Pragmatism",
    author: "William James",
    year: 1907,
    tradition: "American",
    era: "Modern",
    genres: ["Philosophy"],
    difficulty: "Advanced",
    synopsis: "James proposes that the truth of an idea lies in its practical consequences, offering pragmatism as a method for settling metaphysical disputes and reconciling science with religion.",
    themes: ["Truth", "Experience", "Pluralism", "Philosophy", "Practicality"],
    country: "USA",
  },
  {
    id: "puddnhead-wilson",
    title: "Pudd'nhead Wilson",
    author: "Mark Twain",
    year: 1894,
    tradition: "American",
    era: "Victorian",
    genres: ["Novel", "Satire", "Mystery"],
    difficulty: "Intermediate",
    synopsis: "When a slave mother switches her light-skinned infant with her master's son, the deception holds for decades until a fingerprinting detective unravels the truth in a small Missouri town.",
    themes: ["Race", "Identity", "Nature vs. nurture", "Justice", "Social criticism"],
    country: "USA",
  },
  {
    id: "pygmalion",
    title: "Pygmalion",
    author: "George Bernard Shaw",
    year: 1913,
    tradition: "Victorian",
    era: "Modern",
    genres: ["Comedy", "Drama"],
    difficulty: "Beginner",
    synopsis: "A linguistics professor bets he can transform a Cockney flower girl into a lady who can pass in high society, but his creation proves far more independent than he anticipated.",
    themes: ["Class", "Language", "Identity", "Gender", "Education"],
    country: "Ireland",
  },
  {
    id: "quicksand",
    title: "Quicksand",
    author: "Nella Larsen",
    year: 1928,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel"],
    difficulty: "Intermediate",
    synopsis: "A mixed-race woman drifts between Black and white worlds in America and Denmark, seeking a place where she belongs but finding suffocation and disillusionment at every turn.",
    themes: ["Race", "Identity", "Gender", "Alienation", "Sexuality"],
    country: "USA",
  },
  {
    id: "red-harvest",
    title: "Red Harvest",
    author: "Dashiell Hammett",
    year: 1929,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Hard-Boiled Detective Fiction"],
    difficulty: "Intermediate",
    synopsis: "A nameless detective arrives in a corrupt Western mining town and plays its warring factions against each other in an escalating bloodbath that leaves the city cleansed but the detective morally stained.",
    themes: ["Corruption", "Violence", "Justice", "Moral ambiguity", "Power"],
    country: "USA",
  },
  {
    id: "richard-ii",
    title: "Richard II",
    author: "William Shakespeare",
    year: 1595,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["History Play", "Drama", "Tragedy"],
    difficulty: "Intermediate",
    synopsis: "A poetic but incompetent king loses his throne to the ruthlessly practical Bolingbroke, discovering the hollow ceremony of kingship only when the crown is torn away.",
    themes: ["Kingship", "Legitimacy", "Language", "Power", "Identity"],
    country: "England",
  },
  {
    id: "richard-iii",
    title: "Richard III",
    author: "William Shakespeare",
    year: 1593,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["History Play", "Drama", "Tragedy"],
    difficulty: "Intermediate",
    synopsis: "The deformed and brilliant Richard of Gloucester schemes, murders, and seduces his way to the English throne, only to find that the crown brings nightmares instead of peace.",
    themes: ["Villainy", "Ambition", "Power", "Deception", "Conscience"],
    country: "England",
  },
  {
    id: "salammbo",
    title: "Salammb\u00f4",
    author: "Gustave Flaubert",
    year: 1862,
    tradition: "French",
    era: "Victorian",
    genres: ["Novel", "Historical Fiction"],
    difficulty: "Advanced",
    synopsis: "In ancient Carthage, a priestess and a mercenary leader are drawn together by passion amid a brutal war between the city and its revolting mercenary armies.",
    themes: ["War", "Desire", "Religion", "Power", "Destruction"],
    country: "France",
    language: "French",
    readingLanguage: "English",
  },
  {
    id: "six-characters-in-search-of-an-author",
    title: "Six Characters in Search of an Author",
    author: "Luigi Pirandello",
    year: 1921,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Drama", "Metafiction"],
    difficulty: "Advanced",
    synopsis: "Six fictional characters invade a theater rehearsal demanding that their unfinished story be staged, blurring the boundaries between art and life, illusion and reality.",
    themes: ["Reality vs. illusion", "Identity", "Art", "Truth", "Theater"],
    country: "Italy",
    language: "Italian",
    readingLanguage: "English",
  },
  {
    id: "so-big",
    title: "So Big",
    author: "Edna Ferber",
    year: 1924,
    tradition: "American",
    era: "Modern",
    genres: ["Novel"],
    difficulty: "Intermediate",
    synopsis: "A spirited woman raises her son on a struggling Illinois farm, valuing beauty and effort over money, but watches him choose material success over the artistic life she championed.",
    themes: ["Ambition", "Motherhood", "Art vs. materialism", "Resilience", "American values"],
    country: "USA",
  },
  {
    id: "steppenwolf",
    title: "Steppenwolf",
    author: "Hermann Hesse",
    year: 1927,
    tradition: "Germanic",
    era: "Modern",
    genres: ["Novel", "Philosophical Fiction"],
    difficulty: "Advanced",
    synopsis: "A middle-aged intellectual torn between his human and wolfish natures descends into a surreal nightlife underworld where jazz, dance, and a magic theater challenge his rigid self-understanding.",
    themes: ["Duality", "Alienation", "Art", "Madness", "Self-discovery"],
    country: "Germany",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "the-ambassadors",
    title: "The Ambassadors",
    author: "Henry James",
    year: 1903,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Psychological Fiction"],
    difficulty: "Advanced",
    synopsis: "A middle-aged American is sent to Paris to retrieve a young man from the clutches of a supposedly wicked woman, but finds that Europe transforms his own narrow convictions instead.",
    themes: ["Perception", "Europe vs. America", "Morality", "Experience", "Freedom"],
    country: "USA",
  },
  {
    id: "the-autobiography-of-an-ex-colored-man",
    title: "The Autobiography of an Ex-Colored Man",
    author: "James Weldon Johnson",
    year: 1912,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Autobiographical Fiction"],
    difficulty: "Intermediate",
    synopsis: "A light-skinned Black man navigates both sides of the color line in turn-of-the-century America, ultimately choosing to pass as white and sacrificing his cultural heritage for safety and prosperity.",
    themes: ["Race", "Passing", "Identity", "Music", "American society"],
    country: "USA",
  },
  {
    id: "the-charterhouse-of-parma",
    title: "The Charterhouse of Parma",
    author: "Stendhal",
    year: 1839,
    tradition: "French",
    era: "Romantic",
    genres: ["Novel", "Historical Fiction", "Political Fiction"],
    difficulty: "Advanced",
    synopsis: "A young Italian nobleman stumbles through Waterloo and the intrigues of a petty Italian court, driven by love, ambition, and an irrepressible zest for life.",
    themes: ["Love", "Ambition", "Politics", "Freedom", "Italian society"],
    country: "France",
    language: "French",
    readingLanguage: "English",
  },
  {
    id: "the-communist-manifesto",
    title: "The Communist Manifesto",
    author: "Karl Marx",
    year: 1848,
    tradition: "Germanic",
    era: "Victorian",
    genres: ["Political Theory", "Philosophy"],
    difficulty: "Intermediate",
    synopsis: "Marx and Engels declare that the history of all society is the history of class struggles, calling on the workers of the world to unite and overthrow the bourgeois order.",
    themes: ["Class struggle", "Revolution", "Capitalism", "Labor", "History"],
    country: "Germany",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "the-economic-consequences-of-the-peace",
    title: "The Economic Consequences of the Peace",
    author: "John Maynard Keynes",
    year: 1919,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Economics", "Political Writing"],
    difficulty: "Advanced",
    synopsis: "Keynes argues that the punitive reparations imposed on Germany at Versailles will destroy the European economy and sow the seeds of future conflict, in a prescient and devastating critique.",
    themes: ["Economics", "War", "Justice", "Diplomacy", "Consequence"],
    country: "England",
  },
  {
    id: "the-faerie-queene",
    title: "The Faerie Queene",
    author: "Edmund Spenser",
    year: 1590,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["Epic Poetry", "Allegory"],
    difficulty: "Scholar",
    synopsis: "Knights undertake quests representing virtues such as holiness, temperance, and justice in a vast allegorical romance celebrating Elizabethan ideals and the glory of the Protestant English state.",
    themes: ["Virtue", "Chivalry", "Allegory", "Good vs. evil", "Elizabeth I"],
    country: "England",
  },
  {
    id: "the-federalist-papers",
    title: "The Federalist Papers",
    author: "Alexander Hamilton",
    year: 1788,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Political Theory", "Essays"],
    difficulty: "Advanced",
    synopsis: "Hamilton, Madison, and Jay make the case for ratifying the new U.S. Constitution in eighty-five essays that remain the definitive commentary on American constitutional government.",
    themes: ["Democracy", "Federalism", "Liberty", "Government", "Constitutional law"],
    country: "USA",
  },
  {
    id: "the-forsyte-saga",
    title: "The Forsyte Saga",
    author: "John Galsworthy",
    year: 1922,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Family Saga"],
    difficulty: "Intermediate",
    synopsis: "Three generations of the property-obsessed Forsyte family navigate love, possession, and social change from Victorian England to the 1920s, as the world they built slowly crumbles around them.",
    themes: ["Property", "Family", "Social change", "Love", "Possession"],
    country: "England",
  },
  {
    id: "the-gambler",
    title: "The Gambler",
    author: "Fyodor Dostoevsky",
    year: 1867,
    tradition: "Russian",
    era: "Victorian",
    genres: ["Novel", "Psychological Fiction"],
    difficulty: "Intermediate",
    synopsis: "A young tutor in the employ of a Russian general becomes consumed by the roulette tables of a fictional German spa town, mirroring the addictive passions that rule all the characters' lives.",
    themes: ["Gambling", "Obsession", "Love", "Money", "Self-destruction"],
    country: "Russia",
    language: "Russian",
    readingLanguage: "English",
  },
  {
    id: "the-genealogy-of-morals",
    title: "The Genealogy of Morals",
    author: "Friedrich Nietzsche",
    year: 1887,
    tradition: "Germanic",
    era: "Victorian",
    genres: ["Philosophy"],
    difficulty: "Scholar",
    synopsis: "Nietzsche traces the origins of moral concepts like 'good,' 'evil,' and 'guilt' to their roots in power, resentment, and ascetic ideals, overturning conventional assumptions about ethics.",
    themes: ["Morality", "Power", "Resentment", "Asceticism", "History of values"],
    country: "Germany",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "the-golden-bowl",
    title: "The Golden Bowl",
    author: "Henry James",
    year: 1904,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Psychological Fiction"],
    difficulty: "Scholar",
    synopsis: "An American heiress and her father marry a pair of former lovers, and the discovery of their ongoing affair is handled with exquisite subtlety in James's most intricate study of consciousness.",
    themes: ["Betrayal", "Perception", "Marriage", "Wealth", "Moral complexity"],
    country: "USA",
  },
  {
    id: "the-hairy-ape",
    title: "The Hairy Ape",
    author: "Eugene O'Neill",
    year: 1922,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Drama", "Expressionism"],
    difficulty: "Intermediate",
    synopsis: "A brutish ship stoker's sense of belonging is shattered when a wealthy woman recoils from him in horror, sending him on a desperate search for identity across the class divide.",
    themes: ["Class", "Identity", "Alienation", "Industrialization", "Belonging"],
    country: "USA",
  },
  {
    id: "the-history-of-the-decline-and-fall-of-the-roman-empire",
    title: "The History of the Decline and Fall of the Roman Empire",
    author: "Edward Gibbon",
    year: 1776,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["History"],
    difficulty: "Scholar",
    synopsis: "Gibbon's monumental history traces the fall of Rome from the age of the Antonines to the fall of Constantinople, blaming Christianity and barbarism for the destruction of classical civilization.",
    themes: ["Decline", "Empire", "Religion", "Civilization", "Power"],
    country: "England",
  },
  {
    id: "the-history-of-tom-jones-a-foundling",
    title: "The History of Tom Jones, a Foundling",
    author: "Henry Fielding",
    year: 1749,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Novel", "Picaresque", "Comedy"],
    difficulty: "Advanced",
    synopsis: "A good-hearted but impulsive foundling is cast out of his benefactor's home and pursues his beloved Sophia Western across England in a rollicking, digressive masterpiece of comic fiction.",
    themes: ["Virtue", "Hypocrisy", "Love", "Fortune", "Social class"],
    country: "England",
  },
  {
    id: "the-inferno",
    title: "The Inferno",
    author: "August Strindberg",
    year: 1897,
    tradition: "Scandinavian",
    era: "Victorian",
    genres: ["Autobiography", "Psychological Fiction"],
    difficulty: "Advanced",
    synopsis: "Strindberg recounts a period of mental crisis, occult obsession, and paranoid hallucination in Paris, transforming his breakdown into a harrowing literary journey through personal hell.",
    themes: ["Madness", "Guilt", "Occultism", "Isolation", "Self-destruction"],
    country: "Sweden",
    language: "Swedish",
    readingLanguage: "English",
  },
  {
    id: "the-jungle",
    title: "The Jungle",
    author: "Upton Sinclair",
    year: 1906,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Social Criticism", "Muckraking"],
    difficulty: "Intermediate",
    synopsis: "A Lithuanian immigrant family is ground down by the horrors of Chicago's meatpacking industry, exposing the brutal exploitation of workers and the corruption of the American food supply.",
    themes: ["Labor", "Immigration", "Corruption", "Capitalism", "Survival"],
    country: "USA",
  },
  {
    id: "the-kalevala",
    title: "The Kalevala",
    author: "Elias L\u00f6nnrot",
    year: 1835,
    tradition: "Scandinavian",
    era: "Romantic",
    genres: ["Epic Poetry", "Mythology"],
    difficulty: "Advanced",
    synopsis: "Finland's national epic weaves together myths of creation, magic, heroic quests, and the forging of the mystical Sampo in a tapestry of pre-Christian Finnic folklore.",
    themes: ["Creation", "Magic", "Heroism", "Nature", "Finnish identity"],
    country: "Finland",
    language: "Finnish",
    readingLanguage: "English",
  },
  {
    id: "the-kingdom-of-god-is-within-you",
    title: "The Kingdom of God Is Within You",
    author: "Leo Tolstoy",
    year: 1894,
    tradition: "Russian",
    era: "Victorian",
    genres: ["Philosophy", "Religious Writing", "Political Theory"],
    difficulty: "Advanced",
    synopsis: "Tolstoy argues that true Christianity demands nonviolent resistance to evil and the rejection of all state authority, in a work that profoundly influenced Gandhi and Martin Luther King Jr.",
    themes: ["Nonviolence", "Christianity", "State authority", "Conscience", "Pacifism"],
    country: "Russia",
    language: "Russian",
    readingLanguage: "English",
  },
  {
    id: "the-life-and-adventures-of-robinson-crusoe",
    title: "The Life and Adventures of Robinson Crusoe",
    author: "Daniel Defoe",
    year: 1719,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Novel", "Adventure"],
    difficulty: "Beginner",
    synopsis: "Shipwrecked alone on a tropical island, an Englishman builds a life from nothing through ingenuity and determination, creating the archetypal survival story.",
    themes: ["Survival", "Self-reliance", "Civilization", "Providence", "Colonialism"],
    country: "England",
  },
  {
    id: "the-life-and-opinions-of-tristram-shandy-gentleman",
    title: "The Life and Opinions of Tristram Shandy, Gentleman",
    author: "Laurence Sterne",
    year: 1759,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Novel", "Satire", "Experimental Fiction"],
    difficulty: "Advanced",
    synopsis: "The narrator attempts to tell his life story but is perpetually derailed by digressions, opinions, and eccentric family members, in a wildly inventive novel that anticipates literary modernism by two centuries.",
    themes: ["Digression", "Time", "Humor", "Identity", "Storytelling"],
    country: "England",
  },
  {
    id: "the-magnificent-ambersons",
    title: "The Magnificent Ambersons",
    author: "Booth Tarkington",
    year: 1918,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Social Fiction"],
    difficulty: "Intermediate",
    synopsis: "The proud Amberson family's fortune and prestige collapse as the automobile age transforms their Midwestern city, and a spoiled heir's arrogance hastens the family's ruin.",
    themes: ["Decline", "Progress", "Pride", "Social change", "Family"],
    country: "USA",
  },
  {
    id: "the-monk",
    title: "The Monk",
    author: "M. G. Lewis",
    year: 1796,
    tradition: "Romantic",
    era: "Romantic",
    genres: ["Gothic", "Novel", "Horror"],
    difficulty: "Intermediate",
    synopsis: "A pious monk of impeccable reputation is tempted into lust, sorcery, and murder by a demonic seductress, falling from sanctity to damnation in a sensational Gothic tale.",
    themes: ["Temptation", "Hypocrisy", "Religion", "Desire", "Damnation"],
    country: "England",
  },
  {
    id: "the-moon-and-sixpence",
    title: "The Moon and Sixpence",
    author: "W. Somerset Maugham",
    year: 1919,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel"],
    difficulty: "Intermediate",
    synopsis: "Inspired by Gauguin's life, a London stockbroker abandons his family to become a painter, pursuing art with ruthless single-mindedness across Europe and the South Pacific.",
    themes: ["Art", "Obsession", "Freedom", "Sacrifice", "Civilization vs. primitivism"],
    country: "England",
  },
  {
    id: "the-murder-of-roger-ackroyd",
    title: "The Murder of Roger Ackroyd",
    author: "Agatha Christie",
    year: 1926,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Mystery", "Detective Fiction"],
    difficulty: "Beginner",
    synopsis: "Hercule Poirot investigates the murder of a wealthy man in a quiet English village, where the narrator's unreliable account conceals a devastating twist that redefined the mystery genre.",
    themes: ["Deception", "Justice", "Secrets", "Trust", "Narrative reliability"],
    country: "England",
  },
  {
    id: "the-mysteries-of-udolpho",
    title: "The Mysteries of Udolpho",
    author: "Ann Radcliffe",
    year: 1794,
    tradition: "Romantic",
    era: "Romantic",
    genres: ["Gothic", "Novel", "Romance"],
    difficulty: "Advanced",
    synopsis: "A young Frenchwoman is imprisoned in a sinister Italian castle by her villainous guardian, surrounded by seemingly supernatural terrors that test her courage and reason.",
    themes: ["Terror", "Imagination", "Virtue", "The sublime", "Reason vs. superstition"],
    country: "England",
  },
  {
    id: "the-nibelungenlied",
    title: "The Nibelungenlied",
    author: "Anonymous",
    year: 1200,
    tradition: "Medieval European",
    era: "Medieval",
    genres: ["Epic Poetry", "Legend"],
    difficulty: "Advanced",
    synopsis: "The hero Siegfried wins the Burgundian princess Kriemhild, but treachery, murder, and a devastating quest for vengeance destroy an entire civilization in this foundational Germanic epic.",
    themes: ["Honor", "Revenge", "Loyalty", "Fate", "Heroism"],
    country: "Germany",
    language: "Middle High German",
    readingLanguage: "English",
  },
  {
    id: "the-origin-of-species",
    title: "The Origin of Species",
    author: "Charles Darwin",
    year: 1859,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Science", "Natural History"],
    difficulty: "Advanced",
    synopsis: "Darwin presents the theory of evolution by natural selection, arguing that species change over time through the survival of the fittest, revolutionizing our understanding of life on Earth.",
    themes: ["Evolution", "Natural selection", "Adaptation", "Science", "Nature"],
    country: "England",
  },
  {
    id: "the-pickwick-papers",
    title: "The Pickwick Papers",
    author: "Charles Dickens",
    year: 1837,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Comedy", "Picaresque"],
    difficulty: "Intermediate",
    synopsis: "The genial Mr. Pickwick and his fellow club members travel across England, stumbling into comic misadventures, encounters with rogues, and Dickens's first great portrait of English life.",
    themes: ["Humor", "Friendship", "English society", "Justice", "Innocence"],
    country: "England",
  },
  {
    id: "the-pilgrims-progress",
    title: "The Pilgrim's Progress",
    author: "John Bunyan",
    year: 1678,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["Allegory", "Novel", "Religious Writing"],
    difficulty: "Intermediate",
    synopsis: "Christian journeys from the City of Destruction to the Celestial City, overcoming temptations and perils in the most famous allegory of the spiritual life in the English language.",
    themes: ["Faith", "Salvation", "Temptation", "Perseverance", "Spiritual journey"],
    country: "England",
  },
  {
    id: "the-problems-of-philosophy",
    title: "The Problems of Philosophy",
    author: "Bertrand Russell",
    year: 1912,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Philosophy"],
    difficulty: "Intermediate",
    synopsis: "Russell provides a lucid introduction to the central questions of philosophy — the nature of reality, knowledge, and the limits of reason — written for the general reader.",
    themes: ["Knowledge", "Reality", "Skepticism", "Reason", "Appearance vs. reality"],
    country: "England",
  },
  {
    id: "the-prophet",
    title: "The Prophet",
    author: "Khalil Gibran",
    year: 1923,
    tradition: "Eastern",
    era: "Modern",
    genres: ["Poetry", "Philosophy", "Spiritual Writing"],
    difficulty: "Beginner",
    synopsis: "A prophet departing his adopted city offers poetic wisdom on love, work, children, freedom, and death to the people who gather to bid him farewell.",
    themes: ["Love", "Freedom", "Wisdom", "Spirituality", "Human experience"],
    country: "Lebanon",
    language: "English",
  },
  {
    id: "the-red-badge-of-courage",
    title: "The Red Badge of Courage",
    author: "Stephen Crane",
    year: 1895,
    tradition: "American",
    era: "Victorian",
    genres: ["Novel", "War Fiction"],
    difficulty: "Intermediate",
    synopsis: "A young Union soldier in the Civil War flees his first battle in terror, then returns to fight with desperate courage, gaining the 'red badge' of a wound that transforms his understanding of heroism.",
    themes: ["Courage", "Fear", "War", "Manhood", "Illusion"],
    country: "USA",
  },
  {
    id: "the-rights-of-man",
    title: "The Rights of Man",
    author: "Thomas Paine",
    year: 1791,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Political Theory", "Philosophy"],
    difficulty: "Advanced",
    synopsis: "Paine defends the French Revolution against Edmund Burke's criticism, arguing that legitimate government must rest on the natural rights of man and the consent of the governed.",
    themes: ["Rights", "Revolution", "Democracy", "Liberty", "Government"],
    country: "England",
  },
  {
    id: "the-rubaiyat-of-omar-khayyam",
    title: "The Rub\u00e1iy\u00e1t of Omar Khayy\u00e1m",
    author: "Omar Khayy\u00e1m",
    year: 1120,
    tradition: "Eastern",
    era: "Medieval",
    genres: ["Poetry"],
    difficulty: "Beginner",
    synopsis: "In haunting quatrains, the Persian poet-mathematician celebrates wine, love, and the fleeting beauty of life against the vast indifference of the universe.",
    themes: ["Mortality", "Pleasure", "Fate", "Beauty", "Transience"],
    country: "Persia",
    language: "Persian",
    readingLanguage: "English",
  },
  {
    id: "the-school-for-scandal",
    title: "The School for Scandal",
    author: "Richard Brinsley Sheridan",
    year: 1777,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Comedy", "Drama", "Satire"],
    difficulty: "Intermediate",
    synopsis: "A circle of malicious gossips in Georgian London spread scandalous rumors that entangle two brothers, a rich uncle in disguise, and a young wife in a brilliantly crafted comedy of manners.",
    themes: ["Hypocrisy", "Gossip", "Reputation", "Virtue", "Appearance vs. reality"],
    country: "Ireland",
  },
  {
    id: "the-sea-wolf",
    title: "The Sea-Wolf",
    author: "Jack London",
    year: 1904,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Adventure"],
    difficulty: "Intermediate",
    synopsis: "A refined literary critic is rescued from drowning by the brutal Captain Wolf Larsen, forced to serve on his seal-hunting schooner in a clash between civilization and primal force.",
    themes: ["Survival", "Nature vs. civilization", "Power", "Will", "Individuality"],
    country: "USA",
  },
  {
    id: "the-song-of-the-lark",
    title: "The Song of the Lark",
    author: "Willa Cather",
    year: 1915,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Bildungsroman"],
    difficulty: "Intermediate",
    synopsis: "A gifted girl from a small Colorado town fights her way to becoming a great opera singer, sacrificing personal happiness for artistic excellence in a portrait of the artist's demanding vocation.",
    themes: ["Art", "Ambition", "Sacrifice", "Identity", "Pioneer spirit"],
    country: "USA",
  },
  {
    id: "the-sorrows-of-young-werther",
    title: "The Sorrows of Young Werther",
    author: "J. W. von Goethe",
    year: 1774,
    tradition: "Germanic",
    era: "Romantic",
    genres: ["Epistolary Novel", "Sentimental Fiction"],
    difficulty: "Intermediate",
    synopsis: "A sensitive young artist falls hopelessly in love with a woman engaged to another man, and his unrequited passion drives him to a tragic end in the novel that made Goethe famous overnight.",
    themes: ["Unrequited love", "Passion", "Nature", "Alienation", "Suicide"],
    country: "Germany",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "the-story-of-my-experiments-with-truth",
    title: "The Story of My Experiments with Truth",
    author: "Mahatma Gandhi",
    year: 1927,
    tradition: "Eastern",
    era: "Modern",
    genres: ["Autobiography"],
    difficulty: "Intermediate",
    synopsis: "Gandhi recounts his life from childhood through the development of nonviolent resistance, describing his spiritual and political experiments with truth as a way of life.",
    themes: ["Truth", "Nonviolence", "Self-discipline", "Justice", "Spiritual growth"],
    country: "India",
  },
  {
    id: "the-subjection-of-women",
    title: "The Subjection of Women",
    author: "John Stuart Mill",
    year: 1869,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Philosophy", "Feminist Writing", "Political Theory"],
    difficulty: "Advanced",
    synopsis: "Mill argues that the legal and social subordination of women is wrong in principle and a barrier to human improvement, making a systematic case for gender equality.",
    themes: ["Women's rights", "Equality", "Liberty", "Marriage", "Justice"],
    country: "England",
  },
  {
    id: "the-tenant-of-wildfell-hall",
    title: "The Tenant of Wildfell Hall",
    author: "Anne Bront\u00eb",
    year: 1848,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Gothic"],
    difficulty: "Intermediate",
    synopsis: "A mysterious young widow takes refuge in a crumbling mansion with her son, and her secret diary reveals a harrowing marriage to a dissolute husband that she dared to flee.",
    themes: ["Marriage", "Female independence", "Alcoholism", "Courage", "Secrecy"],
    country: "England",
  },
  {
    id: "the-theory-of-moral-sentiments",
    title: "The Theory of Moral Sentiments",
    author: "Adam Smith",
    year: 1759,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Philosophy", "Ethics"],
    difficulty: "Advanced",
    synopsis: "Before writing about economics, Smith explored how human beings develop moral judgment through sympathy and imagination, founding a theory of ethics based on fellow-feeling.",
    themes: ["Sympathy", "Morality", "Justice", "Self-interest", "Social bonds"],
    country: "Scotland",
  },
  {
    id: "the-thirty-nine-steps",
    title: "The Thirty-Nine Steps",
    author: "John Buchan",
    year: 1915,
    tradition: "Victorian",
    era: "Modern",
    genres: ["Thriller", "Adventure", "Spy Fiction"],
    difficulty: "Beginner",
    synopsis: "A bored expatriate is drawn into an international conspiracy after a murdered man leaves him a cryptic message, sending him on a breathless chase across the Scottish Highlands.",
    themes: ["Adventure", "Espionage", "Patriotism", "Disguise", "Pursuit"],
    country: "Scotland",
  },
  {
    id: "the-tragical-history-of-doctor-faustus",
    title: "The Tragical History of Doctor Faustus",
    author: "Christopher Marlowe",
    year: 1592,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["Tragedy", "Drama"],
    difficulty: "Advanced",
    synopsis: "A brilliant scholar sells his soul to the devil in exchange for twenty-four years of unlimited power and knowledge, only to face eternal damnation when his time runs out.",
    themes: ["Ambition", "Damnation", "Knowledge", "Power", "Repentance"],
    country: "England",
  },
  {
    id: "the-voyage-of-the-beagle",
    title: "The Voyage of the Beagle",
    author: "Charles Darwin",
    year: 1839,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Travel Writing", "Natural History", "Science"],
    difficulty: "Intermediate",
    synopsis: "Darwin's journal of his five-year voyage around the world aboard HMS Beagle records the observations of geology, botany, and zoology that would lead to the theory of evolution.",
    themes: ["Exploration", "Nature", "Science", "Discovery", "Observation"],
    country: "England",
  },
  {
    id: "the-voyage-out",
    title: "The Voyage Out",
    author: "Virginia Woolf",
    year: 1915,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel"],
    difficulty: "Advanced",
    synopsis: "A sheltered young Englishwoman voyages to South America, awakening to love, art, and ideas among a group of fellow travelers, only to meet an unexpected and devastating end.",
    themes: ["Coming of age", "Love", "Death", "Colonialism", "Female identity"],
    country: "England",
  },
  {
    id: "the-way-of-all-flesh",
    title: "The Way of All Flesh",
    author: "Samuel Butler",
    year: 1903,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Satire", "Autobiographical Fiction"],
    difficulty: "Intermediate",
    synopsis: "Four generations of a clergyman's family are blighted by oppressive religiosity and parental tyranny, until the youngest breaks free to find his own path in a blistering attack on Victorian values.",
    themes: ["Family", "Religion", "Rebellion", "Hypocrisy", "Self-discovery"],
    country: "England",
  },
  {
    id: "the-way-we-live-now",
    title: "The Way We Live Now",
    author: "Anthony Trollope",
    year: 1875,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Satire", "Social Criticism"],
    difficulty: "Advanced",
    synopsis: "A mysterious foreign financier takes London by storm, and his speculative bubble draws in aristocrats, politicians, and social climbers in Trollope's fiercest satire of Victorian corruption.",
    themes: ["Corruption", "Greed", "Social climbing", "Deception", "Money"],
    country: "England",
  },
  {
    id: "the-well-of-loneliness",
    title: "The Well of Loneliness",
    author: "Radclyffe Hall",
    year: 1928,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel"],
    difficulty: "Intermediate",
    synopsis: "An upper-class Englishwoman comes to terms with her identity as a 'sexual invert,' facing rejection and isolation in a groundbreaking novel that pleaded for understanding of same-sex love.",
    themes: ["Identity", "Sexuality", "Isolation", "Social rejection", "Love"],
    country: "England",
  },
  {
    id: "the-wings-of-the-dove",
    title: "The Wings of the Dove",
    author: "Henry James",
    year: 1902,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Psychological Fiction"],
    difficulty: "Scholar",
    synopsis: "A penniless young woman conspires with her lover to marry a dying American heiress for her fortune, but the heiress's generosity transforms their scheme into something far more complex.",
    themes: ["Greed", "Love", "Morality", "Wealth", "Sacrifice"],
    country: "USA",
  },
  {
    id: "the-winters-tale",
    title: "The Winter's Tale",
    author: "William Shakespeare",
    year: 1611,
    tradition: "Renaissance",
    era: "Renaissance",
    genres: ["Romance", "Drama", "Tragicomedy"],
    difficulty: "Intermediate",
    synopsis: "A king's irrational jealousy destroys his family, but after sixteen years of grief, a series of miraculous reunions proves that time and repentance can heal even the deepest wounds.",
    themes: ["Jealousy", "Redemption", "Time", "Forgiveness", "Renewal"],
    country: "England",
  },
  {
    id: "the-woodlanders",
    title: "The Woodlanders",
    author: "Thomas Hardy",
    year: 1887,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Pastoral", "Tragedy"],
    difficulty: "Intermediate",
    synopsis: "In a secluded Dorset woodland, a timber merchant's daughter is torn between a faithful local suitor and a worldly doctor, as Hardy explores how class and ambition destroy simple lives.",
    themes: ["Nature", "Class", "Love", "Fate", "Rural life"],
    country: "England",
  },
  {
    id: "three-lives",
    title: "Three Lives",
    author: "Gertrude Stein",
    year: 1909,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Experimental Fiction"],
    difficulty: "Advanced",
    synopsis: "Three novellas portray the inner lives of working-class women in Baltimore — a German servant, a Black woman, and another servant — in Stein's revolutionary, repetitive prose style.",
    themes: ["Identity", "Race", "Class", "Language", "Female experience"],
    country: "USA",
  },
  {
    id: "three-sisters",
    title: "Three Sisters",
    author: "Anton Chekhov",
    year: 1901,
    tradition: "Russian",
    era: "Modern",
    genres: ["Drama", "Tragedy"],
    difficulty: "Intermediate",
    synopsis: "Three sisters stranded in a provincial Russian garrison town yearn to return to Moscow, but their dreams slowly erode under the weight of disappointment, routine, and the passage of time.",
    themes: ["Longing", "Disillusionment", "Time", "Provincial life", "Hope"],
    country: "Russia",
    language: "Russian",
    readingLanguage: "English",
  },
  {
    id: "thus-spake-zarathustra",
    title: "Thus Spake Zarathustra",
    author: "Friedrich Nietzsche",
    year: 1885,
    tradition: "Germanic",
    era: "Victorian",
    genres: ["Philosophy", "Prose Poetry"],
    difficulty: "Scholar",
    synopsis: "The prophet Zarathustra descends from his mountain solitude to teach humanity about the Overman, the death of God, and the eternal recurrence, in Nietzsche's most ambitious and poetic work.",
    themes: ["Overman", "Eternal recurrence", "Will to power", "God's death", "Self-overcoming"],
    country: "Germany",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "tractatus-logico-philosophicus",
    title: "Tractatus Logico-Philosophicus",
    author: "Ludwig Wittgenstein",
    year: 1921,
    tradition: "Germanic",
    era: "Modern",
    genres: ["Philosophy", "Logic"],
    difficulty: "Scholar",
    synopsis: "In a series of numbered propositions, Wittgenstein attempts to show the limits of language and thought, concluding that what cannot be said must be passed over in silence.",
    themes: ["Language", "Logic", "Meaning", "Limits of thought", "Silence"],
    country: "Austria",
    language: "German",
    readingLanguage: "English",
  },
  {
    id: "two-treatises-of-government",
    title: "Two Treatises of Government",
    author: "John Locke",
    year: 1689,
    tradition: "Enlightenment",
    era: "Enlightenment",
    genres: ["Political Theory", "Philosophy"],
    difficulty: "Advanced",
    synopsis: "Locke refutes the divine right of kings and argues that government derives its authority from the consent of the governed, who retain the right to revolution when their trust is betrayed.",
    themes: ["Natural rights", "Government", "Liberty", "Property", "Social contract"],
    country: "England",
  },
  {
    id: "typee",
    title: "Typee",
    author: "Herman Melville",
    year: 1846,
    tradition: "American",
    era: "Romantic",
    genres: ["Novel", "Adventure", "Travel Writing"],
    difficulty: "Intermediate",
    synopsis: "A sailor jumps ship in the Marquesas Islands and lives among a tribe of supposed cannibals, finding both paradise and menace in a narrative that questions civilization's superiority.",
    themes: ["Civilization vs. nature", "Adventure", "Cultural encounter", "Freedom", "Colonialism"],
    country: "USA",
  },
  {
    id: "villette",
    title: "Villette",
    author: "Charlotte Bront\u00eb",
    year: 1853,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Autobiographical Fiction"],
    difficulty: "Advanced",
    synopsis: "A lonely Englishwoman takes a teaching position in a Belgian boarding school, where she battles solitude, unrequited love, and her own passionate nature in Bront\u00eb's most psychologically complex novel.",
    themes: ["Loneliness", "Love", "Independence", "Identity", "Religious conflict"],
    country: "England",
  },
  {
    id: "washington-square",
    title: "Washington Square",
    author: "Henry James",
    year: 1880,
    tradition: "Victorian",
    era: "Victorian",
    genres: ["Novel", "Psychological Fiction"],
    difficulty: "Intermediate",
    synopsis: "A plain, wealthy young woman is courted by a charming fortune hunter, and her tyrannical father's opposition forces her to discover her own quiet strength.",
    themes: ["Love", "Money", "Parental authority", "Independence", "Betrayal"],
    country: "USA",
  },
  {
    id: "we",
    title: "We",
    author: "Yevgeny Zamyatin",
    year: 1924,
    tradition: "Russian",
    era: "Modern",
    genres: ["Novel", "Dystopian Fiction", "Science Fiction"],
    difficulty: "Intermediate",
    synopsis: "In a future totalitarian state of glass walls and regimented lives, a rocket engineer begins an illicit love affair that awakens his imagination and threatens the entire social order.",
    themes: ["Totalitarianism", "Freedom", "Individuality", "Love", "Surveillance"],
    country: "Russia",
    language: "Russian",
    readingLanguage: "English",
  },
  {
    id: "where-angels-fear-to-tread",
    title: "Where Angels Fear to Tread",
    author: "E. M. Forster",
    year: 1905,
    tradition: "Modernist",
    era: "Modern",
    genres: ["Novel", "Comedy of Manners"],
    difficulty: "Intermediate",
    synopsis: "A young English widow's impulsive marriage to an Italian causes a family crisis, and the disastrous rescue mission that follows exposes English snobbery and Italian passion in equal measure.",
    themes: ["Culture clash", "Snobbery", "Passion", "Tragedy", "Italy vs. England"],
    country: "England",
  },
  {
    id: "white-fang",
    title: "White Fang",
    author: "Jack London",
    year: 1906,
    tradition: "American",
    era: "Modern",
    genres: ["Novel", "Adventure"],
    difficulty: "Beginner",
    synopsis: "A wild wolf-dog hybrid survives the brutal Yukon wilderness and the cruelty of men before being tamed by kindness, in a companion piece to The Call of the Wild.",
    themes: ["Nature vs. civilization", "Survival", "Domestication", "Cruelty vs. kindness", "Instinct"],
    country: "USA",
  },
];

// ── Main ───────────────────────────────────────────────────────────────────────

function main() {
  // Read existing files
  let booksContent = fs.readFileSync(BOOKS_FILE, "utf-8");
  let chaptersContent = fs.readFileSync(CHAPTERS_FILE, "utf-8");

  // Extract existing book IDs from books.ts
  const existingBookIds = new Set<string>();
  const bookIdRegex = /id:\s*"([^"]+)"/g;
  let match: RegExpExecArray | null;
  while ((match = bookIdRegex.exec(booksContent)) !== null) {
    existingBookIds.add(match[1]);
  }

  // Extract existing chapter IDs from chapters.ts
  const existingChapterIds = new Set<string>();
  const chapterIdRegex = /id:\s*"([^"]+)"/g;
  while ((match = chapterIdRegex.exec(chaptersContent)) !== null) {
    existingChapterIds.add(match[1]);
  }

  console.log(`Found ${existingBookIds.size} existing books in books.ts`);
  console.log(`Found ${existingChapterIds.size} existing chapters in chapters.ts`);

  let booksAdded = 0;
  let chaptersAdded = 0;
  let booksSkipped = 0;

  const newBookEntries: string[] = [];
  const newChapterEntries: string[] = [];

  for (const config of BOOK_CONFIGS) {
    // Skip if book already exists
    if (existingBookIds.has(config.id)) {
      console.log(`  SKIP: ${config.id} (already exists)`);
      booksSkipped++;
      continue;
    }

    // Read meta.json for chapter data
    const metaPath = path.join(CONTENT_DIR, config.id, "meta.json");
    if (!fs.existsSync(metaPath)) {
      console.log(`  SKIP: ${config.id} (no meta.json found at ${metaPath})`);
      booksSkipped++;
      continue;
    }

    const meta: MetaJson = JSON.parse(fs.readFileSync(metaPath, "utf-8"));

    // Get cover colors from tradition
    const colors = TRADITION_COLORS[config.tradition] || TRADITION_COLORS["Victorian"];

    // Build book entry
    const authorId = toAuthorId(config.author);
    const readingTime = formatReadingTime(meta.totalMinutes);

    let bookEntry = `  {\n`;
    bookEntry += `    id: "${config.id}",\n`;
    bookEntry += `    title: "${config.title.replace(/"/g, '\\"')}",\n`;
    bookEntry += `    author: "${config.author.replace(/"/g, '\\"')}",\n`;
    bookEntry += `    authorId: "${authorId}",\n`;
    bookEntry += `    year: ${config.year},\n`;
    if (config.language) {
      bookEntry += `    language: "${config.language}",\n`;
    }
    if (config.readingLanguage) {
      bookEntry += `    readingLanguage: "${config.readingLanguage}",\n`;
    }
    bookEntry += `    tradition: "${config.tradition}",\n`;
    bookEntry += `    era: "${config.era}",\n`;
    bookEntry += `    genres: [${config.genres.map(g => `"${g}"`).join(", ")}],\n`;
    bookEntry += `    difficulty: "${config.difficulty}",\n`;
    bookEntry += `    chapters: ${meta.chapterCount},\n`;
    bookEntry += `    estimatedReadingTime: "${readingTime}",\n`;
    bookEntry += `    wordCount: ${meta.totalWordCount},\n`;
    bookEntry += `    synopsis: "${config.synopsis.replace(/"/g, '\\"')}",\n`;
    bookEntry += `    themes: [${config.themes.map(t => `"${t}"`).join(", ")}],\n`;
    bookEntry += `    country: "${config.country}",\n`;
    bookEntry += `    coverColors: { primary: "${colors.primary}", secondary: "${colors.secondary}", accent: "${colors.accent}" },\n`;
    bookEntry += `    featured: false,\n`;
    bookEntry += `    source: "standard-ebooks",\n`;
    bookEntry += `  }`;

    newBookEntries.push(bookEntry);
    booksAdded++;

    // Build chapter entries
    for (const ch of meta.chapters) {
      const chapterId = `${config.id}-ch-${ch.index}`;
      if (existingChapterIds.has(chapterId)) {
        continue;
      }

      let chapterEntry = `  {\n`;
      chapterEntry += `    id: "${chapterId}",\n`;
      chapterEntry += `    bookId: "${config.id}",\n`;
      chapterEntry += `    number: ${ch.index},\n`;
      chapterEntry += `    title: "${ch.title.replace(/"/g, '\\"')}",\n`;
      chapterEntry += `    wordCount: ${ch.wordCount},\n`;
      chapterEntry += `    estimatedMinutes: ${ch.estimatedMinutes},\n`;
      chapterEntry += `    summary: "",\n`;
      chapterEntry += `    quizAvailable: false,\n`;
      chapterEntry += `  }`;

      newChapterEntries.push(chapterEntry);
      chaptersAdded++;
    }
  }

  // Append new book entries before the final `];`
  if (newBookEntries.length > 0) {
    const booksInsert = "\n\n  // ── CANONICAL ADDITIONS BATCH 2 (auto-generated) ──────────────────────────\n\n" +
      newBookEntries.join(",\n") + ",";

    // Find the last `];` in books.ts and insert before it
    const booksCloseIdx = booksContent.lastIndexOf("];");
    if (booksCloseIdx === -1) {
      console.error("ERROR: Could not find closing `];` in books.ts");
      process.exit(1);
    }
    booksContent = booksContent.slice(0, booksCloseIdx) + booksInsert + "\n" + booksContent.slice(booksCloseIdx);
    fs.writeFileSync(BOOKS_FILE, booksContent, "utf-8");
    console.log(`\nWrote ${booksAdded} new books to books.ts`);
  }

  // Append new chapter entries before the final `]`
  if (newChapterEntries.length > 0) {
    const chaptersInsert = "\n\n  // ── CANONICAL ADDITIONS BATCH 2 (auto-generated) ──────────────────────────\n\n" +
      newChapterEntries.join(",\n") + ",";

    // Find the last `]` in chapters.ts and insert before it
    const chaptersCloseIdx = chaptersContent.lastIndexOf("]");
    if (chaptersCloseIdx === -1) {
      console.error("ERROR: Could not find closing `]` in chapters.ts");
      process.exit(1);
    }
    chaptersContent = chaptersContent.slice(0, chaptersCloseIdx) + chaptersInsert + "\n" + chaptersContent.slice(chaptersCloseIdx);
    fs.writeFileSync(CHAPTERS_FILE, chaptersContent, "utf-8");
    console.log(`Wrote ${chaptersAdded} new chapters to chapters.ts`);
  }

  // Summary
  console.log("\n══════════════════════════════════════════════════════");
  console.log(`  SUMMARY`);
  console.log(`  Books added:   ${booksAdded}`);
  console.log(`  Books skipped: ${booksSkipped} (already existed)`);
  console.log(`  Chapters added: ${chaptersAdded}`);
  console.log("══════════════════════════════════════════════════════\n");
}

main();
