#!/usr/bin/env npx tsx
/** add-canonical-books-15.ts — New SE downloads + remaining high-value content */
import * as fs from "fs";
import * as path from "path";
const ROOT = path.resolve(__dirname, "..");
const BOOKS_FILE = path.join(ROOT, "src/data/books.ts");
const CHAPTERS_FILE = path.join(ROOT, "src/data/chapters.ts");
const CONTENT_DIR = path.join(ROOT, "public/content");
const TC: Record<string,{primary:string;secondary:string;accent:string}> = {Victorian:{primary:"#2D1B5E",secondary:"#1E1145",accent:"#8B5CF6"},Russian:{primary:"#5C1A1A",secondary:"#3D1010",accent:"#DC2626"},American:{primary:"#143220",secondary:"#0A1F14",accent:"#22C55E"},French:{primary:"#0A1F3D",secondary:"#061428",accent:"#EC4899"},Modernist:{primary:"#111827",secondary:"#0A0F1A",accent:"#14B8A6"},Germanic:{primary:"#1F2937",secondary:"#111827",accent:"#10B981"},"Medieval European":{primary:"#1B4332",secondary:"#0F2B20",accent:"#F59E0B"},Renaissance:{primary:"#3D1A6E",secondary:"#2A1050",accent:"#D97706"},Scandinavian:{primary:"#1E293B",secondary:"#0F172A",accent:"#38BDF8"},"Post-Colonial":{primary:"#065F46",secondary:"#034335",accent:"#10B981"},Enlightenment:{primary:"#0F2744",secondary:"#091A2E",accent:"#06B6D4"},"Ancient Greek":{primary:"#1E3A5F",secondary:"#0F2744",accent:"#0EA5E9"},Romantic:{primary:"#4A0E2D",secondary:"#2D0819",accent:"#F43F5E"},Eastern:{primary:"#5C2800",secondary:"#3D1A00",accent:"#F97316"},};
interface BC{id:string;title:string;author:string;year:number;tradition:string;era:string;genres:string[];difficulty:"Beginner"|"Intermediate"|"Advanced"|"Scholar";synopsis:string;themes:string[];country:string;language?:string;readingLanguage?:string;}
interface MJ{bookId:string;title:string;author:string;chapterCount:number;totalWordCount:number;totalMinutes:number;chapters:Array<{index:number;title:string;wordCount:number;estimatedMinutes:number}>;}
function toAId(a:string){return a.toLowerCase().replace(/\./g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}
function frt(m:number){const h=Math.round(m/60);return h<1?`~${m} minutes`:`~${h} hour${h!==1?"s":""}`;}

const BOOKS: BC[] = [
  // ── New SE Downloads ───────────────────────────────────────────────────────
  { id: "winesburg-ohio", title: "Winesburg, Ohio", author: "Sherwood Anderson", year: 1919, tradition: "American", era: "Modern", genres: ["Short Stories", "Modernist Fiction"], difficulty: "Intermediate", synopsis: "Connected stories of a small Ohio town's grotesques — people warped by loneliness, repression, and the truths they cannot speak — that revolutionized the American short story and influenced Hemingway and Faulkner.", themes: ["Small-town life", "Loneliness", "Repression", "Truth", "Grotesque", "America"], country: "USA" },
  { id: "the-worm-ouroboros", title: "The Worm Ouroboros", author: "E. R. Eddison", year: 1922, tradition: "Modernist", era: "Modern", genres: ["Novel", "Fantasy", "Epic"], difficulty: "Scholar", synopsis: "Lords of Mercury wage cosmic war in a fantasy of Homeric grandeur, with prose that Tolkien admired and C. S. Lewis called among the most splendid in English — the great forgotten masterpiece of pre-Tolkien fantasy.", themes: ["War", "Honor", "Heroism", "Magic", "Fate", "Glory"], country: "England" },
  { id: "a-voyage-to-arcturus", title: "A Voyage to Arcturus", author: "David Lindsay", year: 1920, tradition: "Modernist", era: "Modern", genres: ["Novel", "Science Fiction", "Philosophical Fiction"], difficulty: "Advanced", synopsis: "A man travels to the planet Tormance orbiting Arcturus and undergoes constant physical and spiritual transformation in the most radically strange and philosophically ambitious science fiction novel ever written.", themes: ["Reality", "Illusion", "Transformation", "God", "Good and evil", "The cosmos"], country: "Scotland" },
  { id: "a-high-wind-in-jamaica", title: "A High Wind in Jamaica", author: "Richard Hughes", year: 1929, tradition: "Modernist", era: "Modern", genres: ["Novel", "Adventure"], difficulty: "Intermediate", synopsis: "English children captured by Caribbean pirates turn out to be more dangerous than their captors, as Hughes shatters every Victorian assumption about childhood innocence in the most disturbing adventure novel of the 20th century.", themes: ["Childhood", "Innocence", "Violence", "Pirates", "Caribbean", "Nature"], country: "England" },
  { id: "anna-of-the-five-towns", title: "Anna of the Five Towns", author: "Arnold Bennett", year: 1902, tradition: "Victorian", era: "Modern", genres: ["Novel", "Social Novel"], difficulty: "Intermediate", synopsis: "A young woman inherits a fortune but is trapped between a miserly father and a loveless engagement in Bennett's portrait of the Staffordshire Potteries — the finest provincial novel of the Edwardian era.", themes: ["Money", "Duty", "Provincial life", "Women", "Industry", "Entrapment"], country: "England" },
  { id: "little-caesar", title: "Little Caesar", author: "W. R. Burnett", year: 1929, tradition: "American", era: "Modern", genres: ["Novel", "Crime Fiction"], difficulty: "Beginner", synopsis: "A small-time hood claws his way to the top of the Chicago underworld in the novel that invented the gangster genre and was immediately adapted into the film that launched the golden age of Hollywood crime movies.", themes: ["Crime", "Ambition", "Power", "Chicago", "Violence", "The American Dream"], country: "USA" },
  { id: "john-silence-stories", title: "John Silence Stories", author: "Algernon Blackwood", year: 1908, tradition: "Victorian", era: "Modern", genres: ["Short Stories", "Horror", "Supernatural Fiction"], difficulty: "Intermediate", synopsis: "A psychic doctor investigates cases of supernatural disturbance — werewolves, ancient Egyptian curses, and malevolent nature spirits — in some of the finest and most atmospheric weird fiction ever written.", themes: ["The supernatural", "Nature", "Terror", "Investigation", "Psychic", "Evil"], country: "England" },
  { id: "not-without-laughter", title: "Not Without Laughter", author: "Langston Hughes", year: 1930, tradition: "American", era: "Modern", genres: ["Novel", "Coming-of-Age"], difficulty: "Beginner", synopsis: "A Black boy grows up in a small Kansas town, caught between his grandmother's faith, his aunt's respectability, and his mother's love of blues and dancing, in Hughes's only novel and a warm portrait of African American community life.", themes: ["Race", "Family", "Music", "Faith", "Coming of age", "Community"], country: "USA" },

  // ── Remaining high-value already-downloaded content ─────────────────────────
  { id: "the-magician", title: "The Magician", author: "W. Somerset Maugham", year: 1908, tradition: "Modernist", era: "Modern", genres: ["Novel", "Gothic Fiction", "Horror"], difficulty: "Intermediate", synopsis: "A sinister occultist modeled on Aleister Crowley seduces a young woman away from her fiancé, dragging her into a nightmare of black magic and vivisection in Maugham's most Gothic and disturbing novel.", themes: ["The occult", "Evil", "Obsession", "Science", "Love", "Paris"], country: "England" },
  { id: "on-a-chinese-screen", title: "On a Chinese Screen", author: "W. Somerset Maugham", year: 1922, tradition: "Modernist", era: "Modern", genres: ["Short Stories", "Travel Writing"], difficulty: "Beginner", synopsis: "Fifty-eight vignettes of life in 1920s China — missionaries, merchants, diplomats, and coolies — sketched with Maugham's characteristic irony and compression, each one a miniature masterpiece of observation.", themes: ["China", "Empire", "Character", "Irony", "Travel", "Human nature"], country: "England" },
  { id: "the-blue-lagoon", title: "The Blue Lagoon", author: "H. de Vere Stacpoole", year: 1908, tradition: "Victorian", era: "Modern", genres: ["Novel", "Romance", "Adventure"], difficulty: "Beginner", synopsis: "Two children shipwrecked on a tropical island grow up in a state of nature, discovering love and parenthood without any guidance from civilization, in a novel that fascinated Edwardian readers with its portrait of prelapsarian innocence.", themes: ["Nature", "Innocence", "Love", "Survival", "Paradise", "Childhood"], country: "England" },
  { id: "the-great-impersonation", title: "The Great Impersonation", author: "E. Phillips Oppenheim", year: 1920, tradition: "Victorian", era: "Modern", genres: ["Novel", "Thriller", "Espionage"], difficulty: "Beginner", synopsis: "A dissolute English nobleman and his exact double — a German spy — trade identities on the eve of World War I, and neither the reader nor the characters can be certain which man has returned to the Norfolk estate.", themes: ["Identity", "Espionage", "War", "Deception", "Doubles", "England"], country: "England" },
  { id: "dorothy-and-the-wizard-in-oz", title: "Dorothy and the Wizard in Oz", author: "L. Frank Baum", year: 1908, tradition: "American", era: "Modern", genres: ["Novel", "Children's Literature", "Fantasy"], difficulty: "Beginner", synopsis: "Dorothy and the Wizard fall through an earthquake into the underground Glass City and must journey upward through ever-stranger lands to reach the surface and the Emerald City.", themes: ["Adventure", "Underground", "Magic", "Friendship", "Oz", "Courage"], country: "USA" },
  { id: "harry-heathcote-of-gangoil", title: "Harry Heathcote of Gangoil", author: "Anthony Trollope", year: 1874, tradition: "Victorian", era: "Victorian", genres: ["Novel", "Adventure"], difficulty: "Beginner", synopsis: "A young English settler in the Australian bush must defend his sheep station against arson on a scorching Christmas Eve, in Trollope's only Australian novel — written during his visit to his son's station.", themes: ["Australia", "Fire", "Courage", "Neighbors", "The bush", "Christmas"], country: "Australia" },
  { id: "the-life-of-buffalo-bill", title: "The Life of Buffalo Bill", author: "William F. Cody", year: 1879, tradition: "American", era: "Victorian", genres: ["Autobiography", "Adventure"], difficulty: "Beginner", synopsis: "Buffalo Bill tells his own story — Pony Express rider, Civil War scout, buffalo hunter, Indian fighter, and showman — in an autobiography that is half genuine frontier memoir and half Wild West mythology.", themes: ["The West", "Adventure", "Frontier", "Show business", "Native America", "Legend"], country: "USA" },
  { id: "tombstone", title: "Tombstone", author: "Walter Noble Burns", year: 1927, tradition: "American", era: "Modern", genres: ["Non-Fiction", "History", "Western"], difficulty: "Beginner", synopsis: "The story of Tombstone, Arizona — Wyatt Earp, Doc Holliday, the O.K. Corral, and the silver boom that created America's most legendary frontier town — told with the vivid immediacy of a man who interviewed the survivors.", themes: ["The West", "Law", "Violence", "Legend", "Silver", "Justice"], country: "USA" },
  { id: "the-chinese-parrot", title: "The Chinese Parrot", author: "Earl Derr Biggers", year: 1926, tradition: "American", era: "Modern", genres: ["Novel", "Mystery", "Detective Fiction"], difficulty: "Beginner", synopsis: "Charlie Chan investigates the mysterious death of a parrot and a missing string of pearls in the California desert, uncovering a web of deception that stretches from San Francisco to a lonely ranch.", themes: ["Murder", "Desert", "Detection", "California", "Pearls", "Deception"], country: "USA" },
  { id: "behind-that-curtain", title: "Behind That Curtain", author: "Earl Derr Biggers", year: 1928, tradition: "American", era: "Modern", genres: ["Novel", "Mystery", "Detective Fiction"], difficulty: "Beginner", synopsis: "When a dead man is found in a San Francisco office, Charlie Chan connects the case to an unsolved crime in the Himalayas and a pair of mysterious embroidered velvet slippers.", themes: ["Murder", "San Francisco", "Detection", "Travel", "Shoes", "Justice"], country: "USA" },
  { id: "when-the-world-shook", title: "When the World Shook", author: "H. Rider Haggard", year: 1919, tradition: "Victorian", era: "Modern", genres: ["Novel", "Science Fiction", "Adventure"], difficulty: "Beginner", synopsis: "Castaways on a Pacific island discover an ancient civilization preserved beneath a volcano, and the god-like being who sleeps within threatens to reshape the entire Earth with his terrifying technology.", themes: ["Lost civilization", "Science", "Adventure", "The Pacific", "Power", "Antiquity"], country: "England" },
  { id: "gladiator", title: "Gladiator", author: "Philip Wylie", year: 1930, tradition: "American", era: "Modern", genres: ["Novel", "Science Fiction"], difficulty: "Intermediate", synopsis: "A man born with superhuman strength, speed, and invulnerability struggles to find purpose in a world that fears and rejects him — the novel that directly inspired Jerry Siegel to create Superman.", themes: ["Superhuman", "Alienation", "Power", "Society", "Purpose", "Loneliness"], country: "USA" },
  { id: "betty-zane", title: "Betty Zane", author: "Zane Grey", year: 1903, tradition: "American", era: "Modern", genres: ["Novel", "Historical Fiction", "Western"], difficulty: "Beginner", synopsis: "Based on the true story of Grey's own ancestor, a young woman runs through a hail of gunfire to fetch gunpowder during a siege of Fort Henry in 1782, in the novel that launched Grey's career as America's greatest Western writer.", themes: ["Frontier", "Courage", "War", "Women", "History", "America"], country: "USA" },
  { id: "his-family", title: "His Family", author: "Ernest Poole", year: 1917, tradition: "American", era: "Modern", genres: ["Novel", "Social Novel"], difficulty: "Intermediate", synopsis: "An aging New York widower watches his three very different daughters navigate the modern world — settlement houses, suffrage, bohemian art — in the first novel to win the Pulitzer Prize for Fiction.", themes: ["Family", "Modernity", "New York", "Women", "Change", "Generations"], country: "USA" },
  { id: "national-avenue", title: "National Avenue", author: "Booth Tarkington", year: 1927, tradition: "American", era: "Modern", genres: ["Novel", "Social Novel"], difficulty: "Intermediate", synopsis: "The sequel to The Turmoil follows a Midwestern industrial family into the 1920s as the grandson struggles between old money values and the ruthless new capitalism of the automobile age.", themes: ["Industry", "Family", "America", "Wealth", "Change", "Generations"], country: "USA" },
  { id: "the-created-legend", title: "The Created Legend", author: "Fyodor Sologub", year: 1908, tradition: "Russian", era: "Modern", genres: ["Novel", "Symbolist Fiction"], difficulty: "Advanced", synopsis: "A provincial schoolteacher creates an alternate reality through sheer will, blending Russian Symbolism with political satire as the 1905 Revolution rages around him in Sologub's most ambitious and strangest novel.", themes: ["Reality", "Creation", "Revolution", "Symbolism", "Russia", "Will"], country: "Russia", language: "Russian", readingLanguage: "English" },
  { id: "the-little-demon", title: "The Little Demon", author: "Fyodor Sologub", year: 1905, tradition: "Russian", era: "Modern", genres: ["Novel", "Psychological Fiction"], difficulty: "Advanced", synopsis: "A paranoid provincial schoolteacher descends into madness as he torments his students and colleagues, pursued by a demonic hallucination in the darkest satire of Russian provincial life since Gogol.", themes: ["Madness", "Cruelty", "Provincial life", "Paranoia", "Russia", "Evil"], country: "Russia", language: "Russian", readingLanguage: "English" },
  { id: "nordenholts-million", title: "Doomed Planet", author: "J. J. Connington", year: 1923, tradition: "Victorian", era: "Modern", genres: ["Novel", "Science Fiction"], difficulty: "Intermediate", synopsis: "A nitrogen-fixing bacteria destroys all plant life on Earth, and a ruthless industrialist creates a sealed colony to preserve a million survivors in one of the earliest and most chillingly realistic apocalyptic novels.", themes: ["Apocalypse", "Survival", "Science", "Leadership", "Ethics", "Civilization"], country: "England" },
  { id: "the-the-old-man-in-the-corner", title: "The Old Man in the Corner", author: "Baroness Orczy", year: 1909, tradition: "Victorian", era: "Modern", genres: ["Short Stories", "Mystery", "Detective Fiction"], difficulty: "Beginner", synopsis: "A mysterious old man in an ABC tea shop solves baffling crimes by pure logic while tying and untying knots in a piece of string — the original armchair detective, created by the author of The Scarlet Pimpernel.", themes: ["Detection", "Logic", "Crime", "London", "Mystery", "Armchair"], country: "England" },
];

function main() {
  let bc = fs.readFileSync(BOOKS_FILE, "utf-8");
  let cc = fs.readFileSync(CHAPTERS_FILE, "utf-8");
  const ebi = new Set<string>(); let m: RegExpExecArray|null;
  const br = /id:\s*"([^"]+)"/g; while((m=br.exec(bc))!==null) ebi.add(m[1]);
  const eci = new Set<string>(); const cr = /id:\s*"([^"]+)"/g; while((m=cr.exec(cc))!==null) eci.add(m[1]);
  let ba=0,ca=0,bs=0; const nbe:string[]=[],nce:string[]=[];
  for(const c of BOOKS){
    if(ebi.has(c.id)){bs++;continue;}
    const mp=path.join(CONTENT_DIR,c.id,"meta.json");
    if(!fs.existsSync(mp)){console.log("SKIP: "+c.id+" (no content)");bs++;continue;}
    const meta:MJ=JSON.parse(fs.readFileSync(mp,"utf-8"));
    const co=TC[c.tradition]||TC["Victorian"];const ai=toAId(c.author);const rt=frt(meta.totalMinutes);
    let e=`  {\n    id: "${c.id}",\n    title: "${c.title.replace(/"/g,'\\"')}",\n`;
    e+=`    author: "${c.author.replace(/"/g,'\\"')}",\n    authorId: "${ai}",\n    year: ${c.year},\n`;
    if(c.language) e+=`    language: "${c.language}",\n`;
    if(c.readingLanguage) e+=`    readingLanguage: "${c.readingLanguage}",\n`;
    e+=`    tradition: "${c.tradition}",\n    era: "${c.era}",\n`;
    e+=`    genres: [${c.genres.map(g=>`"${g}"`).join(", ")}],\n`;
    e+=`    difficulty: "${c.difficulty}",\n    chapters: ${meta.chapterCount},\n`;
    e+=`    estimatedReadingTime: "${rt}",\n    wordCount: ${meta.totalWordCount},\n`;
    e+=`    synopsis: "${c.synopsis.replace(/"/g,'\\"')}",\n`;
    e+=`    themes: [${c.themes.map(t=>`"${t}"`).join(", ")}],\n`;
    e+=`    country: "${c.country}",\n`;
    e+=`    coverColors: { primary: "${co.primary}", secondary: "${co.secondary}", accent: "${co.accent}" },\n`;
    e+=`    featured: false,\n    source: "standard-ebooks",\n  }`;
    nbe.push(e);ba++;
    for(const ch of meta.chapters){
      const ci=`${c.id}-ch-${ch.index}`;if(eci.has(ci))continue;
      let ce=`  {\n    id: "${ci}",\n    bookId: "${c.id}",\n    number: ${ch.index},\n`;
      ce+=`    title: "${ch.title.replace(/"/g,'\\"')}",\n    wordCount: ${ch.wordCount},\n`;
      ce+=`    estimatedMinutes: ${ch.estimatedMinutes},\n    summary: "",\n    quizAvailable: false,\n  }`;
      nce.push(ce);ca++;
    }
  }
  if(nbe.length>0){
    const ins="\n\n  // ── CONTINUING EXPANSION (auto-generated) ──────────────────────────────────\n\n"+nbe.join(",\n")+",";
    const idx=bc.lastIndexOf("];");bc=bc.slice(0,idx)+ins+"\n"+bc.slice(idx);fs.writeFileSync(BOOKS_FILE,bc,"utf-8");
  }
  if(nce.length>0){
    const ins="\n\n  // ── CONTINUING EXPANSION (auto-generated) ──────────────────────────────────\n\n"+nce.join(",\n")+",";
    const idx=cc.lastIndexOf("]");cc=cc.slice(0,idx)+ins+"\n"+cc.slice(idx);fs.writeFileSync(CHAPTERS_FILE,cc,"utf-8");
  }
  console.log(`\nBooks: ${ba}, Skipped: ${bs}, Chapters: ${ca}`);
}
main();
