/**
 * Tome — Cover Art Search Configurations
 *
 * Defines thematic search strategies for all 84 books.
 * Searches are by THEME, SETTING, and ERA — not literal title.
 * Used by fetch-cover-art.ts to query the Met Museum Open Access API.
 *
 * Met Department IDs:
 *   6  = Asian Art
 *   9  = Drawings & Prints
 *   11 = European Paintings
 *   13 = Greek and Roman Art
 */

export interface CoverSearchConfig {
  bookId: string
  title: string
  tradition: string
  queries: string[]             // Met API search queries, in priority order
  preferredDepartments?: number[]  // Met department IDs
  artKeywords?: string[]        // keywords to boost relevance scoring
  avoidKeywords?: string[]      // keywords to deprioritize
}

export const COVER_SEARCH_CONFIGS: CoverSearchConfig[] = [
  // ─── Ancient Greek ───────────────────────────────────────────────────────────
  {
    bookId: "the-iliad",
    title: "The Iliad",
    tradition: "Ancient Greek",
    queries: [
      "Achilles Trojan War Greek",
      "Greek warrior battle ancient",
      "Ajax Greek hero vase",
    ],
    preferredDepartments: [13],
    artKeywords: ["Achilles", "Troy", "warrior", "Greek", "vase"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "the-odyssey",
    title: "The Odyssey",
    tradition: "Ancient Greek",
    queries: [
      "Odysseus Greek mythology",
      "Circe Ulysses painting",
      "ancient Greek sea voyage",
    ],
    preferredDepartments: [13],
    artKeywords: ["Odysseus", "Ulysses", "sea", "voyage"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "oedipus-rex",
    title: "Oedipus Rex",
    tradition: "Ancient Greek",
    queries: [
      "Oedipus sphinx Greek",
      "Greek tragedy theater ancient",
      "ancient Greek oracle Delphi",
    ],
    preferredDepartments: [13],
    artKeywords: ["Oedipus", "sphinx", "tragedy"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "antigone",
    title: "Antigone",
    tradition: "Ancient Greek",
    queries: [
      "Greek woman ancient funeral",
      "Antigone Greek tragedy",
      "ancient Greek burial scene",
    ],
    preferredDepartments: [13],
    artKeywords: ["Greek", "woman", "dignity"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "medea",
    title: "Medea",
    tradition: "Ancient Greek",
    queries: [
      "Medea Greek mythology painting",
      "Circe sorcery ancient Greek woman",
      "Jason Argonauts Greek",
    ],
    preferredDepartments: [13],
    artKeywords: ["Medea", "Colchis", "sorceress"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "the-republic",
    title: "The Republic",
    tradition: "Ancient Greek",
    queries: [
      "Plato Socrates philosophy Greek",
      "ancient Athens philosophers",
      "Greek philosopher portrait",
    ],
    preferredDepartments: [13],
    artKeywords: ["Plato", "philosopher", "Athens"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "symposium",
    title: "Symposium",
    tradition: "Ancient Greek",
    queries: [
      "ancient Greek symposium banquet",
      "Greek drinking party red-figure",
      "Plato banquet ancient",
    ],
    preferredDepartments: [13],
    artKeywords: ["symposium", "banquet", "Eros", "love"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "apology",
    title: "Apology",
    tradition: "Ancient Greek",
    queries: [
      "Socrates death hemlock painting",
      "Socrates trial ancient Athens",
      "Greek philosopher ancient",
    ],
    preferredDepartments: [13],
    artKeywords: ["Socrates", "trial", "hemlock"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "nicomachean-ethics",
    title: "Nicomachean Ethics",
    tradition: "Ancient Greek",
    queries: [
      "Aristotle Greek philosopher",
      "ancient Greek school Athens",
      "philosophy virtue ancient Greek",
    ],
    preferredDepartments: [13],
    artKeywords: ["Aristotle", "virtue", "philosophy"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "the-histories",
    title: "The Histories",
    tradition: "Ancient Greek",
    queries: [
      "Persian Wars Greek ancient battle",
      "Herodotus ancient world map",
      "Battle of Salamis ancient Greek",
    ],
    preferredDepartments: [13],
    artKeywords: ["Persian", "war", "ancient", "battle"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "the-persians",
    title: "The Persians",
    tradition: "Ancient Greek",
    queries: [
      "Persian army ancient war",
      "Xerxes Persian king ancient",
      "ancient Persian court battle",
    ],
    preferredDepartments: [13],
    artKeywords: ["Persian", "Xerxes", "war", "defeat"],
    avoidKeywords: ["modern", "photograph"],
  },
  {
    bookId: "anabasis",
    title: "Anabasis",
    tradition: "Ancient Greek",
    queries: [
      "Greek soldiers ancient march",
      "ancient Greek mercenaries sea",
      "Xenophon Greek army Persia",
    ],
    preferredDepartments: [13],
    artKeywords: ["soldiers", "march", "Persian", "sea"],
    avoidKeywords: ["modern", "photograph"],
  },

  // ─── Roman ───────────────────────────────────────────────────────────────────
  {
    bookId: "the-aeneid",
    title: "The Aeneid",
    tradition: "Roman",
    queries: [
      "Aeneas Dido Carthage painting",
      "Roman founding Troy ancient",
      "Virgil Aeneid Roman mythology painting",
    ],
    preferredDepartments: [13, 11],
    artKeywords: ["Aeneas", "Dido", "Troy", "Rome"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "metamorphoses",
    title: "Metamorphoses",
    tradition: "Roman",
    queries: [
      "Ovid metamorphosis mythology painting",
      "Roman mythology transformation classical",
      "Apollo Daphne Baroque painting",
    ],
    preferredDepartments: [13, 11],
    artKeywords: ["transformation", "metamorphosis", "mythology"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "de-bello-gallico",
    title: "De Bello Gallico",
    tradition: "Roman",
    queries: [
      "Caesar Roman legions conquest",
      "Roman army battle ancient",
      "Julius Caesar Roman military",
    ],
    preferredDepartments: [13, 11],
    artKeywords: ["Caesar", "Roman", "legions", "battle"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "confessions",
    title: "Confessions",
    tradition: "Roman",
    queries: [
      "Augustine early Christian painting",
      "early Christian saint North Africa",
      "Roman Christian saint portrait",
    ],
    preferredDepartments: [13, 11],
    artKeywords: ["Augustine", "conversion", "Christian", "Roman"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "meditations",
    title: "Meditations",
    tradition: "Roman",
    queries: [
      "Marcus Aurelius Roman emperor bust",
      "Roman emperor philosopher portrait",
      "Stoic philosopher Roman marble",
    ],
    preferredDepartments: [13, 11],
    artKeywords: ["Marcus Aurelius", "emperor", "Stoic"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "letters-to-lucilius",
    title: "Letters to Lucilius",
    tradition: "Roman",
    queries: [
      "Seneca Roman philosopher portrait",
      "Stoic philosopher ancient Rome bust",
      "Roman philosopher writing letter",
    ],
    preferredDepartments: [13, 11],
    artKeywords: ["Seneca", "Stoic", "philosopher"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "de-rerum-natura",
    title: "De Rerum Natura",
    tradition: "Roman",
    queries: [
      "ancient Roman cosmos atom universe",
      "Lucretius Roman philosophy landscape",
      "Roman countryside ancient pastoral",
    ],
    preferredDepartments: [13, 11],
    artKeywords: ["nature", "cosmos", "Roman", "Epicurean"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "on-friendship",
    title: "On Friendship",
    tradition: "Roman",
    queries: [
      "Cicero Roman orator portrait ancient",
      "Roman senators friendship ancient",
      "Roman republic ancient forum",
    ],
    preferredDepartments: [13, 11],
    artKeywords: ["Cicero", "friendship", "Rome", "republic"],
    avoidKeywords: ["photograph"],
  },

  // ─── Medieval European ───────────────────────────────────────────────────────
  {
    bookId: "inferno",
    title: "Inferno",
    tradition: "Medieval European",
    queries: [
      "Dante Inferno Hell painting",
      "Gustave Dore Hell engraving",
      "Medieval Hell fire demons painting",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Dante", "Hell", "Inferno", "demons"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "purgatorio",
    title: "Purgatorio",
    tradition: "Medieval European",
    queries: [
      "Dante Purgatory mountain painting",
      "Medieval souls purgatory Italian art",
      "Purgatorio Dante fresco Italian",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Purgatory", "souls", "ascent", "Medieval"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "paradiso",
    title: "Paradiso",
    tradition: "Medieval European",
    queries: [
      "Dante Paradise Heaven light painting",
      "Medieval Paradise celestial Italian art",
      "Dante Beatrice Paradise illuminated",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Paradise", "Heaven", "light", "Beatrice"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-canterbury-tales",
    title: "The Canterbury Tales",
    tradition: "Medieval European",
    queries: [
      "Medieval English pilgrimage Canterbury",
      "Chaucer Canterbury pilgrims",
      "Medieval pilgrims English manuscript",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["pilgrimage", "Canterbury", "Medieval", "pilgrims"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "beowulf",
    title: "Beowulf",
    tradition: "Medieval European",
    queries: [
      "Anglo-Saxon warrior medieval sword",
      "Germanic hero dragon medieval",
      "Medieval Norse warrior illumination",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["warrior", "dragon", "Anglo-Saxon", "heroic"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-decameron",
    title: "The Decameron",
    tradition: "Medieval European",
    queries: [
      "Boccaccio storytelling Renaissance Italian",
      "Italian garden storytelling medieval",
      "Black Death plague Florence Medieval",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Florence", "storytelling", "garden", "Renaissance"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "le-morte-darthur",
    title: "Le Morte d'Arthur",
    tradition: "Medieval European",
    queries: [
      "Arthurian legend Camelot knight painting",
      "King Arthur Round Table pre-Raphaelite",
      "Sir Lancelot Guinevere medieval",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Arthur", "Lancelot", "Round Table", "knight", "Camelot"],
    avoidKeywords: ["photograph"],
  },

  // ─── Renaissance ─────────────────────────────────────────────────────────────
  {
    bookId: "hamlet",
    title: "Hamlet",
    tradition: "Renaissance",
    queries: [
      "Hamlet Shakespeare painting Victorian",
      "Danish prince melancholy portrait Renaissance",
      "Ophelia drowning pre-Raphaelite",
    ],
    preferredDepartments: [11],
    artKeywords: ["Hamlet", "melancholy", "prince", "Shakespeare"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "macbeth",
    title: "Macbeth",
    tradition: "Renaissance",
    queries: [
      "Macbeth witches painting",
      "Macbeth Lady Macbeth painting",
      "Scottish dark castle night painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Macbeth", "witches", "ambition", "dark"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "othello",
    title: "Othello",
    tradition: "Renaissance",
    queries: [
      "Othello Desdemona painting Shakespeare",
      "Venetian Moor portrait Renaissance",
      "Othello jealousy Shakespeare Victorian",
    ],
    preferredDepartments: [11],
    artKeywords: ["Othello", "Venice", "jealousy", "Moor"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-tempest",
    title: "The Tempest",
    tradition: "Renaissance",
    queries: [
      "Prospero tempest magic island",
      "Shakespeare Tempest Ariel painting",
      "island storm magic Renaissance painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Prospero", "Ariel", "island", "storm", "magic"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "don-quixote",
    title: "Don Quixote",
    tradition: "Renaissance",
    queries: [
      "Don Quixote windmills painting",
      "Daumier Don Quixote painting",
      "Cervantes Spanish knight painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Don Quixote", "windmill", "Sancho", "knight", "Spanish"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-prince",
    title: "The Prince",
    tradition: "Renaissance",
    queries: [
      "Machiavelli Renaissance Italian portrait",
      "Italian Renaissance court ruler painting",
      "Renaissance nobleman Florence portrait",
    ],
    preferredDepartments: [11],
    artKeywords: ["Machiavelli", "Renaissance", "Florence", "power", "ruler"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "paradise-lost",
    title: "Paradise Lost",
    tradition: "Renaissance",
    queries: [
      "Paradise Lost Satan Milton painting",
      "Satan rebel angel fallen painting",
      "Milton Paradise Lost Blake engraving",
    ],
    preferredDepartments: [11],
    artKeywords: ["Satan", "Paradise", "Milton", "Blake", "fallen angel"],
    avoidKeywords: ["photograph"],
  },

  // ─── Enlightenment ───────────────────────────────────────────────────────────
  {
    bookId: "candide",
    title: "Candide",
    tradition: "Enlightenment",
    queries: [
      "Voltaire Candide 18th century satire",
      "18th century European traveler painting",
      "Rococo French painting 18th century",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Voltaire", "Candide", "satire", "18th century"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "gullivers-travels",
    title: "Gulliver's Travels",
    tradition: "Enlightenment",
    queries: [
      "Gulliver Lilliput illustration Swift",
      "18th century traveler sea voyage",
      "Swift satire Enlightenment illustration",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Gulliver", "Swift", "satire", "voyage"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-social-contract",
    title: "The Social Contract",
    tradition: "Enlightenment",
    queries: [
      "Rousseau French Revolution painting",
      "French Enlightenment philosophy portrait",
      "French Revolution liberty 18th century",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Rousseau", "French Revolution", "liberty", "philosophy"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "discourse-on-method",
    title: "Discourse on Method",
    tradition: "Enlightenment",
    queries: [
      "Descartes philosopher French 17th century",
      "17th century philosopher portrait",
      "René Descartes French portrait painting",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Descartes", "Enlightenment", "philosophy", "portrait"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-wealth-of-nations",
    title: "The Wealth of Nations",
    tradition: "Enlightenment",
    queries: [
      "Adam Smith Scottish Enlightenment portrait",
      "Industrial Revolution British 18th century",
      "18th century British merchant trade",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Adam Smith", "economics", "Scotland", "trade", "Enlightenment"],
    avoidKeywords: ["photograph"],
  },

  // ─── Romantic ────────────────────────────────────────────────────────────────
  {
    bookId: "pride-and-prejudice",
    title: "Pride and Prejudice",
    tradition: "Romantic",
    queries: [
      "Regency English countryside woman portrait",
      "Jane Austen Regency social scene",
      "19th century English garden woman painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Regency", "English", "countryside", "garden", "woman"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "frankenstein",
    title: "Frankenstein",
    tradition: "Romantic",
    queries: [
      "Gothic night laboratory Romantic painting",
      "Frankenstein creature Gothic moonlight",
      "Mary Shelley Gothic Romantic dark",
    ],
    preferredDepartments: [11],
    artKeywords: ["Gothic", "laboratory", "creature", "Romantic", "dark"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "les-miserables",
    title: "Les Misérables",
    tradition: "Romantic",
    queries: [
      "French Revolution barricade painting",
      "Victor Hugo Paris poor 19th century",
      "French 19th century social suffering painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Hugo", "Paris", "barricade", "Revolution", "poor"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-count-of-monte-cristo",
    title: "The Count of Monte Cristo",
    tradition: "Romantic",
    queries: [
      "Mediterranean prison 19th century French",
      "Alexandre Dumas revenge 19th century",
      "French Romantic adventure sword duel",
    ],
    preferredDepartments: [11],
    artKeywords: ["Monte Cristo", "prison", "revenge", "Mediterranean"],
    avoidKeywords: ["photograph"],
  },

  // ─── Victorian ───────────────────────────────────────────────────────────────
  {
    bookId: "jane-eyre",
    title: "Jane Eyre",
    tradition: "Victorian",
    queries: [
      "Victorian governess English house portrait",
      "Bronte Yorkshire moors woman",
      "Jane Eyre Victorian woman painting dark house",
    ],
    preferredDepartments: [11],
    artKeywords: ["Victorian", "governess", "Yorkshire", "moors", "woman"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "wuthering-heights",
    title: "Wuthering Heights",
    tradition: "Victorian",
    queries: [
      "Yorkshire moors stormy Romantic landscape",
      "Victorian Gothic moors wind dark painting",
      "Heathcliff Bronte moors wild painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["moors", "Yorkshire", "Gothic", "storm", "wild"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "great-expectations",
    title: "Great Expectations",
    tradition: "Victorian",
    queries: [
      "Victorian London Dickens orphan painting",
      "Victorian England boy poor 19th century",
      "Dickens Victorian London painting social",
    ],
    preferredDepartments: [11],
    artKeywords: ["Dickens", "Victorian", "orphan", "London", "poor"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "a-tale-of-two-cities",
    title: "A Tale of Two Cities",
    tradition: "Victorian",
    queries: [
      "French Revolution guillotine painting",
      "Dickens French Revolution London Paris",
      "19th century Paris London revolution scene",
    ],
    preferredDepartments: [11],
    artKeywords: ["Revolution", "Paris", "London", "sacrifice", "guillotine"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-picture-of-dorian-gray",
    title: "The Picture of Dorian Gray",
    tradition: "Victorian",
    queries: [
      "Victorian portrait young man aesthete",
      "Aesthetic movement portrait Victorian",
      "Oscar Wilde Victorian dandy portrait painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["portrait", "Victorian", "aesthete", "beauty", "moral decay"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-importance-of-being-earnest",
    title: "The Importance of Being Earnest",
    tradition: "Victorian",
    queries: [
      "Victorian comedy drawing room English",
      "Wilde Victorian parlor scene painting",
      "19th century English social comedy scene",
    ],
    preferredDepartments: [11],
    artKeywords: ["Victorian", "comedy", "parlor", "Wilde", "social"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "a-dolls-house",
    title: "A Doll's House",
    tradition: "Victorian",
    queries: [
      "Ibsen Norwegian 19th century woman",
      "Victorian woman interior domestic scene painting",
      "19th century Scandinavian interior woman painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Ibsen", "Norwegian", "domestic", "woman", "Victorian"],
    avoidKeywords: ["photograph"],
  },

  // ─── Russian ─────────────────────────────────────────────────────────────────
  {
    bookId: "war-and-peace",
    title: "War and Peace",
    tradition: "Russian",
    queries: [
      "Tolstoy Russia Napoleonic war 19th century",
      "Russian winter battle 1812 painting",
      "19th century Russian aristocracy painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Russia", "Napoleonic", "winter", "battle", "aristocracy"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "anna-karenina",
    title: "Anna Karenina",
    tradition: "Russian",
    queries: [
      "Tolstoy Russia 19th century woman portrait",
      "Russian aristocratic woman 19th century painting",
      "Russian railway 19th century woman",
    ],
    preferredDepartments: [11],
    artKeywords: ["Russia", "Anna", "woman", "passion", "train"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "crime-and-punishment",
    title: "Crime and Punishment",
    tradition: "Russian",
    queries: [
      "Dostoevsky St Petersburg 19th century painting",
      "Russian poverty urban 19th century",
      "St Petersburg Russia dark painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Russia", "St Petersburg", "poverty", "guilt", "crime"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-brothers-karamazov",
    title: "The Brothers Karamazov",
    tradition: "Russian",
    queries: [
      "Russian Orthodox church painting 19th century",
      "Dostoevsky Russian religious painting",
      "Russian interior 19th century dramatic painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Russia", "brothers", "guilt", "church", "Dostoevsky"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "eugene-onegin",
    title: "Eugene Onegin",
    tradition: "Russian",
    queries: [
      "Pushkin Russia Romantic 19th century",
      "Russian Romantic duel winter 19th century",
      "Russian aristocrat Romantic portrait 19th century",
    ],
    preferredDepartments: [11],
    artKeywords: ["Pushkin", "Russia", "Romantic", "duel", "aristocrat"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-cherry-orchard",
    title: "The Cherry Orchard",
    tradition: "Russian",
    queries: [
      "Chekhov Russian estate autumn painting",
      "Russian orchard country house autumn",
      "19th century Russian countryside estate painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Chekhov", "orchard", "estate", "Russia", "autumn"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "notes-from-underground",
    title: "Notes from Underground",
    tradition: "Russian",
    queries: [
      "Russian 19th century basement dark interior",
      "Dostoevsky Russia underground poverty painting",
      "19th century Russian interior solitary figure",
    ],
    preferredDepartments: [11],
    artKeywords: ["underground", "Russia", "solitary", "Dostoevsky", "dark"],
    avoidKeywords: ["photograph"],
  },

  // ─── American ────────────────────────────────────────────────────────────────
  {
    bookId: "moby-dick",
    title: "Moby-Dick",
    tradition: "American",
    queries: [
      "whale hunt 19th century ocean painting",
      "American whaling ship ocean painting",
      "Herman Melville sea monster whale hunting",
    ],
    preferredDepartments: [11],
    artKeywords: ["whale", "whaling", "ocean", "sea", "ship"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "little-women",
    title: "Little Women",
    tradition: "American",
    queries: [
      "American Civil War era women domestic scene",
      "19th century American women family portrait",
      "Louisa May Alcott Victorian American domestic",
    ],
    preferredDepartments: [11],
    artKeywords: ["American", "Civil War", "women", "family", "domestic"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-scarlet-letter",
    title: "The Scarlet Letter",
    tradition: "American",
    queries: [
      "Puritan New England 17th century painting",
      "American colonial Puritan religious scene",
      "Hawthorne Puritan guilt 17th century",
    ],
    preferredDepartments: [11],
    artKeywords: ["Puritan", "colonial", "New England", "guilt", "scarlet"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "adventures-of-huckleberry-finn",
    title: "Adventures of Huckleberry Finn",
    tradition: "American",
    queries: [
      "Mississippi River 19th century American painting",
      "American frontier river boat 19th century",
      "Huck Finn Mississippi American landscape",
    ],
    preferredDepartments: [11],
    artKeywords: ["Mississippi", "river", "American", "frontier", "raft"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "walden",
    title: "Walden",
    tradition: "American",
    queries: [
      "New England forest pond Thoreau nature",
      "American nature painting Transcendentalist 19th century",
      "Walden Pond New England landscape painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Thoreau", "pond", "forest", "nature", "New England"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-great-gatsby",
    title: "The Great Gatsby",
    tradition: "American",
    queries: [
      "1920s American Jazz Age Long Island party",
      "Art Deco American 1920s painting",
      "Gatsby 1920s American dream party",
    ],
    preferredDepartments: [11],
    artKeywords: ["Jazz Age", "1920s", "American Dream", "party", "Long Island"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-call-of-the-wild",
    title: "The Call of the Wild",
    tradition: "American",
    queries: [
      "Alaskan wilderness sled dog 19th century",
      "Jack London Klondike Yukon winter painting",
      "American wilderness wolf dog painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Alaska", "Yukon", "wilderness", "dog", "winter"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-adventures-of-tom-sawyer",
    title: "The Adventures of Tom Sawyer",
    tradition: "American",
    queries: [
      "Mississippi River American boy 19th century",
      "Mark Twain 19th century American countryside",
      "American boy adventure river painting 19th century",
    ],
    preferredDepartments: [11],
    artKeywords: ["Twain", "boy", "river", "adventure", "American"],
    avoidKeywords: ["photograph"],
  },

  // ─── French ──────────────────────────────────────────────────────────────────
  {
    bookId: "madame-bovary",
    title: "Madame Bovary",
    tradition: "French",
    queries: [
      "Flaubert French bourgeois woman 19th century",
      "French provincial woman Realist painting",
      "19th century French domestic scene woman",
    ],
    preferredDepartments: [11],
    artKeywords: ["Flaubert", "French", "provincial", "woman", "bourgeois"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "les-fleurs-du-mal",
    title: "Les Fleurs du Mal",
    tradition: "French",
    queries: [
      "Baudelaire Symbolist French dark beauty poem",
      "Symbolist French painting decadent 19th century",
      "Paris Symbolist dark woman painting 19th century",
    ],
    preferredDepartments: [11],
    artKeywords: ["Baudelaire", "Symbolist", "beauty", "dark", "flowers"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "germinal",
    title: "Germinal",
    tradition: "French",
    queries: [
      "French coal miners working class 19th century painting",
      "Zola French labor workers miners painting",
      "19th century French industrial workers painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["miners", "labor", "France", "workers", "industrial"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-three-musketeers",
    title: "The Three Musketeers",
    tradition: "French",
    queries: [
      "French musketeers 17th century sword duel",
      "Louis XIII French court 17th century painting",
      "French cavaliers sword fighting Baroque",
    ],
    preferredDepartments: [11],
    artKeywords: ["musketeers", "French", "Baroque", "sword", "cavalier"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "pere-goriot",
    title: "Père Goriot",
    tradition: "French",
    queries: [
      "Balzac Paris 19th century French society painting",
      "French Realist Paris poor boarding house 19th century",
      "Honoré Daumier French social Paris painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Balzac", "Paris", "French", "social", "19th century"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-stranger",
    title: "The Stranger",
    tradition: "French",
    queries: [
      "Camus Algeria Mediterranean 20th century art",
      "North Africa sun desert French Algeria painting",
      "Mediterranean coast light heat modern painting",
    ],
    preferredDepartments: [11],
    artKeywords: ["Algeria", "Mediterranean", "sun", "existentialism", "Camus"],
    avoidKeywords: ["photograph"],
  },

  // ─── Modernist ───────────────────────────────────────────────────────────────
  {
    bookId: "ulysses",
    title: "Ulysses",
    tradition: "Modernist",
    queries: [
      "James Joyce Dublin Ireland 1920s modernist",
      "Irish cityscape modernist early 20th century",
      "Dublin street scene painting early 20th century",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Dublin", "Ireland", "modernist", "Joyce", "stream"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "mrs-dalloway",
    title: "Mrs Dalloway",
    tradition: "Modernist",
    queries: [
      "Virginia Woolf London 1920s woman painting",
      "Bloomsbury modernist painting London 1920s",
      "English post-war woman interior modernist painting",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Woolf", "London", "1920s", "modernist", "woman"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-metamorphosis",
    title: "The Metamorphosis",
    tradition: "Modernist",
    queries: [
      "Kafka Prague expressionist insect painting",
      "Expressionist dark figure alienation painting",
      "German Expressionist lonely figure room painting",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Kafka", "Expressionist", "alienation", "transformation", "dark"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-trial",
    title: "The Trial",
    tradition: "Modernist",
    queries: [
      "Kafka bureaucracy Expressionist painting",
      "German Expressionist dark corridor labyrinth painting",
      "Expressionist isolation figure dark painting",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Kafka", "Expressionist", "bureaucracy", "dark", "labyrinthine"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "heart-of-darkness",
    title: "Heart of Darkness",
    tradition: "Modernist",
    queries: [
      "Joseph Conrad Congo river darkness painting",
      "African river colonial 19th century painting",
      "Dark river jungle colonial painting",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Congo", "darkness", "Conrad", "river", "jungle"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "to-the-lighthouse",
    title: "To the Lighthouse",
    tradition: "Modernist",
    queries: [
      "Virginia Woolf seaside lighthouse painting",
      "Scottish island lighthouse sea Bloomsbury",
      "Post-Impressionist sea coast lighthouse painting",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["lighthouse", "sea", "Scotland", "Woolf", "coast"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "thus-spoke-zarathustra",
    title: "Thus Spoke Zarathustra",
    tradition: "Modernist",
    queries: [
      "Nietzsche mountain prophet painting",
      "German Romantic mountain solitary figure",
      "Alpine mountain lone figure Romantic painting",
    ],
    preferredDepartments: [11, 9],
    artKeywords: ["Nietzsche", "mountain", "prophet", "solitary", "Romantic"],
    avoidKeywords: ["photograph"],
  },

  // ─── Eastern ─────────────────────────────────────────────────────────────────
  {
    bookId: "bhagavad-gita",
    title: "Bhagavad Gita",
    tradition: "Eastern",
    queries: [
      "Bhagavad Gita Krishna Arjuna Indian painting",
      "Hindu battlefield chariot Indian art painting",
      "Mahabharata Indian miniature painting",
    ],
    preferredDepartments: [6, 9],
    artKeywords: ["Krishna", "Arjuna", "India", "Hindu", "chariot"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-art-of-war",
    title: "The Art of War",
    tradition: "Eastern",
    queries: [
      "Sun Tzu Chinese ancient war painting scroll",
      "Chinese ancient military painting scroll",
      "Chinese classical painting warrior strategy",
    ],
    preferredDepartments: [6, 9],
    artKeywords: ["Sun Tzu", "Chinese", "strategy", "military", "ancient"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "tao-te-ching",
    title: "Tao Te Ching",
    tradition: "Eastern",
    queries: [
      "Chinese Taoist landscape painting mountain river",
      "Chinese landscape ink painting classic",
      "Chinese classical landscape water mountain",
    ],
    preferredDepartments: [6, 9],
    artKeywords: ["Tao", "Chinese", "landscape", "mountain", "water"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-tale-of-genji",
    title: "The Tale of Genji",
    tradition: "Eastern",
    queries: [
      "Genji Japanese Heian court painting scroll",
      "Japanese Heian period painting scroll",
      "Japanese court painting classical scroll Lady Genji",
    ],
    preferredDepartments: [6, 9],
    artKeywords: ["Genji", "Heian", "Japan", "court", "scroll"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "rubaiyat-of-omar-khayyam",
    title: "Rubáiyát of Omar Khayyám",
    tradition: "Eastern",
    queries: [
      "Omar Khayyam Persian miniature painting",
      "Persian garden wine miniature painting",
      "Persian Islamic miniature painting classical",
    ],
    preferredDepartments: [6, 9],
    artKeywords: ["Persian", "garden", "wine", "miniature", "Khayyam"],
    avoidKeywords: ["photograph"],
  },
  {
    bookId: "the-masnavi",
    title: "The Masnavi",
    tradition: "Eastern",
    queries: [
      "Rumi Sufi Persian whirling dervish painting",
      "Islamic Sufi mystical painting Persian",
      "Persian Sufi miniature painting divine love",
    ],
    preferredDepartments: [6, 9],
    artKeywords: ["Rumi", "Sufi", "Persian", "dervish", "divine love"],
    avoidKeywords: ["photograph"],
  },
]
