import type { OdysseyGloss } from "../odyssey-glosses"

// Books I–XII. Phrases are cross-checked against Bryant's rendered verse
// lines. Greek transliterations use the Latinate forms Bryant uses
// (Ulysses, Jove, Pallas) with the canonical Greek noted in the gloss.

export const ODYSSEY_GLOSSES_BOOK_1_THROUGH_12: OdysseyGloss[] = [

  // ── Book I ──────────────────────────────────────────────────────────
  { chapterIndex: 1, phrase: "O Muse", definition: "Invocation of the Muse — Calliope, patroness of epic poetry; Homer requests divine help to begin the song." },
  { chapterIndex: 1, phrase: "sagacious man", definition: "Bryant's rendering of Greek *polytropos* — literally 'of many turns,' the epithet that opens the poem and defines Odysseus." },
  { chapterIndex: 1, phrase: "Ilium", definition: "Ancient name for Troy, from its founder Ilus; the city whose fall in the Trojan War begins the Odyssey's backstory." },
  { chapterIndex: 1, phrase: "Neptune", definition: "Bryant's Latin name for Poseidon, god of the sea; wrathful at Odysseus for blinding his son Polyphemus (see Book IX)." },
  { chapterIndex: 1, phrase: "Calypso", definition: "Sea-nymph, daughter of Atlas; holds Odysseus on her island Ogygia for seven years before Zeus orders his release." },
  { chapterIndex: 1, phrase: "Aegisthus", definition: "Lover of Clytemnestra who helped murder Agamemnon on his return from Troy; killed in turn by Agamemnon's son Orestes." },
  { chapterIndex: 1, phrase: "Orestes", definition: "Son of Agamemnon; avenges his father by killing Aegisthus and Clytemnestra — held up throughout the Odyssey as a model for Telemachus." },
  { chapterIndex: 1, phrase: "Pallas", definition: "Epithet of Athena, goddess of wisdom, craft, and war-strategy; Odysseus's chief divine patron." },
  { chapterIndex: 1, phrase: "blue-eyed goddess", definition: "Bryant's rendering of Greek *glaukōpis* — literally 'gray-eyed' or 'owl-eyed,' Athena's signature epithet." },
  { chapterIndex: 1, phrase: "Ithaca", definition: "Odysseus's rocky island kingdom in the Ionian Sea, off the west coast of Greece." },
  { chapterIndex: 1, phrase: "Telemachus", definition: "Son of Odysseus and Penelope; a boy when his father left for Troy, now a young man facing the suitors alone." },
  { chapterIndex: 1, phrase: "Penelope", definition: "Wife of Odysseus, daughter of Icarius; has held her household against 108 suitors for the ten years since the end of the Trojan War." },
  { chapterIndex: 1, phrase: "Laertes", definition: "Odysseus's aged father; has withdrawn to his country farm in grief." },
  { chapterIndex: 1, phrase: "Hermes", definition: "Messenger of the gods, called the Argicide ('Argus-slayer'); Bryant often uses the Roman 'Mercury.'" },
  { chapterIndex: 1, phrase: "suitor", definition: "One of 108 young noblemen from Ithaca and the neighboring islands, pressuring Penelope to remarry and consuming Odysseus's wealth." },
  { chapterIndex: 1, phrase: "Mentes", definition: "Taphian king, family guest-friend of Odysseus — the form Athena assumes for her first Ithacan disguise." },
  { chapterIndex: 1, phrase: "Phemius", definition: "The bard of Odysseus's household; compelled to sing for the suitors." },
  { chapterIndex: 1, phrase: "Taphians", definition: "A sea-going people from Taphos, a small island near Ithaca; Mentes rules them." },
  { chapterIndex: 1, phrase: "Antinoüs", definition: "Son of Eupeithes; the most aggressive of the suitors and Homer's first-named ringleader." },
  { chapterIndex: 1, phrase: "Eurymachus", definition: "Son of Polybus; the second ringleader of the suitors, smoother-tongued than Antinoüs." },
  { chapterIndex: 1, phrase: "Eurycleia", definition: "Daughter of Ops; Laertes's slave-woman bought for twenty oxen; nurse to Odysseus from infancy and a lifelong loyal retainer." },
  { chapterIndex: 1, phrase: "Jove", definition: "Bryant's Latin rendering of Zeus, supreme god of Olympus; called 'cloud-compeller' and 'Saturn's son' throughout." },
  { chapterIndex: 1, phrase: "stranger", definition: "Greek *xenia* — the sacred code of guest-friendship, the reciprocal obligation between host and stranger; the Odyssey's chief moral axis." },

  // ── Book II ─────────────────────────────────────────────────────────
  { chapterIndex: 2, phrase: "assembly", definition: "Greek term for the public assembly-place; the first one held on Ithaca in twenty years is the opening scene of this book." },
  { chapterIndex: 2, phrase: "Halitherses", definition: "Ithacan elder, one of the few who supports Telemachus; a 'bird-discerning sage' who correctly reads the eagle omen." },
  { chapterIndex: 2, phrase: "Mentor", definition: "Old friend of Odysseus left in charge of the household; Athena borrows his shape for her second disguise." },
  { chapterIndex: 2, phrase: "Icarius", definition: "Penelope's father; pressing her (through the suitors' messages) to remarry and return to his house." },
  { chapterIndex: 2, phrase: "Pylos", definition: "Kingdom of Nestor on the southwest coast of the Peloponnese; Telemachus's first stop." },
  { chapterIndex: 2, phrase: "Sparta", definition: "Kingdom of Menelaus and Helen in Laconia; Telemachus's second stop." },
  { chapterIndex: 2, phrase: "Aegyptius", definition: "Aged Ithacan noble whose son sailed with Odysseus to Troy; speaks first in the assembly." },
  { chapterIndex: 2, phrase: "web", definition: "Penelope's unfinished burial-shroud for Laertes — she weaves by day, unweaves by night, stalling the suitors for three years." },
  { chapterIndex: 2, phrase: "Achaians", definition: "Homeric collective name for the Greeks — used especially by Bryant in the senses of 'Achaians' or 'Greeks.'" },
  { chapterIndex: 2, phrase: "long-haired Greeks", definition: "Homer's formulaic epithet for the Achaeans — long hair marked free men of status; Bryant keeps it verbatim." },
  { chapterIndex: 2, phrase: "Phronius", definition: "Ithacan noble; father of Noemon, whose ship Telemachus borrows." },
  { chapterIndex: 2, phrase: "libation", definition: "A ritual pouring of wine (or milk, honey, oil) as an offering to the gods before a meal, voyage, or undertaking." },
  { chapterIndex: 2, phrase: "barque", definition: "Bryant's archaic term for a small sea-going ship; the usual vessel in the Odyssey is a single-masted galley with twenty oars." },
  { chapterIndex: 2, phrase: "shroud", definition: "Burial cloth; Penelope's pretended weaving of Laertes's funeral shroud is her delaying tactic." },

  // ── Book III ────────────────────────────────────────────────────────
  { chapterIndex: 3, phrase: "Nestor", definition: "Aged king of Pylos; survivor of three generations; the Iliad's wisest counsellor now old and at peace." },
  { chapterIndex: 3, phrase: "Peisistratus", definition: "Youngest son of Nestor; accompanies Telemachus to Sparta and becomes his first peer." },
  { chapterIndex: 3, phrase: "Thrasymedes", definition: "Elder son of Nestor; commands Pylian troops during the sacrifice scene." },
  { chapterIndex: 3, phrase: "hecatomb", definition: "Greek *hekatombē* — a large-scale sacrifice, originally one hundred oxen; Homer uses it for any major ritual slaughter." },
  { chapterIndex: 3, phrase: "Gerenian", definition: "Epithet of Nestor — from Gerena, where he was raised after Heracles killed his brothers." },
  { chapterIndex: 3, phrase: "Geraestus", definition: "Cape at the southern tip of Euboea; Homer names it as a landmark on the Achaean return-voyage." },
  { chapterIndex: 3, phrase: "Atrides", definition: "Patronymic 'son of Atreus' — normally Agamemnon or Menelaus; Homer uses it of both." },
  { chapterIndex: 3, phrase: "Clytemnestra", definition: "Wife of Agamemnon; lover of Aegisthus and co-conspirator in Agamemnon's murder." },
  { chapterIndex: 3, phrase: "Argos", definition: "Agamemnon's kingdom in the eastern Peloponnese; here the site of his assassination, not the dog Argos of Book XVII." },
  { chapterIndex: 3, phrase: "Menelaus", definition: "King of Sparta; younger brother of Agamemnon; husband of Helen whose abduction caused the Trojan War." },
  { chapterIndex: 3, phrase: "Ajax", definition: "In Book III likely Ajax the Lesser, son of Oileus, whose drowning death at sea is recounted among the returns." },
  { chapterIndex: 3, phrase: "Peisistratus", definition: "Alternate spelling of Peisistratus, Nestor's son and Telemachus's companion." },
  { chapterIndex: 3, phrase: "Diocles", definition: "Host of Telemachus at Pherae on his overland journey from Pylos to Sparta." },
  { chapterIndex: 3, phrase: "Pherae", definition: "Waystation between Pylos and Sparta on Telemachus's overland trip; modern Kalamata." },

  // ── Book IV ─────────────────────────────────────────────────────────
  { chapterIndex: 4, phrase: "Megapenthes", definition: "Menelaus's son by a slave-woman; being married off in the double wedding at Sparta." },
  { chapterIndex: 4, phrase: "Hermione", definition: "Only legitimate daughter of Menelaus and Helen; being married off to Achilles's son Neoptolemus." },
  { chapterIndex: 4, phrase: "Polydamna", definition: "Egyptian woman who gave Helen the nepenthe drug; wife of Thon." },
  { chapterIndex: 4, phrase: "Proteus", definition: "'Old man of the sea,' Egyptian sea-god who can change shape; Menelaus wrestles him for prophecy." },
  { chapterIndex: 4, phrase: "Pharos", definition: "Small island off the Egyptian coast where Menelaus is stranded; later the site of the famous lighthouse." },
  { chapterIndex: 4, phrase: "Eidothea", definition: "Daughter of Proteus; betrays her father to help the stranded Menelaus capture him." },
  { chapterIndex: 4, phrase: "Asteris", definition: "Small island in the straits between Ithaca and Samos; the suitors' ambush-station." },
  { chapterIndex: 4, phrase: "Iphthime", definition: "Penelope's sister; Athena animates her image as a consoling dream-visitor." },
  { chapterIndex: 4, phrase: "Sidonians", definition: "Phoenician people of Sidon; Menelaus passed through their cities amassing treasure." },
  { chapterIndex: 4, phrase: "Cyprus", definition: "Large eastern Mediterranean island; one of Menelaus's ports of call." },
  { chapterIndex: 4, phrase: "Argive", definition: "Of Argos; in Homer often a synonym for 'Greek' more broadly." },
  { chapterIndex: 4, phrase: "Phaedimus", definition: "Sidonian prince; gave the silver-and-gold bowl Menelaus re-gifts to Telemachus." },

  // ── Book V ──────────────────────────────────────────────────────────
  { chapterIndex: 5, phrase: "Leucothea", definition: "Sea-goddess (formerly the mortal Ino, daughter of Cadmus); gives Odysseus her magical veil to survive the storm." },
  { chapterIndex: 5, phrase: "Scheria", definition: "Land of the Phaeacians; Odysseus's landing-place after the storm; a utopian refuge between worlds." },
  { chapterIndex: 5, phrase: "Phaeacians", definition: "Seafaring people settled on Scheria by Nausithoüs after their exile from the Cyclopes' neighborhood." },
  { chapterIndex: 5, phrase: "Ethiopians", definition: "In Homer, a distant fortunate people living at the edge of the world; Poseidon visits them in the opening council." },
  { chapterIndex: 5, phrase: "Eos", definition: "Dawn, often 'rosy-fingered'; opens many books of the poem as she opens each day." },
  { chapterIndex: 5, phrase: "Tithonus", definition: "Mortal lover of Eos; granted immortality without eternal youth; cited in Calypso's grievance about goddesses and mortal men." },
  { chapterIndex: 5, phrase: "Orion", definition: "Mortal hunter loved by Eos and killed by Artemis at the gods' request; Calypso cites his case too." },
  { chapterIndex: 5, phrase: "Poseidon", definition: "Greek god of the sea, the earth-shaker; punishing Odysseus for the blinding of Polyphemus." },

  // ── Book VI ─────────────────────────────────────────────────────────
  { chapterIndex: 6, phrase: "Hypereia", definition: "Former homeland of the Phaeacians, abandoned because of conflict with the Cyclopes who lived nearby." },
  { chapterIndex: 6, phrase: "Dymas", definition: "Father of Nausicaä's girlhood friend; the form Athena assumes in her dream-visitation." },
  { chapterIndex: 6, phrase: "Delos", definition: "Aegean island, Apollo's birthplace; Odysseus mentions seeing a young palm-tree there in his supplication to Nausicaä." },
  { chapterIndex: 6, phrase: "Nausithoüs", definition: "Former Phaeacian king who founded Scheria; Alcinoüs's father." },
  { chapterIndex: 6, phrase: "Athena", definition: "Bryant alternates between 'Athenè,' 'Pallas,' 'Minerva,' and 'blue-eyed goddess' — all names of Odysseus's divine patron." },

  // ── Book VII ────────────────────────────────────────────────────────
  { chapterIndex: 7, phrase: "Alcinoüs", definition: "King of the Phaeacians, grandson of Poseidon; hosts Odysseus with ideal xenia." },
  { chapterIndex: 7, phrase: "Arete", definition: "Queen of the Phaeacians; exceptionally honored in a culture that defers to her — Odysseus supplicates her, not the king." },
  { chapterIndex: 7, phrase: "Rhexenor", definition: "Arete's father (and Alcinoüs's brother) — making Arete Alcinoüs's niece as well as his wife." },
  { chapterIndex: 7, phrase: "Euboea", definition: "Large Aegean island that Alcinoüs cites as the furthest point his magical ships have reached." },
  { chapterIndex: 7, phrase: "Rhadamanthus", definition: "Legendary judge; Alcinoüs says the Phaeacians once carried him to Euboea in a single day." },

  // ── Book VIII ───────────────────────────────────────────────────────
  { chapterIndex: 8, phrase: "Demodocus", definition: "Blind bard of the Phaeacian court; the Odyssey's portrait of an inspired poet." },
  { chapterIndex: 8, phrase: "Euryalus", definition: "Young Phaeacian athlete who insults Odysseus, then apologizes with a gift." },
  { chapterIndex: 8, phrase: "Laodamas", definition: "Son of Alcinoüs; invites Odysseus to compete in the games." },
  { chapterIndex: 8, phrase: "Mars", definition: "Bryant's Latin name for Ares, war-god; caught with Aphrodite in Hephaestus's net." },
  { chapterIndex: 8, phrase: "Venus", definition: "Bryant's Latin name for Aphrodite, goddess of desire; the net-captured adulteress of Demodocus's second song." },
  { chapterIndex: 8, phrase: "Vulcan", definition: "Bryant's Latin name for Hephaestus, the lame smith-god; forger of the chain-net that traps Aphrodite and Ares." },
  { chapterIndex: 8, phrase: "Lemnos", definition: "Aegean island sacred to Hephaestus; the god's limping retreat after the adultery is discovered." },

  // ── Book IX ─────────────────────────────────────────────────────────
  { chapterIndex: 9, phrase: "Cicones", definition: "Thracian tribe whose city Ismarus Odysseus sacks on his first day after leaving Troy; they counter-attack and kill 72 Greeks." },
  { chapterIndex: 9, phrase: "Ismarus", definition: "Thracian port-city, the Cicones' home; location of Odysseus's first post-Troy violence." },
  { chapterIndex: 9, phrase: "Lotus-eaters", definition: "North African people whose lotus fruit makes visitors forget home; the first of the wanderings' temptations." },
  { chapterIndex: 9, phrase: "lotus", definition: "Dream-fruit of the Lotus-eaters; whoever tastes it loses desire to return home." },
  { chapterIndex: 9, phrase: "Cyclops", definition: "One-eyed giant; specifically Polyphemus, son of Poseidon and the nymph Thoosa." },
  { chapterIndex: 9, phrase: "Polyphemus", definition: "Cyclops son of Poseidon; eats six of Odysseus's men before being blinded with a fire-hardened olive-wood stake." },
  { chapterIndex: 9, phrase: "Maron", definition: "Priest of Apollo at Ismarus; gives Odysseus the divine wine that will intoxicate the Cyclops." },
  { chapterIndex: 9, phrase: "Noman", definition: "Bryant's rendering of Greek *Outis* — Odysseus's assumed name, pun on *mētis* (cunning); gave modern 'no one' riddles their paradigm." },
  { chapterIndex: 9, phrase: "whelps", definition: "Young animals; Odysseus describes the cheeses, lambs, and kids separated by age in the Cyclops's cave." },
  { chapterIndex: 9, phrase: "Telemus", definition: "Cyclops prophet who foretold Polyphemus's blinding; the Cyclops recalls his prophecy only after the fact." },
  { chapterIndex: 9, phrase: "return", definition: "Greek for 'homecoming, return'; the plot of the Odyssey and a thematic keyword; Polyphemus specifically curses Odysseus's nostos." },

  // ── Book X ──────────────────────────────────────────────────────────
  { chapterIndex: 10, phrase: "Aeolus", definition: "'Keeper of the winds' on the floating island Aeolia; gives Odysseus the bag of contrary winds." },
  { chapterIndex: 10, phrase: "Aeolia", definition: "Floating island of Aeolus; its bronze walls and perpetual feast mark it as liminal space." },
  { chapterIndex: 10, phrase: "Antiphates", definition: "Lestrigonian king whose wife the Greek scouts first encounter; his seizure of a crewman begins the massacre." },
  { chapterIndex: 10, phrase: "Circe", definition: "Witch-goddess on the island of Aeaea; turns Odysseus's men into swine, then becomes his guide and lover for a year." },
  { chapterIndex: 10, phrase: "Aeaea", definition: "Circe's island, at 'the eastern gateway of the world'; a liminal geographic stopover before the Nekyia." },
  { chapterIndex: 10, phrase: "Hermes", definition: "Messenger god, here the Argicide, giver of moly; protector of travelers and heralds." },
  { chapterIndex: 10, phrase: "Eurylochus", definition: "Odysseus's second-in-command; distrustful, vocal, consistently wrong; leads the sacrilegious cattle-slaughter on Thrinacia." },
  { chapterIndex: 10, phrase: "Elpenor", definition: "Youngest of Odysseus's crew; falls drunkenly from Circe's roof and breaks his neck; first shade met in Book XI." },

  // ── Book XI — the Nekyia ────────────────────────────────────────────
  { chapterIndex: 11, phrase: "Cimmerians", definition: "Mythical people dwelling in perpetual fog at the edge of the world; Odysseus beaches near them to perform the necromantic rite." },
  { chapterIndex: 11, phrase: "Tiresias", definition: "Blind Theban seer who retained his prophetic wits in death; gives Odysseus the inland-oar prophecy." },
  { chapterIndex: 11, phrase: "Anticlea", definition: "Odysseus's mother; died of grief; her shade is the Odyssey's most heartbreaking encounter." },
  { chapterIndex: 11, phrase: "Tyro", definition: "Daughter of Salmoneus; first heroine in the catalogue; seduced by Poseidon in the guise of a river." },
  { chapterIndex: 11, phrase: "Salmoneus", definition: "Father of Tyro; punished by Zeus for impiety." },
  { chapterIndex: 11, phrase: "Alcmena", definition: "Mother of Heracles by Zeus; in the catalogue." },
  { chapterIndex: 11, phrase: "Oedipus", definition: "King of Thebes who killed his father and married his mother; his story is told briefly in the catalogue." },
  { chapterIndex: 11, phrase: "Chloris", definition: "Wife of Neleus, mother of Nestor; in the catalogue." },
  { chapterIndex: 11, phrase: "Neleus", definition: "Father of Nestor; king of Pylos before his son." },
  { chapterIndex: 11, phrase: "Pero", definition: "Daughter of Neleus and Chloris; won as a bride by Bias through the effort of his brother the seer Melampus." },
  { chapterIndex: 11, phrase: "Leda", definition: "Mother of the Dioscuri (Castor and Polydeuces) and of Helen and Clytemnestra; in the catalogue." },
  { chapterIndex: 11, phrase: "Castor", definition: "One of the Dioscuri — divine twins of Leda, alternating between life and death." },
  { chapterIndex: 11, phrase: "Phaedra", definition: "Daughter of Minos; wife of Theseus; in the catalogue (not yet the Phaedra of Euripides's tragedy)." },
  { chapterIndex: 11, phrase: "Ariadne", definition: "Daughter of Minos; helped Theseus escape the Minotaur; died on Naxos before marriage." },
  { chapterIndex: 11, phrase: "Agamemnon", definition: "King of Mycenae, leader of the Greeks at Troy; murdered on his return by Clytemnestra and Aegisthus." },
  { chapterIndex: 11, phrase: "Achilles", definition: "Greatest Greek warrior at Troy; his shade famously wishes he were alive as a hired farmhand." },
  { chapterIndex: 11, phrase: "Patroclus", definition: "Achilles's closest companion; killed by Hector; his shade is with Achilles's in Hades." },
  { chapterIndex: 11, phrase: "Antilochus", definition: "Nestor's son; killed at Troy defending his father from Memnon; shade in the Nekyia." },
  { chapterIndex: 11, phrase: "Ajax", definition: "Here the greater Ajax, Telamon's son; refuses to speak to Odysseus; the Odyssey's most famous silent shade." },
  { chapterIndex: 11, phrase: "Minos", definition: "Cretan king turned judge of the dead; Dante will remake him into a demon-judge." },
  { chapterIndex: 11, phrase: "Orion", definition: "Giant hunter; shade in Hades still pursuing the beasts he killed in life." },
  { chapterIndex: 11, phrase: "Tityus", definition: "Giant son of Gaia; punished in Hades by two vultures eating his liver for assaulting Leto." },
  { chapterIndex: 11, phrase: "Tantalus", definition: "King tormented in Hades by recedding water and withdrawing fruit; eternally unsatisfied hunger and thirst." },
  { chapterIndex: 11, phrase: "Sisyphus", definition: "King condemned to push a stone up a hill forever; it rolls back each time he nears the top." },
  { chapterIndex: 11, phrase: "Nekyia", definition: "Greek term for a ritual by which the dead are summoned and questioned; the name for Book XI in ancient scholia." },
  { chapterIndex: 11, phrase: "Gorgon", definition: "Monstrous female with snake-hair whose gaze turns viewers to stone; Odysseus fears Persephone may send one against him." },

  // ── Book XII ────────────────────────────────────────────────────────
  { chapterIndex: 12, phrase: "Sirens", definition: "Two (sometimes three) monstrous female singers whose song lures sailors to wreck; they sing specifically of kleos — glory-stories." },
  { chapterIndex: 12, phrase: "Scylla", definition: "Six-headed monster in a cliff-cave who plucks sailors from passing ships; daughter of Crataeis." },
  { chapterIndex: 12, phrase: "Charybdis", definition: "Giant whirlpool opposite Scylla; swallows and vomits the sea three times a day; together they make the strait impassable." },
  { chapterIndex: 12, phrase: "Crataeis", definition: "Scylla's mother, a sea-goddess; her invocation the only possible remedy against her daughter." },
  { chapterIndex: 12, phrase: "Lampetia", definition: "Daughter of Helios; tends her father's cattle on Thrinacia and reports their slaughter." },
  { chapterIndex: 12, phrase: "thunderbolt", definition: "Zeus's signature weapon; splinters Odysseus's ship after the crew's sacrilege against Helios." },
]
