// ─────────────────────────────────────────────
// Tome Book Experience Engine — Registry
// ─────────────────────────────────────────────
// The single source of truth for the twelve featured book experiences
// (MASTER_EXECUTION_PLAN §10). Palettes, motifs, archetypes, Virgil
// variants, Seals, and Stoa rewards live here — not in components.
//
// Canonical book IDs verified against data_canon_books.json (repo root).
// Palettes are mirrored by scripts/covers/tome-vector-covers.mjs; if you
// change a palette here, regenerate public/covers/tome-generated/.

import type {
  BookExperience,
  BookSlug,
  CoverArchetype,
} from "./types"

const COVER_DIR = "/covers/tome-generated"

const PROVENANCE_NOTE =
  "Original Tome vector cover art, procedurally generated by " +
  "scripts/covers/tome-vector-covers.mjs (SVG source, sharp raster exports). " +
  "Not a public-domain historical source; no title/author text is baked in."

function coverAssets(slug: BookSlug) {
  return {
    svg: `${COVER_DIR}/${slug}.svg`,
    webp: `${COVER_DIR}/${slug}.webp`,
    png: `${COVER_DIR}/${slug}.png`,
  }
}

// ── The twelve featured experiences ──────────

export const BOOK_EXPERIENCES: Record<BookSlug, BookExperience> = {
  macbeth: {
    slug: "macbeth",
    bookId: "macbeth",
    title: "Macbeth",
    author: "William Shakespeare",
    paletteSlot: "macbeth",
    palette: {
      ground: "#1B2437",
      ink: "#0E1420",
      primary: "#3D4E6E",
      accent: "#B03A2E",
      gold: "#E3B34C",
    },
    motif: "crown, dagger, storm",
    coverArchetype: "emblem-relic",
    portalScene:
      "A storm-lit battlement: the cover's dagger tilts as thunderheads part, " +
      "and the reader steps through a curtain of rain into a candlelit great hall.",
    mapPathStyle: "spiraling battlement stair of candle-flame nodes",
    virgilVariantKey: "storm-cloak",
    ambientMotionKey: "storm-drift",
    chapterNodeAppearance: "flickering candle flames set into stone stair treads",
    trialEmphasis: "ambition, equivocation, and the language of prophecy",
    sealName: "The Dagger in the Dark",
    stoaReward:
      "A restored painting of the storm-lit heath — three figures around a " +
      "cauldron's glow — hung in the reader's Stoa once a Macbeth Trial is passed.",
    heroCopy: "A crown promised by lightning, paid for in sleep.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "distant-thunder-and-candle-flutter",
    altText:
      "Original Tome vector cover for Macbeth: a gold crown above an upright " +
      "dagger on a storm-dark indigo field, framed by a gold hairline.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("macbeth"),
  },

  "moby-dick": {
    slug: "moby-dick",
    bookId: "moby-dick",
    title: "Moby-Dick",
    author: "Herman Melville",
    paletteSlot: "moby-dick",
    palette: {
      ground: "#0F3B4C",
      ink: "#082430",
      primary: "#1F6E8C",
      accent: "#E9F1F2",
      gold: "#E8C46A",
    },
    motif: "sea horizon, whale curve, compass star",
    coverArchetype: "horizon-negative-space",
    portalScene:
      "The horizon line on the cover rises like a swell; the pale whale curve " +
      "sounds, and the reader is carried under a spray of stars onto the Pequod's deck.",
    mapPathStyle: "dotted whaling voyage line across open ocean swells",
    virgilVariantKey: "maritime-coat",
    ambientMotionKey: "sea-swell",
    chapterNodeAppearance: "brass harpoon points bobbing on animated wave lines",
    trialEmphasis: "obsession, symbol, and the sea as mirror of the self",
    sealName: "The White Silence",
    stoaReward:
      "A restored painting of a white fluke vanishing into a starlit sea, " +
      "added to the Stoa after a passed Moby-Dick Trial.",
    heroCopy: "Chase the white whale across a map of your own making.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "low-whale-call-and-rigging-creak",
    altText:
      "Original Tome vector cover for Moby-Dick: a pale whale curve breaching " +
      "a dark teal sea beneath a wide negative-space sky, gold compass star above.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("moby-dick"),
  },

  alice: {
    slug: "alice",
    bookId: "alices-adventures-in-wonderland",
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    paletteSlot: "alice",
    palette: {
      ground: "#F6EFE3",
      ink: "#2A2438",
      primary: "#5B4E8C",
      accent: "#D94F5C",
      gold: "#DFAF4F",
    },
    motif: "keys, cards, doors, scale shifts",
    coverArchetype: "constellation-cabinet",
    portalScene:
      "The cabinet of tiny doors swings open at once; keys orbit like a mobile, " +
      "and the reader shrinks through the smallest door into a garden of giant flowers.",
    mapPathStyle: "rabbit-hole descent of mismatched door and key nodes",
    virgilVariantKey: "key-and-cabinet",
    ambientMotionKey: "tumble-and-scale",
    chapterNodeAppearance: "floating playing-card suits that gently swap scale",
    trialEmphasis: "logic, nonsense, and the rules that bend under questions",
    sealName: "The Door Too Small",
    stoaReward:
      "A restored painting of a tiny golden key before a curtain-hidden door, " +
      "unlocked in the Stoa by a passed Alice Trial.",
    heroCopy: "Fall gently. Nothing here is quite the size it seems.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "clock-chime-and-paper-flutter",
    altText:
      "Original Tome vector cover for Alice's Adventures in Wonderland: a " +
      "constellation of small doors, keys, and card diamonds on warm ivory, " +
      "joined by dotted lines.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("alice"),
  },

  "paradise-lost": {
    slug: "paradise-lost",
    bookId: "paradise-lost",
    title: "Paradise Lost",
    author: "John Milton",
    paletteSlot: "paradise-lost",
    palette: {
      ground: "#171226",
      ink: "#0B0817",
      primary: "#43346B",
      accent: "#D98E4A",
      gold: "#F0C766",
    },
    motif: "gate, falling star, celestial geometry",
    coverArchetype: "threshold-portal",
    portalScene:
      "The great gate on the cover grinds open; a star falls past the reader's " +
      "shoulder as they cross the threshold between light and the vast dark.",
    mapPathStyle: "descending celestial stair between concentric spheres",
    virgilVariantKey: "falling-star-gate",
    ambientMotionKey: "star-fall",
    chapterNodeAppearance: "orbiting sphere rings that lock into gates",
    trialEmphasis: "temptation, free will, and rhetoric's dangerous beauty",
    sealName: "The Fallen Star",
    stoaReward:
      "A restored painting of a single star falling past an open gate of light, " +
      "hung in the Stoa after a passed Paradise Lost Trial.",
    heroCopy: "Stand at the gate where every choice still shines.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "choir-chord-and-stone-gate-rumble",
    altText:
      "Original Tome vector cover for Paradise Lost: a tall rounded gate of " +
      "gold light on deep violet, a single star falling beside it.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("paradise-lost"),
  },

  "divine-comedy": {
    slug: "divine-comedy",
    bookId: "the-divine-comedy",
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    paletteSlot: "divine-comedy",
    palette: {
      ground: "#26160F",
      ink: "#170D08",
      primary: "#7A4A2B",
      accent: "#4E7D5B",
      gold: "#EFC25E",
    },
    motif: "rings, steps, lantern, laurel",
    coverArchetype: "ascent-journey",
    portalScene:
      "Concentric rings turn like a great lock; a lantern lifts from the lowest " +
      "circle and the reader follows its light upward, step by step, out of the dark wood.",
    mapPathStyle: "spiral ascent of stepped terraces in three-realm color progression",
    virgilVariantKey: "ascent-lantern",
    ambientMotionKey: "ring-rise",
    chapterNodeAppearance: "lantern-lit stair markers climbing the spiral",
    trialEmphasis: "consequence, ascent, and the architecture of hope",
    sealName: "The Lantern Ascent",
    stoaReward:
      "A restored painting of a lantern rising through turning rings toward a " +
      "single white star, added to the Stoa after a passed Divine Comedy Trial.",
    heroCopy: "Begin in the dark wood. Climb toward the stars.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "low-gregorian-drone-and-lantern-hum",
    altText:
      "Original Tome vector cover for The Divine Comedy: concentric gold rings " +
      "and steps rising toward a small lantern light on a deep umber field.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("divine-comedy"),
  },

  iliad: {
    slug: "iliad",
    bookId: "the-iliad",
    title: "The Iliad",
    author: "Homer",
    paletteSlot: "iliad",
    palette: {
      ground: "#26354A",
      ink: "#141E2C",
      primary: "#4A6B8A",
      accent: "#C57B3A",
      gold: "#D9A94E",
    },
    motif: "shield, spear, shoreline fragments",
    coverArchetype: "fragment-evidence",
    portalScene:
      "The broken shield on the cover reassembles piece by piece; bronze warms " +
      "in the sun, and the reader steps onto a shoreline strewn with the evidence of wrath.",
    mapPathStyle: "shoreline trail of bronze fragments from ships to city walls",
    virgilVariantKey: "bronze-shoreline",
    ambientMotionKey: "shore-shimmer",
    chapterNodeAppearance: "shield fragments that slot together as chapters complete",
    trialEmphasis: "rage, honor, and the cost of glory",
    sealName: "Wrath in Bronze",
    stoaReward:
      "A restored painting of a bronze shield catching dawn light on a " +
      "shoreline, unlocked in the Stoa by a passed Iliad Trial.",
    heroCopy: "Sing the rage — and count what it costs.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "bronze-shield-ring-and-surf",
    altText:
      "Original Tome vector cover for The Iliad: a fragmented bronze shield " +
      "and a diagonal spear above an ochre shoreline on slate blue.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("iliad"),
  },

  odyssey: {
    slug: "odyssey",
    bookId: "the-odyssey",
    title: "The Odyssey",
    author: "Homer",
    paletteSlot: "odyssey",
    palette: {
      ground: "#14243F",
      ink: "#0A1426",
      primary: "#2E4E86",
      accent: "#3FA08C",
      gold: "#E6BC58",
    },
    motif: "stars, islands, path, rope",
    coverArchetype: "map-voyage",
    portalScene:
      "The dotted path on the cover ignites star by star; islands rise from " +
      "the indigo sea, and the reader sails the glowing line toward home.",
    mapPathStyle: "star-navigated dotted voyage between island nodes",
    virgilVariantKey: "star-navigation",
    ambientMotionKey: "constellation-drift",
    chapterNodeAppearance: "island markers that light as the voyage advances",
    trialEmphasis: "cunning, fidelity, and the long discipline of return",
    sealName: "The Long Way Home",
    stoaReward:
      "A restored painting of a mast under a turning field of stars, hung in " +
      "the Stoa after a passed Odyssey Trial.",
    heroCopy: "Ten years, one bearing: home.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "night-sea-and-distant-buoy-bell",
    altText:
      "Original Tome vector cover for The Odyssey: a dotted gold voyage path " +
      "curving between small islands under stars on an indigo sea.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("odyssey"),
  },

  frankenstein: {
    slug: "frankenstein",
    bookId: "frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    paletteSlot: "frankenstein",
    palette: {
      ground: "#101C26",
      ink: "#070F16",
      primary: "#23455A",
      accent: "#5FD3D0",
      gold: "#E3C169",
    },
    motif: "alpine silhouette, laboratory spark, ice",
    coverArchetype: "experiment-spark",
    portalScene:
      "A cyan spark runs along the cover's energy line; the alpine ridge " +
      "splinters with light, and the reader follows the charge into the frozen laboratory.",
    mapPathStyle: "glacier traverse of spark-lit cairn nodes",
    virgilVariantKey: "alpine-spark",
    ambientMotionKey: "static-crackle",
    chapterNodeAppearance: "cairn stones that flare cyan as each summit is reached",
    trialEmphasis: "creation, responsibility, and the boundary of knowledge",
    sealName: "The Spark in the Ice",
    stoaReward:
      "A restored painting of an alpine ridge split by a single line of light, " +
      "added to the Stoa after a passed Frankenstein Trial.",
    heroCopy: "You made it live. Now answer for it.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "electrical-crackle-and-wind-over-ice",
    altText:
      "Original Tome vector cover for Frankenstein: dark alpine peaks under a " +
      "pale moon, crossed by a single cyan spark line.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("frankenstein"),
  },

  "pride-prejudice": {
    slug: "pride-prejudice",
    bookId: "pride-and-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    paletteSlot: "pride-prejudice",
    palette: {
      ground: "#F4EBDD",
      ink: "#3A2E2A",
      primary: "#8C6A4F",
      accent: "#5E7D4F",
      gold: "#D9A94E",
    },
    motif: "ribbon, letter, garden geometry",
    coverArchetype: "social-geometry-letter",
    portalScene:
      "The overlapping circles on the cover turn like dancers changing " +
      "partners; a sealed letter opens, and the reader steps into a sunlit garden room.",
    mapPathStyle: "garden promenade of interlocking social-circle nodes",
    virgilVariantKey: "ribbon-and-letter",
    ambientMotionKey: "garden-breeze",
    chapterNodeAppearance: "wax-sealed letters that open along the promenade",
    trialEmphasis: "first impressions, irony, and the geometry of society",
    sealName: "The Letter Unsent",
    stoaReward:
      "A restored painting of two ribbons crossing above an open letter in a " +
      "garden, unlocked in the Stoa by a passed Pride and Prejudice Trial.",
    heroCopy: "Every first impression is a draft awaiting revision.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "pianoforte-arpeggio-and-turned-page",
    altText:
      "Original Tome vector cover for Pride and Prejudice: overlapping circles, " +
      "a ribbon curve, and a small letter on warm cream with garden-green accents.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("pride-prejudice"),
  },

  "jane-eyre": {
    slug: "jane-eyre",
    bookId: "jane-eyre",
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    paletteSlot: "jane-eyre",
    palette: {
      ground: "#2B1E24",
      ink: "#180F14",
      primary: "#5C3A46",
      accent: "#C4553B",
      gold: "#E0B45C",
    },
    motif: "window, ember, moor, red room",
    coverArchetype: "window-ember",
    portalScene:
      "The ember in the cover's window flares; the casement swings open onto " +
      "the moor, and the reader climbs through into wind and wide grey light.",
    mapPathStyle: "moorland causeway of window-frame nodes, each lit from within",
    virgilVariantKey: "window-ember",
    ambientMotionKey: "ember-glow",
    chapterNodeAppearance: "window panes that warm from cold grey to ember red",
    trialEmphasis: "integrity, passion, and the self that refuses to be owned",
    sealName: "The Ember in the Window",
    stoaReward:
      "A restored painting of a four-paned window glowing ember-red against a " +
      "dark moor, added to the Stoa after a passed Jane Eyre Trial.",
    heroCopy: "I am no bird; and no net ensnares me.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "wind-over-moor-and-low-hearth-crackle",
    altText:
      "Original Tome vector cover for Jane Eyre: a four-paned window glowing " +
      "ember red above a dark moor line on deep plum.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("jane-eyre"),
  },

  meditations: {
    slug: "meditations",
    bookId: "meditations",
    title: "Meditations",
    author: "Marcus Aurelius",
    paletteSlot: "meditations",
    palette: {
      ground: "#F0E7D8",
      ink: "#2E2620",
      primary: "#6E5B49",
      accent: "#9C3D33",
      gold: "#CFA050",
    },
    motif: "wax tablet, stylus, quiet dawn",
    coverArchetype: "quiet-symbol-tablet",
    portalScene:
      "The wax tablet on the cover warms at first light; the stylus lifts, and " +
      "the reader steps into a quiet colonnade where morning arrives slowly.",
    mapPathStyle: "straight dawn colonnade of plain stone tablet nodes",
    virgilVariantKey: "wax-tablet",
    ambientMotionKey: "dawn-stillness",
    chapterNodeAppearance: "unadorned tablets that brighten with the dawn gradient",
    trialEmphasis: "attention, duty, and the discipline of the inner citadel",
    sealName: "The Quiet Citadel",
    stoaReward:
      "A restored painting of a wax tablet and stylus in first dawn light, " +
      "unlocked in the Stoa by a passed Meditations Trial.",
    heroCopy: "The empire within is the only one you must govern.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "dawn-birdsong-and-soft-stylus-scratch",
    altText:
      "Original Tome vector cover for Meditations: a single wax tablet and " +
      "stylus on warm ivory, with a quiet dawn band of stoic red and gold.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("meditations"),
  },

  republic: {
    slug: "republic",
    bookId: "the-republic",
    title: "The Republic",
    author: "Plato",
    paletteSlot: "republic",
    palette: {
      ground: "#16233D",
      ink: "#0B1322",
      primary: "#2C4A7C",
      accent: "#3FA08C",
      gold: "#EAC35E",
    },
    motif: "geometric city, cave light, sun",
    coverArchetype: "cave-city-light",
    portalScene:
      "The cave mouth on the cover widens; shadows flatten against the wall " +
      "and then release, and the reader climbs toward the geometric city and the sun.",
    mapPathStyle: "upward ascent from cave shadow to city grid to open light",
    virgilVariantKey: "cave-light",
    ambientMotionKey: "cave-flicker",
    chapterNodeAppearance: "shadow shapes on the cave wall that resolve into city blocks",
    trialEmphasis: "justice, appearance versus reality, and the examined city",
    sealName: "The Light Outside the Cave",
    stoaReward:
      "A restored painting of a gold sun rising over a geometric cobalt city, " +
      "hung in the Stoa after a passed Republic Trial.",
    heroCopy: "Turn from the shadows. The light is climbable.",
    fourteenDayJourney: true,
    journeyLengthDays: 14,
    soundAccent: "echoing-cave-drip-and-distant-city-bell",
    altText:
      "Original Tome vector cover for The Republic: a geometric cobalt city " +
      "above a dark cave opening, with a beam of gold light from a low sun.",
    provenance: "tome-generated",
    provenanceNote: PROVENANCE_NOTE,
    coverAssets: coverAssets("republic"),
  },
}

// ── Accessors ────────────────────────────────

const BOOK_SLUGS = Object.keys(BOOK_EXPERIENCES) as BookSlug[]

/** All featured book slugs, in registry order. */
export function listBookSlugs(): BookSlug[] {
  return BOOK_SLUGS
}

/** Type guard for Living Archive world slugs. */
export function isBookSlug(value: string): value is BookSlug {
  return value in BOOK_EXPERIENCES
}

/** Look up a featured book experience by world slug. Returns undefined for
 * unknown slugs — callers decide the fallback (usually a procedural cover). */
export function getBookExperience(slug: string): BookExperience | undefined {
  return isBookSlug(slug) ? BOOK_EXPERIENCES[slug] : undefined
}

/** Look up a featured book experience by canonical catalog book ID
 * (e.g. "alices-adventures-in-wonderland"). */
export function getBookExperienceByBookId(
  bookId: string,
): BookExperience | undefined {
  return BOOK_SLUGS.map((s) => BOOK_EXPERIENCES[s]).find(
    (experience) => experience.bookId === bookId,
  )
}

/** Cover archetype used by a book, if it is one of the featured twelve. */
export function getCoverArchetype(slug: string): CoverArchetype | undefined {
  return getBookExperience(slug)?.coverArchetype
}
