export interface BookCoverArt {
  bookId: string
  objectId: number           // Met Museum object ID (or AIC/Rijks ID)
  title: string              // artwork title
  artist: string             // artist name
  date: string               // artwork date string e.g. "1891"
  imageUrl: string           // full res IIIF/CDN image URL from museum
  thumbnailUrl: string       // small version
  localPath?: string         // e.g. "/covers/museum/the-odyssey.jpg" after download
  localThumbnailPath?: string // e.g. "/covers/museum/thumbs/the-odyssey.jpg"
  department: string
  medium: string
  creditLine: string         // attribution text for display
  objectUrl: string          // link to museum page
  source: "met" | "art-institute-chicago" | "rijksmuseum"
  score: number
}

// ── Load generated data if available ─────────────────────────────────────
// Generated by scripts/download-covers.ts after running the art pipeline.
// Falls back to empty object when the pipeline hasn't been run yet.

let _generatedData: Record<string, BookCoverArt> = {}
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = require("./generated/cover-art-data")
  if (mod?.GENERATED_BOOK_COVER_ART) {
    _generatedData = mod.GENERATED_BOOK_COVER_ART
  }
} catch {
  // generated file doesn't exist yet — that's fine, ClassicsCover fallback will be used
}

export const BOOK_COVER_ART: Record<string, BookCoverArt> = _generatedData

// Helper to get cover art for a book (returns undefined if not yet fetched)
export function getBookCoverArt(bookId: string): BookCoverArt | undefined {
  return BOOK_COVER_ART[bookId]
}
