import { GENERATED_BOOK_COVER_ART } from "@/data/generated/cover-art-data"

export interface BookCoverArt {
  bookId: string
  objectId: number           // Met Museum object ID (or AIC/Rijks ID)
  title: string              // artwork title
  artist: string             // artist name
  date: string               // artwork date string e.g. "1891"
  imageUrl: string           // full res IIIF/CDN image URL from museum
  thumbnailUrl: string       // small version
  localPath?: string         // e.g. "/covers/museum/the-odyssey.jpg" after download
  localThumbnailPath?: string // e.g. "/covers/museum/thumbs/the-odyssey.jpg"
  department: string
  medium: string
  creditLine: string         // attribution text for display
  objectUrl: string          // link to museum page
  source: "met" | "aic" | "art-institute-chicago" | "rijksmuseum"
  score: number
}

// Generated by scripts/download-covers.ts after running the art pipeline.
export const BOOK_COVER_ART: Record<string, BookCoverArt> = GENERATED_BOOK_COVER_ART

// Helper to get cover art for a book (returns undefined if not yet fetched)
export function getBookCoverArt(bookId: string): BookCoverArt | undefined {
  // Cover cull (2026-06-18): museum painting covers were archived to
  // archive/covers/museum. Return undefined so covers fall back to the
  // procedural ClassicsCover. The data map above is retained for reversibility.
  void bookId
  return undefined
}
